### ISSUE TITLE
Unused @angular/material scripts being pulled to application bundle

### ISSUE THREAD

**Issue by luisfpg** [Teradata/covalent#1001]
#### Bug Report
I just include the `TdSteps` module in the application. However, I see several other parts of @angular/material, such as chips, autocomplete, snackbar, etc.. being pulled into the generated code.

##### Screenshots
Below is the output for source-map-explorer when I don't import the `TdStepsModule`:
![image](https://user-images.githubusercontent.com/1183737/33433918-ae535f5c-d5c4-11e7-96fd-422c4c008e6c.png)

And here is the output after importing the `TdStepsModule`:
![image](https://user-images.githubusercontent.com/1183737/33433945-c0f3cf02-d5c4-11e7-9e8e-98774967573e.png)

#### What is the expected behavior?
No additional material code should be included in the bundle

#### What is the motivation / use case for changing the behavior?
Reduce the application size, which improves the user experience

#### Which version of Angular and Material, and which browser and OS does this issue affect?
Angular 5.0.3
Material 5.0.0-rc.2
Teradata covalent 1.0.0-rc.0

Did this work in previous versions of Angular / Material?
Not tested

##### Other information
I tried to chase which covalent script was causing the issue, but couldn't find it

**Comment by aciccarello** [comment]
@luisfpg Since those are all in the core module, try looking at your prod build. That will do tree shaking which should remove those unused parts

**Comment by luisfpg** [comment]
@aciccarello I've generated the build using `ng build -prod --source --sourcemaps`, and used `source-map-explorer` on its output.

**Comment by aciccarello** [comment]
Yeah, it looks like there is a problem. Below is the material bundle that I'm seeing. What is odd is that I don't think covalent is importing many of these modules. For example, I'm not using the material datepicker and neither is covalent but it appears in the material module.

![sourcemap explorer output showing material modules](https://user-images.githubusercontent.com/11273838/33440232-b4769042-d5ac-11e7-88c9-81f1672db088.png)

**Comment by emoralesb05** [comment]
This should solve the issue from a covalent perspective 

https://github.com/Teradata/covalent/pull/1019

but be aware that you need to import from the secondary entry points else everything gets loaded..
