### ISSUE TITLE
CommonJS bundle

### ISSUE THREAD

**Issue by portah** [Teradata/covalent#1006]
I work with your package almost half a year now and really love it. I use angular(2,4,5) in my meteor's projects thanks to angular-meteor (https://github.com/Urigo/angular-meteor) package. Recently I've got an issue with the bundle: meteor/meteor-angular/covalent https://github.com/Urigo/angular-meteor/issues/1755. The meteor-angular team come up with a solution, but also recommended to ask your to provide CommonJS bundle as more permanent and the right way solution. 
Thanks.

**Comment by emoralesb05** [comment]
We are in the middle of actually trying to mimic what the angular and material team do since we want to be able to provide support for SSR + any other bundles.

**Comment by emoralesb05** [comment]
We just merge the PR that changes our build format to the Angular Format. So this should be working fine now.
