### ISSUE TITLE
Simple dialogs do not support word-wrapping on strings that contain *very long* words 

### ISSUE THREAD

**Issue by peter-gergely-horvath** [Teradata/covalent#1011]
### Do you want to request a *feature* or report a *bug*?
Reporting a bug.
#### Bug Report
Apparently, Covalent Simple dialogs do not support word-wrapping on strings that contain *very long* words (without spaces). A word longer than certain threshold (lower case: about 50, Upper case: about 40 characters) cases the dialog to start displaying a vertical scroll bar.

While you usually have shorted words that say 40 characters, sometimes the application is displaying some kind of technical information (e.g. database table name, MQ queue name etc), which can exceed the threshold, after which it is not displayed correctly.

While one can argue this is not a bug, please consider the behaviour of a standard JavaScript 'alert()' method call, where even long words are wrapped properly.

I would expect something similar to happen when using  Covalent Simple dialogs.

The following piece of code reproduces the behaviour -- again a ridiculously long string is not very common, but definitely can happen:

<img width="450" alt="dialog with extreme long content" src="https://user-images.githubusercontent.com/15800802/33611741-c53e89d0-d9cf-11e7-9a5f-7ad9a31a3271.png">
  

```    
import { ViewContainerRef } from '@angular/core';
import { TdDialogService } from '@covalent/core';

export class FooBarComponent implements OnInit {

   
  constructor(...
              private _dialogService: TdDialogService,
              private _viewContainerRef: ViewContainerRef) { }

private openDialog() {
 this._dialogService.openConfirm({
          message: 'THISISAVERYLONGTEXTWHICHISNOTWRAPPEDINTHEDIALOGSATALL',
          disableClose: true,
          viewContainerRef: this._viewContainerRef,
          title: 'ISSUE DEMONSTRATION',
          cancelButton: 'CANCEL',
          acceptButton: 'OK',
        }).afterClosed().subscribe((accept: boolean) => {
          if (accept) {
            // ...
        });
  }
}
```

On Chrome, for instance, the following JavaScript code displays an alert box with the text broken into multiple lines.
```
alert('ThisIsAVeryLongTextThisIsAVeryLongTextThisIsAVeryLongTextThisIsAVeryLongTextThisIsAVeryLongTextThisIsAVeryLongTextThisIsAVeryLongTextThisIsAVeryLongTextThisIsAVeryLongTextThisIsAVeryLongText');
```
<img width="501" alt="chrome alert wrapping extreme long string into multiple lines" src="https://user-images.githubusercontent.com/15800802/33611841-009b8064-d9d0-11e7-8e54-a93dd4e009b6.png">

StackBlitz template: https://stackblitz.com/edit/covalent
Plunker template: http://plnkr.co/edit/7uZQn4mLNJkL6XN9WSNd

#### What is the expected behavior?
  * Dialogs should break extreme long words into multiple lines similarly to a standard `alert()` call
  * And/Or dialogs should be sizeable from the API so as to be able to accommodate long content.

#### What is the motivation / use case for changing the behavior?
I had a case, where I wanted to display a confirmation dialog containing a technical / system generated name. The content was not visible in the dialog. I myself had to write the logic to add spaces to into long strings so that the dialog show them properly.  

#### Which version of Angular and Material, and which browser and OS does this issue affect?
All versions affected AFAIK.

Did this work in previous versions of Angular / Material?

**Comment by emoralesb05** [comment]
We are going to do both things actually, making it so you can pass any MatDialogConfig when opening the dialog and making sure long words wrap also.

**Comment by emoralesb05** [comment]
https://github.com/Teradata/covalent/pull/1059 will take care of this
