### ISSUE TITLE
Font weight appears higher after upgrading

### ISSUE THREAD

**Issue by HumbleRedHead** [Teradata/covalent#1012]
#### Bug Report
The font weight across my application appears higher after upgrading from Covalent 1.0.0-beta.8-1 to 1.0.0-rc.0. Was this intentional?

##### Screenshots
BEFORE:
![image](https://user-images.githubusercontent.com/34315847/33685515-b7d4086c-da86-11e7-8999-c0059ce842dc.png)

AFTER:
![image](https://user-images.githubusercontent.com/34315847/33685495-a33330ae-da86-11e7-9d98-1eac8bf97db0.png)

BEFORE:
![image](https://user-images.githubusercontent.com/34315847/33685529-c2a249fc-da86-11e7-84e3-cce2d3bf888e.png)

AFTER:
![image](https://user-images.githubusercontent.com/34315847/33685540-ce410e10-da86-11e7-832b-513839678b4b.png)

#### Which version of Angular and Material, and which browser and OS does this issue affect?
Angular 5.0.5
Angular Material 5.0.0-rc0
Covalent 1.0.0-rc.0

Built with Angular CLI 1.5.5

Did this work in previous versions of Angular / Material?
Yes. In Covalent 1.0.0-beta.8-1

**Comment by kyleledbetter** [comment]
So this has been driving me crazy and I think it's actually an Angular Material bug.

The font weight for toolbars and buttons is supposed to be 400, but they're using 500 for buttons and toolbars

The reason we weren't catching it, is that their demo site doesn't actually pull in that Roboto 500 font weight, they just use `<link href="https://fonts.googleapis.com/css?family=Roboto|Roboto+Mono:300" rel="stylesheet">`

And we were using their recommendation from their typography docs
`<link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500" rel="stylesheet">`
so ours looked wrong

We have 2 workarounds:

1. One workaround is just removing 500 and using
`<link href="https://fonts.googleapis.com/css?family=Roboto:300,400" rel="stylesheet">`
BUT that will not have the proper 500 weight for typography `mat-title` and `mat-body-2`

OR the better workaround
2. In theme.scss you can change their mixins for typography by using:
```
// Custom typography
$custom-typography: mat-typography-config(
  $button: mat-typography-level(14px, 14px, 400)
);
$custom-toolbar-typography: mat-typography-config(
  $title: mat-typography-level(20px, 32px, 400)
);

// Include the base styles for Angular Material core. We include this here so that you only
// have to load a single css file for Angular Material in your app.
@include mat-core($custom-typography);

// Setting the toolbar to the proper spec weight
@include mat-toolbar-typography($custom-toolbar-typography);
```

**Comment by kyleledbetter** [comment]
I just committed this to our docs in a PR https://github.com/Teradata/covalent/pull/1013/commits/1c3dd005bf07725f0cd28ba4f43242dbd6c5908f

**Comment by aciccarello** [comment]
Should an upstream issue be opened with the material team? I didn't see any in angular/material2.

**Comment by kyleledbetter** [comment]
I think so @aciccarello, stating:

$button should have font weight 400
and they need to add a new $toolbar variable w/ font weight 400 instead of reusing $title

**Comment by aciccarello** [comment]
@kyleledbetter Okay, I'm putting together an issue. Can you help explain why the `$toolbar` variable is needed? From briefly looking at 1c3dd00 it seems like if you want to change the typography of the toolbars it should be done through the `mat-toolbar-typography` mixin

**Comment by aciccarello** [comment]
Per the upstream issue, the 500 font weight is correct for a medium font weight. So it appears that the change was intentional and aligns with the spec.

**Comment by jeremysmartt** [comment]
closing as not a Covalent issue
