### ISSUE TITLE
[Bug] Loading component breaks when strategy is 'overlay'

### ISSUE THREAD

**Issue by luchillo17** [Teradata/covalent#1021]
### Do you want to request a *feature* or report a *bug*?
Bug

#### Bug Report
Using strategy `overlay` for the loading component breaks the app with following issue as shown in image, it was working before i updated to `@covalent/core@1.0.0-rc.0`.

##### Screenshots or link to CodePen/Plunker/JSfiddle
![image](https://user-images.githubusercontent.com/9698639/33808235-d82e33d0-ddb0-11e7-92f8-c4b49971a483.png)

#### What is the expected behavior?
To just work or at least not blow up my app.

#### What is the motivation / use case for changing the behavior?
It's a bug.

#### Which version of Angular and Material, and which browser and OS does this issue affect?

Did this work in previous versions of Angular / Material? Yes

![image](https://user-images.githubusercontent.com/9698639/33808269-7763ecba-ddb1-11e7-9154-cbe117ecf6bc.png)

##### Other information
* If i remove the loading component strategy, it uses the default which is `replace`, that's my current workaround.

* In the error image note that for a few `transforms`, for example the `75%` one tries to `transform: rotateX(...) rotate(...)`, note the last rotate, shouldn't be `rotateY` or `rotateZ`?

**Comment by kyleledbetter** [comment]
Try node 6.11.x. V9 isn't supported

**Comment by luchillo17** [comment]
So this is an issue with node version?

**Comment by kyleledbetter** [comment]
Possibly just caught my eye. Test with the supported version and see if that helps

**Comment by luchillo17** [comment]
No difference except i had to re-build deps.

**Comment by emoralesb05** [comment]
This CSS keyframe comes directly from the `mat-progress-spinner` so im not sure if there is much we can do.. we havent seen this error before so if you can create a plnkr or stackblitz to replicate it it would be appreciated to try and debug it.

**Comment by luchillo17** [comment]
Soo should i transfer this bug into Material repo?

**Comment by jotatoledo** [comment]
Currently using `overlay `in one of my projects will not hide the passed into `ng-template` through transclusion

**Comment by KerMiiTT** [comment]
I have exactly the same problem. I did not find a solution. I'm waiting for a post update.

**Comment by kyleledbetter** [comment]
Can you both make a Plunker or Stackblitz so we can test?

**Comment by emoralesb05** [comment]
So i actually think we fixed this a while back because i cant replicate it

https://github.com/Teradata/covalent/pull/973/files#diff-0d22f546d39ab49964181c6d6344e8a8R209

Can you all install the nightly build to test it?

**Comment by jotatoledo** [comment]
@emoralesb05  You can see my problem in the doc site actually. In the `[tdLoading] until template syntax with booleans` section, the mask doesnt overlay the elements inside of `ng-template`

**Comment by emoralesb05** [comment]
Ah, thats actually a change we did.. it only adds a background if its `circle`.. if its `linear` then it behaves that way since we wanted to follow the loading MD spec a bit more.

**Comment by emoralesb05** [comment]
@luchillo17 can you try our latest release? this should probably be fixed in that one.

**Comment by jotatoledo** [comment]
@emoralesb05 my bad, missed that point in the rc.0 release

**Comment by KerMiiTT** [comment]
for my part the latest version fixed the bug. Thx all

**Comment by emoralesb05** [comment]
Awesome, thanks for letting us know @KerMiiTT

**Comment by emoralesb05** [comment]
Closing this since it was fixed in rc.1
