### ISSUE TITLE
Custom Collection

### ISSUE THREAD

**Issue by nueko** [Teradata/covalent#1036]
Hello, it is may be just a discussion/question.

What about creating collection,
something like [@feloy/angular-cli-collection](https://github.com/feloy/angular-cli-collection) and written [here ](https://blog.angularindepth.com/creating-your-own-application-template-for-angular-cli-95e22319cc24)?

**Comment by jotatoledo** [comment]
- Use the issue template
- Explain yourself furthermore

**Comment by aciccarello** [comment]
Are you talking about a starter project? For that https://github.com/Teradata/covalent-quickstart

**Comment by nueko** [comment]
@aciccarello, something like that, but easier starter. something just like
```powershell
ng new --collection=@covalent/collection myapp --layout=dashboard
```

**Comment by aciccarello** [comment]
Sounds like something that would work well as part of the new [covalent-tools project](https://github.com/Teradata/covalent-tools)

**Comment by jeremysmartt** [comment]
I believe this is a duplicate of #1166

**Comment by jeremysmartt** [comment]
closing as duplicate #1166
