### ISSUE TITLE
Inconsistent spacing in notifications menu

### ISSUE THREAD

**Issue by freastro** [Teradata/covalent#1038]
#### Bug Report
The example for the Toolbar notification includes extra spacing in the header that's not visible in the Updates notification menu on the same page. It looks like the 'Updates' header does not have any margin while the 'Notifications' header has a bottom margin.

##### Screenshot
![notifications](https://user-images.githubusercontent.com/297631/34014557-72a330ec-e0d0-11e7-8f2e-cfc1f26d3acf.png)

#### What is the expected behavior?
Both should be displayed the same, probably without a margin.

#### What is the motivation / use case for changing the behavior?
Consistency across Covalent and Teradata apps.

#### Which version of Angular and Material, and which browser and OS does this issue affect?
You can `git checkout bddc8bf606e3d3bca5969b481d19cc3c0568cab2` to see the version of GitHub pages that had this issue. I saw this on macOS Sierra with Google Chrome 62.

**Comment by emoralesb05** [comment]
This actually happens because the `material` typography adds by default bottom-margin that we removed for the `update` one.. we need to do the same in the demo.

Thanks for the heads up.

**Comment by kyleledbetter** [comment]
@freastro change `<div td-menu-header class="mat-subheading-2">Notifications</div>` to `<div td-menu-header class="mat-subheading-2 push-none">Notifications</div>` for a workaround
