### ISSUE TITLE
[Design Pattern]: Loading indicators

### ISSUE THREAD

**Issue by aciccarello** [Teradata/covalent#1039]
#### Design Pattern Request
I would like to discuss patterns of when and how to use loading indicators.

[Covalent](https://teradata.github.io/covalent/#/components/loading), [Angular Material](https://material.angular.io/components/progress-spinner/overview), and the [Material Spec](https://material.io/guidelines/components/progress-activity.html#) all defined how to create progress spinners and progress bars. But there is not a lot of guidance on when to use which method of indicating progress.

- When to use a spinner vs a bar?
- When to **not** use a loading indicator?
- When to use a page level loading indicator?
- What to use to indicate card content loading?
- When to use an overlay?

**Comment by freastro** [comment]
I'm also looking for a design pattern around a similar use case. I have a form that when the user clicks submit it may take a couple seconds for the backend to send a response to the UI. I'd like to disable the submit button (to prevent multiple clicks) and use a loader to indicate to the user that something is happening. Should I put a spinner in the submit button? Or should I use a spinner that overlays the form? Or should I use a progress bar at the top of the page?

**Comment by aciccarello** [comment]
@freastro the [material spec](https://material.io/guidelines/components/progress-activity.html#progress-activity-types-of-indicators) shows how to integrate a circular loader with a Floating Action Button. But I'm not sure what you'd do if it's not an icon button. The two options that I think would make sense are a spinner overlay or a progress bar at top of page.

It is also worth noting that the [material progress bar](https://material.angular.io/components/progress-bar/examples) has a query mode which might be relevent for submitting a form.

**Comment by freastro** [comment]
Unfortunately, it's a form submit button and not a floating action button.

Here's an example of the spinner overlay. I had to add an extra div around mat-card-content and mat-card-actions to ensure the overlay covered both.
https://stackblitz.com/edit/covalent-1ttiu3

And here's an example of loading bar at the top of the page and the form button disabled. I couldn't see how to set the progress bar to query mode though.
https://stackblitz.com/edit/covalent-kdx1ga
