### ISSUE TITLE
Data table should report value of the invalid sortBy columnName

### ISSUE THREAD

**Issue by peter-gergely-horvath** [Teradata/covalent#1042]
### Do you want to request a *feature* or report a *bug*?
Feature Request
#### Feature Request

`td-data-table` component exposes `[sortBy]` bindable attribute. If this attribute contains an invalid value, a generic error message is emitted: "`[sortBy] must be a valid column name`"

For debugging purposes, it would be helpful if the message also included the incorrect `columnName` parameter passed. 

This should be trivial to implement, just change the 
`throw new Error('[sortBy] must be a valid column name');` to e.g. `throw new Error('[sortBy] must be a valid column name, but was: ' + columnName);` in the section below:

```
Object.defineProperty(TdDataTableComponent.prototype, "sortBy", {
        /**
         * sortBy?: string
         * Sets the active sort column. [sortable] needs to be enabled.
         */
        set: function (columnName) {
            if (!columnName) {
                return;
            }
            var column = this.columns.find(function (c) { return c.name === columnName; });
            if (!column) {
                throw new Error('[sortBy] must be a valid column name');
            }
            this._sortBy = column;
        },
```

**Comment by emoralesb05** [comment]
Thats a good point. Gonna add this as part of our RC stages.

**Comment by owilliams320** [comment]
this component is deprecated please use https://material.angular.io/components/table
