### ISSUE TITLE
Typo in Single upload input button example

### ISSUE THREAD

**Issue by JoshSchoen** [Teradata/covalent#1043]
#### Bug/Typo Report
Missing `</span>` in file upload example documentation. Closing tag should be just before `</ng-template>` I will create a PR for this.

##### Screenshots
<img width="988" alt="screen shot 2017-12-15 at 8 15 18 am" src="https://user-images.githubusercontent.com/8234649/34045877-8712b9ee-e170-11e7-9966-f69ab057f34a.png">

**Comment by emoralesb05** [comment]
Closing since this is already fixed
