### ISSUE TITLE
[BUG] TdChips with Autocomplete in mobile does not select

### ISSUE THREAD

**Issue by gputrick** [Teradata/covalent#1044]
#### Bug Report
Autocomplete options in mobile doesn't select.

![Teradata issue screen shot giff](https://media.giphy.com/media/3oxHQlL0uqBQgkQGtO/giphy.gif)

#### Which version of Angular and Material, and which browser and OS does this issue affect?

I'm using the latest release 1.0.0-rc.1

**Comment by emoralesb05** [comment]
Looks like the issue is that the `optionSelected` event of the `mat-autocomplete` is not triggered in mobile... going to debug it a bit more but looks like its a material issue. (upstream)

**Comment by ekoeryanto** [comment]
is it already in 1.0?

**Comment by c0desolut1ons** [comment]
Any news for this bug?
