### ISSUE TITLE
feature: time picker

### ISSUE THREAD

**Issue by jotatoledo** [Teradata/covalent#1054]
#### Feature Request

A simple time picker based on the material design specs.

#### What is the motivation / use case?

Same as https://github.com/Teradata/covalent/issues/849

##### Other information

An implementation of it for vuejs according to the material specs can be found here:
https://vuetifyjs.com/components/pickers#example-14

An implementation of it for angular according to the material specs can be found here:
https://github.com/SteveDunlap13/MaterialTimeControl

**Comment by jeremysmartt** [comment]
closing for duplicate of #1167
