### ISSUE TITLE
Extra Scrollbar in contacts template

### ISSUE THREAD

**Issue by franklloydteh** [Teradata/covalent#1062]
![screenshot-covalent-contacts-template stackblitz io-2018-01-03-17-40-19-523](https://user-images.githubusercontent.com/927229/34515432-0607314e-f0ad-11e7-8135-bfe9c43c2843.png)
 There is an extra scrollbar in the contacts template.

**Comment by lordKnighton** [comment]
@franklloydteh Are you still having this issue?

Working fine in Mac (High Sierra) - chrome,safari & firefox ✅

**Comment by franklloydteh** [comment]
Yes. It seems that the problems is when the number of contacts exceed what the screen can display. When that happens, you can scroll the top navbar (I guess the entire body) upwards. I am using windows  and these are my settings. 

![image](https://user-images.githubusercontent.com/927229/34754932-e94f2bde-f5fb-11e7-839b-9bf3f8460449.png)

**Comment by owilliams320** [comment]
These examples will be revised for future versions stay tuned
