### ISSUE TITLE
Select a row in a table & tabbed table

### ISSUE THREAD

**Issue by rajnaveenrajendran** [Teradata/covalent#1077]
I'm looking to select a single row in the data table component. The 'selectable' and 'multiple' of the data table component lets to select more than one row which is not what I'm looking for. Also, is there an option for displaying the table as tabs using the data-table component? 

#### Bug Report

StackBlitz template: https://stackblitz.com/edit/covalent
Plunker template: http://plnkr.co/edit/XhSrUWBw2RhCkXPoE4fn

#### Which version of Angular and Material, and which browser and OS does this issue affect?

Did this work in previous versions of Angular / Material?

**Comment by emoralesb05** [comment]
Just remove the `multiple` attribute and it will select only one.

What do you mean data-table as tabs?

**Comment by rajnaveenrajendran** [comment]
I tried removing multiple attribute but it did not help. Still I'm able to select multiple rows with check boxes. The attachment is the current behavior:
![current behavior](https://user-images.githubusercontent.com/35467135/34963947-ea810740-f9ff-11e7-889f-a9d8a5ecd23c.png)
The following is the expected behavior:
![expected behavior](https://user-images.githubusercontent.com/35467135/34963965-00d4f24a-fa00-11e7-864d-4151ae784129.png)
Is there a way to achieve it using data-table component?

Please ignore my clarification about table with tabs. I found an alternative for that.

**Comment by emoralesb05** [comment]
The checkboxes will still appear on either case, but you can only select one.. if you select another one the previous selection is unselected.. this is because thats the Material Design spec on data-table selection.

**Comment by jeremysmartt** [comment]
closing as question answered no traction in 9 months
