### ISSUE TITLE
bug(tdFileDrop): no way to remove .drop-zone flag

### ISSUE THREAD

**Issue by quanterion** [Teradata/covalent#109]
tdFileDrop directive adds .drop-zone class on (dragenter). And I expect .drop-zone class to be removed after user released mouse button and  (fileDrop) event emitted. However It doesn't happen and I can't find a way to do it manually.

**Comment by emoralesb05** [comment]
Hey @quanterion,
Can you provide more info on the example? Since its supposed to remove it on `dragleave`, although the ripple in the button might affect it since we have a target validation (which we might need to remove because of the ripple background).

**Comment by emoralesb05** [comment]
oh! nvm, just replicated it haha we never noticed cause we use it inside the `td-file-upload` component.

Thanks for the heads up!
