### ISSUE TITLE
Build error with Angular 5.2 & fullTemplateTypeCheck enabled

### ISSUE THREAD

**Issue by Enngage** [Teradata/covalent#1094]
Hi guys,

I noticed that when you enable `fullTemplateTypeCheck` and try building the project with `ng build --aot` you get a bunch of errors due to incorrect accessibility of some properties within the library such as:

![b](https://user-images.githubusercontent.com/7137351/35030619-f21842c8-fb5f-11e7-8e51-83b9a825f0da.png)

**Comment by emoralesb05** [comment]
Thanks for the heads up, we will test soon.

**Comment by emoralesb05** [comment]
Ok, so we d have some `fullTemplateTypeCheck` issues, but the ones you found are actually on your side of the code.. `files` doesnt exist anymore in `TdFileUploadComponent` as mentioned in our changelog..
