### ISSUE TITLE
fix(data-table): height

### ISSUE THREAD

**Issue by gozeon** [Teradata/covalent#1098]
#### Bug Report

StackBlitz template: https://stackblitz.com/edit/covalent
Plunker template: http://plnkr.co/edit/XhSrUWBw2RhCkXPoE4fn

### Description
Why is height +1 [here](https://github.com/Teradata/covalent/blob/develop/src/platform/core/data-table/data-table.component.ts#L426)?  This means that there will be 1px of redundancy for each line displayed and 1000px for 1000 lines. . .

**Comment by emoralesb05** [comment]
the row border (`1px`) is taken into account for the row height.. so we have to add it in the calculations.
