### ISSUE TITLE
i18n hooks

### ISSUE THREAD

**Issue by kyleledbetter** [Teradata/covalent#110]
Just wanted to add this to start thinking of how we and make internationalization easier/abstracted in Covalent. Obviously optional, but if i18n is configured to be on, it's easy to just drop translated files into a languages directory and have the UI use them

**Comment by kyleledbetter** [comment]
https://angular.io/docs/ts/latest/cookbook/i18n.html

**Comment by emoralesb05** [comment]
Closing since we already follow being able to support string interpolation (or inputs) in https://github.com/Teradata/covalent/issues/324
