### ISSUE TITLE
chips bug not handling long text content well

### ISSUE THREAD

**Issue by stevenov7** [Teradata/covalent#1102]
### Do you want to request a *feature* or report a *bug*?
bug

#### Bug Report
- Found this issue in AppCenter while working on restyling the "adding user flow/chips as an admin", put a temp fix atm into AppCenter need to remove it after this fix gets in.
- [ ] Go here https://teradata.github.io/covalent/#/components/chips
- [ ] Scroll down to the "Stacked chips and Autocomplete with custom inputs"
- [ ] Inspect the text within one of the chips (EX: "stepper" text chip)
- [ ] Enter a long string though the inspector, you should see that the chips looks odd (see gif below)

##### Screenshots or link to CodePen/Plunker/JSfiddle
![rec](https://user-images.githubusercontent.com/24550592/35303889-6b934250-0048-11e8-8a3b-0f7a900df941.gif)

#### What is the expected behavior?
- The chips should be able to handle long text along at the same time using `td-chip-avatar`

#### What is the motivation / use case for changing the behavior?
- Conflicting override styles in AppCenter (note: `span`):
```
// AppCenter styles.scss
// fix for long strings in chips
.td-chip {
  span {
    white-space: nowrap;
    text-overflow: ellipsis;
    overflow: hidden;
  }
}

//html
<td-chips ...>
        <ng-template td-chip let-chip="chip">
          <div class="tc-grey-100 bgc-teal-700" td-chip-avatar>{{chip.initials}}</div>
          <span class="mat-caption">{{ chip.nameInfo }}</span>
        </ng-template>
      </td-chips>
```
cause issues to the `td-chip-avatar` too look like its being cut in half issue appears to be coming from the these styles being applied to the internal <td-chips> `span`s. If we change in AppCenter the `span` css selector to be more specific like below. The issue does not occur but another issue arise with long text and the per chips "X" remove button.
 ```
// AppCenter styles.scss
// fix for long strings in chips
.td-chip {
  .chip-ellipsis {
    white-space: nowrap;
    text-overflow: ellipsis;
    overflow: hidden;
  }
}

//html
<td-chips ...>
        <ng-template td-chip let-chip="chip">
          <div class="tc-grey-100 bgc-teal-700" td-chip-avatar>{{chip.initials}}</div>
          <span class="chip-ellipsis mat-caption">{{ chip.nameInfo }}</span>
        </ng-template>
      </td-chips>
```

#### Which version of Angular and Material, and which browser and OS does this issue affect?
Covalent: 1.0.0-rc.2
Angular Material: 5.0.4
Chrome/Mac

Did this work in previous versions of Angular / Material?
No

**Comment by kyleledbetter** [comment]
We need this CSS to emulate `flex="none"` on the td-chip-avatar

```css
    -webkit-box-flex: 0;
    -webkit-flex: 0 0 auto;
    flex: 0 0 auto;
    box-sizing: border-box;
```

**Comment by kyleledbetter** [comment]
as for the long text you're already in a custom template so in that template just use a `class="text-truncate"` around the text
