### ISSUE TITLE
readme reader goes bold on 2nd level titles

### ISSUE THREAD

**Issue by lincze** [Teradata/covalent#1103]
#### Bug Report

after the last release, the flagship https://teradata.github.io/covalent/ app may switch 2nd level md titles to bold from a point. E.g.

![screenshot at 2018-01-24 16-12-44](https://user-images.githubusercontent.com/4760711/35339669-791693ee-0121-11e8-913a-40f2de314534.png)

----
i do like the principle to provide leaf pages of the documentation by rendered md's. it is more usable (readable off line in a text editor, can be printed, it is handy in an IDE, etc.), and i would use it whenever it is possible, with a unified style according to the docs text structure. So, one could avoid other structuring/styling problems (for me, not really obvious, when does a section start with 1st level md titles /e.g. in 'Getting Started' or in 'Quick Start Repo'/ and when with 2nd level md titles /e.g. in 'Utility SAAS Mixins'/ and how they relate to stylings when the text comes from html /e.g. material card title in the 'Angular', or 'Angular Material' page/).

**Comment by aciccarello** [comment]
I wonder if this is related to material typography changes and the roboto associated font weights being loaded.

**Comment by emoralesb05** [comment]
This was due styles we added internally.. we just removed that style from `td-markdown` so all headers should act as normal now.
