### ISSUE TITLE
ie 11 preformance with angular cli.json "styles"

### ISSUE THREAD

**Issue by yaronmil** [Teradata/covalent#1110]
when using the angular cli with this configuration :

.angular-cli.json

"styles": [
  "../node_modules/@covalent/core/common/platform.scss"
],

ie 11 has very poor preformance

**Comment by emoralesb05** [comment]
Yup, this is because the `layout` attribute CSS rules arent really great for IE11.. if you dont want to use them you can cherry pick the CSS and not include those.

Check this for more information https://teradata.github.io/covalent/#/docs/utility-sass-mixins

**Comment by aciccarello** [comment]
See #845 for a related discussion.

Using [`@angular/flex-layout`](https://github.com/angular/flex-layout) has decent performance in IE.
