### ISSUE TITLE
Firefox bug - td-data-table selectable

### ISSUE THREAD

**Issue by AliceCasari** [Teradata/covalent#1123]
Only in Firefox, when i select a row (with checkbox) the click on row is triggered!!

**Comment by AliceCasari** [comment]
This happen even on your site: if I try to check a row (so table with selectable rows case), instead of checking the chekbox, the click on the row is fired so I will never be able to select the rows I want. Please answer me!

**Comment by Axeirt** [comment]
Same problem here.

**Comment by grissivu** [comment]
Same problem here! Very annoying! Please fix asap!!!!!

**Comment by jeremysmartt** [comment]
I have tried to duplicate this issue with Firefox but cannot seem to.  Here is a gif of it working, @AliceCasari @Axeirt @grissivu can you provide one of it not working so I can see the behavior?

![select](https://user-images.githubusercontent.com/10502797/42708347-e24f781c-8691-11e8-9d9b-464f68fee8cf.gif)
