### ISSUE TITLE
Card Pattern - points to wrong stackblitz

### ISSUE THREAD

**Issue by pabloxn** [Teradata/covalent#1125]
*Bug*

The link  on the card Patterns page to stack blitz points to the wrong page:

https://stackblitz.com/edit/card-patterns

whereas it should point to:

https://stackblitz.com/edit/cards-patterns

minor bug - thought you should know - cheers for all the work you have all done so far.

**Comment by jennmedellin** [comment]
This is resolved by making a Stackblitz at card-patterns
