### ISSUE TITLE
DynamicForm doesn't show custom errors after submit

### ISSUE THREAD

**Issue by berga** [Teradata/covalent#1130]
As discussed on gitter I'm unable to display custom errors in dynamic form components
via `control.setErrors({...})` (eg. when I receive server-side validation errors) 
until the input get focus or user clicks on the input with error.

errors have been set via the suggested TemplatePortal:

```
<ng-template let-element ngFor [ngForOf]="elements">
  <ng-template let-control="control" [tdDynamicFormsError]="element.name">
...
```

I've made a StackBlitz template: 

https://stackblitz.com/edit/covalent-dynamic-forms-2jypqc

showing the error and a pure Material/Angular solution with FormGroup.

It seems to be a change detection issue.

**Comment by berga** [comment]
I've updated the template to Angular 6 and Covalent 2 but the error still exists:

https://stackblitz.com/edit/covalent-dynamic-forms-angular-6-1sy243

**Comment by gitsby** [comment]
@berga Hello. 

I have faced with the same problem today. I solved it but not so elegant decision (in my opinion). I noticed, that errors showed only after clicked for some form element. 

In my component where i used dynamic form, i injected ElementRef.
When i set errors, i invoke focus() method from the first input.


`
this.el.nativeElement.getElementsByTagName("input")[0].focus();   `

**Comment by MRMokwa** [comment]
I'm having the same issue, any updates on this?

**Comment by emoralesb05** [comment]
Yeah, seems like change detection issue. Ill get someone from the team to look at this.

**Comment by emoralesb05** [comment]
BTW, does it still happen with the latest version? Since we started using `mat-error` now

**Comment by MRMokwa** [comment]
Yes, I'm using the latest versions:

> "@covalent/core": "^2.0.0-beta.4",
> "@covalent/dynamic-forms": "^2.0.0-beta.4",

As a temporary solution I used the solution that @gitsby suggested, but I don't need to call `this.ref.detectChanges()` as @berga did on his plunker, but `setTimeout()` is a must to make it work.

```
  private setServerSideErrors(err: HttpResponse<any>) {
    const dForm: TdDynamicFormsComponent = this.formComponent.dynamicForm;
    let setFocus = false;

    setTimeout(() => {
      for (const key of Object.keys(err.body)) {
        const control = dForm.controls[key];
        control.setErrors({ server: err.body[key] });
        control.markAsTouched();

        // Only need to focus once to make it work
        setFocus = !setFocus ? this.setFocus(key) : true;
      }
    }, 10);
  }

```
```
private setFocus(key: string): boolean {
    const elem = document.getElementById(key);

    const input = <HTMLInputElement>elem.getElementsByTagName('input')[0];
    const select = <HTMLSelectElement>(elem.getElementsByTagName('mat-select')[0]);

    const object = input || select;

    if (object) {
      object.focus();
      return true;
    }

    return false;
  }
```

Response example:
```
{
   status: 400,
   body: {
      name: ['Choose another name']
   }
}
```
