### ISSUE TITLE
Angular 6 & rxjs 6

### ISSUE THREAD

**Issue by Enngage** [Teradata/covalent#1133]
Hey,

Any chance you can start preparing for Angular 6 with rxjs 6? I've recently updated my project to rxjs 6 only to found out that I can no longer compile the solution:

![aa](https://user-images.githubusercontent.com/7137351/38022115-f3922848-327e-11e8-9997-eb8b8bf615ef.png)

This happens also with the [rxjs-compat ](https://www.npmjs.com/package/rxjs-compat) package installed.

Edit: The workaround I managed to get it working was  `node_modules\@covalent\core\esm5\covalent-core.js` 

```javascript
import { toPromise } from 'rxjs/operators/toPromise';
```
to

```javascript
import 'rxjs/add/operator/toPromise';
```

This seems like an issue with rxjs library which I raised in their repo.

**Comment by emoralesb05** [comment]
Yup, we are gonna start again with the `beta` process getting ready for `angular 6`.. so expect this soon 😄

**Comment by Enngage** [comment]
Awesome, happy to hear that :-)

**Comment by emoralesb05** [comment]
Just FYI, started the process here https://github.com/Teradata/covalent/pull/1136 but we still have to test and fix a few things 😄
