### ISSUE TITLE
td-data-table / ng-template unusable for dynamically updated data with vertical scrolling

### ISSUE THREAD

**Issue by brent-williams** [Teradata/covalent#1143]
### Do you want to request a *feature* or report a *bug*?
Bug
#### Bug Report

When td-data-table / ng-template data is updated the vertical scroll is reset.  td-data-table seems therefore practically useless in the simple circumstance of:
1. dynamically updating the data and 
2. allowing the user to vertically scroll through the data.  

##### Screenshots or link to CodePen/Plunker/JSfiddle
Illustration captures table updated every second.  User tries to scroll through, data updates, vertical scroll is reset.  
![2018-04-20 17 50 00](https://user-images.githubusercontent.com/1694687/39037626-64e9adac-44c4-11e8-9318-26afc4619e51.gif)

#### What is the expected behavior?
Provide some method to update the table data without resetting the vertical scroll.  [ngForTrackBy] may be a solution but it is used with *ngFor, which isn't exposed (?) by td-data-table.

#### What is the motivation / use case for changing the behavior?
Table unusable when combining dynamically updated data and vertical scrolling.

#### Which version of Angular and Material, and which browser and OS does this issue affect?
`@covalent/core 1.0.0`
`@angular/common 5.2.10`

Did this work in previous versions of Angular / Material?
Not that I'm aware of

**Comment by emoralesb05** [comment]
Thanks for the report, we will look into this!

**Comment by brent-williams** [comment]
Hi @emoralesb05 I tried to find a solution on [stackoverflow](https://stackoverflow.com/questions/49770271/how-to-maintain-vertical-scroll-when-updating-angular-5-data-table).  Even with a bounty no accepted solution other than:
1. Use `td-data-table-column-row/column` where `*ngFor` is available but then of course loosing all the nice template, sticky headers, etc. or
2. Use some other table altogether.  

I'll shortly have to take one of these options and abandon the considerable time invested in `td-data-table/ng-template`.

**Comment by brent-williams** [comment]
Gave up, switched to https://material.angular.io/, works fine now.
