### ISSUE TITLE
Hi, please ai dont do this works. I fallow your starter guide, but not works! i tru to clone the starter guide project in git, but its not fine to me. can you helpe me?

### ISSUE THREAD

**Issue by dannieljunior** [Teradata/covalent#1149]
#### Bug Report

StackBlitz template: https://stackblitz.com/edit/covalent

#### Which version of Angular and Material, and which browser and OS does this issue affect?

Did this work in previous versions of Angular / Material?

**Comment by jeremysmartt** [comment]
if still having problems please ask question in gitter channel
