### ISSUE TITLE
Incorrect Data Table Sort Order for Numeric Data

### ISSUE THREAD

**Issue by fxstein** [Teradata/covalent#115]
#### Bug Report

Data Table component does not sort numeric data correctly.
As seen here: https://teradata.github.io/covalent/#/components/data-table
##### Screenshots or link to CodePen/Plunker/JSfiddle

![screen shot 2016-10-24 at 11 07 53 am](https://cloud.githubusercontent.com/assets/773967/19657826/86a305ce-99da-11e6-9a15-2d2f284cd939.png)
#### What is the expected behavior?

When sorting a numeric column, smaller number should come before larger number when sorted ascending and vice versa. 

Hope this helps!

**Comment by emoralesb05** [comment]
Huh, its doing `string` sorting. 
Sorry we didnt notice this before, i will add this as a priority for this release. 

Thanks for letting us know!

**Comment by emoralesb05** [comment]
Fixed in https://github.com/Teradata/covalent/pull/128 while abstracting the local sort into `TdDataTableService`

**Comment by fxstein** [comment]
Thank you!

**Comment by zeeshangithub** [comment]
i need some help about integrating covalent in ng2 manually

**Comment by emoralesb05** [comment]
You can ask in our gitter channel for support questions or additional info.

https://gitter.im/Teradata/covalent
