### ISSUE TITLE
Covalent HTTP Service question

### ISSUE THREAD

**Issue by lincze** [Teradata/covalent#1150]
#### Feature Request (a Question)

I'm just curious, what would be the fate of the Covalent HTTP Service, as it is based in the old @angular/http, which is deprecated (almost revoked, but not yet) in 6.0. (I've used e.g. the RestService). Is it a better bet to replace it with some code (based on the @angular/common/http), or there would be some kind of replacement.

**Comment by emoralesb05** [comment]
Thats a very good question, and whats gonna happen is that we are probably gonna change it under the covers to use `HttpClient` very soon and introduce some changes.. 

We just started our beta process again for 2.0.0, so those changes will start soon 😄

**Comment by jeremysmartt** [comment]
httpclient will be replaced with a restclient soon, leaving this issue for now
