### ISSUE TITLE
[IE11/Edge] - ng6 - after toggling nav drawer, the sidenav contents are hidden and cant be restored

### ISSUE THREAD

**Issue by jaa1982** [Teradata/covalent#1153]
#### Bug Report

In IE11 or Edge , when opening the sidenav and toggle to the navigation drawer, the td-navigation-drawer-menu items are not displayed, and the sidenav's contents can not be restored . It works fine in Chrome

This is in angular/material@6.0.2 and covalent@2.0.0beta.1

##### Screenshots or link to CodePen/Plunker/JSfiddle

Open normal stackblitz in IE11 or Edge

https://covalent.stackblitz.io/

![covalent - sidenav issue in ie and edge](https://user-images.githubusercontent.com/12563163/40131818-9c7f7b2a-5900-11e8-9ae8-7c528f3eed15.gif)

#### What is the expected behavior?

Toggling to navigation drawer should display nav-drawer items, and not hide regular sidenav content items

#### Which version of Angular and Material, and which browser and OS does this issue affect?

Did this work in previous versions of Angular / Material?

Yes, worked in covalent@1.0.0 and material@5.2.5

##### Other information

From material changelog [6.0.0-beta.5](https://github.com/angular/material2/blob/master/CHANGELOG.md#600-beta5-2018-03-23)

> sidenav: The MatDrawerToggleResult class has been turned into an type.
> The promise returned from open, close and toggle now resolves with the MatDrawerToggleResult type rather than the class.

Believe the change is affecting this line

https://github.com/Teradata/covalent/blob/feature/cli-6/src/platform/core/layout/navigation-drawer/navigation-drawer.component.ts#L178

**Comment by jaa1982** [comment]
Hi @emoralesb05  , first, thanks for the great library. Covalent has been a huge benefit for us,  we really appreciate your contributions

I saw this has a needs repro label on it.  Did you have any issue replicating? I'm able to consistently reproduce in both IE11 and Edge on stackblitz using the stock starter on Win 10 OS

https://covalent.stackblitz.io/

If you have any any update it would be much appreciated, this is the last thing holding us back from upgrading to ng6, and 2.0.0-beta.1  . Thank you

**Comment by jaa1982** [comment]
@emoralesb05  , I put some work into trying to nail this down. Looks like root cause is actually an with tdCollapse animation in IE11 and Edge . I'm not very familiar with how animations work or I'd attempt a fix  , but hope this helps

**Comment by emoralesb05** [comment]
Awesome! Thanks for this.

**Comment by AliceCasari** [comment]
Same bug on Safari!!

**Comment by jaa1982** [comment]
Issue is due to https://github.com/angular/angular/issues/23915

You can see in screenshot that element animation doesnt complete , hence display stays 'none'

I'll add comment in angular that issue is also present on IE11 and Edge

![image](https://user-images.githubusercontent.com/12563163/40675183-9f2dfb62-633c-11e8-9025-9055a79a0442.png)

**Comment by sudheerdixit-kiwi** [comment]
I have done using CSS & Its working on all browser, Below are my Code.

______________
div.td-navigation-drawer-menu-content.ng-trigger.ng-trigger-tdCollapse{
display: block !important;
animation: gen_css_kf_101 150ms linear 0ms 1 normal forwards running; 
}
div.td-navigation-drawer-content.ng-trigger.ng-trigger-tdCollapse.ng-animating{
display: block !important; 
height: auto !important; 
animation: gen_css_kf_101 150ms linear 0ms 1 normal forwards running;
}
______________
