### ISSUE TITLE
Stackblitz Sandbox App

### ISSUE THREAD

**Issue by jennmedellin** [Teradata/covalent#1164]
Add Stackblitz demos for
Patterns
Info
Repo: https://github.com/jennmedellin/covalent-sandbox

- [ ] Breadcrumb based on https://stackblitz.com/edit/sidesheet-filters-fqu78h
- [ ] Contextual Docs based on https://stackblitz.com/edit/contextual-docs-sw14j8
- [ ] Side Sheet
- [ ] Filters: https://stackblitz.com/edit/sidesheet-filters
- [ ] Side sheet: Summaries and Logs 
- [x] Stepper Form 
- [x] Alerts
- [x] Cards > Update
- [x] Alerts > Update
- [x] Management List CRUD > Update
- [x] Nav Drawer Patterns > Update
- [x] FAB > Replace w/new creation flow
- [x] Steppers > move to components
- [x] Empty state > update

Layouts
- [x] Nav view
- [x] Nav list
- [x] Card Over
- [x] Management List

**Comment by lordKnighton** [comment]
@jennmedellin if you need any help with this, tap me in for a few components. If you could use a hand, do let me know 😸

**Comment by jennmedellin** [comment]
See also https://github.com/Teradata/covalent/issues/1169, which will be covered here

**Comment by jennmedellin** [comment]
Transcribed to https://github.com/Teradata/covalent-resources/issues/10
