### ISSUE TITLE
docs: improve navigation

### ISSUE THREAD

**Issue by jotatoledo** [Teradata/covalent#1169]
#### What is the current behavior?

Although the current docs are complete and well written, there are almost no direct links or quick-jumps to specific sections of a component documentation, eg API or examples.

#### What is the expected behavior?

Improve the navigation concept and accessibility of docs by adding direct links to the subsections (cards) of all the components. Furthermore, this links should be collected in a list that is visible at all times, allowing quick nav. to sections instead of scrolling.

#### What is the motivation / use case for changing the behavior?

Revisiting specific sections of a component doc should be a quick process.

##### Other information

Take as example the material docs site. Every component has nav list on the right side, allowing navigation to specific sections of the view.

**Comment by emoralesb05** [comment]
Great point, we are actually in the midst of the Covalent 2.0.0 planning, and this could be a perfect improvement to the documentation.

**Comment by jeremysmartt** [comment]
This is related to #1164

**Comment by jennmedellin** [comment]
This will be covered by https://github.com/Teradata/covalent/issues/1164

**Comment by jennmedellin** [comment]
Oh, this is beyond the scope of the sandbox changes, sorry!

**Comment by jeremysmartt** [comment]
closing in favor of #1418
