### ISSUE TITLE
Error with slice in DataTable

### ISSUE THREAD

**Issue by Gnorro** [Teradata/covalent#1174]
### Do you want to request a *feature* or report a *bug*?
bug

#### Bug Report
Use a DataTable with slice in [data]:
`<td-data-table *ngIf="returnsData.length > 0" [data]="returnsData.slice(from, to)" [columns]="returnsColumns" #returnsTableList clickable="true" 
        (rowClick)="selectRow($event)">
      <ng-template tdDataTableTemplate="id" let-value="value">
        <strong>{{ value }}</strong>
      </ng-template>
      <ng-template tdDataTableTemplate="createTime" let-value="value">
            {{ value | date:'dd/MM/yyyy'}}
      </ng-template>
      <ng-template tdDataTableTemplate="lastUpdateTime" let-value="value">
            {{ value | date:'dd/MM/yyyy HH:mm'}}
      </ng-template>
      <ng-template tdDataTableTemplate="orderId" let-value="value">
        {{ value }}
      </ng-template>
      <ng-template tdDataTableTemplate="invoiceId" let-value="value">
        {{ value }}
      </ng-template>
      
      
      <ng-template tdDataTableTemplate="statusDescription" let-value="value">
        <span [innerHTML]="value"></span>
      </ng-template>
      <ng-template tdDataTableTemplate="code" let-value="value">
        <mat-icon svgIcon="search" [routerLink]="['../rma/' + value]"></mat-icon>
      </ng-template>
    </td-data-table>`

#### What is the expected behavior?
DataTable display data

#### Which version of Angular and Material, and which browser and OS does this issue affect?
`Angular CLI: 6.0.7
Node: 8.11.2
OS: win32 x64
Angular: 6.0.3
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.7
@angular-devkit/build-angular     0.6.7
@angular-devkit/build-optimizer   0.6.7
@angular-devkit/core              0.6.7
@angular-devkit/schematics        0.6.7
@angular/cdk                      6.2.0
@angular/cli                      6.0.7
@angular/material                 6.2.0
@ngtools/webpack                  6.0.7
@schematics/angular               0.6.7
@schematics/update                0.6.7
rxjs                              6.2.0
typescript                        2.7.2
webpack                           4.8.3`

Did this work in previous versions of Angular / Material?
Yes, in angular 4

##### Other information
Without .slice(from, to) it works

**Comment by jeremysmartt** [comment]
I don't believe you want to do it this way.  Instead have it so in html you have:
`<td-data-table [data]="slicedData"`
Then in Typescript have:
```
async ngOnInit(): Promise<void> {
    this.returnsData = await functionThatGetData().toPromise();
    this.slicedData = this.returnsData.slice(0, 10);
 }
```
