### ISSUE TITLE
Update covalent docs to be able to toggle between different major @covalent versions (EX: v1.x.x vs v2.x.x docs)

### ISSUE THREAD

**Issue by stevenov7** [Teradata/covalent#1177]
Premise: Developer was trying to get started with covalent@1.x.x because their customer did not want to use covalen@2.x.x because it was still in `beta` and was having trouble getting setup because the docs were not version proofed.

Associated with Pavel Ermakov (developer) reported having issues getting started with covalent@1.x.x stable, which supports angular@^5.2.x, in the Covalent slack channel. The current docs/instructions to setup covalent are "more" targeted towards how to setup covalent@2.x.x, which support angular@^6.x.x, but covalent@2.x.x is not yet stable (beta-2). The Covalent docs say to install the latest `@angular/cli` in the docs (this gives the developer the latest version of angular that is support by the cli in this case it was angular@6.x.x) but when using covalent@1.x.x docs/instructions should actually say use `@angular/cli@1.7.4` which support angular@^5.2.x.

We need to look at having different version of Covalent docs (Angular and Angular material do this by having a dropdown to select which version of the docs you want to see) so developers don't have these versioning issues when just trying to get started.  

Start of slack convo with Pavel Ermakov about the issue: https://teradata.slack.com/archives/C17U55B4K/p1528581353000014

**Comment by emoralesb05** [comment]
Dup of https://github.com/Teradata/covalent/issues/1593
