### ISSUE TITLE
Navigational Stepper

### ISSUE THREAD

**Issue by richavyas** [Teradata/covalent#1179]
## Design
[Design Document](https://docs.google.com/document/d/1kKaraKteHcjgUBzAhlT2M7R8BEl1hkP6sknrSA2AL9s/edit?usp=sharing)

**Comment by jotatoledo** [comment]
Im almost sure that I saw this concept sometime ago in a github repository.

**Comment by emoralesb05** [comment]
Yeah, we just found out that the current `horizontal` implementation of the stepper doesnt make much sense.. and it makes more sense when you introduce routing.. 

One of our teams in teradata hacked it to work that way and we were like.. well.. we should probably create a component to make it easier haha
