### ISSUE TITLE
Tree Component

### ISSUE THREAD

**Issue by emoralesb05** [Teradata/covalent#118]
#### Feature Request

Tree component for menus and parent child viz.
##### Screenshots or link to CodePen/Plunker/JSfiddle

![image](https://cloud.githubusercontent.com/assets/5846742/19710958/0afd96b0-9ae7-11e6-8393-11e2fa6006d5.png)
#### What is the expected behavior?

It should be flexible enough to be able to create a menu with nodes/leafs and bind any kind of events to it, following material design.
#### What is the motivation / use case for changing the behavior?

Used to show parent/child relationships for databases/tables/columns , etc etc

**Comment by aciccarello** [comment]
:+1:  Currently working on an Angular 1 version of this for an IT application. Would love to have a set of Covalent components to do this if we migrate.

**Comment by thomaslennan** [comment]
You've probably already considered all these features, but figured I'd write them down anyway...

Here are a set of features that would be good to have in the tree. I don't see a use case for horizontal tree, but I know you guys have a use case elsewhere.

### Basic Look and Feel

- Label
- Open Icon
- Closed Icon

### Required Events

In all cases, report item(s) effected.

- Single and multi-select
- Double click
- Right click
- Item expand

### Optional Actions

- Search/Filter content
- Expand all
- Collapse all
- Expand to level/item

**Comment by ajitsonlion** [comment]
Cool, I am using covenant in our project, but for tree component ended up using 
https://angular2-tree.readme.io/docs, 
had to customize the looks to material, but really liked the API and customization they provided.
I could suggest that we keep loading tree nodes async also in list of features :)

**Comment by quanterion** [comment]
https://github.com/angular/material2/issues/3175

**Comment by jmls** [comment]
@ajitsonlion : would you care to share your material customisations ?

**Comment by harsha00790** [comment]
@emoralesb05 
![covalent_tree](https://user-images.githubusercontent.com/2087076/30597681-5c87d414-9d75-11e7-8430-1f4e67793aeb.gif)

Created a material style tree on top of the angular2-tree component. Its material styled and the checkboxes, icons are all configurable.
If this is something similar to what you; re looking for .. let me know... I'll assign it to myself and work on the PR

**Comment by omar-nassar** [comment]
@harsha00790 are you planning to share your materialized style customization? they looks awesome, and I encourage you to do so.

Thanks!
