### ISSUE TITLE
Search is not correctly aligned, I have the fix

### ISSUE THREAD

**Issue by ranouf** [Teradata/covalent#1181]
Hi,

Packages:
"@covalent/core": "2.0.0-beta.1",

As you can see, the search is not correctly aligned:
![image](https://user-images.githubusercontent.com/1764519/41556134-d7383ee8-7307-11e8-8a68-9a1fa7e81dea.png)

To fix it, in styles.scss:
```
td-search-box .mat-form-field-appearance-legacy .mat-form-field-infix {
  padding-bottom: inherit;
  padding-top: 5px !important;
}
```

Covalent team, can you please update the package to fix this issue?

**Comment by emoralesb05** [comment]
Thanks, noticed this also. Will relay this to the team so we can fix it.

**Comment by ranouf** [comment]
My first fix ;) #proud
