### ISSUE TITLE
[Bug] Datatable inside mat-tab not visible until scroll

### ISSUE THREAD

**Issue by kkulikowski** [Teradata/covalent#1189]
### Do you want to request a *feature* or report a *bug*?
Bug

#### Bug Report
1. Go there - https://teradata.github.io/covalent/#/components/data-table
2. look for table with title "Data table with components
3. Scroll table a bit (important!)
4. Go to Code tab
5. Go back to Demo tab
6. you won't see any data until you scroll a bit (look for the first data table you can see (or not) here. It is the selected table, it appears much lower than it should.
![zrzut ekranu 2018-07-08 o 00 04 47](https://user-images.githubusercontent.com/6926970/42415016-ff9d4690-8242-11e8-912a-8d921cce5a3d.png)

#### What is the expected behavior?
Data is always visible, no need to scroll after switching tabs

#### What is the motivation / use case for changing the behavior?
It's not working corectly i guess :)

#### Which version of Angular and Material, and which browser and OS does this issue affect?
The one that is used in docs. Localy i have Angular 5.2.3, Material 5.2.3, Covalent core 2.0.0-beta.2
Did this work in previous versions of Angular / Material?
Yes
##### Other information
I guess there is something wrong with virtual scroll, but i'm not sure yet.
What i found out is that after switching tabs (with scrolling previously) TranslateY should be opposite to Height (you can see it on screenshots below). When transform === -height it's all working well, but it appears that after re-rendering after clicking on tab transform is wrong.
![zrzut ekranu 2018-07-08 o 00 17 09](https://user-images.githubusercontent.com/6926970/42415099-b49ea2e0-8244-11e8-990a-13170b99551d.png)
![zrzut ekranu 2018-07-08 o 00 16 49](https://user-images.githubusercontent.com/6926970/42415100-b4bc9912-8244-11e8-8f7c-520bd0f9218b.png)
So there goes another edit..
I'm not sure, but i guess there is an issue here (covalent-core-data-table.js):
`        if (scrolledRows > TD_VIRTUAL_OFFSET) {
            for (var index = 0; index < this.fromRow; index++) {
                offset += this._rowHeightCache[index];
            }
        }
        this._offsetTransform = this._domSanitizer.bypassSecurityTrustStyle('translateY(' + (offset - this.totalHeight) + 'px)');` I think that scrolledRows is not 0 here, probably because some variable that is used to set scrolledRows is not re-set, it's kept as it was or something..

**Comment by pavansai1** [comment]
@kkulikowski facing the same issue. Did you find any solution? If so please do share.
