### ISSUE TITLE
Data-Table: Server-side paging and sorting

### ISSUE THREAD

**Issue by crain** [Teradata/covalent#119]
This repository's issues are reserved for feature requests and bug reports.
#### Feature Request

It should be possible to use server-side paging and sorting with the data table component.
#### What is the motivation / use case for changing the behavior?

Currently it is not possible to page and sort over large datasets as all data needs to be present in the client browser. I would have to load all records from my backend at once to the data table component.
##### Other information

Suggestion:
The developer could hook in his own backend calls and reload data from the backend based on page/sort events:

@Output() sortChanged(already available)
@Output() pagingChanged(missing)

**Comment by emoralesb05** [comment]
We are currently working on building smaller components like `paging-bar`, `search-box`, etc etc so you could either use the `local` `data-table` or build your own with server paging/sorting.

**Comment by crain** [comment]
OK that sounds like a good seperation. Do you have a list what other things you are planning for the data table?

I am asking because there are some tiny features missing which could be useful such as:

- event emitter on row selection
- single row selection without checkboxes
- rendering of buttons within the grid

Let me know if I should create seperate feature request for those.

**Comment by emoralesb05** [comment]
Probably separate the `<td-data-table>` into a wrapper, headers and rows (still looking if its possible). So it gives the flexibility to implement anyway you want, while still providing a `<td-local-data-table>` that works like it works atm. (Or something like that)

We are trying to see what works best for this particular component.

**Comment by emoralesb05** [comment]
Btw, we are working together with one contributer (gistia) atm to allow template rendering in the data-table. So you will be able to add icons, buttons or w/e you want.

**Comment by emoralesb05** [comment]
Closing since it was addressed in https://github.com/Teradata/covalent/pull/128.
We broke apart the data-table to allow this and much more. Feel free to reopen or open a new issue for specific data table features :smile:
