### ISSUE TITLE
Stepper active, completed parent access

### ISSUE THREAD

**Issue by kcprabase** [Teradata/covalent#1190]
**Hello All,**

I wanted to change the design of the **"td-stepper-header"** background for the completed and active state through the SCSS but I couldn't find any classes that are accessible through SCSS except for the mat-icon class that are changed according to the state. 

I have tried using the following scss using **ng-reflect** property for both active and completed state but it is not effective in production mode:
```

td-step-header[ng-reflect-active="true"] {
      background: #FEC107 !important;
      .td-step-header {
        .ng-star-inserted {
          color: #000;
        }

        .td-circle {
          background: #fff !important;

          span {
            color: #616161;
          }
        }

        .td-step-label-wrapper {
          span {
            color: #616161;
          }
        }
      }
    }
```

So, Is there a way to change the background color of "td-stepper-header" through accessing the parent level of the mat-icon determining the state of stepper that are completed and active like the following image here below:

![initial](https://user-images.githubusercontent.com/33727948/42438412-baefffe0-837f-11e8-9837-0c46f4223142.PNG)

Thanks any help regarding this would be really appreciable!

**Comment by lordKnighton** [comment]
Hey @kcprabase did you solve this?

**Comment by kcprabase** [comment]
Not yet!

Thanks

**Comment by kcprabase** [comment]
Sure. thanks!

**Comment by owilliams320** [comment]
this component is deprecated and will not be supported future versions please use https://material.angular.io/components/stepper/overview
