### ISSUE TITLE
Bug in @covalent/highlight

### ISSUE THREAD

**Issue by Halynsky** [Teradata/covalent#1193]
#### Bug Report
Problem is that all highlighted code is in one line

##### Here are screenshots:
http://prntscr.com/k5po4n
http://prntscr.com/k5pnk6

##### Here is Stackblitz example:
https://stackblitz.com/edit/covalent-highlight-bug

#### What is the expected behavior?
Indents between code blocks

#### Which version of Angular and Material, and which browser and OS does this issue affect?
@angular/...": "6.0.9
"@angular/material": "6.3.3",
"@covalent/highlight": "2.0.0-beta.2"

**Comment by emoralesb05** [comment]
This is not a `highlight` issue.. the problem is that the angular/cli by default now removes all white space.. either have the snippets not be bundled with your code base and load the separately or use the `preserveWhitespaces: true` property in your component view.

**Comment by ericis** [comment]
Could this be added to the documentation? @emoralesb05
