### ISSUE TITLE
Not able to use td-layouts inside mat-tab-group component

### ISSUE THREAD

**Issue by pavansai1** [Teradata/covalent#1200]
### Do you want to request a *feature* or report a *bug*?
bug
##### Screenshots or link to CodePen/Plunker/JSfiddle
Below is my app.component.html
![screenshot 6](https://user-images.githubusercontent.com/21265305/42928479-00f37f62-8b55-11e8-8632-c88a6a320211.png)

#### What is the expected behavior?
Should be able to use td-layouts inside mat-tab-group component

#### Which version of Angular and Material, and which browser and OS does this issue affect?
Angular version -6.0.8
Covalent version-2.0.0-beta.1
Browser- Google Chrome
OS -Windows
Did this work in previous versions of Angular / Material?

**Comment by lordKnighton** [comment]
you're closing `<td-layout-nav>` after `<td-layout>` when it should be the opposite

-----------------
 `<td-layout>` should be on the outer, just a minor mistake

**Comment by pavansai1** [comment]
@lordKnighton that was my bad. But even after closing them in the reverse way as you said. The layout is not rendering inside the tab. Below is the changed code
   <mat-tab-group>
      <mat-tab label="hello">
      <td-layout>
      <td-layout-nav  toolbarTitle="Covalent" >
          <td-layout-manage-list opened="true" mode="side">
            <mat-toolbar td-sidenav-content>Nav Title</mat-toolbar>
            <div td-sidenav-content>
              Sidenav content here
            </div>
            <mat-toolbar>
              <button mat-button tdLayoutManageListToggle>
                Toggle
              </button>
              Content Title
            </mat-toolbar>
            Content goes here
          </td-layout-manage-list>
        </td-layout-nav>
      </td-layout>
</mat-tab>
</mat-tab-group>

It is just displaying an empty tab with no contents. I want it to display the layout inside the tab. if I just execute the layout part it works fine but when i put it in tab it's not working. Am I doing everything right?. Please help me with this.

**Comment by lordKnighton** [comment]
@pavansai1 from my experiencing with your code and taking off the material layer, the covalent code works fine. But I don't think you are supposed to be coupling Material and Covalent in that fashion, but i do think there are a few things you can do with it, like stick a material button in Covalent code. But thats something i would have to experiment with. But to my knowledge i don't think it's supposed to work like that. You're welcome wait to close this issue until a more senior member looks over and try to help with this issue, but let me know if i helped. Thanks :)

**Comment by pavansai1** [comment]
@lordKnighton But covalent doesn't provide me with the tabs component. So I am supposed to use angular material tabs component. Do you any work arounds for this. I think this is a bug in covalent they should make both angular material and mat tabs compatible some how. Any one have any work arounds  please let me know. Yes you were helpful. Thanks
