### ISSUE TITLE
[Bug] Paging Bar range incorrect when using search with data table

### ISSUE THREAD

**Issue by olsonjj** [Teradata/covalent#1202]
### Do you want to request a *feature* or report a *bug*?

Bug

#### Bug Report

1. Go to https://teradata.github.io/covalent/#/components/data-table 
2. Scroll down to "Data Table with components" example
3. Click the "last page" button on the td-paging-bar component.  The paging bar shows Rows per page 50  451-500 of 500. 
4.  Click on the search icon and type in "abc" into the search input field. 
The data table shows "no results to display", the paging bar shows  rows per page 50, 451-3 (*incorrect) of 3.  

##### Screenshots or link to CodePen/Plunker/JSfiddle

<img width="1210" alt="pagingbardatatable" src="https://user-images.githubusercontent.com/138858/43286250-4e65c31e-90d6-11e8-936b-c14bbdfe89bc.png">

#### What is the expected behavior?

The paging bar should show 1-3 of 3 for the range. and the data table should be showing the 3 results returns by the search.  

#### What is the motivation / use case for changing the behavior?

Non-functional UI behavior. 

#### Which version of Angular and Material, and which browser and OS does this issue affect?

Angular 5.2.0

Did this work in previous versions of Angular / Material?

N/A - untested previously

**Comment by jeremysmartt** [comment]
Thank you for the bug 👍
