### ISSUE TITLE
Can't bind to 'ngOutletContext' since it isn't a known property of 'ng-template'

### ISSUE THREAD

**Issue by durdevic** [Teradata/covalent#1204]
Hi guys, this is the error I have been receiving from the Angular 5.1.1 version and Covalent 1.0.1, and only solution for me is that I manually find the files with ngOutletContext and replace them with ngTemplateOutletContext within node_modules.

Are you aware of this issue because it's really annoying to do this every time when I clone my repo?

Cheers!

#### Bug Report
```
Can't bind to 'ngOutletContext' since it isn't a known property of 'ng-template'.
1. If 'ngOutletContext' is an Angular directive, then add 'CommonModule' to the '@NgModule.imports' of this component.
2. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("
          <ng-template
            [ngTemplateOutlet]="template"
            [ERROR ->][ngOutletContext]="{ model: context }">
          </ng-template>
        </span>
"): ng:///TooltipModule/TooltipContentComponent.html@11:12
Property binding ngOutletContext not used by any directive on an embedded template. Make sure that the property name is spelled correctly and all directives are listed in the "@NgModule.declarations". ("
      <div class="tooltip-content">
        <span *ngIf="!title">
          [ERROR ->]<ng-template
            [ngTemplateOutlet]="template"
            [ngOutletContext]="{ model: contex"): ng:///TooltipModule/TooltipContentComponent.html@9:10
    at syntaxError (compiler.js:1016)
    at TemplateParser.push../node_modules/@angular/compiler/fesm5/compiler.js.TemplateParser.parse (compiler.js:14813)
    at JitCompiler.push../node_modules/@angular/compiler/fesm5/compiler.js.JitCompiler._parseTemplate (compiler.js:23992)
    at JitCompiler.push../node_modules/@angular/compiler/fesm5/compiler.js.JitCompiler._compileTemplate (compiler.js:23979)
    at compiler.js:23922
    at Set.forEach (<anonymous>)
    at JitCompiler.push../node_modules/@angular/compiler/fesm5/compiler.js.JitCompiler._compileComponents (compiler.js:23922)
    at compiler.js:23832
    at Object.then (compiler.js:1007)
    at JitCompiler.push../node_modules/@angular/compiler/fesm5/compiler.js.JitCompiler._compileModuleAndComponents (compiler.js:23831)
```

#### Which version of Angular and Material, and which browser and OS does this issue affect?
Occurs on both 
Angular 5.5.5 and 6.0.1
Covalent 1.0.1 and 2.0.0-beta.2

Did this work in previous versions of Angular / Material?
No (always needed to do it manually)

**Comment by jotatoledo** [comment]
Which files are you manually updating?
This seems to have been addressed by https://github.com/Teradata/covalent/pull/865

**Comment by durdevic** [comment]
All the files which contain ngOutletContext in node_modules (just in Covalent package I guess), but now I successfully upgraded to Angular 6 and put Covalent to 2.0.0-beta.2 and now it works fine.

Probably won't be going back to Angular 5, but the problem was hunting me for a while.

Thanks for the reply @jotatoledo  💪
