### ISSUE TITLE
bug(breadcrumbs): crumbs are incorrectly set to hidden

### ISSUE THREAD

**Issue by jotatoledo** [Teradata/covalent#1216]
#### Bug Report

The issue appears when a td-breadcrumbs component is inside of a multi-row mat-toolbar.
I`ll update the issue with a repro later.

#### What is the expected behavior?

Breadcrumbs should be correctly displayed.

#### Which version of Angular and Material, and which browser and OS does this issue affect?

@angular/core: 6.0.x
@angular/material,cdk: 6.4.x
@covalent/core: 2.0.0-beta.3

**Comment by emoralesb05** [comment]
Awesome dude, thanks for the feedback!

**Comment by jotatoledo** [comment]
Still havent found the time to create a small repro for the issue ;/

**Comment by jeremysmartt** [comment]
@jotatoledo Were you going to make a stackblitz for this issue?

**Comment by jotatoledo** [comment]
Ill get it on the weekend, last time I tried to reproduce it on a local repro I had no luck, came across another issue.

Is it possible to add `@covalent/experimental` as a dependency in a stackblitz?

**Comment by emoralesb05** [comment]
Yup, just use the `git` url from the nightly build:

`https://github.com/Teradata/covalent-experimental-nightly` when entering it in the dependencies box

**Comment by jeremysmartt** [comment]
@jotatoledo Were you able to get the stackblitz going with that nightly build?

**Comment by jotatoledo** [comment]
@jeremysmartt hey jeremy, sorry for the delay. I had a couple of issues while trying to reproduce my issue(s) in stackblitz.

I created a repository for this purpose, please refer to https://github.com/jotatoledo/covalent-issue to see a collection of examples that showcase some estrange situations.
