### ISSUE TITLE
matTooltip in a step of stepper

### ISSUE THREAD

**Issue by pavansai1** [Teradata/covalent#1226]
### Do you want to request a *feature* or report a *bug*?
Feature
#### Feature Request

Stepper component doesn't support the usage of matTooltip within each step of the component. It would be great if there is one more property for the td-step component to expose behaviour as the matTooltip.

#### What is the expected behavior?
Hovering over the step of the component. It should display the tooltip which describes the step in detail.

#### What is the motivation / use case for changing the behavior?
When the sublabel is more than 3-4 lines on the screen display of the below steps is getting disturbed and the view is not completely good. Above steps  sublabel collides with the below steps main label.

#### Which version of Angular and Material, and which browser and OS does this issue affect?

Did this work in previous versions of Angular / Material?

##### Other information
If the matTooltip can some how be used(like any work arounds). Please share them.
@gnomeontherun @fcoury @berga @pdjota

**Comment by alikian** [comment]
Any news on this?

**Comment by AngularTx** [comment]
This feature is required and  will be used if the text is more  . Please support this feature, or if there is any alternative please provide.

**Comment by jeremysmartt** [comment]
Stepper to be deprecated, see #1421
