### ISSUE TITLE
Support autosize in td-layout-manage-list

### ISSUE THREAD

**Issue by f-loris** [Teradata/covalent#1230]
#### Feature Request

Is it possible to add somewhere the possibility to set `autosize` for the `<mat-sidenav-container>` here: https://github.com/Teradata/covalent/blob/47b0b2f38ca53d67fd25f031ca2123448ee7a5c8/src/platform/core/layout/layout-manage-list/layout-manage-list.component.html#L1

This would ease the development of a mini nav. You can find a simple example here: https://stackblitz.com/edit/angular-b4gmby?file=app%2Fsidenav-autosize-example.html

Furthermore, it should make your mini nav example [here](https://stackblitz.com/edit/covalent-dashboard) working since it's currently broken. 
![image](https://user-images.githubusercontent.com/9257417/44584042-ef3e1380-a7a7-11e8-9d5e-8af84f2737a1.png)

Some discussion on this topic can also be found in [material2](https://github.com/angular/material2/issues/6743)

I would also be open to contribute a PR.

**Comment by emoralesb05** [comment]
This can be possible now with #1234

**Comment by jotatoledo** [comment]
niiiiiiceeeeeeeeeee
