### ISSUE TITLE
Angular 7 release

### ISSUE THREAD

**Issue by Enngage** [Teradata/covalent#1241]
Hi, 

are you planning on releasing stable version for Angular 7 when its available (in few weeks)? I noticed you skipped Angular 6 and there seems to be little to no updates which I find unfortunately since I happen to like this lib and use many of the components.

**Comment by jeremysmartt** [comment]
Yes we will support new Angular versions as they come out.  Also if you look at the nightly or 2.0.0 beta versions of Covalent you will see we support Angular 6.

**Comment by Enngage** [comment]
Yeah, I'm using the latest beta 3 and it is working fine and I'm not sure why its not pushed as a regular release. 

Anyway, I'm glad to hear that.

**Comment by jeremysmartt** [comment]
We are still adding several features to the 2.0.0 release, so it is still in beta mode.  If you would like to see what we have done so far for 2.0.0 as well as the remaining features to be done you are welcome to see the project plan here:
https://github.com/orgs/Teradata/projects/1

**Comment by Gustav0ar** [comment]
> I´ve seen that the `mat-elevation` has been changed in angular material 7, so you´ll get a sass error like
> 
> ```
> Module build failed (from ./node_modules/sass-loader/lib/loader.js):
> chunk {styles} styles.js, styles.js.map (styles) 1.38 MB [initial] [rendered]
> 
>   @include mat-elevation($zValue, $elevation-color-or-default, $opacity);
>           ^
>       Wrong number of arguments (3 for 1) for `mat-elevation'
> ```

I'm getting this error too

**Comment by jotatoledo** [comment]
Please avoid noisy comments, the covalent team is most likely aware of all the (breaking) changes in material/cdk@7.x

**Comment by Enngage** [comment]
Awesome, thank you!
