### ISSUE TITLE
Problem with sweetalert

### ISSUE THREAD

**Issue by lippomano** [Teradata/covalent#1253]
[sweetalert2](https://sweetalert2.github.io/) seems not compatible with your theme, is it right?
In my application I need to use this type of alert, is there a fix to make it works?

At the moment when the alert appears I don't see nothing in the background
![alert](https://user-images.githubusercontent.com/27501745/46941336-3095c580-d06b-11e8-8264-d6110eefa3c2.PNG)

**Comment by kyleledbetter** [comment]
not familiar w/ sweet alerts but would material dialogs work for your use case? https://teradata.github.io/covalent/#/components/dialogs

**Comment by emoralesb05** [comment]
Not entirely sure how `sweetalert2` works.. can you provide a stackblitz with the issue and explain what the problem is with bigger detail?

**Comment by jeremysmartt** [comment]
Closing issue, reopen if still a problem
