### ISSUE TITLE
Allow case-insensitive sorting in TdDataTableService

### ISSUE THREAD

**Issue by freastro** [Teradata/covalent#1270]
##### Screenshots or link to CodePen/Plunker/JSfiddle
TdDataTableService.sortData() versus a custom case-insensitive sort:
https://stackblitz.com/edit/covalent-4d6dxt

#### What is the expected behavior?
I was expecting sortData() to use String.prototype.localeCompare() for comparing strings, or allow the sortBy argument to be a comparison function.

#### What is the motivation / use case for changing the behavior?
I find case-insensitive sorting to be more intuitive. In a long list it's not clear that upper-case letters are sorted before lower-case letters.

#### Which version of Angular and Material, and which browser and OS does this issue affect?
All

##### Other information
Allowing sortBy to be a comparison function could be useful in other scenarios too.

**Comment by jeremysmartt** [comment]
This sorting service will be deprecated in favor of documented examples for sort.
