### ISSUE TITLE
TdCollapseAnimation broken in Safari

### ISSUE THREAD

**Issue by DaSchTour** [Teradata/covalent#1271]
#### Bug Report
* Open Safari
* Browse to Covalent documentation https://teradata.github.io/covalent/#/components/animations
* Navigate to Collapse Animation
* Click on "Collapse" button
* Nothing happens

#### What is the expected behavior?
* TdCollapseAnimation should work in all browsers

#### Which version of Angular and Material, and which browser and OS does this issue affect?

Did this work in previous versions of Angular / Material?

**Comment by emoralesb05** [comment]
which version of covalent and safari are you using? we fixed an animation issue with safari in our last beta release.

**Comment by DaSchTour** [comment]
I probably use the same version that was used for the covalent website the day I reported the issue.

**Comment by emoralesb05** [comment]
Its fixed for me in the site. Is it still broken for you?
