### ISSUE TITLE
docs version information

### ISSUE THREAD

**Issue by janez89** [Teradata/covalent#1272]
#### Feature Request
Please provide somewhere Version information for documentation.

Version to version I detect changes but I don't know many times which version of the docs what I read now.

Is there any plan related to more version info in the future?

Thanks

**Comment by emoralesb05** [comment]
Yes, we will have versioned docs soon.. we just need to see were are we going to host them.

**Comment by kriswinbush** [comment]
iresearching options for documentation hosting.

**Comment by emoralesb05** [comment]
We have the versions v2 and v3 out. So docs are now version per major release. 

Let us know if that helps!
