### ISSUE TITLE
[IE11] - td-navigation-drawer-menu not show/hiding correctly in IE11

### ISSUE THREAD

**Issue by jaa1982** [Teradata/covalent#1273]
#### Bug Report

In IE11, after toggling the td-navigation-drawer-menu , the original td-navigation-drawer's contents are still displayed in addition to the new td-navigation-drawer-menu's contents.  Successive toggles have no effect of restoring to original state

You can reproduce this with the standard stackblitz, running in IE11

StackBlitz template: https://stackblitz.com/edit/covalent

##### Screenshots or link to CodePen/Plunker/JSfiddle

![covalent - td-navigation-drawer-menu error in ie11](https://user-images.githubusercontent.com/12563163/48214012-a6c4d980-e344-11e8-9006-fbef520f5881.gif)

#### What is the expected behavior?

Should toggle back and forth between <td-navigation-drawer> and <td-navigation-drawer-menu> contents

#### Which version of Angular and Material, and which browser and OS does this issue affect?

angular@7
material@7
covalent@2.0.0-beta.4

Did this work in previous versions of Angular / Material?

yes 

##### Other information

This should be related to an issue I'd previously reported ,    #1153

**Comment by owilliams320** [comment]
ie1
