### ISSUE TITLE
bug(breadcrumbs): potential infinite loops

### ISSUE THREAD

**Issue by jotatoledo** [Teradata/covalent#1274]
#### Bug Report

The current implementation of `TdBreadcrumbs` is prone to fall into an infinite loop under certain conditions.

For example in [this blitz](https://stackblitz.com/edit/covalent-breadcrumb-infiniteloop):

If the array bounded to the `ngFor` (line 27)  is the `breadcrumbs` member in the component, it works fine. But if the bounded array is `getterBreadcrumbs`, then the app will fall into an infinite loop (view will freeze), as the bounded array is recalculated during change detection which triggers a change detection at the `TdBreadcrumbs` component level.

#### What is the expected behavior?

Although bounding getters that returns new references to the template isnt a good pattern, this shouldnt result in the app transitioning into an infinite loop state.

#### Which version of Angular and Material, and which browser and OS does this issue affect?

angular: 7.x
materia/cdk: 7.x
covalent/core: 2.0.0-beta.4

#### Did this work in previous versions of Angular / Material?

The bug was not present on covalent/core: 2.0.0-beta.3 with angular,cdk,material: 6.x

**Comment by emoralesb05** [comment]
Well, for some reason the `Promise.resolve` was causing this, when changing to `setInterval` it fixed it  and im not entirely sure why.. maybe the execution was pushed after at the end of the execution stack queue too much every single time the element was rendered.
