### ISSUE TITLE
Create wiki to help users figure out what Angular CLI versions are compatible with Covalent v1/v2-beta

### ISSUE THREAD

**Issue by stevenov7** [Teradata/covalent#1284]
Create wiki matrix of compatible version to use Covalent v1/v2-beta + Angular CLI version.
Some users of Covalent were having issues when moving from Covalent v1 to v2-beta. And the issue was using an in compatible Angular CLI version

https://github.com/Teradata/covalent/wiki/Covalent---Angular-Compatibility-Info

**Comment by jeremysmartt** [comment]
not going to work
