### ISSUE TITLE
Clarification on "angular/flex-layout" support

### ISSUE THREAD

**Issue by RaduGrama** [Teradata/covalent#1287]
#### Documentation Request
Can someone please comment on the use of "angular/flex-layout" with Covalent?

We have an existing Angular app and we already use "angular/flex-layout". We could benefit from some of the Covalent components, but it is not clear what dependencies we are taking on and if Covalent's Media Queries (as described at https://teradata.github.io/covalent/#/components/media) and Covalent's Flexbox Layout ("grid") (as described at https://teradata.github.io/covalent/#/layouts) are such dependencies, are required, and are conflicting with "angular/flex-layout".

**Comment by emoralesb05** [comment]
You can choose not to use `flex layout` by not importing the `covalent-layout` mixin in your sass file. But even if you do import it and use it, it will not conflict.. same with the media service.

**Comment by jeremysmartt** [comment]
closing issue, question answered
