### ISSUE TITLE
Feature : Selected rows as a Output element for the data-table

### ISSUE THREAD

**Issue by asaph26** [Teradata/covalent#129]
Thanks for a really good data-table module.

Currently there is no way to know which rows were selected outside of the data-table component. After looking briefly at the code, I wasn't able to find this being implemented.

####Expected Behaviour
When rows in a data table are selected, the selected items must be provided as an EventEmitter output.

#### What is the motivation / use case for changing the behavior?
There is currently no obvious way to know which rows were selected and which weren't.

Would [#128](https://github.com/Teradata/covalent/pull/128) solve this?

**Comment by emoralesb05** [comment]
Yep, will be adding ngModel support with that PR.

**Comment by asaph26** [comment]
@emoralesb05 : This issue could be closed as it is addressed as part of the atomic data-table, right?

**Comment by emoralesb05** [comment]
Oh yeah, we added a `rowSelect` event into the `<td-data-table>` molecule + the atomic abstractions can be used in multiple diff ways.

**Comment by emoralesb05** [comment]
Closing since its addressed in https://github.com/Teradata/covalent/pull/128. Feel free to reopen or open a new issue if we missed anything.
