### ISSUE TITLE
Markdown doesn't render line ends properly

### ISSUE THREAD

**Issue by Enngage** [Teradata/covalent#1290]
Markdown doesn't render line ends properly. See (tested in [https://teradata.github.io/covalent/#/components/text-editor](https://teradata.github.io/covalent/#/components/text-editor)): 

![breaks](https://user-images.githubusercontent.com/7137351/48673169-fa060b80-eb3e-11e8-9f6c-b93da9ef503d.png)

However, the built-in preview does display text correctly:

![built_in_preview](https://user-images.githubusercontent.com/7137351/48673171-04280a00-eb3f-11e8-8425-dc1f32d8769c.png)

**Comment by emoralesb05** [comment]
Just realized its a configuration of `showdown` that is disabled by default. Going to keep this open to add an input for that configuration.
