### ISSUE TITLE
Advanced Chips Filter

### ISSUE THREAD

**Issue by natashasandiego** [Teradata/covalent#1294]
## Feature Request

The goal is to provide advanced chips-filter (like o Google Flights) as a new Covalent pattern or possibly component

## Design
[Design Document](https://docs.google.com/document/d/1k70g0HuJLbjVDHOXmqm-HFWdvernOkvNnCBawTJ5shU/edit?usp=sharing)

**Comment by owilliams320** [comment]
this component is deprecated and will no longer be supported in future versions. please use https://material.angular.io/components/chips/overview
