### ISSUE TITLE
md text area needed with validator

### ISSUE THREAD

**Issue by saketh1991** [Teradata/covalent#131]
<md-input-container><textarea class="appname" wrap ="hard" maxlength="60" placeholder="Config Description (optional)" [(ngModel)]="appdesc"></textarea></md-input-container>
 need this md text area in covalent

**Comment by kyleledbetter** [comment]
@saketh1991 you're in luck! it's coming in the next angular-material2 update and will be included in Covalent directly after https://github.com/angular/material2/commit/aff22e5a92a669c14c5d95518ebbad74121bad52

**Comment by emoralesb05** [comment]
mx-textarea was added with alpha.10 which will be part of 0.9
