### ISSUE TITLE
Feature Validation for Media query based Show/Hide 

### ISSUE THREAD

**Issue by ajetnewera** [Teradata/covalent#132]
#### Feature Request

https://material.angularjs.org/latest/layout/options

Is there functionality like show hide depending on window sizes implemented like ones in the above link ?

**Comment by emoralesb05** [comment]
Yes, we provide the same `hide-xs` and `show-xs` (or any breakpoint) as those from flex layout.

**Comment by emoralesb05** [comment]
Closing since its an old issue, and now its deprecated since `@angular/flex-layout` is out
