### ISSUE TITLE
[Bug] JSON Formatter property name should not be centered when value is large

### ISSUE THREAD

**Issue by emoralesb05** [Teradata/covalent#1323]
#### Bug Report

When the value is too large, the property name is centered.. this should not happen since it should be aligned to the top.

##### Screenshots or link to CodePen/Plunker/JSfiddle

![image](https://user-images.githubusercontent.com/5846742/50542127-4a26b380-0b6a-11e9-9a60-1dade4b6ab2c.png)

**Comment by richavyas** [comment]
UX LGTM
