### ISSUE TITLE
[Usability Bug] Last breadcrumb is to grayed out

### ISSUE THREAD

**Issue by emoralesb05** [Teradata/covalent#1324]
#### Bug Report

We should probably make the grayed out breadcrumb a bit more solid since when used in practice it doesnt look proper in a toolbar the way it is right now.

![image](https://user-images.githubusercontent.com/5846742/50545341-3492a780-0bc5-11e9-886c-1724310b7891.png)

**Comment by joejcarey** [comment]
@emoralesb05 Can you clarify this bug for me? Are you saying that the last breadcrumb is too light? If so does the attached image work better for you. Also, is the 'HTTP' that appears first part of the issue? If so, can you advise where and how to replicate? 

![screen shot 2019-02-06 at 3 00 51 pm](https://user-images.githubusercontent.com/34658520/52374954-28033980-2a24-11e9-8b46-1b1cd2cda928.png)
_The text opacity has been changed from `0.38` to `0.54`_

**Comment by emoralesb05** [comment]
The main "issue" is how light the last breadcrumb is.

When actually using this, it looks like its disabled instead of "selected"

**Comment by joejcarey** [comment]
I put together some options and examples from google to review.
https://covalent-breadcrumbs.stackblitz.io

**Comment by jeremysmartt** [comment]
Let's go with Example #2

**Comment by emoralesb05** [comment]
PR merged already.
