### ISSUE TITLE
Error while upgrading to version 2.0.0

### ISSUE THREAD

**Issue by joeldatabox** [Teradata/covalent#1325]
Guys, I just did an update on my dependencies.
Before it was like this:
`
"dependencies": {
"@angular/animations": "7.0.3",
    "@angular/cdk": "7.0.3",
    "@angular/common": "7.0.3",
    "@angular/compiler": "7.0.3",
    "@angular/core": "7.0.3",
    "@angular/forms": "7.0.3",
    "@angular/http": "7.0.3",
    "@angular/material": "7.0.3",
    "@angular/platform-browser": "7.0.3",
    "@angular/platform-browser-dynamic": "7.0.3",
    "@angular/router": "7.0.3",
    "@covalent/core": "2.0.0-beta.3",
    "angular2-text-mask": "^9.0.0",
    "chart.js": "^2.7.3",
    "class-transformer": "^0.2.0",
    "core-js": "^2.5.7",
    "hammerjs": "^2.0.8",
    "moment": "^2.22.2",
    "ng2-logger": "^2.0.35",
    "ngx-color-picker": "^7.1.1",
    "rxjs": "^6.3.3",
    "sr-meeseeks": "^0.7.0",
    "text-mask-addons": "^3.8.0",
    "zone.js": "^0.8.26"
}`

After updating it looks like this:

`
"dependencies": {
"@angular/animations": "7.1.4",
    "@angular/cdk": "7.2.0",
    "@angular/common": "7.1.4",
    "@angular/compiler": "7.1.4",
    "@angular/core": "7.1.4",
    "@angular/forms": "7.1.4",
    "@angular/http": "7.1.4",
    "@angular/material": "7.2.0",
    "@angular/platform-browser": "7.1.4",
    "@angular/platform-browser-dynamic": "7.1.4",
    "@angular/router": "7.1.4",
    "@covalent/core": "2.0.0",
    "angular2-text-mask": "^9.0.0",
    "chart.js": "^2.7.3",
    "class-transformer": "^0.2.0",
    "core-js": "^2.6.1",
    "hammerjs": "^2.0.8",
    "moment": "^2.23.0",
    "ng2-logger": "^2.0.46",
    "ngx-color-picker": "^7.2.0",
    "rxjs": "^6.3.3",
    "sr-meeseeks": "^0.7.5",
    "text-mask-addons": "^3.8.0",
    "zone.js": "^0.8.26"
}`

But now I have a annoying problem, during the build I'm having the following error:

```
ERROR in Module build failed (from ./node_modules/sass-loader/lib/loader.js):

    #{map-get(_get-umbra-map($color, $opacity), $zValue)},
                                                        ^
      Argument `$map` of `map-get($map, $key)` must be a map
      in /home/joel/Documentos/Projects/invistate/invistate-front/node_modules/@covalent/core/common/styles/_elevation.scss (line 149, column 58)
```

Could someone tell me how I can solve this problem? Note: Before upgrading to version 2.0.0 everything was normal

Thank you in advance for your attention!

**Comment by christianmemije** [comment]
@joeldatabox Can you first check what version of node you have? Then can you try updating node-sass and/or rebuilding it.

**Comment by joeldatabox** [comment]
Currently installed the following version
```
node-sass@4.10.0
libsass@3.5.4
```
After I updated it was like this
```
node-sass@4.11.0
libsass@3.5.4
```

Unfortunately the problem persists! Is there anything else that can be done?

**Comment by joeldatabox** [comment]
After an arduous code review, you can find the source of the problem. I have a component that customizes some aspects of the td-expansion-panel component and this is the possible source of the problems.
Before my ".scss" file was like this:
```
@import "~@covalent/core/common/styles/variables";
@import "~@covalent/core/common/styles/elevation";

.td-expansion-panel {
  @include mat-elevation(1);
  transition: 120ms ease-in;

  &.td-expanded {
    margin-bottom: $margin;
  }

  &.td-expanded {
    margin-top: $margin;
  }

  &:focus:not(.mat-disabled) {
    *:not(.td-expanded) {
      background: #f5f5f5;
    }
  }

  &:hover:not(.mat-disabled) {
    *:not(.td-expanded) {
      background: #f5f5f5;
    }
  }
}

```
After the review it was like this:
```
@import '~@covalent/core/common/styles/variables';
@import '~@angular/material/theming';

.td-expansion-panel {
  @include mat-elevation(1);
  transition: 120ms ease-in;

  &.td-expanded {
    margin-bottom: $margin;
  }

  &.td-expanded {
    margin-top: $margin;
  }

  &:focus:not(.mat-disabled) {
    *:not(.td-expanded) {
      background: #f5f5f5;
    }
  }

  &:hover:not(.mat-disabled) {
    *:not(.td-expanded) {
      background: #f5f5f5;
    }
  }
}
```

**Comment by emoralesb05** [comment]
https://github.com/Teradata/covalent/pull/1443 takes care of this.
