### ISSUE TITLE
TdDialogService cannot find component factories in lazy loaded modules

### ISSUE THREAD

**Issue by freastro** [Teradata/covalent#1327]
#### Bug Report
If TdDialogModule is imported into the root module either directly or indirectly, then lazy loaded modules cannot open dialogs using custom components. Instead they get an error saying:

> ERROR
> Error: No component factory found for [Component class name]. Did you add it to @NgModule.entryComponents?

This issue does not occur when using MatDialog.

##### Screenshots or link to CodePen/Plunker/JSfiddle
In the following CodePen, TdDialogService and MatDialog work the same in the root AppModule, but differ when used from a lazy loaded module. MatDialog.open() works in both cases but TdDialogService.open() only works from the root AppModule.

https://stackblitz.com/edit/covalent-q2ktm6

#### What is the expected behavior?
If MatDialog.open() works then I expect to be able to replace it with TdDialogModule.open() and also have it work.

#### What is the motivation / use case for changing the behavior?
To have the functionality of TdDialogModule.open() be consistent with MatDialog.open().

#### Which version of Angular and Material, and which browser and OS does this issue affect?
Tested with Angular 5, Material 5, and Covalent 1 with Chrome on macOS.
Also tested with Angular 7, Material 7, and Covalent 2-rc2 with Chrome on macOS.

Did this work in previous versions of Angular / Material?
Not that I'm aware of.

##### Other information
I think the issue is that the TdDialogService tries to be a singleton and so only has access to the components of the first module where it's imported. Removing TdDialogModule from AppModule and replacing it with MatDialogModule fixes the issue as shown in the following CodePen:

https://stackblitz.com/edit/covalent-nxn6uw

**Comment by emoralesb05** [comment]
Interesting, i guess that this is one of the services that should not be singleton in the application.

Let me try a few things and get back to you

**Comment by jeremysmartt** [comment]
closed with https://github.com/Teradata/covalent/pull/1338

**Comment by iget-esoares** [comment]
@jeremysmartt This is still an issue on v3.0.0 with angular 9

**Comment by emoralesb05** [comment]
Can you elaborate on how to replicate? `entryComponents` is deprecated when using `ivy`.. so im not sure how the problem still persists.
