### ISSUE TITLE
Scrolling of the main content panel via the keyboard is not possible until clicking

### ISSUE THREAD

**Issue by pgh-tba** [Teradata/covalent#1328]
### Do you want to request a *feature* or report a *bug*?
This is a bug report.

#### Bug Report
The layout contains a big scrollable container, which you cannot scroll using the keyboard until you actually click inside of it. 

StackBlitz: https://pgh-scroll-issue.stackblitz.io/

Note: sometimes the StackBlitz does not load properly; please try it later, as it has been put together properly to reproduce/demonstrate this issue.

#### What is the expected behavior?
It should be possible to make the main content panel keyboard-scrollable somehow: either declaratively / programmatically. 

#### What is the motivation / use case for changing the behavior?
This is confusing for the users. Imagine a dashboard screen that aggregates status and progress information from various systems etc with operations people who literally use that single screen: they bookmark it and use the arrow keys to repeatedly scan the system for any issues.

#### Which version of Angular and Material, and which browser and OS does this issue affect?
Angular: 5.2.0
Covalent: 1.0.0

Google Chrome Version 71.0.3578.98 (Official Build) (64-bit)
Mac OS 17.7.0 Darwin Kernel Version 17.7.0: Fri Nov  2 20:43:16 PDT 2018; root:xnu-4570.71.17~1/RELEASE_X86_64 x86_64

Did this work in previous versions of Angular / Material?
No

##### Other information

I even tried something like this: programatically "clicking" the main content element, but still, scrolling using the keyboard does not work until I actually (manually) click the main content element. 

If this solution, or something like it would work, that would be perfectly fine. 

HTML:
```
  <td-layout-nav logo="assets:teradata" toolbarTitle="Covalent" navigationRoute="/">
    <button mat-icon-button td-menu-button tdLayoutToggle>
      <mat-icon>menu</mat-icon>
    </button>
    <div #mainViewContainer>
    Content goes here
  </td-layout-nav>
```

Typescript class:
```
   //...
   @ViewChild('mainViewContainer') mainViewContainer: ElementRef;
   //...

  ngAfterViewInit(): void {
    this.mainViewContainer.nativeElement.click();

    this.mainViewContainer.nativeElement.focus();
  }

  ngOnInit(): void {
        setTimeout(()=>{
              this.mainViewContainer.nativeElement.click();

              this.mainViewContainer.nativeElement.focus();

         }, 3000);
    });
```

**Comment by jeremysmartt** [comment]
Closing issue, question answered
