### ISSUE TITLE
Click event is not working on the td-chip, click event is triggered when clicked outside the chip or bottom of the chip

### ISSUE THREAD

**Issue by kmeeraj** [Teradata/covalent#1331]
### Do you want to request a *feature* or report a *bug*?

Covalent version: 1.0.0

#### Feature Request

[td-chip](https://github.com/Teradata/covalent-nightly/tree/master/chips)

#### Bug Report

Click event is not working on the td-chip, click event is triggered when clicked outside the chip or bottom of the chip

This is how we are using chip
`<td-chips
 color="primary"
 class="chip-container"
 [(ngModel)]="inputData"
 [disabled]="true"
 (click)="openDialog()">
</td-chips>`

This is the generated HTML Code:
`<mat-basic-chip _ngcontent-c47="" class="mat-chip mat-basic-chip mat-primary td-chip-disabled td-chip-after-pad ng-star-inserted" role="option" tabindex="-1" ng-reflect-color="primary" aria-disabled="false" aria-selected="false">
     <div _ngcontent-c47="" class="td-chip">
       <span _ngcontent-c47="" class="td-chip-content">
         <span _ngcontent-c47="" class="ng-star-inserted">H</span>
         
       </span>
       
     </div>
   </mat-basic-chip>`

#### What is the expected behavior?

Click event should work on the chip

#### Which version of Angular and Material, and which browser and OS does this issue affect?

Did this work in previous versions of Angular / Material?

**Comment by richavyas** [comment]
If you want to add click event on the chip, you will have to add it on the div inside 
`ng-template td-chip` 
which iterates on the chip items so instead of adding it on `<td-chips>`, please add it on the div below and span:
```
<ng-template td-chip let-chip="chip">
   <div class="tc-grey-100 bgc-teal-700" td-chip-avatar (click)="clickItem('item clicked')">{{chip.substring(0, 1).toUpperCase()}}</div>
   <span class="text-truncate" (click)="clickItem('item clicked')">{{chip}}</span>
</ng-template>
```

**Comment by kmeeraj** [comment]
I have reproduced this issue in https://stackblitz.com/edit/angular-5nmbpw?file=src%2Fapp%2Fapp.component.ts.

Please note , check in the browser console, for click event console logs. Click event is not fired on chips. It is working only on outside of the chip.

**Comment by jotatoledo** [comment]
@kmeeraj in your blitz, the `ng-template` element should be nested in the `td-chips`, not outside of it.
