### ISSUE TITLE
Relax Node dependency

### ISSUE THREAD

**Issue by tycho01** [Teradata/covalent#134]
#### Bug Report

To reproduce: try installing Covalent on a new Node version (e.g. `6.9`) through a package manager enforcing strict checks, such as Yarn.
This errors due to the `"node": ">4.4 < 5",` check in `package.json`. In actuality, a new Node version would work fine (as is the case when installing using `npm` over `yarn`).

#### What is the expected behavior?
Install without errors; a version check updated to match more recent versions that do in fact work.

#### What is the motivation / use case for changing the behavior?
Yarn is more desirable than NPM since it helps locking down exact package versions.

**Comment by emoralesb05** [comment]
Thanks for pointing us this issue, we are gonna lax our node dependency to `< 7` for now, and maybe even remove the upper limit later on.

**Comment by emoralesb05** [comment]
Done with https://github.com/Teradata/covalent/pull/136
