### ISSUE TITLE
Integrate/install Pa11y 🐶❤️ tooling + fix a11y issues reported

### ISSUE THREAD

**Issue by ghost** [Teradata/covalent#1341]
Integrate pa11y so we can start automating our accessibility testing. (Ilsun already did a first pass on this)
https://github.com/pa11y/pa11y

Also, fix the related a11y issues pa11y is reporting. 

(Future: swap out pa11y implementation for "pa11y-ci" tool, more CI focused and can run test in parallel.

**Comment by stevenov7** [comment]
https://github.com/Teradata/covalent/issues/1417 is a dependency on completing this ticket.

**Comment by jeremysmartt** [comment]
Julie to Review
