### ISSUE TITLE
Update td-loading docs related to community member feedback

### ISSUE THREAD

**Issue by stevenov7** [Teradata/covalent#1349]
Make the td-loading docs more clear to help resolve community member feedback, see below. 
<img width="797" alt="screen shot 2019-02-19 at 3 39 38 pm" src="https://user-images.githubusercontent.com/24550592/53055539-f1361600-345c-11e9-9ab3-b92bfad25079.png">

**Comment by chriscurnow** [comment]
Hi @stevenov7 , it's great you've raised this issue. However, in the meantime can someone give me some brief details of what I am supposed to do to get this working. @jotatoledo says I shouldn't register those services manually. That is what I thought. Certainly they are not registered manually anywhere in the Quickstart. However I simply cannot get it to work without registering them manually.

**Comment by abdullahsaleem93** [comment]
+1 for this. Even if `CovalentLoadingModule` from `@covalent/core/loading` is added to imports. It  still doesn't work for some components, weird behavior.

**Comment by jeremysmartt** [comment]
Will add to docs:
*Notice - When importing make sure everything is from primary or secondary entry point in all cases

**Comment by jeremylcarter** [comment]
I recently had this issue and resolved it using the instructions from @abdullahsaleem93 
The console error was "no provider for TdLoadingService".

**Comment by aqupriyanka** [comment]
As Angular Material is getting rid of entry points as mentioned below : 

`Importing directly from the root @angular/material entry-point is deprecated. You should instead
import from specific entry-points, e.g. @angular/material/button. This aligns with @angular/cdk,
makes clear where symbols originate, and helps safeguard against including unused code. The
deprecated style will be removed in Angular v9.`
https://github.com/angular/components/releases

We are trying to follow the same standards and with Covalent 3.0 release, will remove the entry points.
