### ISSUE TITLE
fix(parse5): Remove parse5 from main package

### ISSUE THREAD

**Issue by richavyas** [Teradata/covalent#1353]
### Description
Remove parse5 from main package when the compile issue with yarn no longer exists. 

#### What is the expected behavior?
With a new version of `@angular-devkit/build-angular`, yarn would correctly resolve parse5 dependencies internally for schematics and explicit dependency in the main package wouldn't be required anymore. 

#### What is the motivation / use case for changing the behavior? 
Parse5 has been added as part of this PR #1350 to fix yarn compile issue.

**Comment by jeremysmartt** [comment]
No longer an issue
