### ISSUE TITLE
Don't force to load Material Icons

### ISSUE THREAD

**Issue by DaSchTour** [Teradata/covalent#1360]
#### Feature Request
I would like to use other icons and not be forced to include Material Icons that are never used

#### What is the expected behavior?
Material Icons can be excluded.

#### What is the motivation / use case for changing the behavior?
I want to be able to create an application without material icons.

**Comment by jotatoledo** [comment]
From the SCSS point of view, this is already possible:

https://teradata.github.io/covalent/#/docs/utility-sass-mixins

The difficult part would be to allow covalent components like search-box/input or paging to opt-in an icon font, as they currently use material icons by default.

**Comment by ericis** [comment]
... would have to make icons used within the framework completely configurable

**Comment by jeremysmartt** [comment]
Covalent is based on Material and use of its icons.
