### ISSUE TITLE
npm audit on vantage-ui-template

### ISSUE THREAD

**Issue by jeremysmartt** [Teradata/covalent#1371]
Get dependencies updated and improve the low/moderate/high vulnerability warnings (even though many are dev dependencies and we don't ship them)

npm audit has been added to Covalent Core repo but needs to be added to all repos:

https://github.com/Teradata/covalent/pull/1370

**Comment by jeremysmartt** [comment]
Steven to Review

**Comment by JulieMarie** [comment]
vantage-ui-template needs `npm audit`
