### ISSUE TITLE
bug Size with two code editor component inside Tabs

### ISSUE THREAD

**Issue by JorgelGtzGtz** [Teradata/covalent#1378]
Hello I use two tabs containers with code editor component but the size is failed because the first tab i can see fine the control but in the second is very very small same a point.

**Comment by JulieMarie** [comment]
Hi @JorgelGtzGtz, could you please provide a stackblitz for the issue you are seeing?

**Comment by aqupriyanka** [comment]
This issue is being resolved with the code-editor's resize PR and will be released in Covalent 2.1
