### ISSUE TITLE
Missing peerDependency on @angular/platform-browser

### ISSUE THREAD

**Issue by mattem** [Teradata/covalent#1382]
### Do you want to request a *feature* or report a *bug*?
*bug*

#### What is the current behavior?
npm peer dep on `@angular/platform-browser` missing in npm distribution
```
"peerDependencies": {
    "@angular/common": "^7.0.0",
    "@angular/core": "^7.0.0"
  }
``` 

#### What is the expected behavior?
npm distro has peer deps on all npm packages required by main bundle: 
https://unpkg.com/@covalent/highlight@2.0.1/bundles/covalent-highlight.umd.js
```
define('@covalent/highlight', ['exports', '@angular/platform-browser', '@angular/core', '@angular/common'])
```

#### What is the motivation / use case for changing the behavior?
When using Bazel with Angular, the missing peer dep means user's need to explicitly add @npm//@angular/platform-browser as a dep in ng_module when using @npm//@covalent/highlight. Adding the peer dep means that depending on @npm//@covalent/highlight will automatically bring in the @npm//@angular/platform-browser transitively.

#### Which version of Angular and Material, and which browser and OS does this issue affect?
All

#### Did this work in previous versions of Angular / Material?
No

##### Other information
suggested fix - if authors are okay with the fix, happy to submit a PR

Add the following to `src/platform/highlight/package.json`
```
"@angular/platform-browser": "^0.0.0-NG"
```

**Comment by JulieMarie** [comment]
Hi @mattem, go ahead and submit a PR and we will review it, thanks!

**Comment by emoralesb05** [comment]
Closed since it was already merged
