### ISSUE TITLE
Default BaseUrl Configuration?

### ISSUE THREAD

**Issue by offwork** [Teradata/covalent#1387]
#### What is the motivation / use case for changing the behavior?

How to configuration to the **baseUrl** for **@TdHttp** decorator? Or, use to default **baseUrl** it possible?

In this case, when we specify baseUrl from a configuration file such as **environment.ts**, there is no use as the following!

```
@TdHttp({
  baseHeaders: new HttpHeaders({ 'Accept': 'application/json' }),
})
@Injectable()
export class TestHttpService {...}
```

**Comment by offwork** [comment]
Perhaps a similar change to be made [here](https://github.com/Teradata/covalent/blob/develop/src/platform/http/actions/http.mixin.ts#L115) can make it possible to use both the default baseUrl and as the manual baseUrl. Code:
```
      const appConfig = new AppConfigService(this.http);
      appConfig.load().then(() => {
        if (config && config.baseUrl) {
          this._baseUrl = config.baseUrl.replace(/\/$/, '');
        } else {
          this._baseUrl = appConfig
            .get<string>(AppConfigValues.BASE_URL)
            .replace(/\/$/, '');
        }
      });
```

**Comment by owilliams320** [comment]
this service is deprecated and will be removed in future versions please use regular angular http
