### ISSUE TITLE
Echarts Legend

### ISSUE THREAD

**Issue by saadzah** [Teradata/covalent#1391]
### Do you want to request a *feature* or report a *bug*?
I want to request a feature.

#### Feature Request

Add legend in echarts.

#### What is the expected behavior?
Have either an attribute for the legend in the <td-chart> tag or add a new tag for defining the legend.

#### What is the motivation / use case for changing the behavior?
Many charts and user requirements require that a legend be added to the chart for better communication of the data.

**Comment by jeremysmartt** [comment]
Please move this issue to this repository:
https://github.com/Teradata/covalent-echarts
