### ISSUE TITLE
dynamic-forms: additional configuration for DynamicCustomComponent

### ISSUE THREAD

**Issue by makuepfer** [Teradata/covalent#1397]
Hi, I created a dynamic custom component like it is described in the [ReadMe](https://github.com/Teradata/covalent/tree/develop/src/platform/dynamic-forms#usage).

I would like to provide some additional configuration to the component like e.g. an Url, where I can query some master data for the input field.

I tried to reach the goal as follows:
#### app.component.ts
```ts
elements: any = [{
    name: 'custom',
    label: 'Custom',
    type: DynamicCustomComponent,
    required: true,
    searchUrl: 'https://www.google.com'
  }];
```

#### dynamic-custom.component.ts
```ts
export class DynamicCustomComponent{
    control: FormControl;
    errorMessageTemplate: TemplateRef<any>;
    
    label: string;
    searchUrl: string;
}
```

The property `label` is filled correctly but the `searchUrl` remains empty.

What is the way-to-go, if I want to provide additional configuration to my DynamicCustomComponent?

**Comment by makuepfer** [comment]
Hey guys

This issue has been open for some time now and I still have no idea what's going on with it.
To be honest, you gave me a little hope by moving it to the ToDo's of the releases.

I assume that my usecase can't be covered at the moment and it needs development work / investigation on your side, right?

Kind regards

**Comment by makuepfer** [comment]
Any news on this? At least a short feedback would be nice!

**Comment by JulieMarie** [comment]
Hi Mauro,

You are correct in that we still need to investigate.  Could you provide a stackblitz (https://stackblitz.com/edit/covalent) with what you're currently doing?  I would think you could use a text input field for the URL, but I'm unclear as to where the problem is.

Also, that same README is available here: https://teradata.github.io/covalent/v3/#/components/dynamic-forms/overview

**Comment by makuepfer** [comment]
Hi Julie Marie,

Thank you for your response. Here is my Stackblitz example: [https://stackblitz.com/edit/covalent-5sf3fm](https://stackblitz.com/edit/covalent-5sf3fm?file=app%2Fapp.component.ts)

We use a custom dynamic component which is essentially a search bar with selectable search results. 
Each instance of this dynamic component should receive a different "base url" to query the search.

What we need is a way to provide additional configuration(-fields) to such a custom dynamic component. Not only the fields available through the interface ITdDynamicElementConfig.

Is there a way to do this without needing to fork your repo and extend the ITdDynamicElementConfig?

Let me know if you need further information or clarification.

**Comment by thomaslennan** [comment]
Hi Mauro, I looked into options to address this. I'm proposing changing the config interfaces as follows:

```typescript
// Properties unique to custom components
export interface ITdDynamicElementCustomConfig {
  [name: string]: any;
}

// The full config payload provided for the dynamic component
export interface ITdDynamicElementConfig {
  label?: string;
  name: string;
  hint?: string;
  type: TdDynamicType | TdDynamicElement | Type<any>;
  required?: boolean;
  disabled?: boolean;
  min?: any;
  max?: any;
  minLength?: any;
  maxLength?: any;
  selections?: string[] | { value: any; label: string }[];
  multiple?: boolean;
  default?: any;
  flex?: number;
  validators?: ITdDynamicElementValidator[];
  customConfig?: ITdDynamicElementCustomConfig;
}
```

The proposal is that any additional properties specific to your custom component would be provided as an object defining one or more property/value pairs. On construction of the component, Covalent code would iterate over the custom config object applying each property value to the component.

```typescript
export class TdDynamicElementComponent extends _TdDynamicElementMixinBase
...

  ngOnInit(): void {
...
    if (this.customConfig) {
      Object.getOwnPropertyNames(this.customConfig).forEach((name: string) => {
        this._instance[name] = this.customConfig[name];
      });
    }
  }
```

Does this approach sound like it would fit your need?

**Comment by makuepfer** [comment]
Hi Tom,
Yes, this approach would fit our needs. I think this extension could also help other devs 👍.

**Comment by makuepfer** [comment]
Thanks for the implementation. With release 3.1.0 I could now cover my requirements.

The ticket can be closed from my point of view.

**Comment by owilliams320** [comment]
this component is deprecated and no longer maintained please use regular angular forms
