### ISSUE TITLE
Feature: Material Design Combo box

### ISSUE THREAD

**Issue by asaph26** [Teradata/covalent#140]
**Description of the feature**
A combination of a dropdown and an input field. The following should be possible

- Ability to select the value of the field by using the dropdown
- Ability to enter the value by typing into the field
- It should be possible to clear out the typed-in/selected value
- While characters are being typed in, the dropdown has a similar behaviour to that of an autocomplete dropdown
- It should work with the Forms module
- It should have the other default attributes of an input field such as mandatory/disabled etc.

**Existing Implementations using other frameworks.**
Polymer(Vaadin) : https://github.com/vaadin/vaadin-combo-box
AngularJS (Kendo UI) : http://demos.telerik.com/kendo-ui/combobox/angular

**Simple API Example**
```
<td-combo-box 
    [label]="fieldLabel"
    [items]="dataItemsArray"
    [value]="initialValue"
    (change)="onChanged()">
</td-combo-box>
```

**A Featured API Example**
```
<td-combo-box 
    [label]="fieldLabel"
    [items]="dataItemsArray"
    [value]="initialValue"
    [item-label]="propertyInArrayThatShouldBeUsedAsLabel"
    [item-value]="propertyInArrayThatShouldBeUsedAsValue"
    [allowCustomValue]="booleanValue"
    [allowMultiple]="booleanValue"
    (change)="onChanged()"
    (customValueSet)="handleCustomValue()">
</td-combo-box>
```

**Comment by kyleledbetter** [comment]
@asaph26 you're referring to the Autocomplete in material design.
This is it in angular-material version1 https://material.angularjs.org/latest/demo/autocomplete

and it's coming in angular-material2, track the progress of their UI components here:
https://github.com/angular/material2#feature-status (issue tracker https://github.com/angular/material2/issues/117)

that issue mentions a side project version if you need one to hold you over until material2 releases it https://github.com/creativedeveloper-net/angular2-autocomplete

**Comment by kyleledbetter** [comment]
we're also tracking those things here https://github.com/Teradata/covalent/issues/9

**Comment by asaph26** [comment]
@kyleledbetter The material 1 implementation(Floating Label/Custom Template) is what I am looking for. However the side project mentioned doesn't satisfy the needs.

The <td-chips> component also contains autocomplete. 

From a usability point of view, this is a select box that allows searching to select the options.

**Comment by kyleledbetter** [comment]
Yup, well it's definitely coming from the official angular-material2 team, keep an eye on https://github.com/angular/material2/issues/117

**Comment by kyleledbetter** [comment]
and it's not nearly as fully featured but we have an autocomplete combined w/ chips in covalent until then https://teradata.github.io/covalent/#/components/chips

**Comment by asaph26** [comment]
@kyleledbetter : Thank you. I actually wanted to say the chips component also contains autocomplete. But missed it.

I will close this issue for now.
