### ISSUE TITLE
bug(help-component): ExpressionChangedAfterItHasBeenCheckedError 

### ISSUE THREAD

**Issue by richavyas** [Teradata/covalent#1403]
### Do you want to request a *feature* or report a *bug*?
Loading help-component throws the following error:

```
ERROR Error: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'id: undefined'. Current value: 'id: mat-dialog-0'. It seems like the view has been created after its parent and its children have been dirty checked. Has it been created in a change detection hook ?
```

#### Bug Report

<img width="1183" alt="expression-error" src="https://user-images.githubusercontent.com/4469548/60137393-98082700-975b-11e9-9fc0-364d1080a59b.png">

**Comment by christianmemije** [comment]
That is a screenshot of the old demo. That error does not show up in the docs.
