### ISSUE TITLE
Error: "Promise rejection: Cannot read property 'currValExpr' of null"

### ISSUE THREAD

**Issue by sharmasourabh** [Teradata/covalent#141]
#### Bug Report

1. Clone the repo.
2. Install latest angular-cli
3. Other necessary steps for setup
4. ng serve
5. Open http://localhost:4200
6. Browser just displays covalent loader message
7. Console shows  error message:
"Promise rejection: Cannot read property 'currValExpr' of null"

#### What is the expected behavior?
Browser should displays the covalent app

#### Which version of Angular and Material, and which browser and OS does this issue affect?
Angular 2.1.2
Chrome 54

Windows 7
Did this work in previous versions of Angular / Material?
Yes on 2.1.1

##### Other information
Workaround: New release is having the fix: (https://github.com/angular/angular/issues/12583)
Or, modified the src\app\components\components\directives\directives.component.html by assigning the value to  [hidden] attribute.

**Comment by emoralesb05** [comment]
Awesome, thanks for the heads up. We are upgrading our repo to 2.1.2 and fixing this
