### ISSUE TITLE
Redesign Covalent Docs

### ISSUE THREAD

**Issue by jeremysmartt** [Teradata/covalent#1418]
* Redesign docs landing page
* Smaller toolbar
* Styling
* No Templates
* No Design Patterns
* Change Style Guide to Utilities
  * Remove Logo, iconography, resources, product icons 
* Move layouts inside components
* Docs look more like a Getting Started Tutorial
* Group components better

**Comment by philgetz** [comment]
Covalent Redesigned finished in #1582
