### ISSUE TITLE
Desktop Apps with Covalent and Electron

### ISSUE THREAD

**Issue by mrjayhawk** [Teradata/covalent#142]
This repository's issues are reserved for feature requests and bug reports.

#### Feature Request
Request the ability to run Covalent as a desktop app utilizing Electron:
https://github.com/electron/electron

#### What is the motivation / use case for changing the behavior?
While running Covalent in the browser has many use cases there is also the need to create desktop apps that give access to the underlying OS while having a similar look and feel as other web and desktop apps utilizing Covalent.  Would like the ease of writing UIs utilizing Javascript and HTML but be able to access the OS for specific use cases.

##### Other information
http://electron.atom.io/

**Comment by emoralesb05** [comment]
Closing this since we are gonna favor the https://github.com/Teradata/covalent-electron repo to keep track of electron issues.
