### ISSUE TITLE
Schematics - Covalent - ng add

### ISSUE THREAD

**Issue by jeremysmartt** [Teradata/covalent#1420]
* ng add create theme.scss if not there, otherwise modify it
* ng add not create style.scss
* ng add echarts
* ng add code-editor
* ng add text-editor

**Comment by jeremysmartt** [comment]
Priyanka Reviewer

**Comment by richavyas** [comment]
A prerequisite for `covalent schematics` is that it should be an angular project. An angular project created using`ng new` has :
```
- src/styles.scss
- package.json
- angular.json
```

If someone has run `ng add @angular/material` (which is *NOT* a prerequisite), it *updates* the following files:
```
- src/main.ts 
- src/app/app.module.ts 
- angular.json 
- src/index.html 
- src/styles.scss 
```

when `ng add for covalent` is run in an angular project, it:
```
- creates src/theme.scss
- updates package.json for all covalent dependencies
- updates angular.json for adding theme.scss in the styles section
```
