### ISSUE TITLE
3.0 Deprecations

### ISSUE THREAD

**Issue by jeremysmartt** [Teradata/covalent#1421]
Datatable
Stepper
Virtual Scroll
Expansion Panel
File Upload
Flex Layout
~Media Service~
Notifications
    check if `mat-badge` does everything we do
Double check our pipes?

* Verify want to deprecate
* Document how to change from Covalent to Material version
* ng update to do it form them (stretch goal)

**Comment by jeremysmartt** [comment]
Phil to Review

**Comment by JulieMarie** [comment]
List of built-in Angular pipes:

- AsyncPipe
- CurrencyPipe
- DatePipe
- DecimalPipe
- I18nPluralPipe
- I18nSelectPipe
- JsonPipe
- KeyValuePipe
- LowerCasePipe
- PercentPipe
- SlicePipe
- TitleCasePipe
- UpperCasePipe

Our pipes:

- Digits
- Bytes
- DecimalBytes
- TimeAgo
- TimeUntil
- TimeDifference
- Truncate

I think we are good to keep all our pipes.

**Comment by JulieMarie** [comment]
`mat-badge` does not provide a `center` placement option....only `above | below` and `before | after`.

The content itself is a `string` and not a `number`, so while you could create something like `50+`, it would be done differently than how we did it with notifications.

**Comment by JulieMarie** [comment]
The current plan is to deprecate the following features:

1. Datatable - @emoralesb05 
2. Stepper - @JulieMarie 
3. Virtual Scroll - @stevenov7 
4. Expansion Panel - @philgetz 
5. File Upload - @emoralesb05 
6. Media Service - @christianmemije
