### ISSUE TITLE
Propagate help component to Covalent Core

### ISSUE THREAD

**Issue by jeremysmartt** [Teradata/covalent#1425]
* Decouple draggable from help component

**Comment by jeremysmartt** [comment]
Review - Priyanka, Mike, Kris, Phil
Design - Steven

**Comment by emoralesb05** [comment]
- [ ] draggable dialog in the dialogs service (agnostic of help)
- [ ] help component a separate package that is leveraged with the draggable dialog or sidenav.

e.g.

```
dialogService.open(CovalentHelpComponent, {draggable: true, links: []});
```

**Comment by christianmemije** [comment]
Notes from a brainstorming session:

- Get rid of help-window component?
- Add a new method to `dialogService.openDraggable(Component, {config, items})` or `dialogService.open(Component,  {config, items, draggable})`
- Check whether cdk drag handle can be in a parent component
- Create `tdHelp` directive that can be placed on a button that would intercept clicks and call service behind the scenes.

**Comment by jennmedellin** [comment]
This is a really cool component.  Nice job 👍!  The interaction on the home button and back button feels a little odd, particularly without a header on that row and when both show at the same time.  I'd recommend showing either the home icon or the back icon, but not both at the same time.

Also, as a potential future enhancement, it'd be nice to be able to resize the window and possibly pop over to another tab in fullscreen for richer documentation

Kyle mentioned making the initial height of the info window taller using the draggableHelpWindowDialogService, something like 90%.

**Comment by christianmemije** [comment]
@jennmedellin Thank you for the feedback. Will take all this into consideration as I begin to make improvements to this component, and will circle back for more feedback.

**Comment by richavyas** [comment]
Recommending a few more enhancements:
- Don't show home icon when there are no items to navigate or nested items
- Help dialog should be responsive when browser is switched to device mode

**Comment by christianmemije** [comment]
Closing this issue since #1476 was merged, and opened a new issue to track the desired UI changes: #1501
