### ISSUE TITLE
[Feature Request] Help: color param for help toolbar

### ISSUE THREAD

**Issue by kyleledbetter** [Teradata/covalent#1445]
#### Feature Request
It would be nice for the toolbar of the Help component to accept all the standard toolbar color options:

[x] - primary
[x] - accent
[x] - warn
[x] - none (default to white like toolbar)

### Screenshots

primary
![image](https://user-images.githubusercontent.com/867883/61567069-18583a00-aa33-11e9-8e0c-3c7a509214eb.png)

accent
![image](https://user-images.githubusercontent.com/867883/61567041-0d9da500-aa33-11e9-8cb7-67a9aa0a54fc.png)

warn
![image](https://user-images.githubusercontent.com/867883/61567083-23ab6580-aa33-11e9-9350-94ea16fb3579.png)

none
![image](https://user-images.githubusercontent.com/867883/61567093-2e65fa80-aa33-11e9-8292-ea0743ad55db.png)

**Comment by jeremysmartt** [comment]
Review - Priyanka
Design - Priyanka, Mike
