### ISSUE TITLE
[Feature Request] Help: dark mode theme support for help component

### ISSUE THREAD

**Issue by kyleledbetter** [Teradata/covalent#1446]
#### Feature Request
The help component content should inherit the dark mode theme toggle similar to the sidenav/sidesheet

##### Screenshots or link to CodePen/Plunker/JSfiddle

Lightmode
![image](https://user-images.githubusercontent.com/867883/61567185-8b61b080-aa33-11e9-8695-1223f14f1715.png)

Darkmode (bg and text color should change):
![image](https://user-images.githubusercontent.com/867883/61567198-9a486300-aa33-11e9-945c-f6651c35b352.png)

**Comment by emoralesb05** [comment]
None issue, theme has to be set at the body level to apply to dialogs also.

**Comment by kyleledbetter** [comment]
Posting the solution for anyone looking to apply a dark theme to the index.html main `<body>` tag, so anything using the Material CDK for portals/dialogs/menus/etc gets a theme toggle w/ localstorage

In main.component.ts (or your main component where you have the theme toggle):
```
// Theme toggle
  get activeTheme(): string {
    return localStorage.getItem('your.theme');
  }
  theme(theme: string = undefined): void {
    if (!theme) {
      localStorage.removeItem('your.theme');
    } else {
      localStorage.setItem('your.theme', theme);
    }
    document.getElementsByTagName('body').item(0).className = theme;
  }
```

and then in index.html

```
    <script>
      let theme = localStorage.getItem('your.theme');
      document.getElementsByTagName('body').item(0).className = theme;
    </script>
```
