### ISSUE TITLE
Toolbar Notification Component 

### ISSUE THREAD

**Issue by kyleledbetter** [Teradata/covalent#148]
#### Feature Request

I'm seeing a trend that many of our apps with need a notification count/icon menu item w/ a dropdown menu w/ list items, etc

##### Screenshots or link to CodePen/Plunker/JSfiddle

![image](https://cloud.githubusercontent.com/assets/867883/20196825/108b685a-a762-11e6-9754-5312e52b9bf2.png)

**Comment by kyleledbetter** [comment]
![image](https://cloud.githubusercontent.com/assets/867883/20196886/5ddf0512-a762-11e6-85ea-9e197c671d19.png)

**Comment by emoralesb05** [comment]
`md-menu-trigger` now accepts a MdMenuPanel interface. 
https://github.com/angular/material2/pull/1564/files#diff-863c4e6ab704390217dec7361906bec8R30

So this might be just a matter of creating a menu like component and leverage material2 menu-trigger.
e.g.
```
<td-notification-menu #menu="tdNotificationMenu">
    <div td-notification-header>...</div>
    <button td-notification-menu-item> Refresh </button>
    <div td-notification-footer>...</div>
</td-notification-menu>
```
where `TdNotificationMenu implements MdMenuPanel` (maybe even extend `MdMenu`)

OR just creating a directive to style the `md-menu` differently, and apply our theme on it.

e.g.
```
<md-menu td-notification-menu #menu="mdMenu">
    <div td-notification-header>...</div>
    <button md-menu-item> Refresh </button>
    <button md-menu-item> Settings </button>
    <button md-menu-item> Help </button>
    <button md-menu-item disabled> Sign Out </button>
    <div td-notification-footer>...</div>
</md-menu>
```

**Comment by asaph26** [comment]
Is this on the roadmap still? Beta.0 or later?

**Comment by emoralesb05** [comment]
We are doing the initial design, if all goes well, we will include it in alpha.10

**Comment by emoralesb05** [comment]
Initial implementation of `notifications` and `menu` core submodules with https://github.com/Teradata/covalent/pull/213
