### ISSUE TITLE
feature: support for nested CRUD resources in RESTService

### ISSUE THREAD

**Issue by tycho01** [Teradata/covalent#153]
#### Feature Request

In practice it is not uncommon for RESTful (?) APIs to expose endpoints for nested CRUD resources. This is particularly relevant when a given object is deemed dependent on a parent object, with URL paths reflecting this hierarchy, e.g. `/foos/123/bars` or even `/foos/123/bars/456` (note if `bars` share ids across parents this latter example could be simplified to `/bars/456`, but this could potentially differ across implementations).
It would be nice if such constructs would become eligible for abstraction like those offered by `RESTService` as well.
That said, I'm still trying to think about what would be an elegant way to address this additional complexity.

**Comment by emoralesb05** [comment]
I like this idea. Ive been trying to think of a way of really improving the `http` module. 

So if you have any ideas, it would be awesome if we can collaborate together. :+1:

**Comment by tycho01** [comment]
I was thinking in the direction of a `{ [nestedResourceName: string]: RestService<?> }` constructor parameter so one could pass a `{ bars: barRestService }`, then have say a `nested` method so one could have e.g. `fooService.nested(id).bars: RestService<Bar>`.
This raises a few questions primarily regarding the URL path though:
- the nested `RestService` needs to knows its URL path. This becomes tougher though in the sense it is no longer static, as it relies on the ids of parent resources. This raises questions as to whether the above `nested` method notation could effectively pass these through.
- the above leaves some bits to be desired, e.g. allowing separation of `nestedResourceName` and the nested resource URL path. This becomes more relevant especially if it's non-trivial, e.g. `/foos/123/blah/bars/456`.
- Extending from the above point, perhaps non-standard endpoints on a resource are currently a question in general, e.g. `/foos/123/someVariation`. I guess at one point this may also start raising questions as to to what extent `RestService` is the right fit there, but at the very least, I like the idea of having the HTTP verbs abstracted away like it does.

**Comment by ajitsonlion** [comment]
Hello
Maybe something like  [ng2-restangular](https://github.com/2muchcoffeecom/ng2-restangular)  is worth having a look :)

**Comment by tycho01** [comment]
I'd forgotten about that. My quick impression: it's lower-level, which means both good and bad things.

Good:
- it makes it flexible enough to address these questions I had w.r.t. `RestService` currently.

Bad:
- it feels like it doesn't encourage abstracting say HTTP verbs per 'custom' (non-standard REST) endpoint unless you'd like curry `customGET` for reusability, which I'm not sure is deemed idiomatic practice.
- no mention of typings, logical from the ng1 legacy but a forte of `RestService`.

It would be nice if there were a golden mean somehow getting the nice bits of both.

**Comment by emoralesb05** [comment]
The team decided not to implement this since its out of our scope. (even in the future)
