### ISSUE TITLE
Layout nav-list "Full demo": Splitting into components breaks the layout

### ISSUE THREAD

**Issue by makuepfer** [Teradata/covalent#1556]
#### Bug Report

We created an app with the layout similar to your [nav-list full demo example](https://teradata.github.io/covalent/#/layouts/nav-list). If you split the components of the layout into seperate components the layout will be destroyed.

Layout all-in-one-component

![layout_before](https://user-images.githubusercontent.com/28920033/68854791-1a7a8e80-06dd-11ea-903f-705453a6a31b.gif)

Layout splitted-into-components

![layout_after](https://user-images.githubusercontent.com/28920033/68854832-2e25f500-06dd-11ea-9795-95be5a7d94dd.gif)

#### Steps to reproduce

[ ] Create a new angular app

[ ] Install Covalent

[ ] Copy layout "Full Demo" into your app.component 

--> Layout looks as expected. [StackBlitz example all-in-one-component](https://stackblitz.com/edit/covalent-layout-rebuilt-joie3jkl212)

[ ] Move components of the navigation to own components (e.g. NavigationDrawer, Sidenav-Toolbar-Content, Content)

--> Layout is broken as seen in the screenshot above. [StackBlitz example splitted-into-components](https://stackblitz.com/edit/covalent-layout-splitted-1kx7d9)

#### What is the expected behavior?

If I split part of the navigations in components, the navigation will look the same as all in one component.

#### What is the motivation / use case for changing the behavior?

To load different components into the sidenav-content based on the url / route.

**Comment by christianmemije** [comment]
@makuepfer This is expected behavior since this is how ng-content works. The slot names have to be within the same template, they cannot be inside children. What you can do to separate your code is to do something like the following. Notice that the slot names are still within the same template.

```html
<td-layout-nav-list>
  <app-sidenav-header td-sidenav-toolbar-content></app-header>
  <app-header td-toolbar-content></app-header>
  <app-list td-sidenav-content></app-list>
</td-layout-nav-list>
```
