### ISSUE TITLE
RTL - LTR Covalent Documentation 

### ISSUE THREAD

**Issue by saadzah** [Teradata/covalent#1559]
#### Bug Report
RTL - LTR seems to have a bug in the covalent documentation at: https://teradata.github.io/covalent/#/components

If I switch from LTR to RTL and then back to LTR then all the brackets in the example code do not appear correctly, they are reversed/flipped.

Normal appearance:
<img width="1311" alt="Screenshot 2019-11-15 at 2 20 09 PM" src="https://user-images.githubusercontent.com/50866378/68932083-ac54cb00-07b3-11ea-81bf-f2017f26fc9f.png">

After switching back to LTR from RTL:
<img width="1311" alt="Screenshot 2019-11-15 at 2 21 15 PM" src="https://user-images.githubusercontent.com/50866378/68931855-36e8fa80-07b3-11ea-9366-8b15f5a98a40.png">

#### What is the expected behavior?
The brackets should return back to normal on switching back to LTR. I have yet to test it in a test environment. 

#### Which version of Angular and Material, and which browser and OS does this issue affect?

Latest deployed documentation build.

**Comment by philgetz** [comment]
Issue fixed in new documentation
