### ISSUE TITLE
how to set default loading color?

### ISSUE THREAD

**Issue by ranouf** [Teradata/covalent#1583]
Hi,

Using the documentation of tdLoading (https://teradata.github.io/covalent/#/components/loading), I saw the possibility to have the loading set to fullscreen.

How could I change the default color of this loading to "accent"?

Thanks

**Comment by christianmemije** [comment]
@ranouf I opened a PR with a demo of a custom configuration for a fullscreen loader. 

https://github.com/Teradata/covalent/pull/1599/files#diff-84d7c29deaf42164c7781cf3db24f828R11

**Comment by owilliams320** [comment]
this component is deprecated and will no longer be supported in future versions https://material.angular.io/components/progress-spinner/overview
