### ISSUE TITLE
In-Product Help: Add button to each help topic to access full doc library (docs.teradata)

### ISSUE THREAD

**Issue by BetsMorris** [Teradata/covalent#1585]
#### Feature Request
In every IPH topic, add some kind of link--either a button up top or link at the bottom--for users to quickly access the full documentation library at docs.teradata.com.

**Comment by jeremysmartt** [comment]
This can be done in the markdown itself, rather than in the UI.  Looks like this is being done on the Trials documentation already.  See at the bottom of the file here:

https://github.com/Teradata/product-help/blob/master/VantageTrial/GettingStarted/GettingStarted.md

**Comment by jeremysmartt** [comment]
Closing this issue as we can solve this in a different way.  @BetsMorris please contact me if need more info.
