### ISSUE TITLE
In-Product Help: Explore best way to allow users to provide feedback directly on content.

### ISSUE THREAD

**Issue by BetsMorris** [Teradata/covalent#1586]
#### Feature Request
In every IPH topic, explore some kind of ability to provide feedback back on that topic. One option would be a git button or link, so the user can submit changes to us via the markdown file.  Alternatively, some way to directly send a message. The goal is to received direct communications with the users re: the content, including accuracy, suggestions, etc.

**Comment by jeremysmartt** [comment]
This could just be part of the markdown itself, rather than something on the component.  Could have at the bottom of the markdown a link to provide feedback or something along those line.

**Comment by jeremysmartt** [comment]
Closing this issue as we can solve this in a different way. @BetsMorris please contact me if need more info.
