### ISSUE TITLE
Error: Unexpected token import(…) for angular 2 webpack quickstart app

### ISSUE THREAD

**Issue by guilhermevrs** [Teradata/covalent#159]
#### Problem Report

````
Uncaught SyntaxError: Unexpected token import(…)

index.js:10 import { NgModule } from '@angular/core';
````
#### Steps to reproduce

1. Create a project using the instructions of Angular2 Webpack Quickstart (https://angular.io/docs/ts/latest/guide/webpack.html)
2. Download covalent core package `npm install --save @covalent/core`
3. Replace the code of _src/app/app.component.html_ by the td-layout-nav-list example

_src/app/app.component.html_
```html
<td-layout-nav-list #list>
  <div list-toolbar-content layout="row" layout-align="center center" flex>
    <span>App Name</span>
    <span flex></span>
    <button md-button (click)="search()" class="md-icon-button"><md-icon class="md-24">search</md-icon></button>
  </div>
  <md-nav-list list-items>
    <a md-list-item>
    <md-icon md-list-avatar>dashboard</md-icon>
    <h3 md-line> Item Name </h3>
    <p md-line> Item description </p>
    </a>
    <md-divider *ngIf="!last" md-inset></md-divider>
  </md-nav-list>
  <div nav-toolbar-content layout="row" layout-align="center center" flex>
    <span>View Name</span>
    <span flex></span>
  </div>
  ...
</td-layout-nav-list>
```
4. Update _src/app/app.module.ts_ to add the covalent import needed

_src/app/app.module.ts_
```javascript
import { NgModule } from '@angular/core';
import { BrowserModule }  from '@angular/platform-browser';

import { CovalentCoreModule, TD_LOADING_ENTRY_COMPONENTS } from '@covalent/core';

import { AppComponent } from './app.component';
@NgModule({
  imports: [
    BrowserModule,
    CovalentCoreModule.forRoot()
  ],
  declarations: [
    AppComponent
  ],
  entryComponents: [ TD_LOADING_ENTRY_COMPONENTS ],
  bootstrap: [ AppComponent ],
})
export class AppModule { }
```
5. Bundle everything using `npm start`

##### Other information

I believe that the problem is that covalent typescript is transpiled to es6, while the webpack quickstart targets commonjs.

Do you have an idea on how I could fix this issue?

Thank you in advance,

Guilherme

**Comment by guilhermevrs** [comment]
Sorry, just found out the way to do it using a babel-loader specific for your package :)

**Comment by kyleledbetter** [comment]
cool thx for reporting back with the solve
