### ISSUE TITLE
Covalent Docs - Identify gaps from all the previous demos

### ISSUE THREAD

**Issue by jeremysmartt** [Teradata/covalent#1591]
Not all the demos that were on each component previously were brought over.  Need to bring over all the demos we want in the new Docs.

**Comment by richavyas** [comment]
Here's the list of components which require more demos to be added in the new docs:

- Messages
- Search
- Notifications
- Breadcrumbs
- Paging
- Nav Steps
- Simple Dialogs
- Dynamic Forms
- Flavored Markdown Parser
- Markdown Parser
- Markdown Navigator : needs some correction
- Code Editor: change theme and language examples are missing
- Text Editor: example isn't working properly
- Syntax Highlight: html & typescript examples are missing
- all echarts: code section requires correction

Components missing demos but are possible deprecs: 
- Chips Autocomplete
- Stepper
- Data Table
