### ISSUE TITLE
Show more on td-message doesnt work anymore

### ISSUE THREAD

**Issue by ranouf** [Teradata/covalent#1592]
Hi,

On the documentation (https://teradata.github.io/covalent/#/components/message/overview) when I click on show more, nothing happens.

Could you fix the issue? 

Thanks

**Comment by ranouf** [comment]
Moreover in the example:
<td-message #message label="Label" sublabel="Sublabel goes here" icon="warning" color="primary | blue | red" [opened]="true">
  <button td-message-actions mat-button>View More</button>
  <button td-message-actions mat-button (click)="message.close()">Close</button>
  // .. body goes here
</td-message> 

Whatever I put in the body section, it ll never appear. 

Could you take a look on it too?

**Comment by thomaslennan** [comment]
I think the docs were confusing. Have updated the example to demonstrate closing a message and re-displaying with external button.
