### ISSUE TITLE
Docs: Home page links show wrong mouse cursor

### ISSUE THREAD

**Issue by aciccarello** [Teradata/covalent#16]
This repository's issues are reserved for feature requests and bug reports.

### Do you want to request a *feature* or report a *bug*?
bug

#### Bug Report
On the docs home page, the four cards which link to pages show a text highlight cursor instead of a pointer. This makes it unclear that these cards can be clicked.

##### Screenshots or link to CodePen/Plunker/JSfiddle
![home page link cursor](https://cloud.githubusercontent.com/assets/11273838/16843514/7f3df6ca-49af-11e6-9ed9-47099634c0bb.gif)

#### What is the expected behavior?
Mouse should change to pointer cursor when hovering over cards that are links. It would also be nice if chrome understood it as a link too and showed the url at the bottom (similar to button links).

#### What is the motivation / use case for changing the behavior?
It is unclear that these are links until they are clicked on

#### Which version of Angular and Material, and which browser and OS does this issue affect?
Chrome

Did this work in previous versions of Angular / Material?
Please also test with the latest stable and snapshot versions.
N/A

##### Other information
(e.g. detailed explanation, stacktraces, related issues, suggestions how to fix)

**Comment by kyleledbetter** [comment]
I saw this too. Seems like angular removes all link classes when you do a prod build :( need to research alternatives

Thx for the report!

**Comment by kyleledbetter** [comment]
fixed in #22
