### ISSUE TITLE
Data Table Demo

### ISSUE THREAD

**Issue by jeremysmartt** [Teradata/covalent#1643]
Data Table
Add all previous demos

**Comment by istvanszoboszlai** [comment]
I remember reading something about datatable being deprecated. Do I remember wrong, or have you guys changed your minds? If you have, what was reason?

**Comment by emoralesb05** [comment]
We do want to deprecate it but we dont have a migration plan yet on to which data table to use.. if we are going to build a wrapper for mat-table or use something else.

Whenever we have an answer to this, we will put a notice and deprecate it properly. Right now we are just encouraging new users to not use it if they find a better solution out there.
