### ISSUE TITLE
[Feature] Add ngx-mask support to TdDynamicInputComponent

### ISSUE THREAD

**Issue by rafaneri** [Teradata/covalent#1645]
#### Feature Request
Add support to `ngx-mask` in `TdDynamicInputComponent` adding a new attribute like mask.

**Comment by owilliams320** [comment]
@rafaneri Thanks for your feature request. Currently the core team is not actively working on Dynamic Forms. If you are looking for this type of support i would recommend looking at https://angular.io/guide/reactive-forms
