### ISSUE TITLE
Dynamic Forms not working on angular 9 and ivy compiler

### ISSUE THREAD

**Issue by RafaelPallaresITB** [Teradata/covalent#1647]
#### Bug Report

On an angular 9 with ivy compiler
Start a new covalent project, copy paste the dynamic forms code from https://teradata.github.io/covalent/#/components/dynamic-forms/overview.
The application will compile but it will not run 

##### Screenshots or link to CodePen/Plunker/JSfiddle

![MicrosoftTeams-image](https://user-images.githubusercontent.com/54269036/74931172-5e1d1c80-53df-11ea-9711-72db017d4c5f.png)

#### What is the expected behavior?
The application should show the dynamic form

#### Which version of Angular and Material, and which browser and OS does this issue affect?
Angular 9, on firefox and chrome

Did this work in previous versions of Angular / Material?

yes, in angular 8 and ivy compiler disabled it works flawlessly

**Comment by ranouf** [comment]
Hi,

Just to group errors with Angular 9 upgrade, I have some too:
```
ERROR in Failed to compile entry-point @covalent/core (es2015 as esm2015) due to compilation errors:
node_modules/@covalent/core/fesm2015/covalent-core.js:8517:26 - error NG1010: Value at position 1 in the NgModule.imports of CovalentLayoutModule is not a reference: [object Object]

8517                 imports: [
                              ~
8518                     CommonModule,
     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 ...
8525                     MatDividerModule,
     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
8526                 ],
     ~~~~~~~~~~~~~~~~~
node_modules/@covalent/core/fesm2015/covalent-core.js:11546:26 - error NG1010: Value at position 4 in the NgModule.imports of CovalentStepsModule is not a reference: [object Object]

11546                 imports: [
                               ~
11547                     CommonModule,
      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  ...
11552                     CovalentCommonModule,
      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
11553                 ],
      ~~~~~~~~~~~~~~~~~
```

Let me know @RafaelPallaresITB  (or admins) if you want me to create a new issue?

**Comment by christianmemije** [comment]
@ranouf In your case, the primary entry points got removed in [3.0.0-beta3](https://github.com/Teradata/covalent/blob/develop/docs/CHANGELOG.md#300-beta3-2020-02-10), so you need to use secondary entry points.

**Comment by christianmemije** [comment]
@RafaelPallaresITB What Covalent version are you using?

**Comment by RafaelPallaresITB** [comment]
Hi!
The problem was that we had @covalent/core on the latest beta 3.0.0 but @covalent/dynamic-forms on the stable branch (2.1.1).
Problem solved, i'm just explaining it to help someone who has the same problem.
Thank you all very much
