### ISSUE TITLE
Theming requires to load all covalent modules in the project

### ISSUE THREAD

**Issue by asaph26** [Teradata/covalent#166]
Compilation of the sass file to css breaks when the covalent-theme function is applied if all covalent modules are not present in the project.

material2 is installed as one package, guaranteeing that all the modules are present, while covalent is separated out as multiple packages.

Suggestion: Add documentation to specify how theming can be done individually for each module.

I would be willing to create a pull request if you think this is a good way to go.

**Comment by asaph26** [comment]
@kyleledbetter @emoralesb05 Need your thoughts on this one.

**Comment by kyleledbetter** [comment]
Short term workaround would be to load all Covalent modules and let tree shake hopefully help with unused code, while we work on a more graceful conditional load of scss themes

**Comment by emoralesb05** [comment]
Sorry for the delay. I think for now we will include docs on how to import the themes for each module, but the end game (maybe) would be package everything in one like material2 does.

We have an issue open to track the bundling part. https://github.com/Teradata/covalent/issues/93

**Comment by emoralesb05** [comment]
We decided to bundle everything that makes sense under `core`.

So the only modules that would be stand alone would be:
- `highlight`  and `markdown` since they use 3rd party js libs,
- `http` since the focus of it is different.
- `core` (with everything else on it)

**Comment by emoralesb05** [comment]
Fixed with https://github.com/Teradata/covalent/pull/201
