### ISSUE TITLE
Provide EasyMDE typings

### ISSUE THREAD

**Issue by KingDarBoja** [Teradata/covalent#1670]
In order to end users to know which options are available while coding (e.g. using Intellisense on VSCode), would be great to provide the EasyMDE typing definition in this package.

In the meantime, had to install `easymde` along with `@types/marked` and `@types/codemirror` to get type hints.

**app.component.ts**
```typescript
import { Component } from '@angular/core';

import { Options } from 'easymde';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'covalent-editor-fu';

  sampleText = 'Hello World!';

  covalentEditorOpts: Options = {
    lineWrapping: true,
    toolbar: true,
  };
}
```

**Comment by owilliams320** [comment]
see https://github.com/Ionaru/easy-markdown-editor/blob/master/types/easymde.d.ts
