### ISSUE TITLE
Dialogs: Add standard hotkeys to simple dialogs

### ISSUE THREAD

**Issue by quanterion** [Teradata/covalent#170]
Can you add hotkeys to dialogs displayed via TdDialogService to emulated native behavior.

1. Pressing ENTER in prompt dialog should accept user input and close the dialog
2. Pressing LEFT_ARROW and RIGHT_ARROW keys should switch focus between AGREE and DISAGREE buttons. Pressing ENTER should close the dialog this result based on focused button.

**Comment by emoralesb05** [comment]
Dialogs do need `a11y` support. 

Adding this to the 0.10 milestone.

**Comment by emoralesb05** [comment]
Added and will be available for 0.10
