### ISSUE TITLE
Dialogs: improve API

### ISSUE THREAD

**Issue by quanterion** [Teradata/covalent#171]
You makes it really simple to open simple dialogs. I suggest a few additions:

1. You have created a service with alert/prompt/confirm methods. If I need to open custom-component dialog I would need to inject MdDialog service to open it. So it often ends up with injecting two similar services. It would be great to have simple open method from MdDialog in TdDialogService to avoid double injection.

2. Add simple alternatives to alert/prompt/confirm that way:
`prompt(string): Observable<string>;`
It would allow even simpler way to use dialogs!

PS: I can make a PR for this if you like the ideas!

**Comment by emoralesb05** [comment]
I agree, it would be simple to create wrapper methods to the `MdDialog` methods inside `TdDialogService` so we dont have to inject both. e.g. `tdDialogService.open(CustomDialog)`

**Comment by emoralesb05** [comment]
Added point no 1 and will be available for 0.10.
