### ISSUE TITLE
Covalent Markdown Parser example doesn't have code highlight

### ISSUE THREAD

**Issue by KingDarBoja** [Teradata/covalent#1717]
#### Bug Report

The markdown parser example available at [markdown-parser](https://teradata.github.io/covalent/v3/#/components/markdown-parser/examples) components section doesn't have any kind of highlighting on code blocks.

##### Screenshots or link to CodePen/Plunker/JSfiddle
![missing-highlight](https://user-images.githubusercontent.com/30560560/77930701-d85b7f00-7270-11ea-94c3-4b790008c986.png)

#### What is the expected behavior?
To show up code highlight as in GitHub.

#### What is the motivation / use case for changing the behavior?
I want to render some markdown which contains code blocks on some languages like Python, TypeScript but tried locally and got no highlighting on the output.

#### Which version of Angular and Material, and which browser and OS does this issue affect?

On my local test, I have the following Angular version:

```console
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/


Angular CLI: 9.1.0
Node: 12.14.0
OS: win32 x64

Angular: 9.1.0
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.0
@angular-devkit/build-angular     0.901.0
@angular-devkit/build-optimizer   0.901.0
@angular-devkit/build-webpack     0.901.0
@angular-devkit/core              9.1.0
@angular-devkit/schematics        9.1.0
@ngtools/webpack                  9.1.0
@schematics/angular               9.1.0
@schematics/update                0.901.0
rxjs                              6.5.4
typescript                        3.8.3
webpack                           4.42.0
```

**Did this work in previous versions of Angular / Material?**

No idea.

**Comment by owilliams320** [comment]
Hello @KingDarBoja
