### ISSUE TITLE
childrenUrl property for markdown navigator

### ISSUE THREAD

**Issue by jeremysmartt** [Teradata/covalent#1721]
childrenUrl property

interface IMarkdownNavigatorItem {
  title?: string;
  url?: string;
  httpOptions?: object;
  markdownString?: string; // raw markdown
  anchor?: string;
  children?: IMarkdownNavigatorItem[];
  childrenUrl?: string;
}

Try to fetch a IMarkdownNavigatorItem[] from that url

**Comment by christianmemije** [comment]
Fixed in #1727
