### ISSUE TITLE
tdLoading nextElementSibling issue on FF

### ISSUE THREAD

**Issue by christianmemije** [Teradata/covalent#1723]
# Bug Report

`nextElementSibling` seems to be behaving differnetly in FF and Chrome. In cases where an elem has no next sibling, the incorrect height is being set. See:

https://github.com/Teradata/covalent/blob/develop/src/platform/core/loading/services/loading.factory.ts#L118-L121

**Comment by owilliams320** [comment]
this component is deprecated and will no longer be supported in future versions https://material.angular.io/components/progress-spinner/overview
