### ISSUE TITLE
tdLoading with :leave animation not working

### ISSUE THREAD

**Issue by filipows** [Teradata/covalent#1724]
### Do you want to request a *feature* or report a *bug*?
bug
#### Bug Report
When using `:leave` animation with `tdLoading` the element is being removed from DOM immediately before the leave animation is being played

Here's reproduction: https://github.com/filipows/covalent-tdloading-animation-on-leave-issue

![tdLoading](https://user-images.githubusercontent.com/884847/78244261-d36c2900-7517-11ea-82fd-a93a29bf52d1.gif)

#### What is the expected behavior?
Animation on leave is being played before removing the element.

#### Which version of Angular and Material, and which browser and OS does this issue affect?
Angular 9.1
Material 9.2
Covalent 3.0

**Comment by owilliams320** [comment]
this component is deprecated and will no longer be supported in future versions https://material.angular.io/components/progress-spinner/overview
