### ISSUE TITLE
Integration with existing Project

### ISSUE THREAD

**Issue by AldrichMascarenhas** [Teradata/covalent#173]
IS there any step by step for Integration with your current project?
I've npm installed the latest Covalent Core, Added to my app.module.ts
I have also added the fololowing to my angular-cli.json file

```
"styles": [
        "theme.scss",
        "../node_modules/@covalent/core/styles/platform.css",
        "../node_modules/@angular/material/core/overlay/overlay.css"
        
      ],
```

"theme.scss",  has been copied from the quickstart repo.

ERROR in multi styles
Module not found: Error: Can't resolve 'G:\Start what\DishMenuWebApp\node_modules\@angular\material\core\overlay\overlay.css' in 'G:\Start what\DishMenuWebApp\node_modules\angular-cli\m
odels'
 @ multi styles

package.json content 
```

{
  "name": "dish-menu-web-app",
  "version": "0.0.0",
  "license": "MIT",
  "angular-cli": {},
  "scripts": {
    "start": "ng serve",
    "lint": "tslint \"src/**/*.ts\"",
    "test": "ng test",
    "pree2e": "webdriver-manager update",
    "e2e": "protractor"
  },
  "private": true,
  "dependencies": {
    "@angular/common": "2.2.1",
    "@angular/compiler": "2.2.1",
    "@angular/core": "2.2.1",
    "@angular/forms": "2.2.1",
    "@angular/http": "2.2.1",
    "@angular/platform-browser": "2.2.1",
    "@angular/platform-browser-dynamic": "2.2.1",
    "@angular/router": "3.2.1",
    "@covalent/core": "^0.9.1",
    "angularfire2": "^2.0.0-beta.6",
    "core-js": "^2.4.1",
    "firebase": "^3.6.1",
    "rxjs": "5.0.0-beta.12",
    "ts-helpers": "^1.1.1",
    "zone.js": "^0.6.23"
  },
  "devDependencies": {
    "@angular/compiler-cli": "2.2.1",
    "@types/jasmine": "2.5.38",
    "@types/node": "^6.0.42",
    "angular-cli": "1.0.0-beta.21",
    "codelyzer": "~1.0.0-beta.3",
    "jasmine-core": "2.5.2",
    "jasmine-spec-reporter": "2.5.0",
    "karma": "1.2.0",
    "karma-chrome-launcher": "^2.0.0",
    "karma-cli": "^1.0.1",
    "karma-jasmine": "^1.0.2",
    "karma-remap-istanbul": "^0.2.1",
    "protractor": "4.0.9",
    "ts-node": "1.2.1",
    "tslint": "3.13.0",
    "typescript": "~2.0.3",
    "webdriver-manager": "10.2.5"
  }
}

```

**Comment by AldrichMascarenhas** [comment]
I should also mention while running
npm install @covalent/core --save
it threw UNMET PEER DEPENDENCY  for angular/core

**Comment by asaph26** [comment]
@AldrichMascarenhas: 
Remove the "../node_modules/@angular/material/core/overlay/overlay.css" from the angular-cli.json file.

For the unmet peer dependency, it is caused because of the version mismatch between the version of angular for your project and the one that covalent has declared. It shouldn't cause any problems as long as your project is not far behind

**Comment by kyleledbetter** [comment]
@AldrichMascarenhas also be sure to checkout how we setup and build the covalent-quickstart (check the package.json and such) https://github.com/Teradata/covalent-quickstart/

**Comment by AldrichMascarenhas** [comment]
@kyleledbetter Was referring to that. I thought the issue was because i was using 0.9.1 of Covalent. 
And the quickstart hasn't been updated to the latest of 0.9.1 
No issues now, Thank you so much.

@asaph26 Solution worked for me. Deleting the line fixed the issue.

**Comment by kyleledbetter** [comment]
Great to hear, I'll close and we'll note this tip.

We'll have the quickstart updated for 0.9.1 tomorrow.

**Comment by emoralesb05** [comment]
Just as something to keep track in this PR. 
We have a PR in covalent-quickstart to migrate from 0.8 to 0.9.1 (which has the correct configurations for 0.9.1)

https://github.com/Teradata/covalent-quickstart/pull/20/commits
