### ISSUE TITLE
Dropdown in Covalent

### ISSUE THREAD

**Issue by totalard** [Teradata/covalent#174]
Dear,

I need Dropdown Feature, To just show user logged in status and Logout in top Navbar right aligned.

I didnt fount it yet in covalent. Any how.. Any possibility? it is a mandatory feature.

**Comment by StefanSinapov** [comment]
@totalard You can use [md-menu](https://github.com/angular/material2/blob/master/src/lib/menu/README.md)

**Comment by kyleledbetter** [comment]
yup, thx @StefanSinapov 

@totalard you can use an md-icon-button with an md-menu in a md-toolbar for what you're asking for, make sure to use the `x-position="after"` on your md-menu if it's going to be right aligned, it's in the docs https://github.com/angular/material2/blob/master/src/lib/menu/README.md#customizing-menu-position

**Comment by kyleledbetter** [comment]
closing since this is solved w/ md-menu
