### ISSUE TITLE
ability to change the theme 

### ISSUE THREAD

**Issue by ineselmufti** [Teradata/covalent#1744]
the user should be able to choose between several themes in the website

**Comment by oussama-ber** [comment]
it's a good feature.

**Comment by youssefbhs8** [comment]
@ineselmufti still working on it?

**Comment by kyleledbetter** [comment]
Check out the theme service used to switch themes in local storage in a separate repo not specific to covalent https://github.com/Teradata/vantage-ui-platform/tree/aab6c1cd3aaefdbea11c3e7a0047353a521986b9/src/lib/theme

**Comment by jeremysmartt** [comment]
closing, see link above for theme service
