### ISSUE TITLE
add contact page

### ISSUE THREAD

**Issue by ineselmufti** [Teradata/covalent#1749]
Adding a contact page will help the user get in touch with the owner for any feedbacks.

**Comment by kyleledbetter** [comment]
Github issues (like this one) are the common pattern for contacting open source maintainers, right?

**Comment by emoralesb05** [comment]
Yup, issues and pull requests are the way for the core maintainers to collaborate with the community and give feedback.

**Comment by youssefbhs8** [comment]
@ineselmufti maybe instead of a contact page we should add terada's facebook page or twitter in the footer
