### ISSUE TITLE
[Feature] Data Table: Drag rows to change the order they are stored in.

### ISSUE THREAD

**Issue by AldrichMascarenhas** [Teradata/covalent#175]
![components_listcontrols_reorder](https://cloud.githubusercontent.com/assets/11980185/20651267/20ea133c-b508-11e6-8380-39124924f599.png)

https://material.google.com/components/lists-controls.html#lists-controls-types-of-list-controls

Suggestion
Create a event that can output the new ordering or something that could be used o reorder the data in the backend?

**Comment by kyleledbetter** [comment]
I'm not sure if we'll add this feature, but you can always either code your own drag'n'drop service or directive, or use an existing ng2 solution like https://github.com/valor-software/ng2-dragula on an md-list-item or data-table row

**Comment by AldrichMascarenhas** [comment]
@kyleledbetter I will have a look at ng2-dragula. Thanks!

**Comment by emoralesb05** [comment]
Closing since we havent heard anything more and we wont implement a drag n drop feature since we favor ng2-dragula.
