### ISSUE TITLE
No component factory found for TdLoadingComponent

### ISSUE THREAD

**Issue by DSchroer** [Teradata/covalent#1759]
### Bug Report
Adding loading component results in an error. The component is no longer registered as an entry component and causes Angular to throw an error. 

Adding a `*tdLoading=` directive to any part of the application will trigger this error. 

StackBlitz: https://stackblitz.com/edit/covalent-ynuejb

```
ERROR Error: "No component factory found for TdLoadingComponent. Did you add it to @NgModule.entryComponents?"
```

#### What is the expected behavior?
The loading component should work correctly.

**Comment by DSchroer** [comment]
I will be submitting a PR with a fix for this shortly. It seems that the entry component was removed recently. I will be restoring it.

**Comment by owilliams320** [comment]
this component is deprecated and will no longer be supported in future versions https://material.angular.io/components/progress-spinner/overview
