### ISSUE TITLE
[Bug] Expansion Panels don't have dynamic height

### ISSUE THREAD

**Issue by Daeluse** [Teradata/covalent#177]
This repository's issues are reserved for feature requests and bug reports.

### Do you want to request a *feature* or report a *bug*?
Bug

#### Bug Report
If the height of the inner content of an expansion panel changes, the expansion panel itself does not grow or shrink to fit the new content.

Normal fit with two fields, new field button is visible.
![bug](https://cloud.githubusercontent.com/assets/6115456/20726256/ba3d7dcc-b642-11e6-862f-310fa1ec5c23.PNG)

After adding one additional field, the button begins to be pushed off screen.
![bug1](https://cloud.githubusercontent.com/assets/6115456/20726258/bb95a8d4-b642-11e6-9451-d89f85fbff46.PNG)

After adding a field again, the button is no longer visible. Closing and re-opening the panel will resolve.
![bug2](https://cloud.githubusercontent.com/assets/6115456/20726260/c112c440-b642-11e6-8cc9-891fcc9720c5.PNG)

**Comment by emoralesb05** [comment]
This was fixed in 0.9.1. There was a problem with ng2 animations.

**Comment by emoralesb05** [comment]
Closed since it was fixed in 0.9.1.
