### ISSUE TITLE
Upgrade to Angular 10

### ISSUE THREAD

**Issue by jeremysmartt** [Teradata/covalent#1774]
https://blog.angular.io/version-10-of-angular-now-available-78960babd41

**Comment by jeremysmartt** [comment]
@emoralesb05 
should most likely upgrade the docs, and keep the packages supporting both 9 and 10 with ^9.0.0 || ^10.0.0

So allow this change in a Covalent dot release

**Comment by smurfy** [comment]
Tested with angluar/material 10, it seems something related to scss changed too.

**Comment by Zwartpet** [comment]
9 and 10 don't use the same tslib and typescript version, sure you wanna support both in the next dot release?
