### ISSUE TITLE
Switch to eslint as tslint is deprecated

### ISSUE THREAD

**Issue by JulieMarie** [Teradata/covalent#1777]
### Do you want to request a *feature* or report a *bug*?

Bug

#### Bug Report

StackBlitz template: https://stackblitz.com/edit/covalent

#### Which version of Angular and Material, and which browser and OS does this issue affect?

Did this work in previous versions of Angular / Material?

**Comment by KingDarBoja** [comment]
I would recommend waiting for the Angular team to migrate its own repo to ESLint as stated at https://github.com/angular/angular-cli/issues/13732 .

Keep in mind that if you still do the migration, not all rules are supported by https://github.com/angular-eslint/angular-eslint, which is the plugin that handles the Angular lint rules (equivalent of codelzyer rules).

Cheers!

**Comment by JulieMarie** [comment]
Thanks for the tips Manuel!
