### ISSUE TITLE
Parameterize confirm dialog button color

### ISSUE THREAD

**Issue by DersJ** [Teradata/covalent#1778]
#### Feature Request

Add the ability to pass a material color (i.e. primary/accent/warn) to the confirm dialog's accept button. 

I'd like to be able to use the confirm dialog to confirm a destructive action with a `color="warn"` button. This can be done by overriding the button color with some css in the product, but obviously that isn't ideal. 

Default would be "accent" to mimic existing implementation.

**Comment by adamnel** [comment]
Could we do this with some sort of state parameter instead? eg this button is destructive, instead of this button is red?
