### ISSUE TITLE
Docs Request: How to guide to integrate this with an existing project?

### ISSUE THREAD

**Issue by georgeedwards** [Teradata/covalent#178]
Firstly, I am unsure if it is even feasible to use this platform with an existing project, if so - Could there be a getting started guide for using this in an existing project?

**Comment by emoralesb05** [comment]
Its included almost the same way you would include material2.

But yeah, i think we need to add step by step docs since it seems most people have a hard time doing this on existing projects.

**Comment by John0x** [comment]
@emoralesb05 I would appreciate this too, since it is is very confusing to setup.
Actually I can't seem to find a clean way to include the platform.css with webpack 2 because of the fonts.

**Comment by emoralesb05** [comment]
@John0x commented on the other issue with a possible fix for it.

**Comment by emoralesb05** [comment]
Added getting started linking to material2 repo for additional info. https://github.com/Teradata/covalent/blob/develop/docs/GETTING_STARTED.md
