### ISSUE TITLE
Issue in documentation

### ISSUE THREAD

**Issue by ranouf** [Teradata/covalent#1783]
Hi,

I can't open it:
![image](https://user-images.githubusercontent.com/1764519/89001396-1d97c800-d2c8-11ea-9f81-e89fadbd2c48.png)

url: https://teradata.github.io/covalent/v3/#/components/message/examples

Could you fix it?

**Comment by sdasari540** [comment]
PR for this fix:  https://github.com/Teradata/covalent/pull/1812
