### ISSUE TITLE
Allow go back flag is not working in guided tour

### ISSUE THREAD

**Issue by sdasari540** [Teradata/covalent#1800]
### Do you want to request a *feature* or report a *bug*?
bug

#### Bug Report
`allowGoBack` flag in `advanceOnOptions` of guided tour is not working as expected.

#### Steps to reproduce the issue
1. create a step in guided tour with no `advanceOn` parameter
2. Define `advanceOnOptions` and assign `allowGoBack` as false
3. back button is still visible.

StackBlitz template: https://stackblitz.com/edit/covalent-nsjjk5?file=app/app.component.ts

#### What is the expected behavior?
Back button should not be visible the `allowGoBack` is set to false.

#### Which version of Angular and Material, and which browser and OS does this issue affect?
Whatever the demo uses (all browsers)

**Comment by 9inpachi** [comment]
I can reproduce this as well.
After looking a little, I found that the problem exists somewhere [HERE](https://github.com/Teradata/covalent/blob/develop/src/platform/guided-tour/guided.tour.ts#L267-L289).
I am trying to solve it. Will open a PR once I do.
