### ISSUE TITLE
Angular version policy?

### ISSUE THREAD

**Issue by craigsmitham** [Teradata/covalent#1810]
We've been using Covalent for over 3 years in production and are very thankful for it and the community contributors. We try to stay on top of updating dependencies and look forward to new features available in Angular 10 and the latest version of TypeScript, but we don't upgrade until a release version Covalent supports the new Angular version. It's been 3 months since Angular v10 was released and not clear from https://github.com/Teradata/covalent/issues/1774 what the target/expectation should be. Obviously support for upgrades sooner rather than later is desirable, but communication to help guide our roadmap would be the most helpful. Is there a policy/target for when new Angular versions will be supported following a major Angular release?

It would also be nice to have a clear documentation of what versions of Covalent support which version(s) of Angular.

**Comment by thomaslennan** [comment]
Hi Craig,

PR [PR 1808](https://github.com/Teradata/covalent/pull/1808) bumping Covalent to Angular 10 is pending final sign off. Approval should be soon. If you'd like to pull the code and play with it, it would be appreciated.

Regards,
Tom

**Comment by craigsmitham** [comment]
@thomaslennan that's good to know re: Angular 10. 

Is there a target timeline/policy for keeping Covalent in version sync with Angular on a regular basis? How can we quickly and confidently identify which version(s) of Covalent are compatible with which version(s) of Angular?

**Comment by craigsmitham** [comment]
@thomaslennan any update on policy or guidance when it comes to major Angular releases and versions of Covalent? Angular is already on RC 2 for version 11. 

This impacts our ability to keep Angular up-to-date. This prevents us from taking advantage of the latest Angular features. This also has a downstream impact on other dependencies. We're not able to upgrade TypeScript and we can't count on other Angular libraries publishing updates for old versions of Angular.

**Comment by emoralesb05** [comment]
Is there an actual issue when trying to use angular 10? as far as i know, covalent 3.X works with angular 10v.. ive been using projects with it so im not getting any issues. 

Having said that, we are trying to upgrade to angular 10 just as a way for the library to leverage the capabilities, but not because of errors or issues.

**Comment by craigsmitham** [comment]
If there was a clear policy or guidance that 3.X should work with Angular 10, then we would attempt to upgrade and do our best to help resolve them. But in the absence of that we're left with ambiguity and it's unclear if we should invest effort in that attempt to upgrade. This issue is asking about any policy or guidance that is available on what version(s) of Covalent support what version(s) of Angular, specifically major versions, so that we can make an informed decision about when to plan on attempting to upgrade.

**Comment by emoralesb05** [comment]
Gotcha, ill create a section on the main README.md to state which versions of angular and material should work with covalent 3.X.

**Comment by craigsmitham** [comment]
Thank you! Look forward to trying Covalent 3.X with Angular 10.

**Comment by emoralesb05** [comment]
Added the matrix on the README.

But please let us know if you encounter any issues, we have tested with our internal products and havent found any issues with covalent 3.X -> ng 9.X/10.X

We already merged the ng10 upgrade and are gonna start focusing on the future releases

**Comment by craigsmitham** [comment]
@emoralesb05 Ed this is great, thank you again and thanks for your work on Covalent!
