### ISSUE TITLE
Dynamic Forms Appearance Attribute

### ISSUE THREAD

**Issue by Keithcat767** [Teradata/covalent#1814]
#### Feature Request
Add the ability to pass in an appearance preference that gets passed to the `mat-form-field` component.

#### What is the motivation / use case for changing the behavior?
This would allow users to leverage the built in appearance variations provided by Angular Material (https://material.angular.io/components/form-field/overview#form-field-appearance-variants)

Currently, this can be done by using the global override Angular Material provides: `MAT_FORM_FIELD_DEFAULT_OPTIONS`.

Example: 
```
providers: [
  {provide: MAT_FORM_FIELD_DEFAULT_OPTIONS, useValue: {appearance: 'outline'}}
]
```

This works for me, but it is possible people would like to have more granular control over this attribute based on the form field type or where it lives. 

If you think this global setting is enough, it might be worth just a small update to the dynamic forms documentation. Otherwise I propose extending the `ITdDynamicElementConfig` to allow for the key of appearance and the value to be equal to an enum of values that match the options allowed by Angular Material.

I am happy to provide a PR for either direction, let me know your thoughts!

Thanks for the great library!

**Comment by luaks** [comment]
Adding to this:
The material spec currently suggests the use of either "outlined" or "filled" text fields. (https://material.io/components/text-fields)
This was done some time ago to combat the bad visibility / bad discoverability of the "legacy" form fields. (https://medium.com/google-design/the-evolution-of-material-designs-text-fields-603688b3fe03)

IMO the default should be either `outlined` or `fill` to conform with the current suggestions by the material spec.

The simplest way would probably be to provide `MAT_FORM_FIELD_DEFAULT_OPTIONS`, but I don't think thats covalents job.
However if `ITdDynamicElementConfig` has a default, it will always override whatever users set in their provided `MAT_FORM_FIELD_DEFAULT_OPTIONS`.

I guess the best first step would be to give a hint for `MAT_FORM_FIELD_DEFAULT_OPTIONS` in the documentation.
Additionally `ITdDynamicElementConfig` should probably have an optional `appearance` property to selectively adjust the appearance.

**Comment by owilliams320** [comment]
This component is deprecated and will not be supported in future versions.
