### ISSUE TITLE
[Question] Search Box/Search Input Clear

### ISSUE THREAD

**Issue by asaph26** [Teradata/covalent#182]
Is there a way to clear the search box/search input through typescript code?

**Comment by emoralesb05** [comment]
You can access the element via @ViewChild(TdSearchBoxComponent) searchBox; and use its `.value` property.

e.g. `searchBox.value = 'val'`

or 

<td-search-box #searchBox>

**Comment by asaph26** [comment]
@emoralesb05 Thank you.
