### ISSUE TITLE
Native browser spell check support

### ISSUE THREAD

**Issue by paulkmoore** [Teradata/covalent#1825]
#### Feature Request

Native browser spell check support was added to EasyMDE from 2.10.0, using the following options:

```
    inputStyle: 'contenteditable',
    nativeSpellcheck: true,
```

The @covalent/text-editor currently uses 2.8.0, so this is a request to update the EasyMDE version to 2.10.0 or higher.

##### Other information
Users may wish to be aware of Ionaru/easy-markdown-editor#133 regarding Grammarly support within EasyMDE

**Comment by owilliams320** [comment]
@paulkmoore this has been update with covalent/text-editor 4.x.
