### ISSUE TITLE
Table column width changes continuously 

### ISSUE THREAD

**Issue by erkevalk** [Teradata/covalent#1826]
### Do you want to request a *feature* or report a *bug*?
bug
#### Bug Report

After update the covalent from version 2.0.0-beta.1 to version 3.0.1 table column width changes randomly between two values continuously. 

##### Screenshots or link to CodePen/Plunker/JSfiddle

![github-1](https://user-images.githubusercontent.com/75480718/101159885-1f95dd00-3654-11eb-95ee-80572c087ed2.PNG)
![github-2](https://user-images.githubusercontent.com/75480718/101159890-215fa080-3654-11eb-8fcd-3dcce65d3f09.PNG)
 

as you can see width changes 136px to 137px and reverse. Because of this behavior table is fluctuating. 
#### What is the expected behavior?
Width should be fixed as it works on previous version.

#### Which version of Angular and Material, and which browser and OS does this issue affect?

Angular: 9.1.12
Material:  9.2.4
Did this work in previous versions of Angular / Material?
yes

**Comment by owilliams320** [comment]
Closing this as we will not be support td-data-table in future versions. please use the data table provide by angular material.

https://material.angular.io/components/table/overview
