### ISSUE TITLE
feat: framework agnostic components

### ISSUE THREAD

**Issue by ericis** [Teradata/covalent#1828]
#### Feature Request

Currently, it seems these components rely on Angular + Material. As a result, engineers must adopt Covalent + Material + Angular and keep them in sync over time to use a single component.

Would you consider a roadmap migration to something like [StencilJS](https://stenciljs.com/docs/faq#how-does-stencil-compare-to-traditional-frameworks) that can target native JavaScript, Angular, React, and Vue as a runtime? Then, a single Covalent component might run on all popular runtimes and only depend on some core node packages and tree shaking can always ensure minimal deployment size.

#### What is the expected behavior?

Using certain Covalent components...

- Conforms to the web component standard
- Does not require the engineer to also choose Angular + Material
- Is agnostic of specific web run-times, instead mapping to the engineer's choice (e.g. Vue, React, Angular)
- Has minimal dependencies

#### What is the motivation / use case for changing the behavior?

Coupling the choice to use Covalent with Angular + Material...

- Opens Covalent to more use cases, people and communities
- Prevents certain projects from even being able to consider using Covalent
- "Locks" a team's code into a single web framework/library runtime

#### Which version of Angular and Material, and which browser and OS does this issue affect?

All

Did this work in previous versions of Angular / Material?

Of course.

##### Other information

Great work!

**Comment by owilliams320** [comment]
Hello @ericis thank you for feature request and comments. We have been taking great consideration into where covalent as a design system for enterprise is going. With that we should have some updates in works related very closely to this feature request!

**Comment by DaSchTour** [comment]
Instead of migrating to StencilJS (which was painful to use when I tried) it might be another option to create an angular elements build for other frameworks. I actually migrated from StencilJS to Angular Elements for one project.

**Comment by ericis** [comment]
https://open-wc.org/ and https://lit.dev/ are also options

**Comment by owilliams320** [comment]
We are now publishing web components made from lit based off of MDC web components 🚀 🔥 
https://github.com/Teradata/covalent/tree/main/libs/components
