### ISSUE TITLE
[Feature] data-table to allow observable object

### ISSUE THREAD

**Issue by bzmillerboy** [Teradata/covalent#183]
#### Feature Request

I'm using AngularFire2 to pull in my data like so:
```
people : FirebaseListObservable<any[]>;
constructor(private af: AngularFire){
this.persons = af.database.list('people');
}
```

When using an *ngFor with the async pipe, this is really easy to implement.
`<md-list-item *ngFor="let person of persons | async">`

 However, I can't seem to get this to work with td-data-table. I'm not sure if this is a feature request or if there is some other way to accomplish observable data in a data-table. If so, I'd be happy to submit a PR to update the documentation and code examples.

#### What is the motivation / use case for changing the behavior?
The ability to populate a data-table with observable data so the table data is dynamic and reactive (aka plays nice with Firebase).

#### Which version of Angular and Material, and which browser and OS does this issue affect?
"angular-cli": "1.0.0-beta.19-3",
"@covalent/data-table": "0.9.1",

**Comment by mxii** [comment]
Should be the same:

```
<tr td-data-table-row *ngFor="let row of (basicData | async)">
  <td> ... you columns ... </td>
</tr>
```

**Comment by emoralesb05** [comment]
Yep, as @mxii said, you need to use the atomic parts of `data-table` to do so.

**Comment by bzmillerboy** [comment]
Yes, I was able to get that working by using the atomic parts of the data-table. That's great!

I was hoping to take advantage of properties

- [sortable]="true"
- [sortBy]="sortBy"
- [sortOrder]="sortOrder"
- (sortChange)="sort($event)"

It looks like it's possible to achieve these features by implementing them manually, I just need to learn how. Thanks!

**Comment by bzmillerboy** [comment]
What is the reason it's not possible to convert the observable to an array for the data: any[] property  to use?

```
people : FirebaseListObservable<any[]>;
public testArray: Array<any[]>;
constructor(private af: AngularFire,) {
      this.people.subscribe(
        data => {
         let mappedData: any = data.map(this.mapFunc);  
          this.testArray = mappedData;
        });
}
```

This appears to make testArray an array just as the documentation uses but whenever I use 

`<td-data-table [data]="basicData" [columns]="columns">`

it fails with a "Unexpected token u in JSON" console error.

**Comment by emoralesb05** [comment]
well, from what i see `[data]` should be `testArray` in that example.. not sure if it was a misstype.

But yeah, if the `testArray` variable is an array of object, it should be rendered correctly.

**Comment by bzmillerboy** [comment]
I was able to get this working with the following:

```javascript
people: FirebaseListObservable<any[]>;
peopleList: any[] = [];
```
```javascript
    this.people = af.database.list('/people');
    this.people.subscribe(peopleDatObj => {
      this.peopleList = peopleDatObj;
    });
```
```html
<td-data-table [data]="peopleList" >
```

This issue causing the JSON error was solved by adding `peopleList: any[] = [];`. I assume the JSON parsing didn't like having an empty undefined array and that was firing before my observable returned data.

There are still issues with observables though. Paging also fires before there is data so it shows "1-0 of 0" results even though there are rows in the table. Any thoughts on how to resolve that?

**Comment by emoralesb05** [comment]
huh, we might need to fix that for an empty array either way. For paging you need to set the total manually in the `[total]` input, since paging and search components are agnostic of the data-table component

**Comment by bzmillerboy** [comment]
I got this working and would love to contribute to the documentation. One last hiccup I'm trying to resolve. After adding paging and filter() method, I don't get any data on initial load, however after I change the number of rows to display in the pager, my data loads into the table perfectly.

Any idea how to initiate the pager and sorting after data is loaded?

```html
    <md-card tdMediaToggle="gt-xs" [mediaClasses]="['push']">
      <span class="push-left-sm">
        <span class="md-title">Data Table using Data Property</span>
      </span>
      <div layout="row" layout-align="start center" class="pad-left-sm pad-right-sm">
        <td-search-box #searchBox class="push-right-sm" placeholder="Search here" [alwaysVisible]="true" (searchDebounce)="search($event)" flex>
        </td-search-box>
      </div>
      <td-data-table           
          [data]="filteredData"
          [columns]="columns"
          [sortable]="true"
          [sortBy]="sortBy"
          [sortOrder]="sortOrder"
          (sortChange)="sort($event)">>
      </td-data-table>
      <td-paging-bar [pageSizes]="[5, 10, 15, 20]" [total]="filteredTotal" (change)="page($event)"></td-paging-bar>
    </md-card>
```

```javascript
export class UsersComponent {

  columns: ITdDataTableColumn[] = [
      { name: "favoriteFruit",  label: 'Name' },
      { name: 'email', label: 'Email' },
      { name: 'registered', label: 'Start Date', numeric: true, },
    ];

  people: FirebaseListObservable<any[]>;
  peopleList: any[] = [];

  filteredData: any[] = this.peopleList;
  filteredTotal: number = this.peopleList.length;
  searchTerm: string = '';
  fromRow: number = 1;
  currentPage: number = 1;
  pageSize: number = 5;
  sortBy: string = 'email';
  sortOrder: TdDataTableSortingOrder = TdDataTableSortingOrder.Descending;

  constructor(private af: AngularFire,
              private _titleService: Title,
              private _router: Router,
              private _dataTableService: TdDataTableService) {

    this.people = af.database.list('/');
    this.people.subscribe(peopleDatObj => {
      this.peopleList = peopleDatObj;
      });
}

  ngOnInit(): void {
    this._titleService.setTitle( 'Intensive Users' );
    this.filter();
  }

  sort(sortEvent: ITdDataTableSortChangeEvent): void {
    this.sortBy = sortEvent.name;
    this.sortOrder = sortEvent.order;
    this.filter();
  }
  search(searchTerm: string): void {
    this.searchTerm = searchTerm;
    this.filter();
  }
  page(pagingEvent: IPageChangeEvent): void {
    this.fromRow = pagingEvent.fromRow;
    this.currentPage = pagingEvent.page;
    this.pageSize = pagingEvent.pageSize;
    this.filter();
  }
  filter(): void {
    let newData: any[] = this.peopleList;
    newData = this._dataTableService.filterData(newData, this.searchTerm, true);
    this.filteredTotal = newData.length;
    newData = this._dataTableService.sortData(newData, this.sortBy, this.sortOrder);
    newData = this._dataTableService.pageData(newData, this.fromRow, this.currentPage * this.pageSize);
    this.filteredData = newData;
  }
}
```

![data-table-load](https://cloud.githubusercontent.com/assets/1130899/21116405/7461054e-c083-11e6-9bc1-345cd4a04f81.gif)

**Comment by emoralesb05** [comment]
Awesome that you got it working! :+1: 

So, the problem with the initial load is that you are doing it in the `constructor` and filtering in `ngOnInit` which dont guarantee that they will be executed in that order.

So you need to do remove the loading part from the `constructor` (since its frowned upon in `angular` either way) and do it all in the `ngOnInit` lifehook component cycle.

 Example:
```typescript
constructor(private af: AngularFire,
              private _titleService: Title,
              private _router: Router,
              private _dataTableService: TdDataTableService) {
}

  ngOnInit(): void {
    this._titleService.setTitle( 'Intensive Users' );
    this.people = af.database.list('/');
    this.people.subscribe(peopleDatObj => {
      this.peopleList = peopleDatObj;
      this.filter();
    });
  }
```

This way you are following the `angular` standard and style guide and executing `filter()` once the callback returns with the necessary data.

**Comment by bzmillerboy** [comment]
That worked great, thanks! I'm still learning JS so sorry for the newbie questions.

Is the empty array need for the observable a bug?

Think this is worthy of an update to the documentation? If so, thoughts on showing the demo with an observable string like I am from Firebase?

If not, you can mark this issue as closed. Thanks again!

**Comment by emoralesb05** [comment]
I will keep this open since that is a legit bug. The data table shouldnt break even if the [data] input is undefined nor empty. 

I will add a fix for this scenario in 0.10.

**Comment by emoralesb05** [comment]
Already added a fix for the undefined array here https://github.com/Teradata/covalent/pull/188/commits/e760d16a1f0885ada8f37177385f5876136fc181

**Comment by emoralesb05** [comment]
Closing this since the `fix` for an undefined array is already in review and will be part of 0.10.

**Comment by michaeljota** [comment]
I wonder why not to return reactive data from the sort and filter options? I think even the paginate could have benefits from using the `observable` pattern.

**Comment by emoralesb05** [comment]
Yeah, that would require some discussion. Please open a new issue regarding that specifically 😄
