### ISSUE TITLE
Covalent Warnings on Build; Please Update to Angular 12

### ISSUE THREAD

**Issue by tsg-tthrash** [Teradata/covalent#1848]
After updating our project to Angular 12, which depends on Covalent, we are getting a lot of warnings on builds due to Covalent SASS code that has been deprecated and will be removed in a future update of SASS.

It would be greatly appreciated if Covalent could have it's dependencies updated, especially Angular to v12, and code properly migrated in the near future.

Thank you

![covalent build errors](https://user-images.githubusercontent.com/74976907/125480468-e75ef7b3-990c-45df-ab77-fb6947062d4a.jpg)

**Comment by owilliams320** [comment]
Hi @tsg-tthrash thank you for you comments. Currently we are only supporting 11.x for Angular on our latest release 3.x versions but do absolutely have updates in future versions for covalent to be compatible with angular 12.x
