### ISSUE TITLE
Angular Universal Awareness

### ISSUE THREAD

**Issue by John0x** [Teradata/covalent#185]
Hello, is this library being developed with Angular Universal in mind, using the abstraction layers instead of accessing the dom directly?

**Comment by emoralesb05** [comment]
Yes, we always try to access DOM in an NG2 way.. like the `Renderer` class, etc etc.

The only 2 components that dont follow it correctly are the `highlight` component and `markup` component since they use 3rd party JS libraries.

**Comment by John0x** [comment]
@emoralesb05 alright, great, thank you :)
