### ISSUE TITLE
Bug - Boolean default value in dynamic select component doesn't appear if false

### ISSUE THREAD

**Issue by BigSchteve** [Teradata/covalent#1876]
Bug:
In the project my team has been working on we have found an edge case when using the dynamic element select component. We wanted to create a custom component for boolean values rather than using the built-in "TdDynamicType" of boolean, we elected to use the "TdDynamicElement" Select. By using select we wanted to have two selections which would have the values true and false presented as "Yes" and "No" to the user. We saw that if the value of the element defaulted to true the selection "Yes" was selected for the user. If it was defaulted to false then nothing was shown. After a brief look at the code the below seems to be the culprit,

https://github.com/Teradata/covalent/blob/f983e55a99b32e0e97d94b028d9b7bfcf4207db0/src/platform/dynamic-forms/dynamic-elements/dynamic-select/dynamic-select.component.html#L11

Our selection object is as follows,
```
element.selections = []
element.selections.push({
  label: 'Yes',
  value: true
} as any)
element.selections.push({
  label: 'No',
  value: false
} as any)
...
...
element.default = false
```
As you can see if false is chosen the value will not be shown. 

It would be nice if you could use boolean values in the select component.

**Comment by owilliams320** [comment]
Hello @BigSchteve thanks for submitting a bug for covalent. Could you provide the version of dynamic forms your working with? Also any stackblitz or live code sample to show the edge case would be great.

**Comment by BigSchteve** [comment]
Hey @owilliams320 , thank you for the prompt response. The version we are working with is 3.1.1. I have pinned this version and all of the other applicable package versions in the stackblitz below,
https://stackblitz.com/edit/angular-ivy-hhq4oy?file=src/app/app.component.ts

In the stackblitz you can see putting a boolean true into the dynamicElement as a default value will put a the default value true into the dropdown box. But by putting false it will not display any value by default.

**Comment by owilliams320** [comment]
ok i see the issue. Looks like you have a good grasp of what the fix might be. We currently under some heavy development to support the latest angular so there might be some delay in getting this fixed. PRs are welcome!
