### ISSUE TITLE
Interceptors

### ISSUE THREAD

**Issue by emoralesb05** [Teradata/covalent#19]
#### Feature Request

Custom HTTP wrapper to intercept requests/responses.

#### What is the expected behavior?

Angular2 does not have a way to provide this. So we need to build it from scratch wrapping the ng2 `Http` service.

#### What is the motivation / use case for changing the behavior?

Need to be able to use interceptors for HTTP requests. (JWT, error control, redirection, headers, etc etc)

**Comment by aciccarello** [comment]
Lots of comments but this is related: **Http interceptors and transformers** angular/angular#2684

**Comment by emoralesb05** [comment]
Closes since it was added in #25
