### ISSUE TITLE
Support node 7.2.1

### ISSUE THREAD

**Issue by John0x** [Teradata/covalent#193]
#### Feature Request
Please add support for Node 7.2.1

Trying to install @covalent/core results in:
````bash
error @covalent/core@0.9.1: The engine "node" is incompatible with this module. Expected version ">4.4 < 7".
````

I have Node 7.2.1 installed.

**Comment by John0x** [comment]
This seems to be a problem with yarn :/

**Comment by richavyas** [comment]
We are supporting what ng2 supports: https://github.com/angular/angular/blob/master/package.json#L11
We don't know if there might be issues going beyond 7 with ng2.

**Comment by John0x** [comment]
@richavyas sorry for the confusion. It seems that Yarn is the problem. It works just fine with NPM

**Comment by richavyas** [comment]
No worries 👍

**Comment by tan9** [comment]
```
yarn install --ignore-engines
```
did the trick.

Related discussion can be found here: https://github.com/yarnpkg/yarn/issues/2208

**Comment by ReneVallecillo** [comment]
It is node just a yarn issue, please reopen.

https://github.com/JakeSidSmith/react-fastclick/issues/45
