### ISSUE TITLE
text-editor not working with angular 12

### ISSUE THREAD

**Issue by ouassimBenMosbah** [Teradata/covalent#1940]
**Describe the bug**
I try to instantiate a rich markdown text editor using `@covalent/text-editor` but I am not able to do it using angular 12, @covalent/text-editor 4.1.8 and easymde 2.16.1

**To Reproduce**
Here is a reproduction: https://codesandbox.io/s/unruffled-davinci-h76k51?file=/src/app/app.component.html

**Expected behavior**
I would like the rich markdown editor to instantiate

**Additional context**
Using angular 8 and @covalent/text-editor 2.1.0 was working fine

**Comment by owilliams320** [comment]
@ouassimBenMosbah thanks for the raising this issue. We have a PR out and are looking into getting this published

**Comment by ouassimBenMosbah** [comment]
> tada This issue has been resolved in version 4.1.11 tada
> 
> The release is available on:
> 
> * `v4.1.11`
> * [GitHub release](https://github.com/Teradata/covalent/releases/tag/v4.1.11)
> 
> Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot packagerocket

Hello and thank you for your quick answer. Actually I am still experimenting the issue :( Can you confirm that the release should have fixed the issue ?

**Comment by owilliams320** [comment]
@ouassimBenMosbah you must include the easymde file in the scripts portion of your angular.json file

     ` "scripts": ["node_modules/easymde/dist/easymde.min.js"],`
