### ISSUE TITLE
Integration issue. Error encountered resolving symbol values statically

### ISSUE THREAD

**Issue by kuncevic** [Teradata/covalent#195]
#### Bug Report

I just added the https://teradata.github.io/covalent/#/components/expansion-panel component to my project. I just got eactly same behaviour as I had in this case https://github.com/angular/flex-layout/issues/38 `ng serve` getting stuck on 20%, `ng build` giving error:

```
c:\Project>ng build
 10% building modules 2/2 modules 0 activeError encountered resolving symbol val
ues statically. Function calls are not supported. Consider replacing the functio
n or lambda with a reference to an exported function, resolving symbol AppModule
 in c:/Project/src/app/app.module.ts, resolving symbol AppM
odule in c:/Project/src/app/app.module.ts
Error: Error encountered resolving symbol values statically. Function calls are
not supported. Consider replacing the function or lambda with a reference to an
exported function, resolving symbol AppModule in c:/Project
/src/app/app.module.ts, resolving symbol AppModule in c:/Project/src/app/app.module.ts
    at simplifyInContext (c:\Project\node_modules\@angular\
compiler-cli\src\static_reflector.js:475:23)
    at StaticReflector.simplify (c:\Project\node_modules\@a
ngular\compiler-cli\src\static_reflector.js:478:22)
    at StaticReflector.annotations (c:\Project\node_modules
\@angular\compiler-cli\src\static_reflector.js:60:36)
    at AotPlugin.getNgModuleMetadata (c:\Project\node_modul
es\@ngtools\webpack\src\plugin.js:330:41)
    at AotPlugin._processNgModule (c:\Project\node_modules\
@ngtools\webpack\src\plugin.js:271:42)
    at c:\Project\node_modules\@ngtools\webpack\src\plugin.
js:242:39
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

 steps to reproduce:
1) `ng new project`
2) `npm install @covalent/core --save`
3) `import { CovalentCoreModule } from '@covalent/core';` and `CovalentCoreModule.forRoot()`
4) `ng serve` getting stuck on 20%, `ng build` giving error above

My `ng -v`: **angular-cli: 1.0.0-beta.22-1**

**Comment by emoralesb05** [comment]
Hey man,

We still havent done anything for AoT support, so this error is expected. 

We will add AoT support soon though. So any info regarding that will be super helpful.

**Comment by asaph26** [comment]
@kuncevic In angular-cli v1.0.0-beta.22-1, the default mode in ng serve is through aot. There are a couple of other issues as well in that version. For now, the recommended solution if you do not want to tinker with the code is to downgrade to angular-cli v1.0.0-beta.21.

**Comment by emoralesb05** [comment]
This was because the `http` module was not AoT friendly. 

https://github.com/Teradata/covalent/pull/202 should fix this
