### ISSUE TITLE
User Profile Component -

### ISSUE THREAD

**Issue by owilliams320** [Teradata/covalent#1954]
**Describe the bug**
Text is cutoff in user profile component when values are too large.

**To Reproduce**
1. Go to [localhost:4200](localhost:4200/#/components/user-profile/overview)
2. Add a really long email or name to the user profile component demo
3. Click on 'Open profile'
4. See text is cut off an not visible

**Expected behavior**
When user hovers over the cutoff email or name a tooltip should appear with entire cutoff text

**Screenshots**
<img width="299" alt="Screen Shot 2022-07-21 at 10 08 49 AM" src="https://user-images.githubusercontent.com/3837706/180234314-361bcf42-ccee-4139-8f72-48554d4859ff.png">

**Comment by wahmd** [comment]
@owilliams320 I'd like to contribute. Is it available to work on?

**Comment by owilliams320** [comment]
Hello @wahmd. yes this is available to work on! go for it.

**Comment by wahmd** [comment]
@owilliams320 created PR. please review.
https://github.com/Teradata/covalent/pull/2007
