### ISSUE TITLE
Unable to find many features like covalent/core/loading, covalent/core/media, covalent/core/steps 

### ISSUE THREAD

**Issue by manasa-rangaraj** [Teradata/covalent#1958]
While trying to upgrade my project from Angular 7 to 12 which used covalent/core, I came across an issue which occured when I upgraded the covalent/core version from 2.1.1(which doesn't support Angular 12) to version 4.0.0 (which supports Angular 12), I found that many features that were present in version 2.1.1 were missing in version 4.0.0. The module like loading, media, steps and many other modules have been removed from the covalent/core versions above 2. Is there a way to access the above mentioned features in Angular 12?

**Comment by owilliams320** [comment]
hello @manasa-rangaraj the components you mentioned have been deprecated in since the last major version. You can find the details here. https://github.com/Teradata/covalent/pull/1872
