### ISSUE TITLE
Remove Material icon Font

### ISSUE THREAD

**Issue by John0x** [Teradata/covalent#196]
I believe it would be better to remove the Material Icon font from the platform.css and do it like Material 2 (include ``<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">`` in the html).

Trying to use Covalent with an existing webpack build system is not that nice because the font cannot be loaded properly.

**Comment by kyleledbetter** [comment]
hmmm, one of the main reasons we built Covalent was to make using Angular-Material easier to use with everything an app needs out of the box...like not having to include the font separately...

I think your point is valid but instead we need to focus on better manual inclusion docs so you can easily cherrypick covalent modules

**Comment by emoralesb05** [comment]
If you are using `webpack` without the `angular-cli` then you need to configure it to load the fonts.

https://shellmonger.com/2016/01/22/working-with-fonts-with-webpack/

Basically add a `loader` for them
