### ISSUE TITLE
Really solid work all :)

### ISSUE THREAD

**Issue by d3viant0ne** [Teradata/covalent#198]
I'm not going to lie when @romelgomez suggested this repo in another thread as an alternative to Material2, I rolled my eyes. "Yet another set of limited components, partially implemented because that's what we need right now ... ". 

I officially stand corrected. Clean component implementations ( little quirks aside ), sensible component API, solid browser compatibility and by far the most complete UI / Util library for Angular 2.x to date. Well done.

> feel free to close after reading

**Comment by kyleledbetter** [comment]
thx so much @d3viant0ne! We absolutely love and need this type of positive feedback to keep everyone working so hard on Covalent.

**Comment by emoralesb05** [comment]
@d3viant0ne Thank you for the support! We are trying to do our best every day. :smile:

**Comment by kyleledbetter** [comment]
gonna close, but print this and put it in a frame in the office or something :)
