### ISSUE TITLE
IE11 layout wonkiness

### ISSUE THREAD

**Issue by djglxxii** [Teradata/covalent#199]
This repository's issues are reserved for feature requests and bug reports.

### Do you want to request a *feature* or report a *bug*?

BUG

#### Feature Request

please first make sure your request falls under the official Material Design spec guidelines https://material.google.com/

#### Bug Report

Simply navigate to the Covalent UI home page https://teradata.github.io/covalent/#/ .  Text overlays on top of other text and other general weirdness.

#### Which version of Angular and Material, and which browser and OS does this issue affect?

Internet Explorer 11.

Did this work in previous versions of Angular / Material?

Material 2 rendering appears to be fine.

Please also test with the latest stable and snapshot versions.

##### Other information
(e.g. detailed explanation, stacktraces, related issues, suggestions how to fix)

**Comment by emoralesb05** [comment]
Thanks @djglxxii. We really havent done much testing with IE, but we are gonna start doing that soon.

So expect all that fixed when we do :smile: (we need to support IE and Edge for our internal products too)

**Comment by kyleledbetter** [comment]
@djglxxii just curious have you tested Edge? I ran it on Virtualbox and things looked pretty good

**Comment by emoralesb05** [comment]
Closing this issue since we have limited support for IE11 due to us heavily depending on `flex box` which `IE11` doesnt support 100%.

https://github.com/Teradata/covalent#browser-support

**Comment by djglxxii** [comment]
@emoralesb05 Is the limited support due to Covalent or Material 2?

**Comment by emoralesb05** [comment]
Due to `flex-layout` https://github.com/angular/flex-layout#browser-support
