### ISSUE TITLE
Data Table Component

### ISSUE THREAD

**Issue by kyleledbetter** [Teradata/covalent#2]
Possibly get inspiration or pull in 

https://justindujardin.github.io/ng2-material/#/components/data-table

or

https://github.com/swimlane/angular2-data-table

**Comment by facilpralembrar** [comment]
Hi guys. I'd like to know whether better either wait for colavent's initial version of datatable (december is my deadline) or use the early options. Do they work together?

**Comment by emoralesb05** [comment]
Hey @facilpralembrar 
We have an initial version of it ready to go, but its going to be redesigned soon to allow more flexibility. 

That being said, we might still upstream it so people can start using it and get feedback but it would come with some `breaking changes` for a second iteration.

Usage:
`<td-data-table [data]="data"></td-data-table>`

Component in use:
![image](https://cloud.githubusercontent.com/assets/5846742/18720430/a5669cb4-7fe0-11e6-899b-7b8fa90cd9e4.png)

**Comment by emoralesb05** [comment]
Closed with https://github.com/Teradata/covalent/pull/92
