### ISSUE TITLE
CovalentStepsModule absent from release 4

### ISSUE THREAD

**Issue by Arnaud73** [Teradata/covalent#2000]
**Describe the bug**
Module CovalentStepsModule seems to have vanished from release 4.

I recently updated an old app on Angular 15 and as I was fixing errors related to updates, I could not find the latest equivalent of the CovalentStepsModule.
It is still mentioned in some documentation in the repository, but the code seems to have been removed.

Can you confirm the component has been ditched from releases 4.x? If yes, may it reappear sometime in the future?

**Comment by owilliams320** [comment]
Yes the recommend equivilent would be to use [Material Stepper](https://material.angular.io/components/stepper/overview)
