### ISSUE TITLE
covalent/core/media equivalent

### ISSUE THREAD

**Issue by redElephants** [Teradata/covalent#2003]
Hello, based on this PR, it seems many libraries have been deprecated. 

https://github.com/Teradata/covalent/pull/1872

What is the equivalent to covalent/core/media though? It seems it was not deprecated outright, but is no longer present in v4. Thanks.

**Comment by owilliams320** [comment]
The recommended equivilent would be to use [BreakpointObserver](https://material.angular.io/cdk/layout/overview)
