### ISSUE TITLE
Compatibility with Ionic 7 - QUESTION

### ISSUE THREAD

**Issue by serkaneken** [Teradata/covalent#2019]
Hi, We are wondering about your covalent dynamic forms( https://teradata.github.io/covalent/v5/#/components/dynamic-forms/overview ) Is compatibility with the latest version of Ionic 7? Or is there someone who used it before? 

Thanks in advance for suggestion and guidance :)

**Comment by owilliams320** [comment]
Hello @serkaneken thanks for your question. We do not specifically test with IONIC so there is no way of us knowing if that will work or not. We are only dependent on Angular and Angular Material....See our readme to know the exact version of angular we support for each version.
