### ISSUE TITLE
Feature: Support Nightly releases

### ISSUE THREAD

**Issue by asaph26** [Teradata/covalent#206]
Is it possible to support Nightly releases similar to how material2 has started doing through Github? 

Do you see any pros/cons to this approach?

**Comment by emoralesb05** [comment]
Problem with this is that material2 is still beta and still introduces breaking changes.. so we have to set a fixed version to have some control over that at the moment.

Maybe we can do this later when its stable.

**Comment by asaph26** [comment]
My thought was to have a fixed material version, but rather get the fixes/features merged with master available from covalent.

**Comment by emoralesb05** [comment]
Ah i see, :+1:  
Once 0.10 is release, we can revisit this.
Its a good idea so we can test the releases better before publishing.

**Comment by emoralesb05** [comment]
This was implemented with https://github.com/Teradata/covalent/pull/308. Still requires some check up to see if it all works fine with travis, but our initial attempt worked.
