### ISSUE TITLE
[Bug]? Using TdChips and TdFileUpload together causes wrong keyup.enter events to be fired

### ISSUE THREAD

**Issue by asaph26** [Teradata/covalent#210]
Currently using TdChips and TdFileUpload in the same page causes some interesting behaviour

**Chips:**
To select a chip when using autocomplete, the enter key is needed to select a chip and also to remove chips. the code is in the following places
https://github.com/Teradata/covalent/blob/develop/src/platform/core/chips/autocomplete/autocomplete.component.html#L15
https://github.com/Teradata/covalent/blob/develop/src/platform/core/chips/chips.component.html#L7

**File Upload**
The file upload Component also uses the enter key to initiate the file selection process. The code is present here
https://github.com/Teradata/covalent/blob/develop/src/platform/core/file/file-upload.component.html#L7

When using AutoComplete, if the overlay with options is not in focus when the enter key is pressed, it triggers the file browse. The browsers Auto-complete overlay is also present causing it to occur rather frequently

**Possible Solution Suggestions**
* [TdFileUpload] Provide the keyboard binding in file upload as an optional feature
* [TdChips] Allow selection of options from Autocomplete overlay by selecting on items. This is also present as a separate issue in #96.

**Comment by emoralesb05** [comment]
I think this happens because its used inside a form, so when you press `enter` anywhere, it wants to send an event to the first focusable button in the form. (HTML5 form submit native functionality)

The fix would be to add `type="button"` in those buttons, so the form doesnt assume they are `type="submit"`

Gonna test it.

**Comment by kyleledbetter** [comment]
fixed in https://github.com/Teradata/covalent/pull/216
