### ISSUE TITLE
Paging bar cobbles up together in Mobile

### ISSUE THREAD

**Issue by asaph26** [Teradata/covalent#214]
When the paging bar is viewed in mobile, the buttons all become cobbled up together as shown below
![screen shot 2016-12-28 at 22 23 37](https://cloud.githubusercontent.com/assets/7847386/21532004/8787a0c6-cd4c-11e6-98be-2708a762ae98.png)

**Solution Suggestion**
Have a dual row setup on xs screens instead of the single row flexbox setup. The screen breaks like that on screen sizes less than 500px in width

**Comment by kyleledbetter** [comment]
thx for reporting @asaph26 we can add some hide-xs on certain things (like "per page" and "of 6" etc)

until then you can use `firstLast="false"` to hide those 2 buttons

**Comment by asaph26** [comment]
According to this, https://github.com/Teradata/covalent/pull/217 , since an md-select is used, would it make sense to actually have the Rows per page like a material label on top, or does that destroy the appearance of the paging bar?

**Comment by emoralesb05** [comment]
Well, there is no definite MD spec for a paging bar.. we just went with what the `data-table` spec had.

https://material.io/guidelines/components/data-tables.html#data-tables-specs

This can be up for discussion.

**Comment by asaph26** [comment]
Appearance wise, it is actually better the way it is. Having a label on top destroys the appearance a bit.

**Comment by asaph26** [comment]
Just FYI, using `firstLast="false"` does not help much, as the spacing gets a bit weird, but on slightly bigger screens looks better.

With First and Last buttons
![screen shot 2016-12-30 at 20 26 28](https://cloud.githubusercontent.com/assets/7847386/21571309/4c9b9534-cece-11e6-9e11-ef7f484e038b.png)

Without First and Last buttons
![screen shot 2016-12-30 at 20 26 22](https://cloud.githubusercontent.com/assets/7847386/21571310/4c9e592c-cece-11e6-9a59-c3fc0529c066.png)
