### ISSUE TITLE
Unable to use chips with autocomplete on Mobile

### ISSUE THREAD

**Issue by asaph26** [Teradata/covalent#215]
When using chips with autocomplete on mobile, the overlay screen does not pop up in all cases.

Test status:
Chrome, Android : Works
Chrome, iOS: No overlay shown
Safari, iOS: No overlay shown

According to caniuse.com this is because datalist is not supported by Safari. (http://caniuse.com/#search=datalist)

![screen shot 2016-12-28 at 22 48 40](https://cloud.githubusercontent.com/assets/7847386/21532399/011917a0-cd50-11e6-90f4-71c23bfc645f.png)

**Comment by emoralesb05** [comment]
Hopefully this wont be an issue once `md-autocomplete` is created in material2.

**Comment by asaph26** [comment]
Yes. An alternative would be to use an overlay like a select instead of the native component.

You can close this issue unless you want to leave it open for the sake of tracking

**Comment by emoralesb05** [comment]
Yep, gonna keep it open until we fix or replace it. :+1:

**Comment by emoralesb05** [comment]
Same issue as https://github.com/Teradata/covalent/issues/165
