### ISSUE TITLE
Support for Angular v15.2.10

### ISSUE THREAD

**Issue by Yuvchenko-Kostiantyn** [Teradata/covalent#2195]
I am currently updating a big project from Angular v14 to Angular v15. We have @covalent/core as one of the dependencies, and use the dialog component in a number of places. 

Latest stable version of Angular 15 is 15.2.10. Latest minor version of @covalent/core that supports Angular 15 is 6.3.0, which has three peer dependencies set to strict version that break the compatibility: @angular/animations, @angular/platform-browser, @angular/platform-browser-dynamic, all of them being set to version 15.2.5, which creates dependency conflicts when trying to use it with the latest Angular 15 release. All the other angular related peer dependencies are set to 15.2.5 and above, so they don't throw any errors.

The ideal solution I would like to see is a new release of @covalent/core@6.x.x, which is fully compatible with the latest Angular 15 patches. I am willing to participate in the process by doing the update myself and creating a PR, but I don't have much experience with dependencies in libraries, so I might need some help with that.

The only alternative for us is completely removing @covalent/core as a dependency and replacing it with something else, as some of the other libraries we use only work with Angular 15.2.10.

**Comment by bsahitya** [comment]
@Yuvchenko-Kostiantyn Support for Angular v15.2.10 is now available in covalent version [6.4.2](https://www.npmjs.com/package/@covalent/core/v/6.4.2?activeTab=readme)
