### ISSUE TITLE
Type 'Timer' is not assignable to type 'number'

### ISSUE THREAD

**Issue by quanterion** [Teradata/covalent#225]
First of all thank you for your hard work on this project. And special appreciation for 0.10 release with AM Beta.1 and AOT!

I'm trying to identify strange problem with 0.10 release. Even simple new ng-cli project after installing covalent fails in ng serve command. It looks like typescript use definition of setTimeout from Node.Js typings which is installed by angular-cli. Replacing setTimeout with window.setTimeout in src/platform/core/common/animations folder fixes the problem

ng-cli logs:

ERROR in ./~/@covalent/core/common/animations/toggle/toggle.directive.ts
Module build failed: Error: /home/rem/fm/WebPlanner2/node_modules/@covalent/core/common/animations/toggle/toggle.directive.ts (95,5): Type 'Timer' is not assignable to type 'number'.)
/home/rem/fm/WebPlanner2/node_modules/@covalent/core/common/animations/toggle/toggle.directive.ts (156,7): Type 'Timer' is not assignable to type 'number'.)
    at _checkDiagnostics (/home/rem/fm/WebPlanner2/node_modules/@ngtools/webpack/src/loader.js:116:15)
    at /home/rem/fm/WebPlanner2/node_modules/@ngtools/webpack/src/loader.js:141:17
 @ ./~/@covalent/core/common/common.module.ts 13:0-73
 @ ./~/@covalent/core/index.ts
 @ ./src/app/app.module.ts
 @ ./src/app/index.ts
 @ ./src/main.ts
 @ multi main

ERROR in ./~/@covalent/core/common/animations/fade/fade.directive.ts
Module build failed: Error: /home/rem/fm/WebPlanner2/node_modules/@covalent/core/common/animations/fade/fade.directive.ts (104,5): Type 'Timer' is not assignable to type 'number'.)
/home/rem/fm/WebPlanner2/node_modules/@covalent/core/common/animations/fade/fade.directive.ts (141,5): Type 'Timer' is not assignable to type 'number'.)
    at _checkDiagnostics (/home/rem/fm/WebPlanner2/node_modules/@ngtools/webpack/src/loader.js:116:15)
    at /home/rem/fm/WebPlanner2/node_modules/@ngtools/webpack/src/loader.js:141:17
 @ ./~/@covalent/core/common/common.module.ts 14:0-67
 @ ./~/@covalent/core/index.ts
 @ ./src/app/app.module.ts
 @ ./src/app/index.ts
 @ ./src/main.ts
 @ multi main

**Comment by emoralesb05** [comment]
Ive seen that before, its the `tdconfig.json` configuration but you are right, its taking the `NodeJS` definition of them.. 

As a work around for now, can you try mimicking the same `tsconfig.json` file we have?

https://github.com/Teradata/covalent/blob/develop/src/tsconfig.json

**Comment by emoralesb05** [comment]
Fixed in patch 0.10.1
