### ISSUE TITLE
Placeholder text can not appear for search bar when expanded

### ISSUE THREAD

**Issue by bazhip** [Teradata/covalent#226]
This repository's issues are reserved for feature requests and bug reports.

### Do you want to request a *feature* or report a *bug*?
bug
#### Feature Request

please first make sure your request falls under the official Material Design spec guidelines https://material.google.com/

#### Bug Report

please provide steps to reproduce and if possible screenhots or animated Gifs.
you can easily create animated Gif with this free PC/OSX App: http://www.cockos.com/licecap/

##### Screenshots or link to CodePen/Plunker/JSfiddle
![searchbar](https://cloud.githubusercontent.com/assets/10350445/21564981/ca0ef1cc-ce57-11e6-8432-d905bb4bcf82.gif)

#### What is the expected behavior?
I'd think the placeholder text should appear when the search is expanded so that they know what the field is for. I ended up adding a block of text to the side for the time being until I play with it more.

#### What is the motivation / use case for changing the behavior?
^
#### Which version of Angular and Material, and which browser and OS does this issue affect?
I'm on the latest build (with 2.4.1) and using chrome

Did this work in previous versions of Angular / Material?
Please also test with the latest stable and snapshot versions.
Haven't checked the others

##### Other information
(e.g. detailed explanation, stacktraces, related issues, suggestions how to fix)
[https://github.com/Teradata/covalent-quickstart/issues/25](url)

**Comment by richavyas** [comment]
Thanks for reporting this @bazhip. we'll look into it.

**Comment by emoralesb05** [comment]
To continue what was discussed in https://github.com/Teradata/covalent-quickstart/issues/25.

This works as intended, but it would be nice to make the placeholder `hiding` function when focuses optional.

Gonna mark this as an `enhancement` for a future release.

**Comment by bazhip** [comment]
That's fair. The only reason I threw it as a bug was the fact that the animations were conflicting with each other, but the end result was what was desired at planning.

Thanks guys!

**Comment by kyleledbetter** [comment]
Since we autofocus the label/placeholder shouldn't be there. The only way something like `search` should technically be there is if it was the default value, but that would be weird bc you'd have to backspace to remove the text...

So this is working as intended as @emoralesb05 said.

> The only reason I threw it as a bug was the fact that the animations were conflicting with each other

what did you mean by `animations where conflicting` @bazhip ?

**Comment by emoralesb05** [comment]
Once `material` releases `beta.2`, it will give us the flexibility to do this.
