### ISSUE TITLE
npm install issue

### ISSUE THREAD

**Issue by harshaldhake** [Teradata/covalent#229]
I am getting warning as below when i do the npm install. Please advise

npm WARN @ngtools/webpack@1.2.1 requires a peer of @angular/compiler@^2.3.1 but none was installed.
npm WARN @ngtools/webpack@1.2.1 requires a peer of @angular/compiler-cli@^2.3.1 but none was installed.
npm WARN @ngtools/webpack@1.2.1 requires a peer of @angular/core@^2.3.1 but none was installed.
npm WARN @ngtools/webpack@1.2.1 requires a peer of @angular/tsc-wrapped@^0.5.0 but none was installed

**Comment by emoralesb05** [comment]
you can ignore `npm` WARN's for the most part, since npm installs stuff at a different order sometimes.

Even though it tells you `@angular/compiler@^2.3.1 is required and there is none`, most of the time it is there, just installed after `@ngtools/webpack@1.2.1`

**Comment by harshaldhake** [comment]
Thanks . I got no error while doing ng serve.
