### ISSUE TITLE
Rendering issue with td-layout-manage-list content

### ISSUE THREAD

**Issue by ZandorZ** [Teradata/covalent#231]
I'm trying to nest a td-layout-manage-list based component in a child route but it doesnt render correctly (the component doesnt show up).
Then if i select td-layout-manage-list on dev inspect tool
then on [_nghost-oxe-60] style,  unmark position:relative , everything works fine.

**Comment by ZandorZ** [comment]
on app.component.scss i added :
td-layout-manage-list{
position:absolute
}

it also works

**Comment by emoralesb05** [comment]
We couldnt replicate it, but we are removing the `position: relative` from it so it should be fixed for `beta.1`
