### ISSUE TITLE
File to import not found or unreadable in _input.scss imports

### ISSUE THREAD

**Issue by akalitenya** [Teradata/covalent#232]
### Do you want to request a *feature* or report a *bug*?
bug

#### Bug Report

i am using this starter:
https://github.com/qdouble/angular-webpack2-starter/tree/no-universal-support

after run "start" command i got error:

"File to import not found or unreadable: ../../../../node_modules/@angular/material/core/theming/palette.\n
Parent style sheet: ...app/node_modules/@covalent/core/common/styles/_input.scss",

#### Which version of Angular and Material, and which browser and OS does this issue affect?
@angular/material@2.0.0-beta.1
@covalent/core@0.10.1
@angular 2.4.1

##### Other information

i think imports in this file "covalent/src/platform/core/common/styles/_input.scss" should have extra level of folder nesting, like this:
../../../../../node_modules/@angular/material/core/theming/palette
^

**Comment by emoralesb05** [comment]
Hmm, can you provide more information? We dont get that error in any of our products, and people have been upgrading to 0.10 without that error.. 

Also, you can try using our pre-compiled `platform.css` file instead of the `platform.scss` if thats an issue.

**Comment by akalitenya** [comment]
Need some time to figure out scss processing in starter repo.
Thank you, closing issue for now.

**Comment by emoralesb05** [comment]
You can also try adding the `platform.css` via `index.html` file.

**Comment by corwinm** [comment]
I am trying to upgrade from v0.9.1 to v1.0.0-beta.2-1 and I am experiencing this issue as well.

**Comment by emoralesb05** [comment]
Are you using the `platform.css` or `platform.css`?

**Comment by corwinm** [comment]
We are using platform.scss. 
Our import statement looks like:
```
@import '~@covalent/core/common/platform';
```
And we are building with webpack 1.14.0

**Comment by thekalinga** [comment]
I have the same issue when using with angular-cli.

I am using `styles/main.scss` instead of `styles.scss` as a starting point in angular cli.

So my styles section under `.angular-cli.json` looks like this

```json
"styles": [
    "styles/main.scss"
]
```

Now if I import `platform` using `@import` within `styles/main.scss`, I am getting the exact same error.

I believe this issue is to do with the relative paths `../../`
