### ISSUE TITLE
Typo for interceptors

### ISSUE THREAD

**Issue by hanego** [Teradata/covalent#233]
Hello,

In the file, http.module.ts, I found a typo line 21
` static forRoot(config: HttpConfig = {inteceptors: []}): ModuleWithProviders {`

I guess it should be **interceptors** not **inteceptors**.

**Comment by emoralesb05** [comment]
Oh snap! Thanks for the heads up.

We were so swamped over the holidays that we didnt notice this haha.

**Comment by emoralesb05** [comment]
Hotfix released with 0.10.2.
