### ISSUE TITLE
Build failed with type error.

### ISSUE THREAD

**Issue by ajmal-shah** [Teradata/covalent#236]
#### Bug Report

ERROR in [at-loader] node_modules\@covalent\core\file\directives\file-drop.directive.ts:84:43 
    Argument of type 'string[]' is not assignable to parameter of type 'DOMStringList'.
  Property 'contains' is missing in type 'string[]'.

#### Which version of Angular and Material, and which browser and OS does this issue affect?
@covalent/core : 0.10.2
typescript version 2.1.4
webpack version 1.14.0

Did this work in previous versions of Angular / Material?
*Covalent/core worked with previous versions.
*CovalentFileModule was an independent module till covalent 0.9.0 (@covalent/file-upload) . *@covalent/core : 0.10.2 build fails with the error.

**Comment by emoralesb05** [comment]
How do you have your `tsconfig.json` configured?

**Comment by ajmal-shah** [comment]
Here is the tsconfig file content.

> {
>   "compilerOptions": {
>     "target": "es5",   
>     "module": "commonjs",
>     "moduleResolution": "node",
>     "sourceMap": true,
>     "emitDecoratorMetadata": true,
>     "experimentalDecorators": true,
>     "removeComments": false,
>     "noImplicitAny": true,
>     "baseUrl": "./src",
>     "suppressImplicitAnyIndexErrors": true,
>     "exclude": [
>       "node_modules",
>       "dist"
>     ],
>     "awesomeTypescriptLoaderOptions": {
>       "forkChecker": true,
>       "useWebpackText": true
>     }
>   }
> }
>

**Comment by kyleledbetter** [comment]
i might be out of my depth but this is what we have in covalent-quickstart

```
{
  "compileOnSave": false,
  "compilerOptions": {
    "declaration": false,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "mapRoot": "./",
    "lib": ["es6", "dom"],
    "module": "es6",
    "moduleResolution": "node",
    "outDir": "../dist/out-tsc",
    "sourceMap": true,
    "target": "es5",
    "typeRoots": [
      "../node_modules/@types"
    ],
    "types": [
      "jasmine", "hammerjs"
    ]
  }
}
```

**Comment by emoralesb05** [comment]
Yeah, please try using the same config as us. Most of the angular/angular@material repos use that same config for `lib`.
```
"lib": ["es6", "dom"],
```
e.g.
https://github.com/jelbourn/material2-app/blob/master/src/tsconfig.json

**Comment by emoralesb05** [comment]
Ok, manage to replicate it.. its a problem when upgrading to `typescript@2.1.4`.

We are still on `2.0.10` because there were known issues. We will start testing on 2.1.4 asap, but for now i would just go back to `2.0.10`
