### ISSUE TITLE
Errors in @covalent/core/common/animations/toggle/toggle.directive.ts

### ISSUE THREAD

**Issue by alvachien** [Teradata/covalent#238]
This repository's issues are reserved for feature requests and bug reports.

### Do you want to request a *feature* or report a *bug*?
Bug.

#### Bug Report

Using Teradata/covalent-quickstart, and adding the animation in Router described in Angular Official documents: https://angular.io/docs/ts/latest/guide/router.html#!#route-animation

**Step 1**. Add codes like following:
import { animate, AnimationEntryMetadata, state, style, transition, trigger } from '@angular/core';

// Component transition animations
export const slideInDownAnimation: AnimationEntryMetadata =
  trigger('routeAnimation', [
    state('*',
      style({
        opacity: 1,
        transform: 'translateX(0)'
      })
    ),
    transition(':enter', [
      style({
        opacity: 0,
        transform: 'translateX(-100%)'
      }),
      animate('0.2s ease-in')
    ]),
    transition(':leave', [
      animate('0.5s ease-out', style({
        opacity: 0,
        transform: 'translateY(100%)'
      }))
    ])
  ]);

**Step 2**. Run "ng Serve".

ERROR in Error encountered resolving symbol values statically. Function calls are not supported. Consider replacing the function or lambda with a reference to an exported function (position 39
:19 in the original .ts file), resolving symbol AppModule in C:/Users/{WinUser}/Documents/git/{prjname}/src/app/app.module.ts

ERROR in ./~/@covalent/core/common/animations/toggle/toggle.directive.ts

Module build failed: Error: C:/Users/{WinUser}/Documents/git/{prjname}/node_modules/@covalent/core/common/animations/toggle/toggle.directive.ts (95,5): Type 'Timer' is not assignable to type 'numb
er'.)
C:/Users/{WinUser}/Documents/git/{prjname}/node_modules/@covalent/core/common/animations/toggle/toggle.directive.ts (156,7): Type 'Timer' is not assignable to type 'number'.)
    
at _checkDiagnostics (C:\Users\{WinUser}\Documents\git\{prjname}\node_modules\@ngtools\webpack\src\loader.js:116:15)
    
at C:\Users\{WinUser}\Documents\git\{prjname}\node_modules\@ngtools\webpack\src\loader.js:141:17
    
at process._tickCallback (internal/process/next_tick.js:103:7)
 
@ ./~/@covalent/core/common/common.module.ts 13:0-73
 
@ ./~/@covalent/core/index.ts
 
@ ./src/app/app.component.ts
 
@ ./src/app/index.ts
 
@ ./src/main.ts
 
@ multi main

ERROR in ./~/@covalent/core/common/animations/fade/fade.directive.ts

Module build failed: Error: C:/Users/{WinUser}/Documents/git/{prjname}/node_modules/@covalent/core/common/animations/fade/fade.directive.ts (104,5): Type 'Timer' is not assignable to type 'number'
.)
C:/Users/{WinUser}/Documents/git/{prjname}/node_modules/@covalent/core/common/animations/fade/fade.directive.ts (141,5): Type 'Timer' is not assignable to type 'number'.)
    
at _checkDiagnostics (C:\Users\{WinUser}\Documents\git\{prjname}\node_modules\@ngtools\webpack\src\loader.js:116:15)
    
at C:\Users\{WinUser}\Documents\git\{prjname}\node_modules\@ngtools\webpack\src\loader.js:141:17
    
at process._tickCallback (internal/process/next_tick.js:103:7)
 
@ ./~/@covalent/core/common/common.module.ts 14:0-67
 
@ ./~/@covalent/core/index.ts
 
@ ./src/app/app.component.ts
 
@ ./src/app/index.ts
 
@ ./src/main.ts
 
@ multi main

**Comment by emoralesb05** [comment]
Are you using `0.10.2`? 

We fixed this issue in `0.10.1`
https://github.com/Teradata/covalent/blob/develop/docs/CHANGELOG.md#0101-2017-1-2

**Comment by alvachien** [comment]
Yes, I am using 0.10.2. I just clone from the quick-start repo.




At 2017-01-06 00:39:05, "Ed Morales" <notifications@github.com> wrote:


Are you using 0.10.2?

We fixed this issue in 0.10.1
https://github.com/Teradata/covalent/blob/develop/docs/CHANGELOG.md#0101-2017-1-2

**Comment by emoralesb05** [comment]
Quickstart repo is in 0.10.0.

**Comment by alvachien** [comment]
@emoralesb05 You are right that the Quickstart using 0.10.0.

Thank you.
