### ISSUE TITLE
ng server failed after covalent upgrade

### ISSUE THREAD

**Issue by harshaldhake** [Teradata/covalent#242]
Could you please help . Getting error while upgrading covalent

ERROR in multi styles
Module not found: Error: Can't resolve '/Users/harshal/node_modules/@covalent/core/styles/platform.css' in '/Users/harshal/node_modules/angular-cli/models'
 @ multi styles

ERROR in ./~/css-loader!./~/postcss-loader!./~/sass-loader!./src/theme.scss
Module build failed: 
@import '~@covalent/core/styles/theming/all-theme';
^
      File to import not found or unreadable: ~@covalent/core/styles/theming/all-theme
Parent style sheet: stdin
      in /Users/harshal/src/theme.scss (line 2, column 1)
 @ ./src/theme.scss 4:14-158
 @ multi styles

ERROR in ./~/css-loader!./~/postcss-loader!./~/sass-loader!./src/styles.scss
Module build failed: 
@import '~@covalent/core/styles/theming/all-theme';
^
      File to import not found or unreadable: ~@covalent/core/styles/theming/all-theme
Parent style sheet: /Users/harshal/src/theme.scss
      in /Users/harshal/src/theme.scss (line 2, column 1)
 @ ./src/styles.scss 4:14-159
 @ multi styles

ERROR in [default] /Users/harshal/node_modules/@covalent/core/data-table/data-table.component.ts:228:8 
Argument of type 'TemplateRef<any>' is not assignable to parameter of type 'TemplateRef<any>'.
  Types of property 'createEmbeddedView' are incompatible.
    Type '(context: any) => EmbeddedViewRef<any>' is not assignable to type '(context: any) => EmbeddedViewRef<any>'.
      Type 'EmbeddedViewRef<any>' is not assignable to type 'EmbeddedViewRef<any>'.
        Property 'markForCheck' is missing in type 'EmbeddedViewRef<any>'.

ERROR in [default] /Users/harshal/node_modules/@covalent/core/data-table/directives/data-table-template.directive.ts:9:23 
Argument of type 'ViewContainerRef' is not assignable to parameter of type 'ViewContainerRef'.
  Types of property 'createComponent' are incompatible.
    Type '<C>(componentFactory: ComponentFactory<C>, index?: number, injector?: Injector, projectableNodes?...' is not assignable to type '<C>(componentFactory: ComponentFactory<C>, index?: number, injector?: Injector, projectableNodes?...'.
      Types of parameters 'componentFactory' and 'componentFactory' are incompatible.
        Type 'ComponentFactory<any>' is not assignable to type 'ComponentFactory<any>'.
          Types have separate declarations of a private property '_viewClass'.

ERROR in [default] /Users/harshal/node_modules/@covalent/core/dialogs/services/dialog.service.ts:76:58 
Argument of type 'IAlertConfig' is not assignable to parameter of type 'MdDialogConfig'.
  Types of property 'viewContainerRef' are incompatible.
    Type 'ViewContainerRef' is not assignable to type 'ViewContainerRef'.

ERROR in [default] /Users/harshal/node_modules/@covalent/core/dialogs/services/dialog.service.ts:102:58 
Argument of type 'IConfirmConfig' is not assignable to parameter of type 'MdDialogConfig'.
  Types of property 'viewContainerRef' are incompatible.
    Type 'ViewContainerRef' is not assignable to type 'ViewContainerRef'.

ERROR in [default] /Users/harshal/node_modules/@covalent/core/dialogs/services/dialog.service.ts:132:58 
Argument of type 'IPromptConfig' is not assignable to parameter of type 'MdDialogConfig'.
  Types of property 'viewContainerRef' are incompatible.
    Type 'ViewContainerRef' is not assignable to type 'ViewContainerRef'.

=========================
"@angular/common": "2.2.1",
        "@angular/compiler": "2.2.1",
        "@angular/core": "2.2.1",
        "@angular/forms": "2.2.1",
        "@angular/http": "2.2.1",
        "@angular/material": "2.0.0-beta.1",
        "@angular/platform-browser": "2.2.1",
        "@angular/platform-browser-dynamic": "2.2.1",
        "@angular/platform-server": "2.2.1",
        "@angular/router": "3.2.1",
        "@covalent/charts": "0.9.1",
        "@covalent/chips": "0.9.1",
        "@covalent/core": "^0.10.2",
        "@covalent/data-table": "0.9.1",
        "@covalent/file-upload": "0.9.1",
        "@covalent/highlight": "0.9.1",
        "@covalent/http": "0.9.1",
        "@covalent/json-formatter": "0.9.1",
        "@covalent/markdown": "0.9.1",
        "@covalent/paging": "0.9.1",
        "@covalent/search": "0.9.1",
        "ts-helpers": "1.1.1"

**Comment by richavyas** [comment]
Hi @harshaldhake, I see that the `package.json` you included still has old dependencies `2.2.1`. Latest covalent is on `2.4.1`. Refer this: https://github.com/Teradata/covalent/blob/develop/package.json
Please run `rm -rf node_modules dist deploy tmp` and re-install.

**Comment by harshaldhake** [comment]
Thank you issue resolved for me 👍  appreciate for help
