### ISSUE TITLE
JSON Formatter appends new object instead of show new object only.

### ISSUE THREAD

**Issue by ajitsonlion** [Teradata/covalent#247]
This repository's issues are reserved for feature requests and bug reports.

#### Bug Report

Use json formattor which receives input, and the input changes,

like
 ```
<td-json-formatter [data]="selectedOperation$|async" [levelsOpen]="1">
    </td-json-formatter>
```
any value into the observable results in the json formatter appending the value instead of showing the  new value.

##### Screenshots or link to CodePen/Plunker/JSfiddle

![covalentjson](https://cloud.githubusercontent.com/assets/7666593/21904984/07cce862-d906-11e6-9a04-fb725b61547a.gif)

#### What is the expected behavior?

the td-json-formatter should not append all the values it received into one object to format.

#### What is the motivation / use case for changing the behavior?

To load dynamically json and show it formatter

#### Which version of Angular and Material, and which browser and OS does this issue affect?

Angular 2.4.2, material beta 1, 
Browser: Chrome Version 55.0.2883.87 m (64-bit)
OS : Windows 10

Did this work in previous versions of Angular / Material?
Did not try.

**Comment by emoralesb05** [comment]
Thanks for the bug report @ajitsonlion !

We will work on this for our betas :tada:

**Comment by ajitsonlion** [comment]
![image](https://cloud.githubusercontent.com/assets/7666593/21935717/d3bccd86-d9ae-11e6-9b44-9374e9a1d1f4.png)
thanks for amazing project :) hope could also learn angular enough to do code contributions :D

**Comment by emoralesb05** [comment]
Thanks! :tada: 
We welcome any sorts of contributions. 
Be it `code` contributions, `doc` update or even just by posting a `bug` or a possible `enhancement` helps us a lot to be honest.
