### ISSUE TITLE
color="primary" is hard coded in td-loading component

### ISSUE THREAD

**Issue by tapas4java** [Teradata/covalent#255]
# Feature Request
Currently `color="primary"` is hard coded in `td-loading` component. We should make it dynamic so that developers can easily change progress-bar color to `accent` or `warn`.  By default, we can make it primary.

#### What is the expected behavior?
`color` property should be configurable

#### What is the motivation / use case for changing the behavior?
I want to show the progress-bar color as `accent` instead of `primary`

**Comment by emoralesb05** [comment]
The `loading` module will be getting some work done over the next few weeks. 

So this is for sure a good enhancement for it. 👍

**Comment by tapas4java** [comment]
Thanks @emoralesb05, Looking forward to this.
