### ISSUE TITLE
How about adding a component like p-messages available in primeng

### ISSUE THREAD

**Issue by tapas4java** [Teradata/covalent#256]
#### Feature Request

Every application must have some requirement to show some messages(info, error, etc) to ther user. What about adding a component like [p-messages](http://www.primefaces.org/primeng/#/messages) available in `primeng` library??

#### What is the motivation / use case for changing the behavior?
Should be able to show messages to user like `Logged out successfully`, `account created sucssfully` etc.

**Comment by emoralesb05** [comment]
So this is more for inline messages, correct?

**Comment by kyleledbetter** [comment]
Hmmm this is interesting bc the messages from Prime are more like Bootstrap CSS alerts and less like Material Design.

In material you show warnings & messages in toasts, and errors i dialogs (usually) like we outline here https://teradata.github.io/covalent/#/style-guide/dialogs

That being said we've come across the need for messages in Covalent:
![image](https://cloud.githubusercontent.com/assets/867883/21967106/3fecbfd2-db46-11e6-9291-382dd833498e.png)

and in Teradata products:
![image](https://cloud.githubusercontent.com/assets/867883/21967113/630ecb22-db46-11e6-8a59-8bc5683452b9.png)

I could see doing a messages component like this and allowing inputs for color & icon, and having action buttons

**Comment by emoralesb05** [comment]
Whoops, forgot to close this since we already merged the message component
