### ISSUE TITLE
Smart TdLoadingService intended for delayed API calls

### ISSUE THREAD

**Issue by davidgabrichidze** [Teradata/covalent#257]
#### Feature Request
Smart TdLoadingService intended for delayed API calls

#### What is the expected behavior?
don't shows progress-bar immediately, but waits for configured period of time and if 'resolve' is not called, after displays progress-bar.

#### What is the motivation / use case for changing the behavior?
If Api call taks longer, than it was expected, progress-bar is shown - there is no need, in most use cases, to show loading immediately (which causes shimming effect if using overlay)

**Comment by emoralesb05** [comment]
Hmm, guess we can configure a delay or something. Gotta think about this a little bit.

**Comment by emoralesb05** [comment]
Closing since this can be done by either `timeouts` and also there would be scenarios where this would still happen even with a delay
