### ISSUE TITLE
Steps :: Add linear (wizard like) steps mode

### ISSUE THREAD

**Issue by ilianiv** [Teradata/covalent#258]
#### Feature Request

It would be nice if you add [linear stepper](https://material.io/guidelines/components/steppers.html#steppers-types-of-steppers) mode that require users to complete one step in order to move on to the next.

##### Screenshots or link to CodePen/Plunker/JSfiddle
![image](https://cloud.githubusercontent.com/assets/3925630/21978473/700020f4-dbe3-11e6-90b8-295aa1d97d76.png)

#### What is the expected behavior?
Linear steppers require users to complete one step in order to move on to the next.

**Comment by emoralesb05** [comment]
You can actually do this by playing around with the `[disabled]` and `[state]` inputs. 

We did it intentional since a user might have all fields required `(full linear)` or maybe just a few.

A good idea might be to add an example of how you would achieve that in the `demo`.

**Comment by kyleledbetter** [comment]
Also @ilianiv not sure if @emoralesb05 was clear, we have the linear stepper mode today, just use `<td-steps mode="vertical">`

**Comment by ianqueue** [comment]
fwiw... i've implemented this and does seem like an implementation detail, not really something to be provided by the covalent UI component ( i could be wrong ).  Create a step.service and decide when the model bound to each step should change state whether its through dynamic form validation or some other method.

**Comment by jennmedellin** [comment]
@ilianiv, we have a horizontal stepper demo at https://teradata.github.io/covalent/#/components/steps.  Would it be helpful to have a demo where each step is required w/validation?

**Comment by jeremysmartt** [comment]
Need to add an example in docs of how you achieve this
