### ISSUE TITLE
Feature: Complete Teradata Covalent NPM packages

### ISSUE THREAD

**Issue by mbellezi** [Teradata/covalent#26]
Greetings,

Very nice work!
As we are using a custom webpack build, we will use the covalent NPM packages.
At this time, there is the core and 3 other custom elements. Do you plan to maintain this NPM packages and add the missing Teradata components?

Regards

**Comment by mbellezi** [comment]
Oops, the other components are inside the core package. :)

**Comment by kyleledbetter** [comment]
@mbellezi yes, sorry for the confusion, we include lots of components and things we consider "core" to all apps, and have individual NPM registries for the extras that not every app would need

**Comment by emoralesb05** [comment]
We are technically in our alpha stage, so we might move things a little as we progress and maybe separate some things from the core package but nothing too extreme.

**Comment by kyleledbetter** [comment]
closing this one, we'll consider moving things out the core into standalone NPM packages if the demand is high enough, trying to keep it simple for now
