### ISSUE TITLE
Feature Request: Dynamic breakpoint in layouts

### ISSUE THREAD

**Issue by gotrecillo** [Teradata/covalent#265]
#### Feature

It would be nice to be able to set the breakpoint in manage-list and nav-list layouts. Right now it is hardcored at 600px. Being able to choose to break at 960px breakpoint would be nice in some applications allowing the user to have more workspace

**Comment by kyleledbetter** [comment]
Agree, we've been talking about this also. We can probably refactor a bit and tie into our media query service so we'd have all those breakpoints https://teradata.github.io/covalent/#/components/media
