### ISSUE TITLE
Feature Request: DataTable dense attribute

### ISSUE THREAD

**Issue by rafizan-baharum** [Teradata/covalent#266]
**Feature Request**

It would be nice to have a "dense" layout for data table similar to md-list. With denser layout, it allows the UI  to display more information.

**Comment by kyleledbetter** [comment]
agree, marked for Beta 2

**Comment by parker-mike** [comment]
Any news on this one?

**Comment by owilliams320** [comment]
this component is deprecated please use https://material.angular.io/components/table
