### ISSUE TITLE
 Bug(?): ng serve on develop (commit 1c4f00a7d...) firefox 50.1.0 

### ISSUE THREAD

**Issue by lincze** [Teradata/covalent#268]
#### Feature Request

please first make sure your request falls under the official Material Design spec guidelines https://material.google.com/

#### Bug Report

{{{
$ ng --version
... banner ...
angular-cli: 1.0.0-beta.25.5
node: 6.9.4
os: linux x64
@angular/common: 2.4.4
@angular/compiler: 2.4.4
@angular/core: 2.4.4
@angular/forms: 2.4.4
@angular/http: 2.4.4
@angular/material: 2.0.0-beta.1
@angular/platform-browser: 2.4.4
@angular/platform-browser-dynamic: 2.4.4
@angular/platform-server: 2.4.4
@angular/router: 3.4.4
@angular/compiler-cli: 2.4.4
$ tsc --version
Version 2.0.10
}}}

ng serve proceeds OK, but after hitting localhost:4200, the startup gives this popup:

"A script on this page may be busy, or it may have stopped responding. You can stop the script now, open the script in the debugger, or let the script continue.

Script: http://localhost:4200/vendor.bundle.js:22462"

after hittting coninue, the application loads.

i can't see anything related on the web console, though, have a copule of loglines:

- Error in parsing value for ‘-webkit-box-ordinal-group’.  Declaration dropped. (more times)
- Error in parsing value for ‘display’.  Declaration dropped. (more times)
- Unknown pseudo-class or pseudo-element ‘-webkit-search-decoration’.  Ruleset ignored due to bad selector. (more times)
- Unknown property ‘user-select’.  Declaration dropped. (more times)

**Comment by emoralesb05** [comment]
We cant really replicate this.. tried with different OS and using same version of Firefox..

**Comment by lincze** [comment]
if it counts: i'm using fedora 24 (w/ latest patches), and can reproduce this behavior on both of my machines (same os, an amd processor acer laptop and an i3 processor hp pc).

![screenshot at 2017-01-20 01-36-44](https://cloud.githubusercontent.com/assets/4760711/22131217/f178e9d8-deb1-11e6-9497-0a2754523316.png)

i experined this same (also on both of my machines with covalent quickstart v0.10.0), this is that screenshot:

![screenshot at 2017-01-20 01-51-16](https://cloud.githubusercontent.com/assets/4760711/22131340/068567b0-deb3-11e6-9360-ef66aba90f54.png)

and never saw this with "ng serve --aot"

**Comment by kyleledbetter** [comment]
There were a couple of hotfixes for 0.10 and we quickly released 0.10.2 can you try that? I dont think it'll fix it but worth a shot 

When you update you'll need to fix the interceptors misspelling in app.modules.ts

**Comment by lincze** [comment]
covalent quickstart:

i came to angular2 and material from java background and am pretty short of knowledge. so, can not be reaaly helpful tracking down the errors. I've upped, the angular dependencies and the covalent dependencies wtih the '^' operator in package.json

```
chunk    {4} inline.bundle.js, inline.bundle.map (inline) 0 bytes [entry] [rendered]
ERROR in ./src/app/app.module.ts
Module build failed: Error: /home/incze/ws/learn/angular/covalent-quickstart/src/app/app.module.ts (67,7): Argument of type '{ inteceptors: { interceptor: typeof RequestInterceptor; paths: string[]; }[]; }' is not assignable to parameter of type 'HttpConfig'.
  Object literal may only specify known properties, and 'inteceptors' does not exist in type 'HttpConfig'.)
    at _checkDiagnostics (/home/incze/ws/learn/angular/covalent-quickstart/node_modules/@ngtools/webpack/src/loader.js:116:15)
    at /home/incze/ws/learn/angular/covalent-quickstart/node_modules/@ngtools/webpack/src/loader.js:141:17
 @ ./src/app/index.ts 2:0-41
 @ ./src/main.ts
 @ multi main
```
'inteceptors' should probably be 'interceptors', and in fact, replacing it in app.module.ts, the application starts ok, without the busy script alarm.

I've got the busy alarm regularly always with the version 0.10.0 (but not before). also, with 0.10.0 if quickstart the alerts panel on the dashboard sometimes remained stuck in the loader animation. now, with the bumped version it's ok, too. all these with firefox, with chrome never experienced these things.

don't know, this was good news, or bad.

this happened to covalent quickstart (and npm update, after):
[cqs.txt](https://github.com/Teradata/covalent/files/720305/cqs.txt)

**Comment by emoralesb05** [comment]
So, just so you know. We are in `0.10.2` but the quickstart wasnt updated to that yet, which fixed the `inteceptors` typo and among other things (that might have caused the issue in firefox).

https://github.com/Teradata/covalent/blob/develop/docs/CHANGELOG.md#0101-2017-1-2
https://github.com/Teradata/covalent/blob/develop/docs/CHANGELOG.md#0102-2017-1-3

**Comment by emoralesb05** [comment]
Closing since we didnt hear any thing else about this. Feel free to re-open if this is still an issue.
