### ISSUE TITLE
Templates and Styles not inlined in NPM packages

### ISSUE THREAD

**Issue by mbellezi** [Teradata/covalent#27]
Greetings,

I'm trying to use the Covalent components within my app using the NPM packages but I'm having a problem. The component's code is already transpiled to Javascript but the styles and templates were not converted to a inline version inside the Javascript file. As a result, when I use the components, the loader does not find the styles and templates.
The Angular Material 2 NPM packages algo have the transpiled versions, but the templates and styles are inlined.
I'm using webpack to bundle and did not found a work around this problem. Do you have any thoughts about how this can be solved, or could you provide the inlined versions in a future release?

Regards

**Comment by emoralesb05** [comment]
Hey @mbellezi 
Right now we arent in-lining the `css`/`html` into the `js` file since we are waiting for `typescript 2.0.0` which will allow `html`/`css` file imports.. also we are kinda hoping CLI will handle this allowing a more official solution.

We dont want to do a custom solution (search and replace with code) in the building process like angular2-material since it will only be temporary.

But if it takes too long for an official solution to come and people need it, we might have to revisit this.

**Comment by mbellezi** [comment]
Ok. Until a solution is not available, I will manually import the platform/core folder from the Covalent github project as it is in Typescript. The NPM can't be used without a preprocessing step.
One other thing I found strange is the use in the styleUrls referencing the css files instead of the scss files.  As the CLI docs states you could reference the scss for the sass processor to work. In my case, in webpack, I have to write a preprocessor step to rename the .css includes to .sass in the Covalent folder.

**Comment by kyleledbetter** [comment]
@mbellezi 
> found strange is the use in the styleUrls referencing the css

It's the standard I've seen to reference compiled CSS in styleUrls, and we try to follow the official material2 repo as closely as possible like: https://github.com/angular/material2/blob/master/src/components/button/button.ts#L29

on the topic SCSS however, I've opened an issue to ship the SCSS and CSS in case you'd want to pull in the source SCSS files in your app https://github.com/Teradata/covalent/issues/28

**Comment by emoralesb05** [comment]
html and styles inlined in https://github.com/Teradata/covalent/pull/78
