### ISSUE TITLE
No way for HttpInterceptors to retry request when ResponseError

### ISSUE THREAD

**Issue by mlardeur** [Teradata/covalent#270]
I'm using a RestAPI with authentication and JWT token mechanism. The HttpInterceptor Interface is perfect for adding Headers with OnResquest method but now I'm trying to add the capability to refresh token when I receive an 401 error from the API and retry the request in case of success. 

The problem is that I've no access to the request when using onResponseError from the HttpInterceptor Interface.

```javascript
onResponseError(response: Response): Response {
    switch (response.status) {
      case 401:
        // User not authenticated
        this.loggingService.refreshToken()
          .then(() => {
            // TODO retry request
            console.log('Need to retry request:' + response.url);
          })
```

I'm missing something or it's not possible with the current implementation?
Precision: I've no way to know when the token has expired from the client side.

**Comment by emoralesb05** [comment]
Sorry for the late response

There si really no way to do so after the response returns `fail` through interceptors.

Also, this approach is not really the best way to handle this, you should refresh the token `before` it expires, not `when` it expires. So i would advice you to revise how you are generating the token.

There are ways to get the token expiration at the time you get it or decoding it from the actual token using `jwt` libs.

We are currently working on implementing this in our current internal products, so you have to take into consideration implicit `refresh` before it expires and maybe even `revoking` after client inactivity (even before it expires). 

Depends on what type of app you are trying to do.. most websites like `github` and `facebook` just generate a token with a ridiculous `expiration` date so it never expires unless explicitly logged out. OR you can leverage the `cookie` expiration to help out with the implementation..

Honestly, there are so many ways to do this.. its up for debate.

**Comment by mlardeur** [comment]
Thanks for the answer. 
I will definitely try another approach than HttpInterceptors
