### ISSUE TITLE
[Enhancement] Mixed Covalent Media Queries

### ISSUE THREAD

**Issue by kyleledbetter** [Teradata/covalent#271]
Scenario: i need a certain css class on xs & sm only, and gt-sm i want a different class.

Currently you can only match one single breakpoint and add one class. Let's add support for multiple like `tdMediaQuery.xs`, `tdMediaQuery.sm` and `tdMediaQuery.gt-sm`

**Comment by emoralesb05** [comment]
I think we can leverage `flex-layout` for this instead of building our own. Since they already implemented it.
