### ISSUE TITLE
[Feature Request] Select/Multi-Select

### ISSUE THREAD

**Issue by mikehutter** [Teradata/covalent#272]
Just ran across your suite of components, looks very promising!  Nice work!

I'd love to see a select with mutli-select capabilities.  It would basically be a hybrid of the angular-material select and the angular-material checkbox list demos on your page.  It would be even better with search/filter capabilities!  ;)

**Comment by christian-laakmann** [comment]
@mikehutter
See https://github.com/angular/material2/pull/2722

**Comment by emoralesb05** [comment]
Yes, this is coming from `material` soon as a feature for `md-select`. 😄

**Comment by kyleledbetter** [comment]
closing since this is coming and we strive not to duplicate material2 features coming
