### ISSUE TITLE
[Com: layout and steps] Argument of type 'Subscription' is not assignable to parameter of type 'Subscription.

### ISSUE THREAD

**Issue by jeffrysteven** [Teradata/covalent#273]
I'm working with [angular seed](https://github.com/mgechev/angular2-seed) and I installed covalent@covalent/core@0.10.2 with the system.js configuration.

When I ran the application, the application starts but shows the next 3 ts errors:

`[16:59:36] Starting 'build.js.dev'...
C:/Users/xxxx/ngWorkspace/project/node_modules/@covalent/core/layout/layout.component.ts(86,29): error TS2345: Argument of type 'Subscription' is not assignable to parameter of type 'Subscription'.
  Property '_subscriptions' is missing in type 'Subscription'.
C:/Users/xxxx/ngWorkspace/project/node_modules/@covalent/core/search/search-input/search-input.component.ts(83,8): error TS2339: Property 'debounceTime' does not exist on type 'Observable<any>'.
C:/Users/xxxx/ngWorkspace/project/node_modules/@covalent/core/steps/steps.component.ts(132,11): error TS2322: Type 'Subscription' is not assignable to type 'Subscription'.
[16:59:43] TypeScript: 3 semantic errors
[16:59:43] TypeScript: emit succeeded (with errors)`

I need to compile the application but these errors are blocking the process.

I need help, thanks in advance.

**Comment by emoralesb05** [comment]
Looks like you are missing the `import 'rxjs/Rx';` pollyfills. or maybe using a diff version of `rxjs`?

**Comment by kyleledbetter** [comment]
i think i saw this issue and it was fixed by removing and installing the node modules:
`rm -rf node_modules`
and
`npm i`

**Comment by jeffrysteven** [comment]
Thank you very much @emoralesb05 and @kyleledbetter, the problem was the version of rxjs, I installed the latest version 5.0.3 and everything is ok now.
