### ISSUE TITLE
Third Line Toolbar with Tabs

### ISSUE THREAD

**Issue by AldrichMascarenhas** [Teradata/covalent#279]
Allow for <md-tab> in Multi Row Toolbar
Attached image shows behaviour but there is a padding at the bottom. [Top is expected, Bottom is current result]

(https://cloud.githubusercontent.com/assets/11980185/22184645/1b184e54-e0fc-11e6-9b50-753f56fd653b.png)
`<md-toolbar class="top-toolbar">

      <md-toolbar-row></md-toolbar-row>

      <div class="toolbar-header-text-container">
        <div class="md-display-1 tc-grey-50">Menu management</div>
        <div class="md-subhead tc-grey-50">Bacon ipsum dolor amet salami jerky sirloin, picanha short ribs pork chop leberkas pig shankles</div>

      </div>
      <md-toolbar-row >
        <md-tab-group [selectedIndex]="0">
          <md-tab>
            <template md-tab-label class="md-title tc-grey-50">Menu management</template>

          </md-tab>
          <md-tab>
            <template md-tab-label class="md-title tc-grey-50">Menu management</template>

          </md-tab>
          <md-tab>
            <template md-tab-label class="md-title tc-grey-50">Menu management</template>

          </md-tab>

        </md-tab-group>
      </md-toolbar-row>
    </md-toolbar>`

**Comment by emoralesb05** [comment]
So this is not `covalent`, this is more of a `material` issue, since they have a set height of 64px (desktop) on `md-toolbar-row` and then they try to center the content which results in that.

https://github.com/angular/material2/blob/master/src/lib/toolbar/toolbar.scss#L16

You would need to override the css specifically for that `md-toolbar-row`

```
     <md-toolbar-row class="custom-class">
        <md-tab-group>
          <md-tab>
            <template md-tab-label class="md-title tc-grey-50">Menu management</template>
          </md-tab>
          <md-tab>
            <template md-tab-label class="md-title tc-grey-50">Menu management</template>
          </md-tab>
          <md-tab>
            <template md-tab-label class="md-title tc-grey-50">Menu management</template>
          </md-tab>
        </md-tab-group>
      </md-toolbar-row>
```
 with either 

```
.custom-class {
    align-items: flex-end; // So content goes to the bottom
}
```

OR if you dont care about the height:

```
.custom-class {
    height: auto;
}
```

Thoughts @kyleledbetter ??

**Comment by AldrichMascarenhas** [comment]
Oh that explains. Fixed the issue by overriding the css
@emoralesb05 Thank you !
Closing issue.

**Comment by kyleledbetter** [comment]
I did something similar in our new landing page template in the quickstart https://teradata.github.io/covalent-quickstart/#/templates

![image](https://cloud.githubusercontent.com/assets/867883/22184895/9d2514a6-e0a0-11e6-9a3f-50388b2f7818.png)

just using Covalent utility classes for padding & margins:
```
  <md-toolbar color="primary" class="pad-none pull-top">
    <nav md-tab-nav-bar class="pull-bottom">
```

https://github.com/Teradata/covalent-quickstart/blob/develop/src/app/templates/templates.component.html#L45

You could play around with that as a starting point

**Comment by emoralesb05** [comment]
Closing since it was a css override issue.
