### ISSUE TITLE
Ship Uncompiled SCSS

### ISSUE THREAD

**Issue by kyleledbetter** [Teradata/covalent#28]
Along w/ the compiled CSS we need to ship the source SCSS for the platform and each component so apps can import them into their local SCSS

Ship all the uncompiled SCSS in:

-  [x] core/styles
-  [x] core/expansion-panel
-  [x] core/layout
-  [x] core/loading
-  [x] core/steps
-  [x] file-upload
-  [x] highlight
-  [x] markdown

**Comment by emoralesb05** [comment]
https://github.com/Teradata/covalent/pull/41 will make sure any `.scss` files inside `/src` (and outside `src/app/`) will be moved to `deploy/` for packaging/
