### ISSUE TITLE
data-table  not showing horizontal scroll when used inside stepper

### ISSUE THREAD

**Issue by cissecedric** [Teradata/covalent#282]
### Do you want to request a *feature* or report a *bug*?
bug

#### Bug Report
When included inside the stepper, the data-table doesn't show the horizontal scroll
Please see the included picture dataTable_KO_InsideStepper.png
![datatable_ko_insidestepper](https://cloud.githubusercontent.com/assets/12851286/22209444/c63d07a4-e186-11e6-9906-d43d03a13009.png)

#### What is the expected behavior?
When included inside the stepper, the data-table should show the horizontal scroll
Please see the included picture dataTable_OK_OutsideStepper.png
![datatable_ok_outsidestepper](https://cloud.githubusercontent.com/assets/12851286/22209338/701efb3e-e186-11e6-8570-bc09a94a2fa3.png)

#### What is the motivation / use case for changing the behavior?
Using data table inside a stepper

#### Which version of Angular and Material, and which browser and OS does this issue affect?
Tested today, current version in the git repo  "version": "0.10.2"

Did this work in previous versions of Angular / Material?
I don't know

Thank you for your help,

**Comment by emoralesb05** [comment]
Thanks for the bug report! We will look into this.
