### ISSUE TITLE
Enhancement: Ability to customise label for TdFileUploadComponent

### ISSUE THREAD

**Issue by asaph26** [Teradata/covalent#286]
Currently the label for the TdFileUploadComponent is set to "Choose a file...". 

It would be helpful to have an input parameter called label which can be used to override the default label.

**Comment by emoralesb05** [comment]
Yep, this is def needed (also incase of i18n).

**Comment by asaph26** [comment]
One other thing that would be interesting to have is to have an event saying that file has been selected. Currently this is what happens

1) User clicks on the "Choose a File..." button. You are allowed to select a file
2) Once the file is selected, the file name becomes the label of the button.
3) User has to click on the File name button again to actually start the uploading process

It would be good to have this determined by code while sticking with the same default behaviour

My Challenges
1) When using with mobile and I allow people to capture images from their cameras, some cameras create really long filenames with a datetime stamp whick breaks layout
2) People are confused when they have to click the same button twice.

Let me know what you think

**Comment by emoralesb05** [comment]
I agree, a `selected` event would be a nice enhancement. ( There are times where ive needed this too haha)

I think a good idea would be to also create a `td-file-browser` so it can be used stand alone (acting mostly just like a glorified `<input type="file">`) AND used inside the `td-file-upload` component as an atom.

**Comment by emoralesb05** [comment]
Im gonna create a separate issue for the `selected` event or `stand alone` `td-file-browse`
