### ISSUE TITLE
[Feature Request] Horizontal Steppers

### ISSUE THREAD

**Issue by Daeluse** [Teradata/covalent#29]
#### What is the expected behavior?

Instead of leveraging the behavior of Material Lists, leveraging or extending the behavior of Material Tabs will provide a Horizontal Stepper which displays progress stacked on top of current step content in a column fashion rather than a row. Switching between steps would have some sort of 'swiping' animation and would emit the same events currently emitted by the vertical stepper.

#### What is the motivation / use case for changing the behavior?

Horizontal Steppers provide a much better user experience for wizards because they keep content above the fold and display progress before content. They also have better reaction to Wide Screen sizes.

#### What would you like to see in addition to expected behavior?

Development would be greatly simplified if a path towards switching between horizontal and vertical on the fly could be made for when the desktop layout turns to mobile.

**Comment by gnomeontherun** [comment]
I think its a great request. We've got a few other priorities to tackle first, but I wanted to acknowledge that this will stay on our radar.

**Comment by kyleledbetter** [comment]
Yeah totally agree, good request @Daeluse thx!

**Comment by kyleledbetter** [comment]
Just so we can see w/o having to click to spec:

![image](https://cloud.githubusercontent.com/assets/867883/17301687/ed0ba9e0-57dd-11e6-8086-ee2b0ad68fd2.png)

![image](https://cloud.githubusercontent.com/assets/867883/17301692/f586f48a-57dd-11e6-80c8-3213f5458612.png)

![image](https://cloud.githubusercontent.com/assets/867883/17301696/fe9952fc-57dd-11e6-88c1-eaf9b2cf7043.png)

**Comment by kyleledbetter** [comment]
I think it would be nice to have these two attributes/settings:

1. An attribute to force horizontal always

2. An attribute to change from vertical to horizontal on responsive breakpoints (using our media query service?)

**Comment by emoralesb05** [comment]
Yes, i was kinda thinking already in my mind to just add an input property that changes the stepper from vertical to horizontal depending on a value (boolean, enum or whatever). Leveraging our `MediaService` without actually depending on it.

**Comment by emoralesb05** [comment]
Design mock for horizontal stepper:
![image](https://cloud.githubusercontent.com/assets/5846742/18611481/3a540f18-7cef-11e6-89c2-ed88d1467117.png)

Starting to work on the code design and implementation, but might have to re-think how the stepper works internally to be able to handle both `horizontal` and `vertical` modes in the same component without too much complexity and easy to maintain.

We will try and keep the same component consumption since we like it that way.

**Comment by emoralesb05** [comment]
Added with https://github.com/Teradata/covalent/pull/95. 

Its a first draft on `horizontal` vs `vertical` stepper with the new `[mode]` input in `td-steps`.
