### ISSUE TITLE
[Enhancement] Dialog when browsing away from dirty edit/add form

### ISSUE THREAD

**Issue by ccpony** [Teradata/covalent#292]
Using Angular 2.

Would be excellent if the framework would display a dialog when attempting to browse away from a a dirty edit or add form.  This would allow the user to cancel an errant route request and complete/save the entry.

Thank you for an amazing framework.

**Comment by emoralesb05** [comment]
This is actually a use case for `Guard`s and their `CanDeactivate` interface. https://angular.io/docs/ts/latest/api/router/index/CanDeactivate-interface.html

`@angular` already provides ways to handle this.

**Comment by ccpony** [comment]
I see.  Does this preclude incorporating it into the framework so that additional code is not necessary in the component.ts?  Thank you.

**Comment by emoralesb05** [comment]
Possibly, but the definition of `dirty` **heavily** depends on the component.. so i dont think there would be a `one to rule them all` solution. 

But its up for debate and we can use this issue to contribute to see if its feasible.

**Comment by emoralesb05** [comment]
The team decided to not do this since its possible to do with pure angular API's
