### ISSUE TITLE
[Enhancement] Add `yarn` as a pkg manager.

### ISSUE THREAD

**Issue by emoralesb05** [Teradata/covalent#313]
#### Feature Request

Look into https://github.com/yarnpkg/yarn and use it inside `covalent`.

**Comment by emoralesb05** [comment]
Some nice docs on usage: https://yarnpkg.com/en/docs/usage

And command comparison between `npm` and `yarn`: https://yarnpkg.com/en/docs/migrating-from-npm

**Comment by d3viant0ne** [comment]
Already using this on my fork, install is faster as you would expect. No breakage from changes in packages due to the deterministic nature of yarn.

Throw in a little guidance on how far you want this `yarn'd` i.e just the lock, lock + travis, "all the things" and i'll throw up a PR.

**Comment by emoralesb05** [comment]
Awesome! For now i think just the lock + travis would suffice. 😄
