### ISSUE TITLE
[Enhancement] Enable insertion of custom input components using dynamic forms

### ISSUE THREAD

**Issue by ianchute** [Teradata/covalent#314]
#### Feature Request
It would work like: 
```
this.elements = [{
      name: 'titleText',
      label: 'Title Text',
      type: MyCustomInputComponent,
      default: this.titleText,
}]
```

I imagine **MyCustomDialComponent** to implement some kind of interface so that the dynamic forms can access and set its values.

@emoralesb05

**Comment by asaph26** [comment]
I am not sure if this helps here as this can be solved in different ways. But this looks a bit cleaner.

http://angularjs.blogspot.se/2017/01/understanding-aot-and-dynamic-components.html

**Comment by ianchute** [comment]
Hello @asaph, I'm talking about Covalent's Dynamic Forms, not Angular2 in general.

https://teradata.github.io/covalent/#/components/dynamic-forms

**Comment by asaph26** [comment]
@ianchute : I was suggesting that as a solution to the problem :)

**Comment by emoralesb05** [comment]
Yeah, any custom element would have to follow an an interface that at least has `name`, `label` and `value` if we go down that road.

**Comment by CoreyT355** [comment]
I would love to be able to do this. I have a form in my site that uses the Quill WYSIWYG editor in a component, and I can't find a way to combine dynamic forms and this component into a single form for reuse.

**Comment by demetrio812** [comment]
Hello, is there any news about it?

I really need to integrate some custom elements in the form, is there any way I can do it?

Thanks a lot,
Dem

**Comment by emoralesb05** [comment]
Will be taken care of with #1212

**Comment by demetrio812** [comment]
@emoralesb05 thanks for that, when is it going to be released? Thanks

**Comment by emoralesb05** [comment]
We want to add a few more things before the next beta, so we are currently debating between releasing by the end of this week, or next one.
