### ISSUE TITLE
[Feature]: Messaging component

### ISSUE THREAD

**Issue by indyplanets** [Teradata/covalent#316]
### Do you want to request a *feature* or report a *bug*?
Feature

#### Feature Request

Messaging component for info, alerts, warnings, errors, and successes.

##### Screenshots or link to CodePen/Plunker/JSfiddle
Examples:
<img width="433" alt="screen shot 2017-02-02 at 11 32 19 am" src="https://cloud.githubusercontent.com/assets/104025/22560853/a775e5fe-e93b-11e6-9a4c-1110363f838c.png">
<img width="387" alt="screen shot 2017-02-02 at 11 32 11 am" src="https://cloud.githubusercontent.com/assets/104025/22560852/a772a6aa-e93b-11e6-85a5-ad3378bdd51b.png">

<img width="789" alt="screen shot 2017-02-02 at 11 34 16 am" src="https://cloud.githubusercontent.com/assets/104025/22560855/a77a1034-e93b-11e6-9611-6bbd2a94aa1d.png">
<img width="686" alt="screen shot 2017-02-02 at 11 34 36 am" src="https://cloud.githubusercontent.com/assets/104025/22560854/a7776ac8-e93b-11e6-8682-78f5c943c468.png">

#### What is the expected behavior?
Component should have the ability to implement color and icon style in the template.

#### What is the motivation / use case for changing the behavior?
Create and standardize patterns for surfacing relevant and timely information to the user.

##### Other information

Material design patterns for errors: https://material.io/guidelines/patterns/errors.html
Material design patterns for notifications: https://material.io/guidelines/patterns/notifications.html

**Comment by emoralesb05** [comment]
Referencing this https://github.com/Teradata/covalent/issues/256 since its related

**Comment by kyleledbetter** [comment]
Example from Covalent docs:
![image](https://cloud.githubusercontent.com/assets/867883/22561304/3fb7a87e-e93d-11e6-8317-7e9bb2bc62ba.png)

And Teradata products:
![image](https://cloud.githubusercontent.com/assets/867883/22561314/47f5101c-e93d-11e6-9803-933c5b41324f.png)

**Comment by kyleledbetter** [comment]
Let's iterate on the API requirements:


## API Summary

| Name | Type | Description |
| --- | --- | --- |
| messageTitle | string | Title set in toolbar (or card title).
| messageSubtitle | string | Subtitle if using card title & card subtitle.
| icon | string | icon name to be displayed before the title
| color | string | optional toolbar color.
| message | string | string content of the message body
| actionPrimary | string | url or route for primary action button in card footer
| actionSecondary | string | url or route for secondary (accent) action button in card footer

**Comment by emoralesb05** [comment]
To make it more flexibly, lets make the actions something the user can add as needed:

```
<td-message messageTitle="" messageSubtitle="" icon="" color="" message="">
  <div layout="row">
    <button md-button href (click)="" [routerLink]=""> <-- different ways of using it -->
      Primary
    </button>
  </div>
</td-message>
```

**Comment by richavyas** [comment]
An attribute showing `type` of message would be helpful too. Icons/colors may change over the time in the process of theming changes/enhancement/revamp but message types are usually restricted to `info/alerts/warnings/errors/successes. e.g.

`<td-message messageTitle="" messageSubtitle="" type="" icon="" color="" message="">`

**Comment by indyplanets** [comment]
<img width="574" alt="screen shot 2017-02-07 at 2 08 22 pm" src="https://cloud.githubusercontent.com/assets/104025/22709476/83f0846a-ed3f-11e6-92c5-c57dab8b7b8b.png">

We want the ability to have both card headers without the toolbar? What about that close/x button up there in the top right. Does it make sense to have the ability to hide the message?

**Comment by indyplanets** [comment]
Referencing ng prime messages: http://www.primefaces.org/primeng/#/messages

![ng-prime-messages](https://cloud.githubusercontent.com/assets/104025/22710686/eb73361a-ed43-11e6-85a9-e96746c0f547.gif)

**Comment by indyplanets** [comment]
Firebase messaging

![firebase-message-dismiss-example](https://cloud.githubusercontent.com/assets/104025/22710728/14255746-ed44-11e6-8430-4ecb988f57a8.gif)

**Comment by indyplanets** [comment]
We should always render a card with toolbar (icon/title/close). No card title/subtitle

<img width="552" alt="screen shot 2017-02-07 at 3 32 57 pm" src="https://cloud.githubusercontent.com/assets/104025/22712544/c05719fe-ed4a-11e6-802b-638fa3639d23.png">

## API

| Name | Type | Description |
| --- | --- | --- |
| messageTitle | string | Title set in toolbar (or card title).
| icon | string | icon name to be displayed before the title
| color | string | optional toolbar color.
| close | string | clear icon for hiding message
| message | string | string content of the message body
| actionPrimary | string | url or route for primary action button in card footer
| actionSecondary | string | url or route for secondary (accent) action button in card footer

<img width="572" alt="screen shot 2017-02-07 at 3 35 46 pm" src="https://cloud.githubusercontent.com/assets/104025/22712632/247f298a-ed4b-11e6-982c-106fccf4e485.png">

**Comment by kyleledbetter** [comment]
Super happy with the progress and UX now. Gonna dig into code review

**Comment by indyplanets** [comment]
Component property bindings

```typescript
  /**
   * messageTitle: string
   *
   * The title set in toolbar.
   */
  @Input() messageTitle: string;

  /**
   * messageSubtitle?: string
   *
   * Optional second line subhead set in toolbar.
   */
  @Input() messageSubtitle: string;

  /**
   * icon: string
   *
   * The icon name to be displayed before the title.
   * Defaults to info_outline icon
   */
  @Input() icon: string = 'info_outline';

  /**
   * color?: string
   *
   * The optional toolbar color.
   */
  @Input() color: string = 'none';

  /**
   * close: string
   *
   * The clear icon for hiding message.
   * Defaults to clear icon "x"
   */
  @Input() close: string = 'clear';

  /**
   * message?: string
   *
   * The optional string content of the message body.
   */
  @Input() message: string;

  /**
   * actionPrimary?: string
   *
   * The optional url or route for primary action button in card footer.
   */
  @Input() actionPrimary: string;

  /**
   * actionSecondary?: string
   *
   * The optional url or route for secondary (accent) action button in card footer.
   */
  @Input() actionSecondary: string;
```

**Comment by emoralesb05** [comment]
Im good with that as a starting base. 

We still need to revisit the buttons though.. since people might want to set their own buttons for other stuff rather than routing, and an `n` number of buttons with different text.

**Comment by emoralesb05** [comment]
Also, it might make more sense to be able to set the message this way too.

```html
<td-message>{{message}}</td-message>
```

As an alternative, and have a quick API (easy) to set it too.

**Comment by jotatoledo** [comment]
Funny fact is that I was about to suggest this as a feature for covalent. Currently Im using [angular2-notifications](https://github.com/flauc/angular2-notifications) in my project.  If something similar could be integrated into covalent it would be awesome.

**Comment by kyleledbetter** [comment]
@jotatoledo notifications is more like material snackbar/toast (they'll be adding more features like the one you're using) https://material.angular.io/components/component/snack-bar

This messages component was being designed for in-page alerts, more like https://v4-alpha.getbootstrap.com/components/alerts/

**Comment by asaph26** [comment]
Would love to see this soon.

**Comment by emoralesb05** [comment]
We are polishing this in one of our products and planning on adding it soon 😄

**Comment by asaph26** [comment]
@emoralesb05 Will this be part of beta.4 or will this be delayed to the next beta/rc?

**Comment by emoralesb05** [comment]
Plans are to include it in `beta.4` and release either today or tomorrow.

**Comment by emoralesb05** [comment]
This will be included with https://github.com/Teradata/covalent/pull/596 😄
