### ISSUE TITLE
compile error with angular-cli using AOT (Ahead-of-Time Compilation)

### ISSUE THREAD

**Issue by joeherold** [Teradata/covalent#319]
#### Bug Report
I just tried it with a clean installation (ng new applicationName).
Compile with --aot flag works fine.
The moment I add covalent, compiling against aot fails.

when compiling with aot commant (**ng build --aot** | **ng bulid --prod --aot**)
I get an error:
```
ERROR in ./~/@covalent/core/index.ts
Module build failed: TypeError: Cannot read property 'text' of undefined
``` 

##### Screenshots of CLI output
<img width="1366" alt="covalent_aot_error" src="https://cloud.githubusercontent.com/assets/3911545/22602564/0f3109d6-ea44-11e6-958a-f9deb6fb4a5d.png">

#### Which version of Angular and Material, and which browser and OS does this issue affect?
_This is my OS setup:_
**OS:** Apple macOS (version 10.12.1)
**node:** v6.9.1
**npm:** 3.10.9
**tsc:** Version 2.1.4
**covalent:** "@covalent/core": "^1.0.0-beta.1-1"

```json
{
  "name": "fidu-box-angular2",
  "version": "0.0.0",
  "license": "MIT",
  "angular-cli": {},
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "test": "ng test",
    "pree2e": "webdriver-manager update --standalone false --gecko false",
    "e2e": "protractor"
  },
  "private": true,
  "dependencies": {
    "@angular/common": "^2.3.1",
    "@angular/compiler": "^2.3.1",
    "@angular/core": "^2.3.1",
    "@angular/forms": "^2.3.1",
    "@angular/http": "^2.3.1",
    "@angular/platform-browser": "^2.3.1",
    "@angular/platform-browser-dynamic": "^2.3.1",
    "@angular/router": "^3.3.1",
    "@covalent/core": "^1.0.0-beta.1-1",
    "core-js": "^2.4.1",
    "rxjs": "^5.0.1",
    "ts-helpers": "^1.1.1",
    "zone.js": "^0.7.2"
  },
  "devDependencies": {
    "@angular/compiler-cli": "^2.3.1",
    "@types/jasmine": "2.5.38",
    "@types/node": "^6.0.42",
    "angular-cli": "1.0.0-beta.28.3",
    "codelyzer": "~2.0.0-beta.1",
    "jasmine-core": "2.5.2",
    "jasmine-spec-reporter": "2.5.0",
    "karma": "1.2.0",
    "karma-chrome-launcher": "^2.0.0",
    "karma-cli": "^1.0.1",
    "karma-jasmine": "^1.0.2",
    "karma-remap-istanbul": "^0.2.1",
    "protractor": "~4.0.13",
    "ts-node": "1.2.1",
    "tslint": "^4.3.0",
    "typescript": "~2.0.3"
  }
}
```

**Comment by bazhip** [comment]
Same here. Just did a full upgrade across all my packages and got his.

**Comment by emoralesb05** [comment]
So, this was fixed already and is gonna be part of next release https://github.com/Teradata/covalent/commit/e5841d6fe62a0f36bf227d9d2b72a2b9f40db5b2

There is also a work around for this here:

https://github.com/Teradata/covalent-quickstart/pull/37

**Comment by emoralesb05** [comment]
btw, we have our nightly build you can pull to test with the latest develop

https://github.com/Teradata/covalent-nightly

**Comment by emoralesb05** [comment]
We are just waiting for `material` to release their `beta.2` so we can upgrade and release also (which will include this fix)

**Comment by emoralesb05** [comment]
Closing since this will be released in `beta.2`.

**Comment by joeherold** [comment]
Great!
+1

**Comment by imVinayPandya** [comment]
@emoralesb05  i am getting same error any solution for this

`ERROR in ./~/@covalent/core/index.ts
Module build failed: TypeError: Cannot read property 'text' of undefined
    at Object.getTokenPosOfNode (/home/vinay/leaf-developer-console/node_modules/typescript/lib/typescript.js:6635:71)
    at IdentifierObject.TokenOrIdentifierObject.getStart (/home/vinay/leaf-developer-console/node_modules/typescript/lib/typescript.js:78683:23)
    at IdentifierObject.TokenOrIdentifierObject.getText (/home/vinay/leaf-developer-console/node_modules/typescript/lib/typescript.js:78704:77)
    at refactor.findAstNodes.filter (/home/vinay/leaf-developer-console/node_modules/@ngtools/webpack/src/loader.js:135:44)
    at Array.filter (native)
    at refactor.findAstNodes.forEach.node (/home/vinay/leaf-developer-console/node_modules/@ngtools/webpack/src/loader.js:134:14)
    at Array.forEach (native)
    at _removeDecorators (/home/vinay/leaf-developer-console/node_modules/@ngtools/webpack/src/loader.js:125:10)
    at Promise.resolve.then (/home/vinay/leaf-developer-console/node_modules/@ngtools/webpack/src/loader.js:295:33)
 @ ./src/$$_gendir/app/app.module.ngfactory.ts 68:0-49
 @ ./src/main.ts
 @ multi main
`

**Comment by emoralesb05** [comment]
The bug has been fixed and will be released in out `beta.2`. 

You are welcomed to try the fix by pointing to our night build https://github.com/Teradata/covalent-nightly

**Comment by imVinayPandya** [comment]
okay @emoralesb05 any ETA for beta 2? and any plan for server side rendering i have tried universal-cli and angular universal but there a different angular 2 dependencies of covalent and angular universal. so its hard to do server side rendering. getting lot of dependency warnings and errors while i was trying to do server side rendering, specially with AOT. if you can provide any stater template which contains covalent and server side rendering both with angular cli than it will be very good. noob like me can make production ready application.

Thank you in advance.

**Comment by emoralesb05** [comment]
ETA would be this following week around friday. The reason because we want to release once we properly test every change from `material@beta.2`.

Server side rendering (Angular Universal) is kind of immature at the moment. We are also looking at it and see how we can leverage it for a few of our products. So whenever we find a solution, we will add it to the quickstart 😄
