### ISSUE TITLE
[Enhancement] Test (or Add) the  `rtl` support to all modules and docs.

### ISSUE THREAD

**Issue by emoralesb05** [Teradata/covalent#323]
#### Feature Request

We need to make sure every component (and the docs) work fine in `rlt` and `ltr`.

Covalent Modules:

- [ ] Common
  - [ ] pad styles
  - [ ] pull styles
  - [ ] push styles
- [x] Chips
- [x] Data Table
- [x] Dialogs
- [x] Expansion Panel
- [x] File
- [x] Json Formatter
- [x] Layout
- [x] Menu
- [x] Notifications
- [x] Paging
- [x] Search
- [x] Steps
- [x] Dynamic Forms
- [ ] Highlight
- [ ] Markdown

Docs:

- [ ] Documentation
- [ ] Style Guide
- [ ] Layouts
- [ ] Components

**Comment by akhedrane** [comment]
hi, i would thank you for this really great work,
I'am a native RTL user so i made a pull request with some change to support RTL direction at #406

**Comment by emoralesb05** [comment]
@akhedrane 💥  awesome! thanks for all the help. 

Will find time to review/test over the week. 😄

**Comment by emoralesb05** [comment]
Closing this since we support RTL in most of our components now.
