### ISSUE TITLE
[Bug?] Deprecated md-input still being used

### ISSUE THREAD

**Issue by asaph26** [Teradata/covalent#327]
Currently it is not possible to use the Nightly Build of Material2 because the deprecated md-input element is still being used. 

Despite the fact that the nightly build is being used, I guess this could potentially break several apps when material beta2 is released.

Places where this is being used in core
https://github.com/Teradata/covalent/blob/develop/src/platform/core/chips/autocomplete/autocomplete.component.html#L2

**Comment by asaph26** [comment]
Saw that there is a PR for this https://github.com/Teradata/covalent/pull/305.

How would Covalent and Material beta 2 releases work out schedule wise

**Comment by emoralesb05** [comment]
Yep, already have the PR ready to go as soon as material releases.

We are just waiting for their `beta.2`, to release our `beta.2` asap.

**Comment by asaph26** [comment]
I so badly wanted to use autocomplete. My shortcut didn't work. :)

Going to wait for it. Closing this issue as this is pretty useless
