### ISSUE TITLE
github.io site routing

### ISSUE THREAD

**Issue by tycho01** [Teradata/covalent#33]
This feature request belongs with the github.io covalent site, but afaict the repo for that is private (?).

I tried linking someone to https://teradata.github.io/covalent/style-guide/material-components, as it's a great overview of ng2 MD components (which they don't even have up yet on their official site yet at all). That link fails though -- it seems the routing is still a one-way street for now. I haven't had much experience with the recent ng2 routers yet either, but hope this might get improved at one point. :)

**Comment by aciccarello** [comment]
Can you do deep linking on a github.io site?

**Comment by tycho01** [comment]
Whoops, good point; since it just 404s rather than giving the `index.html` SPA, I guess probably not. I'll close then; too bad. :(
I wonder if there'd be a way to similarly file a feature request at Github Pages instead, if they have a repo for that...

**Comment by gnomeontherun** [comment]
I have a PR ready to use hash urls to fix this. GitHub doesn't support url
rewrites though we could also use something like cloud flare I think to
help.

>

-- 
------------------------------------------
Jeremy Wilken
