### ISSUE TITLE
Covalent TD-Chart: no provider for TdChartsComponent

### ISSUE THREAD

**Issue by DaMair** [Teradata/covalent#330]
Hi,

 i'm using Covalent 0.10.2 and imported the import { CovalentChartsModule } from '@covalent/charts';  and imported the  CovalentChartsModule.forRoot(), as shown in the docu. I have no clue why i get a "no provider for TdChartsComponent" error while using Covalent charts as followed:

<td-chart-bar #chartBar1
              [colors]="['pink', 'deepPurple']"
              [data]="chartData"
              [padding]="0.1"
              bottomAxis="x"
              columns="y"
              [transition]="true"
              transitionDuration="1000"
              transitionDelay="3000">
</td-chart-bar>

Thanks for any help!

**Comment by emoralesb05** [comment]
You need to have a `<td-charts>` component as parent for it to work.

That being said, we deprecated the `CovalentChartsModule` in favor of `NGX-charts` when we released `0.10.2`. https://github.com/swimlane/ngx-charts
So we encourage you to use those charts since we are partnered with them.

**Comment by DaMair** [comment]
Hi, thx for the fast answer! switched to ngx-charts and the template is working:) 
BTW: Great DataTable!
Greetings David

**Comment by emoralesb05** [comment]
Awesome to hear that! Thanks 😄 

Closing this since its not an issue.
