### ISSUE TITLE
flex styles are missing

### ISSUE THREAD

**Issue by yaronmil** [Teradata/covalent#338]
any ideas why flex is not applyied to this copied demo ?
 
![untitled](https://cloud.githubusercontent.com/assets/954494/22939550/bc2b8eb2-f2e7-11e6-990b-23b509570706.png)

&lt;td-layout-nav logo=&quot;assets:covalent&quot; class=&quot;dark-grey-blue&quot;&gt;
   &lt;div td-toolbar-content layout=&quot;row&quot; layout-align=&quot;start center&quot; flex&gt;
      &lt;span&gt;App Templates&lt;/span&gt;
      &lt;span flex &gt;&lt;/span&gt;
      &lt;button md-icon-button [mdMenuTriggerFor]=&quot;notificationsMenu&quot;&gt;
         &lt;td-notification-count color=&quot;accent&quot; [notifications]=&quot;4&quot;&gt;
            &lt;md-icon&gt;apps&lt;/md-icon&gt;
         &lt;/td-notification-count&gt;
      &lt;/button&gt;
      &lt;md-menu #notificationsMenu=&quot;mdMenu&quot;&gt;
         &lt;td-menu&gt;
            &lt;div td-menu-header class=&quot;md-subhead&quot;&gt;Templates&lt;/div&gt;
            &lt;md-nav-list dense&gt;
               &lt;a md-list-item [routerLink]=&quot;['/templates']&quot;&gt;
                  &lt;md-icon md-list-avatar&gt;system_update_alt&lt;/md-icon&gt;
                  &lt;h4 md-line&gt;&lt;span class=&quot;text-wrap&quot;&gt;Landing Page&lt;/span&gt;&lt;/h4&gt;
                  &lt;p md-line&gt;a landing page template&lt;/p&gt;
               &lt;/a&gt;
               &lt;md-divider&gt;&lt;/md-divider&gt;
               &lt;a md-list-item [routerLink]=&quot;['/templates/dashboard']&quot;&gt;
                  &lt;md-icon md-list-avatar&gt;dashboard&lt;/md-icon&gt;
                  &lt;h4 md-line&gt;&lt;span class=&quot;text-wrap&quot;&gt;Dashboard&lt;/span&gt;&lt;/h4&gt;
                  &lt;p md-line&gt;an ngx-charts dashboard template&lt;/p&gt;
               &lt;/a&gt;
               &lt;md-divider&gt;&lt;/md-divider&gt;
               &lt;a md-list-item [routerLink]=&quot;['/templates/email']&quot;&gt;
                  &lt;md-icon md-list-avatar&gt;email&lt;/md-icon&gt;
                  &lt;h4 md-line&gt;&lt;span class=&quot;text-wrap&quot;&gt;Email App&lt;/span&gt;&lt;/h4&gt;
                  &lt;p md-line&gt;an email app template&lt;/p&gt;
               &lt;/a&gt;
               &lt;md-divider&gt;&lt;/md-divider&gt;
               &lt;a md-list-item [routerLink]=&quot;['/templates/editor']&quot;&gt;
                  &lt;md-icon md-list-avatar&gt;view_array&lt;/md-icon&gt;
                  &lt;h4 md-line&gt;&lt;span class=&quot;text-wrap&quot;&gt;IDE Editor&lt;/span&gt;&lt;/h4&gt;
                  &lt;p md-line&gt;an IDE text editor app template&lt;/p&gt;
               &lt;/a&gt;
            &lt;/md-nav-list&gt;
            &lt;a md-button color=&quot;accent&quot; td-menu-footer href=&quot;https://github.com/Teradata/covalent-quickstart/tree/develop/src/app/templates&quot; target=&quot;_blank&quot;&gt;
            View Code
            &lt;/a&gt;
         &lt;/td-menu&gt;
      &lt;/md-menu&gt;
      &lt;a md-icon-button mdTooltip=&quot;View this code&quot; href=&quot;https://github.com/Teradata/covalent-quickstart/tree/develop/src/app/templates&quot; target=&quot;_blank&quot;&gt;
         &lt;md-icon svgIcon=&quot;assets:github&quot;&gt;&lt;/md-icon&gt;
      &lt;/a&gt;
   &lt;/div&gt;
   &lt;div class=&quot;bgc-black inset charts-dark&quot; flex&gt;
      &lt;div layout-gt-xs=&quot;row&quot; layout-wrap&gt;
         &lt;div flex-gt-xs=&quot;40&quot;&gt;
            &lt;md-card&gt;
               &lt;md-card-title&gt;Total Sales&lt;/md-card-title&gt;
               &lt;md-card-subtitle&gt;combined sales for all products&lt;/md-card-subtitle&gt;
               &lt;md-divider&gt;&lt;/md-divider&gt;
               &lt;div style=&quot;height:290px;overflow:hidden;&quot; class=&quot;pad-top-sm&quot;&gt;
                  &lt;ngx-charts-area-chart-stacked
                  [scheme]=&quot;colorScheme&quot;
                  [results]=&quot;multi&quot;
                  [gradient]=&quot;gradient&quot;
                  [xAxis]=&quot;showXAxis&quot;
                  [yAxis]=&quot;showYAxis&quot;
                  [legend]=&quot;showLegend&quot;
                  [showXAxisLabel]=&quot;showXAxisLabel&quot;
                  [showYAxisLabel]=&quot;showYAxisLabel&quot;
                  [xAxisLabel]=&quot;xAxisLabel&quot;
                  [yAxisLabel]=&quot;yAxisLabel&quot;&gt;
                  &lt;/ngx-charts-area-chart-stacked&gt;
               &lt;/div&gt;
            &lt;/md-card&gt;
         &lt;/div&gt;
         &lt;div flex-gt-xs=&quot;60&quot;&gt;
            &lt;div layout-gt-xs=&quot;row&quot;&gt;
               &lt;div flex-gt-xs=&quot;100&quot;&gt;
                  &lt;ngx-charts-number-card
                  [scheme]=&quot;colorSchemeDark&quot;
                  [results]=&quot;single&quot;&gt;
                  &lt;/ngx-charts-number-card&gt;
               &lt;/div&gt;
            &lt;/div&gt;
            &lt;div layout-gt-xs=&quot;row&quot; class=&quot;pull-top-xs&quot;&gt;
               &lt;div flex-gt-xs=&quot;100&quot;&gt;
                  &lt;md-card&gt;
                     &lt;div style=&quot;height:224px;overflow:hidden;&quot; class=&quot;pad-top push-right&quot;&gt;
                        &lt;ngx-charts-bar-horizontal-stacked
                        [scheme]=&quot;colorScheme&quot;
                        [results]=&quot;multi&quot;
                        [gradient]=&quot;gradient&quot;
                        [xAxis]=&quot;showXAxis&quot;
                        [yAxis]=&quot;showYAxis&quot;
                        [legend]=&quot;showLegend&quot;
                        [showXAxisLabel]=&quot;showXAxisLabel&quot;
                        [showYAxisLabel]=&quot;showYAxisLabel&quot;
                        [xAxisLabel]=&quot;xAxisLabel&quot;&gt;
                        &lt;/ngx-charts-bar-horizontal-stacked&gt;
                     &lt;/div&gt;
                  &lt;/md-card&gt;
               &lt;/div&gt;
            &lt;/div&gt;
         &lt;/div&gt;
         &lt;div flex-gt-xs=&quot;33&quot;&gt;
            &lt;md-card&gt;
               &lt;md-card-title&gt;Product Sales&lt;/md-card-title&gt;
               &lt;md-divider&gt;&lt;/md-divider&gt;
               &lt;div style=&quot;height:250px;&quot; class=&quot;pad-top&quot;&gt;
                  &lt;ngx-charts-bar-vertical-2d
                  [scheme]=&quot;colorScheme&quot;
                  [results]=&quot;multi&quot;
                  [gradient]=&quot;gradient&quot;
                  [xAxis]=&quot;showXAxis&quot;
                  [yAxis]=&quot;showYAxis&quot;
                  [legend]=&quot;showLegend&quot;
                  [showXAxisLabel]=&quot;showXAxisLabel&quot;
                  [showYAxisLabel]=&quot;showYAxisLabel&quot;
                  [xAxisLabel]=&quot;xAxisLabel&quot;
                  [yAxisLabel]=&quot;yAxisLabel&quot;&gt;
                  &lt;/ngx-charts-bar-vertical-2d&gt;
               &lt;/div&gt;
            &lt;/md-card&gt;
         &lt;/div&gt;
         &lt;div flex-gt-xs=&quot;33&quot;&gt;
            &lt;md-card&gt;
               &lt;md-card-title&gt;Product Usage&lt;/md-card-title&gt;
               &lt;md-divider&gt;&lt;/md-divider&gt;
               &lt;div style=&quot;height:250px;&quot; class=&quot;pad-top&quot;&gt;
                  &lt;ngx-charts-gauge
                  [scheme]=&quot;colorScheme&quot;
                  [results]=&quot;single&quot;
                  [min]=&quot;0&quot;
                  [max]=&quot;100&quot;
                  [units]=&quot;'usage'&quot;
                  [bigSegments]=&quot;10&quot;
                  [smallSegments]=&quot;5&quot;&gt;
                  &lt;/ngx-charts-gauge&gt;
               &lt;/div&gt;
            &lt;/md-card&gt;
         &lt;/div&gt;
         &lt;div flex-gt-xs=&quot;33&quot;&gt;
            &lt;md-card&gt;
               &lt;md-card-title&gt;Sales Forecast&lt;/md-card-title&gt;
               &lt;md-divider&gt;&lt;/md-divider&gt;
               &lt;div style=&quot;height:250px;&quot; class=&quot;pad-top&quot;&gt;
                  &lt;ngx-charts-line-chart
                  [scheme]=&quot;colorScheme&quot;
                  [results]=&quot;multi&quot;
                  [gradient]=&quot;gradient&quot;
                  [xAxis]=&quot;showXAxis&quot;
                  [yAxis]=&quot;showYAxis&quot;
                  [legend]=&quot;showLegend&quot;
                  [showXAxisLabel]=&quot;showXAxisLabel&quot;
                  [showYAxisLabel]=&quot;showYAxisLabel&quot;
                  [xAxisLabel]=&quot;xAxisLabel&quot;
                  [yAxisLabel]=&quot;yAxisLabel&quot;
                  [autoScale]=&quot;autoScale&quot;&gt;
                  &lt;/ngx-charts-line-chart&gt;
               &lt;/div&gt;
            &lt;/md-card&gt;
         &lt;/div&gt;
      &lt;/div&gt;
   &lt;/div&gt;
   &lt;td-layout-footer&gt;
      &lt;div layout=&quot;row&quot; layout-align=&quot;start center&quot;&gt;
         &lt;span class=&quot;md-caption&quot;&gt;Days Shown:&lt;/span&gt;
         &lt;md-slider flex thumbLabel tickInterval=&quot;1&quot; step=&quot;1&quot; min=&quot;1&quot; max=&quot;30&quot; value=&quot;14&quot;&gt;&lt;/md-slider&gt;
      &lt;/div&gt;
   &lt;/td-layout-footer&gt;
   &lt;a md-fab color=&quot;accent&quot; class=&quot;md-fab-position-bottom-right&quot; style=&quot;bottom:20px;&quot; href=&quot;https://github.com/Teradata/covalent-quickstart/tree/develop/src/app/templates&quot; target=&quot;_blank&quot;&gt;
      &lt;md-icon&gt;code&lt;/md-icon&gt;
   &lt;/a&gt;
&lt;/td-layout-nav&gt;

**Comment by yaronmil** [comment]
solved 
i had to add this : @import '~@covalent/core/common/styles/layout'
to themes.scss;

**Comment by kyleledbetter** [comment]
If you're using angular-cli you can also import our platform styles there https://github.com/Teradata/covalent-quickstart/blob/develop/angular-cli.json#L24

**Comment by yaronmil** [comment]
it is working thank's
