### ISSUE TITLE
[Enhancement] Allow fixed headers for the data table.

### ISSUE THREAD

**Issue by jraadt** [Teradata/covalent#341]
This is a great data table.  It would be nice if it also included an option to make the header fixed or sticky within a scrollable area.  I've worked with daniel-nagy's fixed-table-header (https://github.com/daniel-nagy/fixed-table-header) and it worked nicely for my AngularJS 1 projects.

**Comment by kyleledbetter** [comment]
I think we need to extrapolate this to any element being "sticky" to be considered for a platform. We have to think about the th header row just as any element and factor making it possible via Flexbox just like we use Flexbox for scrolling overflow of layout=column with the content having a vertical flex

**Comment by jraadt** [comment]
@kyleledbetter I agree.  I made an implementation of fixed-table-header using $mdSticky service from Angular Material 1.  So maybe instead this should be a feature request for a sticky service.

**Comment by kyleledbetter** [comment]
That's a much more reusable atomic approach for a platform 👍

**Comment by jraadt** [comment]
Should I rename this issue or close and create a new issue for creating a sticky service?  Not sure the etiquette.

**Comment by emoralesb05** [comment]
This was done in beta.7
