### ISSUE TITLE
Paging should support unknown number of results

### ISSUE THREAD

**Issue by thekalinga** [Teradata/covalent#343]
#### Feature Request

Paging component should support unknown number of total results

For performance reasons, many apps dont query the total number of records (gmail). They just return results given the offset & page size.

The only way to be certain that there are no results is either

1. If the results returned for any offset are less than page size
2. No more results to return (if it so happens that the number of results on the server happen to be a multiple of page size)

**Comment by owilliams320** [comment]
this component will be deprecated in future versions please use https://material.angular.io/components/paginator/overview
