### ISSUE TITLE
Date Picker

### ISSUE THREAD

**Issue by victorblq** [Teradata/covalent#345]
##### Other information
There is plans to add a date picker in covalent? I work a lot with dates and the only option that I found was vaadin date picker but it has a lot of problems with the data binding (One and two-way).

**Comment by d3viant0ne** [comment]
There is already a spec & issue in material2 proper for a [datepicker](https://github.com/angular/material2/issues/675)

**Comment by emoralesb05** [comment]
Yes, for the most part we arent trying to duplicate efforts with the `material` team. So we are waiting on them for that, while we focus on services or components that arent in their roadmap or not in their priority list.

**Comment by victorblq** [comment]
Thanks! :) Nice work.

**Comment by emoralesb05** [comment]
Closing since its coming from material in their `beta.3`
