### ISSUE TITLE
[Enhancement] Configurable sortable column with td-data-table

### ISSUE THREAD

**Issue by saurabh1e** [Teradata/covalent#347]
It would be great if we can configure which column to sort, when using
```js
<td-data-table
  [data]="filteredData"
  [columns]="columns"
  [sortBy]="sortBy"
  [sortable]="true"
  [sortOrder]="sortOrder"
  (sortChange)="sort($event)">
</td-data-table>
```
A property can be added to **`ITdDataTableColumn`**  check whether column is sortable or not

``` js
columns: ITdDataTableColumn[] = [
    { name: 'sku', label: 'SKU #', tooltip: 'Stock Keeping Unit', sortable: true },
    { name: 'item', label: 'Item name' },
    { name: 'price', label 'Price (US$)', numeric: true, format: v => v.toFixed(2) },
  ];
```

**Comment by emoralesb05** [comment]
Yes, totally agree! Thanks for bringing this up.

**Comment by ranouf** [comment]
Hi,

Where you use a custom template, when you put sortable: false in the column array, the parameter is not used by the component and the header is still sortable.
Can you fix the pb?
