### ISSUE TITLE
data table (Atomic) column sort not working

### ISSUE THREAD

**Issue by pabloxn** [Teradata/covalent#349]
This repository's issues are reserved for feature requests and bug reports.

#### Bug Report
I am trying to get the sort to work using the atomic components.

When I click the header to sort I am getting:

> Object {name: "", order: "DESC"}

No matter what I set name to in the column header it always returns an empty name.

http://plnkr.co/edit/XEkeyFTT36VbR44gXDXk?p=preview

**Comment by emoralesb05** [comment]
Wow, i dont know how we missed that.

Thanks for letting us know! Will fix asap for beta.2.

**Comment by emoralesb05** [comment]
Fix will be available in `beta.2`
