### ISSUE TITLE
Update to angular cli with webpack

### ISSUE THREAD

**Issue by Isigiel** [Teradata/covalent#35]
This repository's issues are reserved for feature requests and bug reports.

### Do you want to request a *feature* or report a *bug*?
Feature
#### Feature Request
Please update covalent to the newest version of the angular cli, that switched the build system to webpack.
Also applies to the starter kit.

**Comment by RemKolomna** [comment]
BTW: material2 temporarily moves from ng-cli to gulp to build its library https://github.com/angular/material2/pull/948

**Comment by gnomeontherun** [comment]
They haven't yet released a more stable version of the cli with webpack, once that is out we'll get on it.

**Comment by kyleledbetter** [comment]
yeah we need to let the smoke settle just a touch, lots of things in the air right now, but excited for the near future!

**Comment by emoralesb05** [comment]
We also need to make sure --prod works.

**Comment by Isigiel** [comment]
To clarify, I was actually not concerned about the starter project. It's not that after all, most people don't build the lib

**Comment by richavyas** [comment]
Yes @Isigiel, we won't be building the lib using webpack as of now. It's not recommended either. angular-cli that has been upgraded to webpack to run the app would be updated in covalent too as soon as all the issues related to `rc.6 + webpack` have been resolved.

**Comment by emoralesb05** [comment]
Quickstart and docs are using angular-cli@webpack now.
