### ISSUE TITLE
s

### ISSUE THREAD

**Issue by joe-vella** [Teradata/covalent#352]
This repository's issues are reserved for feature requests and bug reports.

#### Feature Request

please first make sure your request falls under the official Material Design spec guidelines https://material.google.com/

#### Bug Report

please provide steps to reproduce and if possible screenhots, animated Gifs and/or a Plunker (or similar).
you can easily create animated Gif with this free PC/OSX App: http://www.cockos.com/licecap/ and a Plunker to help us reproduce it
Plunker template: http://plnkr.co/edit/7uZQn4mLNJkL6XN9WSNd

#### Which version of Angular and Material, and which browser and OS does this issue affect?

Did this work in previous versions of Angular / Material?
Please also test with the latest stable and snapshot versions.

##### Other information
(e.g. detailed explanation, stacktraces, related issues, suggestions how to fix)

**Comment by joe-vella** [comment]
I'm not sure how an issue was opened by me two days ago-- it was not my intention. Sorry for the trouble.

**Comment by emoralesb05** [comment]
No worries 😄 . we were just confused haha
