### ISSUE TITLE
File upload error

### ISSUE THREAD

**Issue by MingyuJeon** [Teradata/covalent#355]
Hi, I found this amazing library today.
I tried to apply it to my project for file upload, but it made errors.
If you have an idea to solve this problem, please let me know
 

> Uncaught Error: Module build failed: Error: /Users/jeonmingyu/work/web-admin/node_modules/@covalent/core/data-table/directives/data-table-template.directive.ts (9,24): Argument of type 'ViewContainerRef' is not assignable to parameter of type 'ViewContainerRef'.)
>     at _checkDiagnostics (/Users/jeonmingyu/work/web-admin/node_modules/@ngtools/webpack/src/loader.js:116:15)
>     at /Users/jeonmingyu/work/web-admin/node_modules/@ngtools/webpack/src/loader.js:141:17
>     at _checkDiagnostics (/Users/jeonmingyu/work/web-admin/node_modules/@ngtools/webpack/src/loader.js:116:15)
>     at /Users/jeonmingyu/work/web-admin/node_modules/@ngtools/webpack/src/loader.js:141:17
>     at Object.<anonymous> (http://localhost:4200/vendor.bundle.js:87617:7) [<root>]
>     at __webpack_require__ (http://localhost:4200/inline.bundle.js:53:30) [<root>]
>     at Object.<anonymous> (http://localhost:4200/vendor.bundle.js:44396:100) [<root>]
>     at __webpack_require__ (http://localhost:4200/inline.bundle.js:53:30) [<root>]
>     at Object.<anonymous> (http://localhost:4200/vendor.bundle.js:87533:80) [<root>]
>     at __webpack_require__ (http://localhost:4200/inline.bundle.js:53:30) [<root>]
>     at Object.<anonymous> (http://localhost:4200/vendor.bundle.js:86727:88) [<root>]
>     at __webpack_require__ (http://localhost:4200/inline.bundle.js:53:30) [<root>]
>     at Object.577 (http://localhost:4200/main.bundle.js:3031:73) [<root>]
>     at __webpack_require__ (http://localhost:4200/inline.bundle.js:53:30) [<root>]
>     at Object.905 (http://localhost:4200/main.bundle.js:5441:86) [<root>]
>     at __webpack_require__ (http://localhost:4200/inline.bundle.js:53:30) [<root>]
>     at Object.917 (http://localhost:4200/main.bundle.js:7177:70) [<root>]
>     at __webpack_require__ (http://localhost:4200/inline.bundle.js:53:30) [<root>]
> 
> ./~/@covalent/core/expansion-panel/expansion-panel.component.ts
> Module build failed: Error: /Users/jeonmingyu/work/web-admin/node_modules/@covalent/core/expansion-panel/expansion-panel.component.ts (12,24): Argument of type 'ViewContainerRef' is not assignable to parameter of type 'ViewContainerRef'.
>   Types of property 'createComponent' are incompatible.
>     Type '<C>(componentFactory: ComponentFactory<C>, index?: number, injector?: Injector, projectableNodes?...' is not assignable to type '<C>(componentFactory: ComponentFactory<C>, index?: number, injector?: Injector, projectableNodes?...'.
>       Types of parameters 'componentFactory' and 'componentFactory' are incompatible.
>         Type 'ComponentFactory<any>' is not assignable to type 'ComponentFactory<any>'.
>           Types have separate declarations of a private property '_viewClass'.)
> /Users/jeonmingyu/work/web-admin/node_modules/@covalent/core/expansion-panel/expansion-panel.component.ts (21,24): Argument of type 'ViewContainerRef' is not assignable to parameter of type 'ViewContainerRef'.)
> /Users/jeonmingyu/work/web-admin/node_modules/@covalent/core/expansion-panel/expansion-panel.component.ts (30,24): Argument of type 'ViewContainerRef' is not assignable to parameter of type 'ViewContainerRef'.)
>     at _checkDiagnostics (/Users/jeonmingyu/work/web-admin/node_modules/@ngtools/webpack/src/loader.js:116:15)
>     at /Users/jeonmingyu/work/web-admin/node_modules/@ngtools/webpack/src/loader.js:141:17
>  @ ./~/@covalent/core/expansion-panel/expansion-panel.module.ts 13:0-206 21:0-72
>  @ ./~/@covalent/core/index.js
>  @ ./src/app/app.module.ts
>  @ ./src/app/index.ts
>  @ ./src/main.ts
>  @ multi main
> 
> ./~/@covalent/core/steps/step.component.ts
> Module build failed: Error: /Users/jeonmingyu/work/web-admin/node_modules/@covalent/core/steps/step.component.ts (17,24): Argument of type 'ViewContainerRef' is not assignable to parameter of type 'ViewContainerRef'.)
> /Users/jeonmingyu/work/web-admin/node_modules/@covalent/core/steps/step.component.ts (26,24): Argument of type 'ViewContainerRef' is not assignable to parameter of type 'ViewContainerRef'.)
> /Users/jeonmingyu/work/web-admin/node_modules/@covalent/core/steps/step.component.ts (35,24): Argument of type 'ViewContainerRef' is not assignable to parameter of type 'ViewContainerRef'.)
> /Users/jeonmingyu/work/web-admin/node_modules/@covalent/core/steps/step.component.ts (138,61): Argument of type 'ViewContainerRef' is not assignable to parameter of type 'ViewContainerRef'.)
>     at _checkDiagnostics (/Users/jeonmingyu/work/web-admin/node_modules/@ngtools/webpack/src/loader.js:116:15)
>     at /Users/jeonmingyu/work/web-admin/node_modules/@ngtools/webpack/src/loader.js:141:17
>  @ ./~/@covalent/core/steps/steps.module.ts 17:0-121 27:0-62
>  @ ./~/@covalent/core/index.js
>  @ ./src/app/app.module.ts
>  @ ./src/app/index.ts
>  @ ./src/main.ts
>  @ multi main
> 
> ./~/@covalent/core/data-table/directives/data-table-template.directive.ts
> Module build failed: Error: /Users/jeonmingyu/work/web-admin/node_modules/@covalent/core/data-table/directives/data-table-template.directive.ts (9,24): Argument of type 'ViewContainerRef' is not assignable to parameter of type 'ViewContainerRef'.)
>     at _checkDiagnostics (/Users/jeonmingyu/work/web-admin/node_modules/@ngtools/webpack/src/loader.js:116:15)
>     at /Users/jeonmingyu/work/web-admin/node_modules/@ngtools/webpack/src/loader.js:141:17
>  @ ./~/@covalent/core/data-table/data-table.module.ts 19:0-90
>  @ ./~/@covalent/core/index.js
>  @ ./src/app/app.module.ts
>  @ ./src/app/index.ts
>  @ ./src/main.ts
>  @ multi main
> 
> ./~/@covalent/core/dialogs/services/dialog.service.ts
> Module build failed: Error: /Users/jeonmingyu/work/web-admin/node_modules/@covalent/core/dialogs/services/dialog.service.ts (65,59): Argument of type 'IAlertConfig' is not assignable to parameter of type 'MdDialogConfig'.
>   Types of property 'viewContainerRef' are incompatible.
>     Type 'ViewContainerRef' is not assignable to type 'ViewContainerRef'.)
> /Users/jeonmingyu/work/web-admin/node_modules/@covalent/core/dialogs/services/dialog.service.ts (91,59): Argument of type 'IConfirmConfig' is not assignable to parameter of type 'MdDialogConfig'.
>   Types of property 'viewContainerRef' are incompatible.
>     Type 'ViewContainerRef' is not assignable to type 'ViewContainerRef'.)
> /Users/jeonmingyu/work/web-admin/node_modules/@covalent/core/dialogs/services/dialog.service.ts (121,59): Argument of type 'IPromptConfig' is not assignable to parameter of type 'MdDialogConfig'.
>   Types of property 'viewContainerRef' are incompatible.
>     Type 'ViewContainerRef' is not assignable to type 'ViewContainerRef'.)
>     at _checkDiagnostics (/Users/jeonmingyu/work/web-admin/node_modules/@ngtools/webpack/src/loader.js:116:15)
>     at /Users/jeonmingyu/work/web-admin/node_modules/@ngtools/webpack/src/loader.js:141:17
>  @ ./~/@covalent/core/dialogs/dialogs.module.ts 18:0-60 33:0-88
>  @ ./~/@covalent/core/index.js
>  @ ./src/app/app.module.ts
>  @ ./src/app/index.ts
>  @ ./src/main.ts
>  @ multi main
> 
> ./~/@covalent/core/loading/services/loading.factory.ts
> Module build failed: Error: /Users/jeonmingyu/work/web-admin/node_modules/@covalent/core/loading/services/loading.factory.ts (80,80): Argument of type 'ViewContainerRef' is not assignable to parameter of type 'ViewContainerRef'.)
>     at _checkDiagnostics (/Users/jeonmingyu/work/web-admin/node_modules/@ngtools/webpack/src/loader.js:116:15)
>     at /Users/jeonmingyu/work/web-admin/node_modules/@ngtools/webpack/src/loader.js:141:17
>  @ ./~/@covalent/core/loading/loading.module.ts 15:0-62
>  @ ./~/@covalent/core/index.js
>  @ ./src/app/app.module.ts
>  @ ./src/app/index.ts
>  @ ./src/main.ts
>  @ multi main

=======================================================================

```
  "dependencies": {
    "@angular/common": "~2.4.1",
    "@angular/compiler": "~2.4.1",
    "@angular/compiler-cli": "^2.4.1",
    "@angular/core": "~2.4.1",
    "@angular/flex-layout": "^2.0.0-beta.1",
    "@angular/forms": "~2.4.1",
    "@angular/http": "~2.4.1",
    "@angular/material": "^2.0.0-beta.0",
    "@angular/platform-browser": "~2.4.1",
    "@angular/platform-browser-dynamic": "~2.4.1",
    "@angular/router": "~3.4.1",
    "@covalent/core": "^1.0.0-beta.1-1",
    "@covalent/file-upload": "^0.9.1",
    "@types/moment-timezone": "^0.2.33",
    "angular-cli": "^1.0.0-beta.24",
    "angular2-google-maps": "^0.17.0",
    "bootstrap": "^3.3.7",
    "bourbon": "^4.2.7",
    "codelyzer": "^2.0.0-beta.4",
    "core-js": "^2.4.1",
    "font-awesome": "^4.7.0",
    "hammerjs": "^2.0.8",
    "material-design-icons": "^3.0.1",
    "moment": "^2.17.1",
    "moment-timezone": "^0.5.10",
    "node-sass": "^3.13.0",
    "primeng": "^2.0.0-rc.1",
    "pubnub": "^4.4.0",
    "pubnub-angular2": "^1.0.0-beta.8",
    "quill": "^1.1.8",
    "rxjs": "^5.0.2",
    "ts-helpers": "^1.1.1",
    "typescript": "^2.0.10",
    "webdriver-manager": "^12.0.2",
    "zone.js": "^0.7.4"
  }
```

I referenced [https://teradata.github.io/covalent/#/components/file-upload](https://teradata.github.io/covalent/#/components/file-upload)

![image](https://cloud.githubusercontent.com/assets/15281293/23147804/179c74a4-f825-11e6-95e5-b8bb19d2a68b.png)

**Comment by emoralesb05** [comment]
This sort of error is related to `npm` cache. 

Sometimes you need to delete the `node_modules` dir and `npm i` from scratch.

**Comment by MingyuJeon** [comment]
@emoralesb05 Thanks for the reply! 👍 

If you could tell me detail, I would appreciate you. :)

Do you mean I should delete all of npm packages in the node_modules and re-install?

**Comment by emoralesb05** [comment]
Np 😄 , so you would only execute `rm -rf node_modules && npm i`.

Since sometimes `npm` installs multiple versions of a dependency causing that sort of error, and its trying to compare the same class definition from different versions of the same dependency. 

Hence the error `ViewContainerRef` not assignable to `ViewContainerRef` which is an `@angular/core` class.

**Comment by MingyuJeon** [comment]
@emoralesb05 Thank you :)
I'm trying now. You're awesome!

**Comment by emoralesb05** [comment]
no worries 😄 . 

Also, i just noticed you have `"@covalent/file-upload": "^0.9.1",` in the package.json

That might affect it too, so you need to remove it since `file-upload` is now part of `@covalent/core`.

**Comment by MingyuJeon** [comment]
@emoralesb05 
Thanks again :)
However, I have a serious problem now.
I follow your step, and now it makes an error.

`
Error: Unexpected value 'undefined' imported by the module 'AppModule' at SyntaxError.ZoneAwareError`

My app.module.ts is like bellow.

```
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { HttpModule } from '@angular/http';

import { AppComponent } from './app.component';
import { environment } from '../environments/environment';

//Dashboard
import { NavComponent } from './nav/nav.component';
import { HomeComponent } from './home/home.component';

//Signin
import { SigninComponent } from './signin/signin.component';
import { ForgetPasswordComponent } from './signin/forget-password/forget-password.component';

//Delivery
import { DeliveryComponent } from './delivery/delivery.component';
import { DeliveryDetailComponent } from './delivery/delivery-detail/delivery-detail.component';
import { TodayOrderComponent } from './home/today-order/today-order.component';
import { ReservationComponent } from './home/reservation/reservation.component';

//Area Management
import { AreaManagementComponent } from './area-management/area-management.component';
import { CountryComponent } from './area-management/country/country.component';
import { ProvinceComponent } from './area-management/province/province.component';
import { CityComponent } from './area-management/city/city.component';
import { AreaComponent } from './area-management/area/area.component';
import { DeliveryAreaComponent } from './area-management/delivery-area/delivery-area.component';

//5delivery setting
import { FDeliverySettingComponent } from './f-delivery-setting/f-delivery-setting.component';

//Terms
import { TermsListComponent } from './terms-list/terms-list.component';
import { TermsComponent } from './terms/terms.component';
import { TermsShowComponent, TermsForUsersComponent, PrivacyForUsersComponent } from './terms-show/terms-show.component';

//User Managment
import { UserManagementComponent } from './user-management/user-management.component';
import { UserDetailComponent } from './user-detail/user-detail.component';
import { UserAddComponent } from './user-add/user-add.component';
import { ClientMapComponent } from './delivery/delivery-detail/client-map/client-map.component';

//Branch Management
import { BranchManagementComponent } from './branch-management/branch-management.component';
import { BranchDetailComponent } from './branch-management/branch-detail/branch-detail.component';
import { NewBranchComponent } from './branch-management/new-branch/new-branch.component';

//DM
import { LicenseComponent } from './license/license.component';
import { LicenseDetailComponent } from './license/license-detail/license-detail.component';
import { InternalComponent } from './home/internal/internal.component';
import { ExternalComponent } from './home/external/external.component';
import { DmStatusComponent } from './dm-status/dm-status.component';

//Classification
import { ClassificationComponent } from './classification/classification.component';

//Accounting
import { DmBillingComponent } from './payment-billing/dm-billing/dm-billing.component';
import { PartnerBillingComponent } from './payment-billing/partner-billing/partner-billing.component';
import { WowbillingComponent } from './payment-billing/wowbilling/wowbilling.component';
import { DailyReportingComponent } from './daily-reporting/daily-reporting.component';
import { AccountClosingComponent } from './account-closing/account-closing.component';
import { AccountingComponent } from "./accounting-balance/accounting-balance.component";

//Partner Managment
import { PartnerComponent } from './partner/partner.component';
import { PartnerAddComponent } from './partner/partner-add/partner-add.component';
import { PartnerEditComponent } from './partner/partner-edit/partner-edit.component';

// dialog
import { DialogsComponent } from './shared/dialogs/dialogs.component';
import { MainCategoryComponent } from './shared/dialogs/dialogs.component';
import { SubCategoryComponent } from './shared/dialogs/dialogs.component';
import { AreaCityComponent } from './shared/dialogs/dialogs.component';
import { CityDialogComponent } from './shared/dialogs/dialogs.component';
import { ProvinceDialogComponent } from './shared/dialogs/dialogs.component';
import { AreaDialogComponent } from './shared/dialogs/dialogs.component';

//Services
import { AreaService } from "./area-management/area-management.service";
import { FDeliveryService } from "./f-delivery-setting/f-delivery.service";
import { TermsListService } from "./terms-list/terms-list.service";
import { TermsService } from "./terms/terms.service";
import { UserService} from "./user-management/user.service";
import { UserDetailService } from "./user-detail/user-detail.service";
import { AuthGuardService } from "./signin/auth-guard.service";
import { AuthService } from "./signin/auth.service";
import { BranchService } from "./branch-management/branch.service";
import { LicenseService } from "./license/license.service";
import { DeliveryService } from "./delivery/delivery.service";
import { NavService } from "./nav/nav.service";
import { PartnerService } from "./shared/partner.service";
import { FileUploadService } from "./shared/file-upload.service";
import { GmapService } from "./shared/gmap.service";
import { PubnubInfoService } from "./shared/pubnub-info.service";
import { ClassificationService } from "./shared/classification.service";

import { routing } from './app.routing';

//3rd Parties
import { MaterialModule } from '@angular/material';
import 'hammerjs';
import { FlexLayoutModule } from '@angular/flex-layout';
import { PubNubAngular } from 'pubnub-angular2';
import { NgUploaderModule } from 'ngx-uploader';
//PrimeNG
import {
  DialogModule,
  ButtonModule,
  DataTableModule,
  InputTextModule,
  TabViewModule,
  DropdownModule,
  EditorModule,
  SharedModule,
  AutoCompleteModule,
  PanelMenuModule,
  MenuModule,
  ContextMenuModule,
  PasswordModule,
  FileUploadModule,
  InputTextareaModule,
  RadioButtonModule,
  CalendarModule,
  CheckboxModule,
  ConfirmDialogModule,
  ConfirmationService,
  InputMaskModule,
  BlockUIModule,
  PaginatorModule,
  GrowlModule,
  GMapModule
} from "primeng/primeng";

import { AgmCoreModule } from "angular2-google-maps/core/core-module";


//covalent
// import { CovalentFileModule } from '@covalent/core';

@NgModule({
  declarations: [
    AppComponent,
    HomeComponent,
    DeliveryComponent,
    AreaManagementComponent,
    CountryComponent,
    ProvinceComponent,
    SigninComponent,
    CityComponent,
    AreaComponent,
    DeliveryAreaComponent,
    FDeliverySettingComponent,
    TermsComponent,
    TermsListComponent,
    UserManagementComponent,
    NavComponent,
    LicenseComponent,
    TermsShowComponent,
    TermsForUsersComponent,
    PrivacyForUsersComponent,
    UserDetailComponent,
    LicenseDetailComponent,
    BranchManagementComponent,
    BranchDetailComponent,
    InternalComponent,
    ExternalComponent,
    AccountingComponent,
    ClassificationComponent,
    DmBillingComponent,
    PartnerBillingComponent,
    WowbillingComponent,
    DailyReportingComponent,
    AccountClosingComponent,
    UserAddComponent,
    PartnerComponent,
    PartnerAddComponent,
    NewBranchComponent,
    ForgetPasswordComponent,
    DeliveryDetailComponent,
    PartnerEditComponent,
    TodayOrderComponent,
    ReservationComponent,
    ClientMapComponent,
    DmStatusComponent,

    //dialog
    DialogsComponent,
    MainCategoryComponent,
    SubCategoryComponent,
    AreaCityComponent,
    CityDialogComponent,
    ProvinceDialogComponent,
    AreaDialogComponent
  ],
  imports: [
    BrowserModule,
    FormsModule,
    HttpModule,
    routing,
    MaterialModule,
    FlexLayoutModule,
    ReactiveFormsModule,
    AgmCoreModule.forRoot({
      apiKey: environment.googleKey
    }),
    // CovalentFileModule.forRoot(),

    //file uploader
    NgUploaderModule,

    //primeNG
    InputTextareaModule,
    InputTextModule,
    DataTableModule,
    DialogModule,
    DropdownModule,
    ButtonModule,
    TabViewModule,
    EditorModule,
    SharedModule,
    PanelMenuModule,
    MenuModule,
    ContextMenuModule,
    PasswordModule,
    FileUploadModule,
    RadioButtonModule,
    CalendarModule,
    CheckboxModule,
    ConfirmDialogModule,
    InputMaskModule,
    PaginatorModule,
    GrowlModule,
    GMapModule
  ],
  entryComponents: [
    DialogsComponent,
    MainCategoryComponent,
    SubCategoryComponent,
    AreaCityComponent,
    CityDialogComponent,
    ProvinceDialogComponent,
    AreaDialogComponent
  ],
  providers: [
    AreaService,
    FDeliveryService,
    TermsListService,
    TermsService,
    UserService,
    AuthGuardService,
    AuthService,
    UserDetailService,
    LicenseService,
    BranchService,
    DeliveryService,
    NavService,
    PartnerService,
    ConfirmationService,
    FileUploadService,
    PubNubAngular,
    GmapService,
    PubnubInfoService,
    ClassificationService
  ],
  bootstrap: [AppComponent]
})
export class AppModule { }
```

**Comment by MingyuJeon** [comment]
I found a solution.
The FlexLayoutModule makes the error. The error's gone, but I have no idea why it happens...

**Comment by emoralesb05** [comment]
Huh, thats a weird error. Im glad that the errors around covalent are fixed though 😄 .

**Comment by MingyuJeon** [comment]
@emoralesb05 It was angular-cli issue :)

It's not about this issue, but I wonder when I could use updated covalent.

I know that you are updating md-input to mdInput in progress.

I'm looking forward to using updated covalent.

**Comment by emoralesb05** [comment]
Closing since it was an `npm` and `cli` issue.
