### ISSUE TITLE
Stepper (Wizard) horizontal mode: Forcing open td-steps

### ISSUE THREAD

**Issue by jnamesky** [Teradata/covalent#358]
Require the ability to force a td-step tab open until a user has gone to another td-step tab. This behavior would be similar to md-tabs.

Currently functionality allows users to toggle open and close td-step tabs like expansion panels, which has been confusing for some of our test users.

**Comment by dapriett** [comment]
I had the same issue - ended up fixing it with CSS

`
td-step-header {
    pointer-events: none;
}
`

**Comment by spinachandkale** [comment]
@dapriett I tried to fix with the solution you've given but it is making entire stepper non-clickable. 

Before change: 
<td-steps  mode="horizontal">

After the change: 
<td-steps class="td-step-header" mode="horizontal">

Then tried with adding td-step-header class in <td-step>, with this change the problem still exist. 
<td-step class="td-step-header" ......>

Functionality I'm looking for is: don't toggle (open/close td-step) when clicked on the step that currently is active.

**Comment by dapriett** [comment]
Yep.  I use Prev/Next buttons to move between step, using the below code:


```
  activeStepIdx = 0;
  activeStep: TdStepComponent;
  stepDeactivateSubscription: Subscription;

  @ViewChildren(TdStepComponent) public steps: QueryList<TdStepComponent>;

  private markStepActive(activeIdx = 0) {
    if ( this.stepDeactivateSubscription ) { this.stepDeactivateSubscription.unsubscribe(); }

    this.activeStepIdx = activeIdx;
    this.steps.forEach((step, idx) => {
      if (this.activeStepIdx === idx) {
        step.disabled = false;
        step.active = true;
      } else {
        step.disabled = true;
      }

      step.state = (idx < this.activeStepIdx) ? StepState.Complete : StepState.None;
    });

    this.activeStep = this.steps.toArray()[this.activeStepIdx];
    this.activeStepForm = this.stepForms.toArray()[this.activeStepIdx];

    this.changeRef.detectChanges();

    if (this.activeStep) {
      this.stepDeactivateSubscription = this.activeStep.onDeactivated
        .subscribe( () => this.activeStep.active = true );

    }
  };
```

**Comment by spinachandkale** [comment]
@dapriett Thank you, I will try same.

**Comment by jeremysmartt** [comment]
should build this functionality into the component

**Comment by owilliams320** [comment]
this component is deprecated please use https://material.angular.io/components/stepper
