### ISSUE TITLE
Async Support in md-chip

### ISSUE THREAD

**Issue by saurabh1e** [Teradata/covalent#359]
#### Feature Request
It would be great if we can have chips accepting only items from autocomplete using a remote endpoint.

```js
<td-chips placeholder="Enter string" [autoCompleteRemote]="autoComplete" [(ngModel)]="model" [readOnly]="readOnly" (add)="add($event)" (remove)="remove($event)" requireMatch>
</td-chips>
```

```js
autoComplete = (event): Observable<any> => {
    return http.query
}
```

**Comment by emoralesb05** [comment]
Yep 👍 , we have an issue open for that https://github.com/Teradata/covalent/issues/252. And we were currently waiting for `md-autocomplete` to be released so we could improve chips even further (which has been released last week in the `material@beta.2`).

As soon as our `beta.2` is released this week, this will be one of the priorities and we will start a design process around how the actual behavior for lazy loading should be.

**Comment by emoralesb05** [comment]
https://github.com/Teradata/covalent/pull/626 will take care of this 😄 .
