### ISSUE TITLE
Update to angular 2.0.0-rc.5 and material 2.0.0-alpha.7

### ISSUE THREAD

**Issue by emoralesb05** [Teradata/covalent#36]
This repository's issues are reserved for feature requests and bug reports.

#### Feature Request

Update `covalent` to angular `2.0.0-rc.5` and material `2.0.0-alpha.7` and modify code to use new ngModules.
Also, need to add new material components to docs.

#### What is the motivation / use case for changing the behavior?

- bootstrap will be deprecated in favor of ngModules.
- Material directives will soon be deprecated in favor of ngModules.
- Need for new material components (menu, tooltip, button-toggle).
- Use new forms API for ngModules.
- Breaking changes on testing setup.

##### Other information
https://github.com/angular/angular/blob/master/CHANGELOG.md#200-rc5-2016-08-09
https://github.com/angular/material2/releases/tag/2.0.0-alpha.7

**Comment by kyleledbetter** [comment]
Yisss

**Comment by Daeluse** [comment]
I would also like to note that the following line:

`moduleId: module.id`

Located in most Component decorators causes errors with WebPack builds as the compiler now expects moduleId to be a string, and not a number. The quick solution is to omit these, and it does not seem to cause any consequences, however it may cause hierarchical issues with systemjs environments.

**Comment by emoralesb05** [comment]
Making the upgrade all the way to rc6 and alpha-8.1 material

**Comment by emoralesb05** [comment]
Closed with https://github.com/Teradata/covalent/pull/37. Still lots of things to do, but its the baseline for the upgrade.
