### ISSUE TITLE
Data table rows don't always display with pagination and searching

### ISSUE THREAD

**Issue by jraadt** [Teradata/covalent#366]
#### Bug Report

With pagination enabled on a data table, if you page and then start searching and it returns less items that can fit on a page, it says there are no results.  But there are just no results on the page you currently are on.  It should flip you back to page 1 so you can see your search results.

To reproduce:
1) Go to the following quickstart: https://teradata.github.io/covalent-quickstart/#/product/stats
2) In the Product Stats table sort the product table in ascending order.
3) Page to the 2nd page.
4) Search for Logs.
5) It says there are no results, but the results are on page 1.  Confusing for the end user.

**Comment by emoralesb05** [comment]
Can you open this issue in the https://github.com/Teradata/covalent-quickstart repo please?

**Comment by jraadt** [comment]
Sure, but I was just using the quickstart as an example to replicate the issue.  I believe it's still an issue overall for the Covalent framework.  Shouldn't filtering for tables automatically take you back to page 1 if the table is paged?

**Comment by emoralesb05** [comment]
Well, depends. The table is agnostic of pagination, thats one of the reasons we abstracted it. 

The data-table doesnt know how many pages there are or how many rows, it only knows what you provide to show. Thats a validation you need to implement on your side.
