### ISSUE TITLE
data table generate two <thead> if wrap <th> with <tr>

### ISSUE THREAD

**Issue by naiteluo** [Teradata/covalent#368]
*Bug Report*

Here is the plunker [http://plnkr.co/edit/z7q95CaeC1BTtET7uT2t?p=preview](http://plnkr.co/edit/z7q95CaeC1BTtET7uT2t?p=preview)

data table will generate two `<thead>` if wrap `<th>` with `<tr>`. And i think it is more standard to write `table` with full syntax.

this is how i wrote, and i got double `thead` in my page:

```html
<table td-data-table>
  <!-- wrap th with tr -->
  <tr >
    <th td-data-table-column>name</th>
    <th td-data-table-column>tag</th>
    <th td-data-table-column>operations</th>
  </tr>
  <tr td-data-table-row *ngFor="let catalog of catalogs">
    <td td-data-table-cell>{{catalog.name}}</td>
    <td td-data-table-cell>{{catalog.tag}}</td>
    <td td-data-table-cell>
      <button type="button" class="btn btn-info">detail</button>
      <button type="button" class="btn btn-danger">delete</button>
    </td>
  </tr>
</table>
```

![image](https://cloud.githubusercontent.com/assets/705655/23244797/c9813ce2-f9c2-11e6-8718-8222f366bad8.png)

this is the way official doc wrote, it works well

```html
<table td-data-table>

    <th td-data-table-column>name</th>
    <th td-data-table-column>tag</th>
    <th td-data-table-column>operations</th>

  <tr td-data-table-row *ngFor="let catalog of catalogs">
    <td td-data-table-cell>{{catalog.name}}</td>
    <td td-data-table-cell>{{catalog.tag}}</td>
    <td td-data-table-cell>
      <button type="button" class="btn btn-info">detail</button>
      <button type="button" class="btn btn-danger">delete</button>
    </td>
  </tr>
</table>
```

**Comment by naiteluo** [comment]
i am using covalent `1.0.0-beta.1-1`

**Comment by emoralesb05** [comment]
Thanks for the heads up. We are gonna focus `beta.3` on improving `data-table`.

So this will be up for discussion.

**Comment by emoralesb05** [comment]
Closing this since now you have to add the header row explicitly since beta.7.
