### ISSUE TITLE
Enhancement/Bug? Ability to set selected rows on Initial Load

### ISSUE THREAD

**Issue by asaph26** [Teradata/covalent#370]
Currently using ngModel, it is not possible to select the rows in a data-table on initial load. This works if you hover over the header row of the data table or if you interact with the table in any way.

Plunker repo: http://plnkr.co/edit/Et3iXNKrf4qveendOfF1

This was originally identified by @akrepon

**Comment by emoralesb05** [comment]
Thanks!

Possible fix with https://github.com/Teradata/covalent/pull/371.

But also there is a need to call `refresh` method in those cases.

**Comment by kyleledbetter** [comment]
closes at it looks fixed on our end, pls reopen if you still see it after updating to beta2
