### ISSUE TITLE
Data Table - Programmatically selection

### ISSUE THREAD

**Issue by maku** [Teradata/covalent#383]
I have the need to show already selected rows. 
To accomplish this, the "hacky" way seems to be to get the TdDataTableComponent instance and set the "value" member.

```
 @ViewChild(TdDataTableComponent)
  tableComponent: TdDataTableComponent;

 ...
   setAlreadySelectedItems(items: Object[]) {
          this.tableComponent.value = items;
   }
```

Is there a better way to do this?

**Comment by emoralesb05** [comment]
You can leverage `[(ngModel)]` to pre-select the rows the same way.

**Comment by maalquin** [comment]
I have a question how I can reset the rows selected.
Thanks.

**Comment by jeremysmartt** [comment]
@maalquin You can still leverage `[(ngModel)]` for that as well.  Whatever you set for the array in ngModel is what is going to be selected in the rows.

**Comment by Abhijeetkdev** [comment]
@emoralesb05 
Please post an example in plunkr or any other editor online i want the checkbox to be checked when i set the values to the ngmodel .

**Comment by uralovs** [comment]
Do make sure that you implement "compareWith" method to compare your rows by some property, otherwise UI may not select your programmatically selected rows correctly

**Comment by maalquin** [comment]
I've an example https://plnkr.co/edit/VC7oPf?p=preview   my Question is how access to DataTable because in my example I added one method for verify if selectedRow array is filled however it doesn't.

Thanks.

**Comment by jeremysmartt** [comment]
If still having an issue please ask question in gitter channel
