### ISSUE TITLE
SearchDebounce event fired on page load

### ISSUE THREAD

**Issue by agpreynolds** [Teradata/covalent#385]
This repository's issues are reserved for feature requests and bug reports.

### Do you want to request a *feature* or report a *bug*?

Bug

#### Bug Report

When using the 'td-search-input' component the 'searchDebounce' event is fired on page load after the number of milliseconds described in the debounce property.

The consequence of this is the event handler attempts to filter my data before it has loaded.

##### Screenshots or link to CodePen/Plunker/JSfiddle

N/A

#### What is the expected behavior?

The searchDebounce event would only be fired once an action has been performed on the input, e.g. keydown, keyup, etc

#### Which version of Angular and Material, and which browser and OS does this issue affect?

Angular: 2.4.0
Material: 2.0.0-beta.2
Covalent: 1.0.0-beta.2

##### Other information

Looking at the source I think the issue is related to the onInit function in:
https://github.com/Teradata/covalent/blob/64ff1100af2983709205833de5900fd3b33076ab/src/platform/core/search/search-input/search-input.component.ts

I think adding distinctUntilChanged here may be the solution, however I haven't managed to test this out yet

**Comment by emoralesb05** [comment]
Thanks for the heads up. We had somebody mentioned this before, so we will try and fix it for the next release. 😄

**Comment by emoralesb05** [comment]
Fixed and will be released in `beta.3`
