### ISSUE TITLE
[Feature] Upgrade to @angular@4.0.0 when stable.

### ISSUE THREAD

**Issue by emoralesb05** [Teradata/covalent#393]
#### Feature Request

We are going to have to make a though call when `4.0.0` is stable because its going to be hard to support `2.X` and `4.X` in the same release.

Either we branch off and support both versions for 1-2 releases (which will be a pain), or just go full on steam ahead with `4.0.0` since we are trying to be cutting edge.. which i am more inclined to do so since `4.0.0` has significant performance enhancements and code reduction.

Note: since we heavily depend on `material` we should see how the handle it too.

**Comment by emoralesb05** [comment]
Some things to look out for:

- [ ] `OpaqueToken` is deprecated.
- [ ] `<template>` is deprecated.
- [ ] `@angular/animations` have been abstracted into their own module.

**Comment by daBishMan** [comment]
4.0.0 release only... the upgrade from 2 to 4 is simple especially with the CLI.

**Comment by jdat82** [comment]
I agree with @daBishMan.

**Comment by lebsral** [comment]
+1 for quick clean upgrade to 4.
