### ISSUE TITLE
Horizontal mode of stepper in Interner Explorer

### ISSUE THREAD

**Issue by anapanadero** [Teradata/covalent#394]
### Bug

Horizontal mode of stepper doesn't work in Internet Explorer 11. I can only see the horizontal line without icons or information.

![stepper](https://cloud.githubusercontent.com/assets/8911984/23405503/cf5af2ba-fdba-11e6-911b-bd1ae2ab2861.png)

**Comment by aciccarello** [comment]
Might be a flexbox issue
https://github.com/Teradata/covalent#browser-support

**Comment by richavyas** [comment]
Yes, we support what flexbox supports hence following is Covalent's browsers support:

![Uploading browser-support.png…]()
