### ISSUE TITLE
Styling of component-expansion panel

### ISSUE THREAD

**Issue by shubhijain106** [Teradata/covalent#398]
I am new to Angular was experimenting with expansion-panel component. I want to add keyboard_key_down arrow that toggles in a custom header for expansion panel.

im using the below template:
template td-expansion-panel-header

**Comment by emoralesb05** [comment]
So you can add anything inside there, so you just need to do this:

```
<template td-expansion-panel-header>
  <div layout="row" flex>
  <span>Label</span>
  <span flex></span>
  <md-icon>keyboard_key_down</md-icon>
  </div>
</template>
```

Or something around that. Its basically on you at that point 😄 

You can even change the icon depending if its open or not, etc etc.

**Comment by kyleledbetter** [comment]
Closing since we have the feature and not an issue
