### ISSUE TITLE
Feature Request - data-table - specify date format in column declaration

### ISSUE THREAD

**Issue by agpreynolds** [Teradata/covalent#403]
This repository's issues are reserved for feature requests and bug reports.

### Do you want to request a *feature* or report a *bug*?

Feature

#### Feature Request

Would it be possible to add the functionality to specify a date format when declaring columns for the data-table component?

I'm thinking something along the lines of:

```
columns: ITdDataTableColumn[] = [
    { name: 'startDate', label: 'Start Date', date: true, format: 'yyyy/mm/dd' },
  ];
```

This would then result in the column cell values being piped to the specified date format.

Apologies if this functionality is already possible through the API, I did notice there is a format field already available but I can't figure out what it does.

**Comment by emoralesb05** [comment]
Hey @agpreynolds 
So the `format` property does exactly what you want to do, it passes in the value and you return the value that you want displayed for that column.

```
columns: ITdDataTableColumn[] = [
    { name: 'startDate', label: 'Start Date', date: true, format: (value) => { return formatToSomething(value)} },
  ];
```

The reason we did it this way is to have the `data-table` agnostic of formats, and have devs provide their own formatting implementation.

**Comment by emoralesb05** [comment]
We are gonna add more examples to show how you can leverage fully the data-table + more enhancements for `beta.3` 😄

**Comment by agpreynolds** [comment]
Ahh I see, thanks for clearing that up

**Comment by rbj325** [comment]
It's cool you have this implemented and this issue should be closed.  Also this is easily doable using a pipe, and therefore reusable in your project, if the excess code becomes burdensome.

**Comment by emoralesb05** [comment]
yup, closing this since you can use the format property or a template cell.
