### ISSUE TITLE
Make @Covalent/core strict null checks compliant.

### ISSUE THREAD

**Issue by kamalbabu57** [Teradata/covalent#404]
#### Feature Request /Bug

Can we have covalent compliant with the --strictNullChecks option of the typescript transpiler?
Currently we have to work around the issue by commenting out strictNullChecks

#### What is the expected behavior?
Should have no issues with --strictNullChecks enabled

#### What is the current behavior?
node_modules\@covalent\core\common\animations\fade\fade.directive.ts:70:12 
    Type 'true | undefined' is not assignable to type 'boolean'.
  Type 'undefined' is not assignable to type 'boolean'.
 node_modules\@covalent\core\common\animations\fade\fade.directive.ts:85:45 
    Argument of type 'undefined' is not assignable to parameter of type 'AnimationStyles'.
node_modules\@covalent\core\common\animations\fade\fade.directive.ts:122:45 
    Argument of type 'undefined' is not assignable to parameter of type 'AnimationStyles'.
node_modules\@covalent\core\common\animations\toggle\toggle.directive.ts:56:12 
    Type 'true | undefined' is not assignable to type 'boolean'.
  Type 'undefined' is not assignable to type 'boolean'.
node_modules\@covalent\core\dialogs\services\dialog.service.ts:69:5 
    Type 'string | undefined' is not assignable to type 'string'.
  Type 'undefined' is not assignable to type 'string'.

#### What is the motivation / use case for changing the behavior?
Enforcing good coding practices.

#### Which version of Angular and Material, and which browser and OS does this issue affect?
` "@angular/material": "2.0.0-beta.1",`
` "@covalent/core": "1.0.0-beta.1-1"`

#### What are the steps to reproduce?
Build an angular app with covalent version 1.0.0-beta.1-1 .
Set --strictNullChecksto true in tsconfig.json

**Comment by emoralesb05** [comment]
This shouldnt be an issue in `beta.2` since we stopped publishing the `ts` files.

**Comment by emoralesb05** [comment]
Closing this since `beta.2` doesnt have the `ts` files anymore
