### ISSUE TITLE
The Search Box component now has a vertical scrollbar

### ISSUE THREAD

**Issue by bengwall** [Teradata/covalent#412]
### Bug

The Search Box component now has a vertical scrollbar.  

You can see it when clicking the search icon in the Search Box example on the demo page:
[https://teradata.github.io/covalent/#/components/search](https://teradata.github.io/covalent/#/components/search)

**Comment by emoralesb05** [comment]
Can you please provide more info? OS, Browser , etc etc

**Comment by bengwall** [comment]
Sure Ed.  Sorry about that.  I've tested on Chrome 55 on Mac and Chrome 56 on Windows 7.  Both show the vertical scrollbar.  Here's a screenshot.

![image](https://cloud.githubusercontent.com/assets/4481748/23753259/5d280cb0-049e-11e7-9bb5-8486d46185a5.png)

**Comment by kyleledbetter** [comment]
Snap i never noticed this w/ the transparent mac scrollbar, thanks for reporting!

**Comment by bengwall** [comment]
Your bet.  Very nice work with all of this to everyone involved.

**Comment by emoralesb05** [comment]
Huh, never noticed either haha thanks for the heads up! i thought it was an `edge` issue for some reason, but now i see its on every browser. 👀

**Comment by plastikaweb** [comment]
Anyway until it is fixed, how could component styles be overwritten with a rule like this?: 
```
.td-search-input {
  height: 75px;
}
```
Thanks for the excellent work!
