### ISSUE TITLE
Failed to load resource: the server responded with a status of 404 (Not Found)

### ISSUE THREAD

**Issue by WebTalentTop** [Teradata/covalent#417]
Hi, I love Covalent so much.
When I tried to install to my local side, I have got an issue now.
http://localhost:3000/@covalent/charts 
Failed to load resource: the server responded with a status of 404 (Not Found).

I have installed all you mentioned. 
Node 6.9+
NPM 3+
Angular CLI
Protractor (for testing)
TSLint (for code style)

Please help me!

**Comment by WebTalentTop** [comment]
I have fixed it showing errors on my own but I can't get any result now.
systemjs.config.js
'@swimlane/ngx-charts': 'https://npmcdn.com/@swimlane/ngx-charts',
I have added this at that file.
And at main ts file.
import {NgxChartsModule} from '@swimlane/ngx-charts';

Why can't I see any result?

**Comment by kyleledbetter** [comment]
Hi @WebTalentTop glad you're enjoying Covalent!

We're retiring our charts in favor of using NGX-Charts

We're recently removed our td-charts from Covalent, are you using the nightly build? https://github.com/Teradata/covalent/pull/376

**Comment by kyleledbetter** [comment]
The quickstart uses ngx-charts, you can reference how we did everything there https://github.com/Teradata/covalent-quickstart

**Comment by WebTalentTop** [comment]
Thanks for your consideration. I really appreciate that.
But actually I like Material Design it provides. What about covalent/core?
And When I tried to integrate ngx-charts, UI can't see any result on my page.
Any tips?

**Comment by WebTalentTop** [comment]
OK...Ngx-chart is pretty fine to use.
