### ISSUE TITLE
data-table customize empty results message

### ISSUE THREAD

**Issue by fernandobandeira** [Teradata/covalent#421]
#### Feature Request

We should be able to change the text displayed when there's no results for a datatable.
[Currently it seems hard coded.](https://github.com/Teradata/covalent/blob/develop/src/platform/core/data-table/data-table.component.html#L46)

#### What is the expected behavior?
Be able to define this text throught a property or something like that.

#### What is the motivation / use case for changing the behavior?
Display a custom localized message when there's no results on the datatable.

**Comment by emoralesb05** [comment]
Part of https://github.com/Teradata/covalent/issues/324
