### ISSUE TITLE
Seed project will not ng serve - invalid angular-cli project

### ISSUE THREAD

**Issue by iceman3000** [Teradata/covalent#424]
#### What is the expected behavior?
To be able to ng serve project

#### What is the motivation / use case for changing the behavior?
To work as documented

#### Which version of Angular and Material, and which browser and OS does this issue affect?
CLI Lateset

##### Other information
Followed instructions exactly as indicated to download the seed project and I get the following error trying to ng serve:

You have to be inside an angular-cli project in order to use the serve command.

**Comment by iceman3000** [comment]
Hi again! I guess the point I was raising here was that following the documentation on how to use the Seed project doesn't work - whether that be changes from angular or covalent, I think that the docs should be accurate in terms of delivering a working product. Again my understanding on how CLI and Packages work is limited, can you please advise what I need to do so that the seed package is recognized as a valid angular-cli package so I may serve it?

ng -v results the following:

angular-cli: 1.0.0-beta.28.3
node: 6.9.1
os: win32 x64
@angular/common: 2.4.9
@angular/compiler: 2.4.9
@angular/core: 2.4.9
@angular/forms: 2.4.9
@angular/http: 2.4.9
@angular/material: 2.0.0-beta.2
@angular/platform-browser: 2.4.9
@angular/platform-browser-dynamic: 2.4.9
@angular/router: 3.4.9
@angular/compiler-cli: 2.4.9

**Comment by asaph26** [comment]
@iceman3000 : As @emoralesb05 mentioned, you are working with an older version of the CLI. The steps to get the latest CLI installed is documented in the CLI repository.

https://github.com/angular/angular-cli#updating-angular-cli

Since you are using a much older version of the CLI, the uninstall step would be different for you. You need to do the following

```bash
npm uninstall -g angular-cli
npm cache clean
npm install -g @angular/cli@latest
```

You should be able to get going after this.

**Comment by iceman3000** [comment]
Thanks again for your help guys, this resolved the issues.
