### ISSUE TITLE
Changing/Modifying a css class in Json Formatter

### ISSUE THREAD

**Issue by swapp1990** [Teradata/covalent#427]
I want to make a very small change to the css class of '.td-json-formatter-wrapper'. Basically this is what I want to change:
` .td-json-formatter-wrapper .value .string {word-break: break-word;}` change to this:
` .td-json-formatter-wrapper .value .string {word-break: normal;}`

Is there any way I can change this in my directive something like this:

`
styles: [` :host /deep/ .td-json-formatter-wrapper .value .string {
        word-break: normal; 
      }
  `],
  template: `
      <td-json-formatter [data]="jsonObject" [levelsOpen]="1" (click)="onClick()">
      </td-json-formatter>
    `,
`
I tried using '/deep/' or '>>>' to override but it's not working.

Thanks

**Comment by emoralesb05** [comment]
You can should be able to override it with `/deep/` from your `component.scss` as 

```
:host /deep/ {
  .td-json-formatter-wrapper .value .string {word-break: normal;}
}
```

Hope this helps.

**Comment by emoralesb05** [comment]
Closing since there isnt any activity and its more of a question than issue.
