### ISSUE TITLE
Rendering issue on menu bar and other elements

### ISSUE THREAD

**Issue by victorboissiere** [Teradata/covalent#436]
## Bug Report

My team and I are having issue getting covalent to work especially with some components like the default toolbar with search. I have checked everything including the scss imports and component imports but nothing seems to work. 

## Screenshot

![selection_025](https://cloud.githubusercontent.com/assets/4125799/24196940/f1a78f08-0eff-11e7-8775-71dfc17832aa.png)

## What is the expected behavior?

![selection_026](https://cloud.githubusercontent.com/assets/4125799/24196980/104fccfe-0f00-11e7-830d-e55e288d739e.png)

# Versions
Angular : 2.4.0
Material : 2.0.0-beta.2
Covalent : 1.0.0-beta.2-1

Web Browser : Google Chrome 57 and Mozilla Firefox 52
OS: Ubuntu 16.04

# Steps to reproduce

I have made a github project using angular-cli with a clean configuration and I just added the toolbar html code found on the covalent documentation as well as adding all needed imports. The html toolbar content is inside `src/app/app.component.html`.

Link : https://github.com/victorboissiere/covalent-issue

**Comment by asaph26** [comment]
@victorboissiere You need to include the @covalent styles in your angular-cli.json under styles

`"../node_modules/@covalent/core/common/platform.css"`

The reason everything breaks is because @covalent uses flexbox styles that are included in the platform.css

This is mentioned in the getting started guide in the bottom
https://github.com/Teradata/covalent/blob/develop/docs/GETTING_STARTED.md#using-platformscss

**Comment by victorboissiere** [comment]
Thank you so much. It fixed the problem. It is unfortunate still that it is not present in the getting started from the online documentation : https://teradata.github.io/covalent/#/docs or style guide.
Thanks

**Comment by emoralesb05** [comment]
Adding `FAQS` label

**Comment by ashishbaghudana** [comment]
I'm facing a somewhat similar issue where all the text in my toolbar is not vertical center aligned. 

![IMG](https://preview.ibb.co/ipjfFk/Screen_Shot_2017_04_28_at_4_05_50_PM.png)

I've included `platform.css` in `.angular-cli.json`. What might be causing this issue?

**Comment by asaph26** [comment]
Are you running the app in IE11?
