### ISSUE TITLE
Issue with node-sass

### ISSUE THREAD

**Issue by akansharaut** [Teradata/covalent#440]
I have cloned this repo and followed all the steps given in readme.md, but got issue with node sass, which is some packages are missing like vender.

Reason for this issue is that some binaries need to be (re-)compiled to target the version of Node that you're using.

#### https://docs.npmjs.com/cli/rebuild

I assume that this will trigger a build-script something like a Make file for the package (node-sass) so that the new binary targets Node correctly.

**Comment by istvanszoboszlai** [comment]
I do now know what the exact problem can be, but I remembered reading about node sass being sometimes a problem for angular-cli.
Look here: https://github.com/angular/angular-cli/blob/master/CHANGELOG.md#100-rc4-2017-03-20

Maybe this can help.

**Comment by emoralesb05** [comment]
Closing this since its not a covalent issue and there hasnt been any activity.
