### ISSUE TITLE
Missing documentation for ngModel property in td-data-table

### ISSUE THREAD

**Issue by jotatoledo** [Teradata/covalent#441]
Hi,

I noticed that there is no documentation/information about the `[(ngModel)]` property. One of the examples on the website (the one with the 3 toggle options) uses this property, but the code snippet doesnt show the binding. I had to take a look on the github repository to find out how the `selectedRows` was being filled with data.

Extract from the example:

`<td-data-table
          [data]="filteredData"
          [columns]="columns"
          [selectable]="selectable"
          [multiple]="multiple"
          [sortable]="true"
          [sortBy]="sortBy"
          [(ngModel)]="selectedRows"
          [sortOrder]="sortOrder"
          (sortChange)="sort($event)">
        </td-data-table>`

Listed properties on the website:

```
<td-data-table
  [data]="data"
  [columns]="columns"
  [selectable]="true|false"
  [multiple]="true|false"
  [sortable]="true|false"
  [sortBy]="sortBy"
  [sortOrder]="'ASC'|'DESC'"
  (sortChange)="sortEvent($event)"
  (rowSelect)="selectEvent($event)"
  (selectAll)="selectAllEvent($event)">
</td-data-table>
```

**Comment by Ludevik** [comment]
I did exactly same thing today. The code part for that example doesn't match what we see on demo tab.
