### ISSUE TITLE
[feat req] Manage reactive data from the Data Table Service

### ISSUE THREAD

**Issue by michaeljota** [Teradata/covalent#442]
### Do you want to request a *feature* or report a *bug*?

*feature*

#### Feature Request

I like the Data Table Service to have common filtering and sorting functions, but I don't like the fact that those 3 functions aren't chainable. So I propose to use reactive data for the service to deliver the filter data. This could have some potencial benefits. 

#### What is the expected behavior?

To return an `observable` from data table service, instead of an object array, 

#### What is the motivation / use case for changing the behavior?

Better handle of the objects.

#### Which version of Angular and Material, and which browser and OS does this issue affect?

Did this work in previous versions of Angular / Material?
Please also test with the latest stable and snapshot versions.

##### Other information
(e.g. detailed explanation, stacktraces, related issues, suggestions how to fix)

**Comment by jdrew1303** [comment]
Hi @michaeljota 

Its currently possible to do this as it currently stands.


We declare the values we want to make available to the template. 
```typescript
public searchTerm = new Subject<string>();
public filteredItems: Observable<Item[]>;
public items: Observable<Item[]>;
```

In here we can join the different events together. We could add more subjects in for sorting and for paging. We would need to create a withLatestFrom for each of the input streams but the function it consumes could be factored out into a function that does the work and anther wrapper that calls it but changes the arg positions as necessary. This would give you Observables all the way through.

[The docs for withLatestFrom.](http://reactivex.io/rxjs/class/es6/Observable.js~Observable.html#instance-method-withLatestFrom)
```typescript
// usually put this in the onInit or afterInit block.
const search: (searchTerm: string, items: Item[]) => Item[] = buildSearch<Item>(['question', 'answer'], 'id');
this.items = this.itemService.getItems();
this.filteredItems = this.searchTerm.withLatestFrom(this.items, search);
```

Then in our template we can subscribe to the event like so: 
```html
<td-search-box (searchDebounce)="searchTerm.next($event)"></td-search-box>
```
Its not perfect but it makes the flows a lot easier to reason about. Hope this helps!! 👍

**Comment by emoralesb05** [comment]
closing since a solution was provided
