### ISSUE TITLE
[Data-Table] Component API vs Directive API

### ISSUE THREAD

**Issue by michaeljota** [Teradata/covalent#443]
# Update 2

I'm open this again, cause it's related to the division of the API. I don't get how to do the same I do with the component API with the directive API. The lastes is having some missing attributes that I don't know how to substitute them. I want to use the sort functionality, but I don't know how to set them with the directive, as I'm using additional cells that are not part of the data grid.

## Update
Sorry, I'm blind or something. This is already implemented, I saw the right docs. Closing. Thanks you. 

### Original (_Separate table headers from table body (or an alternative)_)

> ### Do you want to request a *feature* or report a *bug*?
> 
> *feature*
> 
> #### Feature Request
> 
> I think it would be nice to have a table header API and a table body API, to make custom tables. This would allow to use custom cells, like a `photo fab button` or something that's not a string or a numeric. I think the current approach it's great as is, so I'm thinking this could be just another API, using as much as posible from the current one.

**Comment by jotatoledo** [comment]
Close? @emoralesb05

**Comment by emoralesb05** [comment]
The atomic design is just for styling, its not really gonna add behavior.

We are currently thinking of ways to improve our data-table to solve most of the people's needs.

**Comment by michaeljota** [comment]
Thanks.
