### ISSUE TITLE
Use SCSS without webpack

### ISSUE THREAD

**Issue by DaSchTour** [Teradata/covalent#446]
#### Feature Request

On my current project we use gulp for build tasks and JSPM for package management and loading. Now we wanted to shift to angular material and covalent. Using the components works great and they are the best currently available. But now as we make the step from the prototype to a shippable version we need some changes to the style. So we wanted to remove a compiled CSS and use the SCSS. But it turned out that this seams to be very hard coupled to using webpack as it uses non-standard import paths. Which was one of the main reasons we didn't use webpack, because webpack introduces a lot of opinionated non-standard behavior and creates a lock-in effect like with proprietary software which than is hard to remove from the code and I really don't want to code according to the style of my module loader.

So that's just for the background. I think with include path SCSS already has solutions for problems solved here in a non-standard way. I really would like to encourage usage of SCSS that isn't tightly coupled to webpack and that can also be included in normal build processes.

**Comment by emoralesb05** [comment]
I agree, there are always lots of people having issues around the `scss` files outside of webpack because this is coupled to the way `sass-loader` works.

**Comment by kombadzomba** [comment]
I've [forked](https://github.com/kombadzomba/covalent) current master (1.0.0-beta.2) and replaced ~ with relative references so we could use it without webpack in our meteor project. npm package name for that is [@enelit/covalent-core](https://www.npmjs.com/package/@enelit/covalent-core) equivalent of @covalent/core.

**Comment by emoralesb05** [comment]
will be fixed in https://github.com/Teradata/covalent/pull/482
