### ISSUE TITLE
npm run build fails at rollup inline step

### ISSUE THREAD

**Issue by ajitsonlion** [Teradata/covalent#447]
#### Bug

npm run build fails to compile the packages in platform 

#### Bug Report

Resources inlined...
[14:15:04] Using gulpfile ~/code/covalent/gulpfile.js
[14:15:04] Starting 'rollup-code'...
[14:15:04] 'rollup-code' errored after 3.57 ms
[14:15:04] Error: Could not resolve entry (deploy/platform/core/index.js)
    at /home/ajit/code/covalent/node_modules/rollup/dist/rollup.js:8544:28
    at process._tickCallback (internal/process/next_tick.js:103:7)
    at Module.runMain (module.js:607:11)
    at run (bootstrap_node.js:418:7)
    at startup (bootstrap_node.js:139:9)
    at bootstrap_node.js:533:3

npm ERR! Linux 4.8.0-39-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "build"
npm ERR! node v7.5.0
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE
npm ERR! covalent@1.0.0-beta.2-1 build: `bash scripts/build-release`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the covalent@1.0.0-beta.2-1 build script 'bash scripts/build-release'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the covalent package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     bash scripts/build-release
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs covalent
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls covalent
npm ERR! There is likely additional logging output above.

#### What is the motivation / use case for changing the behavior?

Trying to use covalent setup to write own component library.

#### Which version of Angular and Material, and which browser and OS does this issue affect?

Ubuntu 16.10
after the 4.0 merge into master, this error occurs.
https://github.com/Teradata/covalent/pull/429

##### Other information
  https://github.com/oasisdigital/rollup-plugin-node-resolve-angular

**Comment by emoralesb05** [comment]
Yep, aware of this. I wanted to split up the upgrade into 3 PR's.

The first was to just merge angular 4
The second one will be to fix this issue
and the third one to upgrade to latest material.

**Comment by emoralesb05** [comment]
Fixed with https://github.com/Teradata/covalent/pull/448
