### ISSUE TITLE
Sass import module resolution of ~ fails

### ISSUE THREAD

**Issue by Maccodonaldo** [Teradata/covalent#450]
#### Bug Report
When importing the CovalentCoreModule the sass import module resolution does not work correctly.
 
```
sass: node_modules/@covalent/core/chips/_chips-theme.scss, line: 1 
            File to import not found or unreadable: ~@angular/material/core/theming/theming. Parent style sheet: 
            /home/user/project/node_modules/@covalent/core/chips/_chips-theme.scss 

       L1:  @import '~@angular/material/core/theming/theming';
       L2:  @import '~@angular/material/core/style/variables';

 sass failed 
```
##### Other information
Using the Ionic CLI not the angular cli, this is probably a webpack config issue, but maybe you can provide some more configuration details.

Can be resolved by replacing `~` with `node_modules/`

**Comment by lgleim** [comment]
This is most likely a gereal issue of the way the ionic-app-scripts handle sass compilation. I created a corresponding bug report at https://github.com/driftyco/ionic-app-scripts/issues/847

**Comment by emoralesb05** [comment]
For now, the work around would be to use `node-sass` to compile the files with a custom importer and then include it.

e.g.

scripts/sass-importer.js
```
var path = require("path");

module.exports = function sassImporter(url, prev, done) {
  if (url.indexOf('~') === 0) {
    url = 'node_modules/' + url.substring(1, url.length);
    return {file: path.relative(path.dirname(prev), url)};
  }
  return {file: url};
}
```

And then `node-sass --importer scripts/sass-importer.js src/theme.scss src/theme.css`

This is what `sass-loader` basically does under the covers.

**Comment by emoralesb05** [comment]
will be fixed in https://github.com/Teradata/covalent/pull/482
