### ISSUE TITLE
Expandable in not including the flex layout settings when using Angular Cli

### ISSUE THREAD

**Issue by pdjota** [Teradata/covalent#451]
This repository's issues are reserved for feature requests and bug reports.

### Do you want to request a *feature* or report a *bug*?
bug

#### Bug Report
After generating a new project, the flex layout classes are not applied to the application. I cannot replicated in PLUNKr, I created a github repo and attached a screenshot.

##### Screenshots or link to CodePen/Plunker/JSfiddle
https://github.com/pdjota/covalentappexample
https://github.com/pdjota/covalentappexample/blob/master/application%20screenshot.png
Plunkr works:
http://plnkr.co/edit/xHgweLDfj8XM05xsuuJq?p=preview

#### What is the expected behavior?
- Generate application with Angular Client
- Install Covalent Core
- After installing include the styles as in doc.
- Component, such as Expandable will have the flex layout

#### Which version of Angular and Material, and which browser and OS does this issue affect?
"@covalent/core": "1.0.0-beta.2"
"@angular/material": "2.0.0-beta.2"
"@angular/common": "2.4.8"

Did this work in previous versions of Angular / Material?
2.4.10
Not tested with Material beta.1

##### Other information
May be related to the dependencies of Covalent, here is the entire npm ls:
https://gist.github.com/pdjota/b9cf7decb7117cb7ec17f0bb20a50fea

**Comment by asaph26** [comment]
You need to include the covalent platform styles in the .angular-cli.json file. 

More details here
https://github.com/Teradata/covalent/issues/436#issuecomment-288412639

**Comment by pdjota** [comment]
thanks @asaph26 . It is kind of unexpected, i.e.: when you install material without covalent, you only need to do the imports in the CSS and module loading, similar to what is pointed here: https://github.com/Teradata/covalent/blob/develop/docs/GETTING_STARTED.md#include-the-core-and-theme-styles

Why do you need to include the CSS itself instead of providing the SASS so it could be referenced in the styles.css?
Eg: 
`
@import '~@angular/material/core/theming/all-theme';
@import '~@covalent/core/theming/all-theme';
@import 'variables';

@include mat-core();
$theme: mat-light-theme($primary, $accent);

@include angular-material-theme($theme);
@include covalent-theme($theme);`
