### ISSUE TITLE
sort for tables not working with date strings

### ISSUE THREAD

**Issue by pascalwhoop** [Teradata/covalent#461]
#### Bug Report

calling sortData on TdDataTableService with sorting field being a date doesn't work as expected

#### What is the expected behavior?
sorting date should sort the dates. But the line
`if (!Number.isNaN(Number.parseFloat(compA)) && !Number.isNaN(Number.parseFloat(compB)))`

causes Problems. This is beacuse `Number.parseFloat("2018-05-14T00:00:00.000Z")` returns a number. 2018

#### What is the motivation / use case for changing the behavior?
Dates should be sorted properly

**Comment by akomarovsky** [comment]
was it fixed? I see that in version 1.0.0-beta.3-1 it is still an issue

**Comment by pascalwhoop** [comment]
No it wasn't fixed but there is no clean way of sorting this without being really careful what you do. I suggested including moment.js but the repo admins don't agree that's a good idea yet so I don't have a good idea at the moment. Doing some sketchy Regex on strings is not a smart move.

**Comment by emoralesb05** [comment]
We are trying to avoid adding external dependencies to reduce the bundle size. Unless the dependency is used heavily in the project, its not really worth it. We want to be able to fix this without it if possible.

That being said, you can always pull `moment.js` on your project and use it.

**Comment by michael-lang** [comment]
Can you just do a custom sort?  See code snippet in #521

**Comment by pascalwhoop** [comment]
Yes of course it's possible to get my date strings sorted manually. And although we shouldn't expect covalent to figure out for us what the string means, a date string is so common it would be nice. The real problem however is that it currently(is it still current?) interprets a date string as a number which becomes the year of the date. That is not correct. I can't look into the code base ATM, I'm on mobile. 

I think best would be to rethink the interpretation of what is a number and leave the date handling out until either moment.js is included or someone finds a solid well proven way of determining strings being ISO date strings or not.

**Comment by ankita3076** [comment]
Hi, 
I am able to sort data manually, but the problem is when I am clicking on pagination, all the sorting has gone. Can anyone help me in that.

**Comment by Vasanthvivi** [comment]
> We are trying to avoid adding external dependencies to reduce the bundle size. Unless the dependency is used heavily in the project, its not really worth it. We want to be able to fix this without it if possible.
> 
> That being said, you can always pull `moment.js` on your project and use it.

any other thing other than moment?
