### ISSUE TITLE
Show list of possible chips by just pressing space

### ISSUE THREAD

**Issue by lebsral** [Teradata/covalent#465]
Feature
#### Feature Request

When seeing possibilities in the drop down of an autocomplete chip make the space key reveal all of the possibilities instead of just the ones that contain a space.

#### What is the expected behavior?
currently hitting just space shows only...
'need more?'
Because that is the only example chip that has a space in it.

Instead the chip suggestion after hitting space should be...
    'stepper',
    'expansion-panel',
    'markdown',
    'highlight',
    'loading',
    'media',
    'chips',
    'http',
    'json-formatter',
    'pipes',
    'need more?',

#### What is the motivation / use case for changing the behavior?
Because we want to display all the possible choices to the user, sometimes they can't remember them, and they end up typing different letters trying to get the right choice to come up.  Space should cause them all to appear.

Did this work in previous versions of Angular / Material?
I don't think so.

**Comment by emoralesb05** [comment]
All the possibilities are shown now with https://github.com/Teradata/covalent/pull/459 since we replaced the native `datalist` with `md-autocomplete`

**Comment by lebsral** [comment]
Ok sounds great.  Any knowledge of a release date on that?

**Comment by emoralesb05** [comment]
When material releases `beta.3` we will release ours since we need to merge this PR first https://github.com/Teradata/covalent/pull/464

**Comment by emoralesb05** [comment]
Closing this since the new chips `a11y` has been merged
