### ISSUE TITLE
onclick event on datatable

### ISSUE THREAD

**Issue by hengkyz** [Teradata/covalent#468]
This repository's issues are reserved for feature requests and bug reports.

### Do you want to request a *feature* or report a *bug*?
Request a feature
#### Feature Request
onclick event in datatable row
this onclick event different with onselect row
because we need this event for show the detail of the row
example:
when we click the row we navigate to the form data which is display the data based on the row we click, 
this event is different from onselect, because we need onselect event too, to do some action

**Comment by elmartino** [comment]
+1 for clickable rows

**Comment by hengkyz** [comment]
hi @emoralesb05 sorry just want to ask,
any rough estimation when the rc 4 will be released?

**Comment by emoralesb05** [comment]
@hengkyz no prob 😄 . Probably a few days after material beta.4 .

We are adding some bug fixes and small enhancements in the meantime.
