### ISSUE TITLE
TdExpansionPanelComponent  not work

### ISSUE THREAD

**Issue by laoergege** [Teradata/covalent#469]
I wrote it according to the document，but it is not work。
This is my  main code:
```
<td-expansion-panel expend="expend">
  Hello
</td-expansion-panel>
```
```
export class MenuItemComponent implements OnInit {

  @ViewChild(TdExpansionPanelComponent)
  expansionPanel: TdExpansionPanelComponent;
  
  expend: boolean;

  constructor() { }

  ngOnInit() {
   this.expend = false;
   console.log(this.expansionPanel.expand)
  }
  
  expandedEvent(): void {
    
  }

  collapsedEvent(): void {
    
  }
  
}
```
```
import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { MenuComponent } from './menu/menu.component';
import { MenuItemComponent } from './menu-item/menu-item.component';
import { CovalentExpansionPanelModule } from '@covalent/core';
import { MdListModule } from '@angular/material';
import { CovalentCoreModule } from '@covalent/core';

@NgModule({
  imports: [
    CommonModule,
    CovalentExpansionPanelModule.forRoot(),
    MdListModule
  ],
  declarations: [MenuComponent, MenuItemComponent]
})
export class MenuModule { }
```

**Comment by asaph26** [comment]
@laoergege : The best place for this question is the gitter channel.

The property is **expand** and not **expend** in the template.

**Comment by laoergege** [comment]
@asaph26 haha，I am very sorry. I am a Chinese student, my English is a bit worse. But I am still no effect after the change

**Comment by asaph26** [comment]
It is hard to answer this question just by looking at the code you posted.
Have you included the styles? 
Are there any errors in the console?

**Comment by laoergege** [comment]
what styles? No errors in the console.

**Comment by asaph26** [comment]
https://github.com/Teradata/covalent/blob/develop/docs/GETTING_STARTED.md#include-the-core-and-theme-styles

**Comment by laoergege** [comment]
Thank you.It is solves my previous problems,but still does not have to solve the problem now.

**Comment by laoergege** [comment]
I found the correct code with style (style = "height: 0px; overflow: hidden; display: none;"), but my code does not have this style.

**Comment by emoralesb05** [comment]
Not sure i understand why its not working. 

Which angular v are you using?

Also, you need the `platform.css` included too. And you shouldnt need any custom css to make it work.

**Comment by asaph26** [comment]
@laoergege I dont think you need that style. I think that style works if you want to build your own expansion panel with custom animations which is a long way to go.

I will try to create a simple example using angular-cli for you

**Comment by laoergege** [comment]
Thank you！！Please let me know after creating it.

**Comment by laoergege** [comment]
@asaph26 Thank you！！Please let me know after creating it.

**Comment by asaph26** [comment]
Here is a plnkr example http://plnkr.co/edit/GKcmqBC9htoMpZf90QtU

1) As @emoralesb05 you need to include the platform.css file in the .angular-cli.json
2) Property bindings in the components in angular use the [propertyName] = "value" syntax. This could be an error

**Comment by d3viant0ne** [comment]
Should probably be closed, expansion panel works just fine per the supplied documentation.
