### ISSUE TITLE
Template tag is deprecated in Angular 4

### ISSUE THREAD

**Issue by laurenskvh** [Teradata/covalent#470]
This is not a big issue seeing as the code still works fine (besides throwing a warning), but it throws an error and makes component testing through Jasmine impossible

`The <template> element is deprecated. Use <ng-template> instead`

Will covalent be upgraded to use angular 4 /material design 2?

**Comment by emoralesb05** [comment]
Covalent was already upgraded to angular 4.0.0 https://github.com/Teradata/covalent/pull/429

We are only waiting for `material@beta.3` to be released so we can release the whole package.
