### ISSUE TITLE
Bug in Nightly Build when used with AOT

### ISSUE THREAD

**Issue by asaph26** [Teradata/covalent#471]
When the nightly build is used with AOT, the following errors are shown
```
Property '_selectable' is private and only accessible within class 'TdDataTableComponent'
Property '_data' is private and only accessible within class 'TdDataTableComponent'
```

This doesn't occur when JIT compilation is used.

**Comment by emoralesb05** [comment]
Thank god for people like you haha 😄 . 

Thanks for the heads up!

**Comment by asaph26** [comment]
It looks like all properties that are used in a template need to be public

**Comment by jotatoledo** [comment]
@asaph26 yes. The funny thing is that angular cli only since v1.0.0 is giving errors when a private variable is used on a template

**Comment by asaph26** [comment]
They mentioned it in the changelog. But those are valid errors.

**Comment by emoralesb05** [comment]
Yeah, this (not accessing private variables in a template) has been a `aot` requirement for a while, they werent exposed correctly before though when using the cli.

**Comment by emoralesb05** [comment]
Fixed with https://github.com/Teradata/covalent/pull/472
