### ISSUE TITLE
Bug? Deprecation of the .forRoot() 

### ISSUE THREAD

**Issue by asaph26** [Teradata/covalent#473]
While initialising the module using .forRoot() using the latest CLI in AOT it fails with 

```ERROR in Error encountered resolving symbol values statically. Calling function 'CovalentCoreModule', function calls are not supported.```

Given that this will be deprecated in the upcoming beta.3, trying to use the nightly version with AOT causes the providers to not be initialised. 

**Note:** 
1) I am trying to run this on Angular v4
2) I had the same problem with material and had to go back to using .forRoot(). This did not cause any AOT compilation problems though

**Comment by asaph26** [comment]
To be a bit more specific, in material2 it was a the LiveAnnouncer that didn't have a provider when I removed forRoot(). In covalent, it was the TdLoadingService.

**Comment by asaph26** [comment]
This could be because of the project being compiled using the @angular/compiler-cli v2.4.x

**Comment by jotatoledo** [comment]
why are u trying to compile angular 4.x.x with compiler cli 2.4.x? For angular 4.x.x you need compiler cli 4.x.x

**Comment by jotatoledo** [comment]
Btw, if you are using the current release version, there is no support for angular 4,x,x

**Comment by asaph26** [comment]
@jotatoledo I am aware that this project doesn't work with angular 4 yet. However as I mentioned, I am using the nightly version which has been patched for Angular 4 support (https://github.com/Teradata/covalent/pull/429) despite being compiled using the 2.4.x compiler. Adding some more details to add context

I just raised this because I was able to get this working in JIT mode with the .forRoot() method which failed in the AOT mode. I was able to compile using AOT after removal of the .forRoot method but then it started complaining that some service wasn't provided

The background is that the forRoot method during bootstrap was deprecated to be removed and every service that needed to be a singleton service was provided as a singleton service without the need for the forRoot method. So I found it a little confusing when it says there is no provider found. (Check https://github.com/Teradata/covalent/pull/389)

So this is basically a ticket to say that I am not sure if there is a bug or not, but seems like something is not the way it should be.

**Comment by jotatoledo** [comment]
@asaph26 my bad, missed the part on ur comment where u mentioned the use of the nighly version

**Comment by emoralesb05** [comment]
Which services werent provided in the error? We stopped using forRoot in the docs a while back and works fine. So im trying to see if we missed something.

**Comment by emoralesb05** [comment]
Found the issue with for `forRoot` AoT error. https://github.com/Teradata/covalent/pull/477

**Comment by emoralesb05** [comment]
@asaph26 this should be fixed between https://github.com/Teradata/covalent/pull/477 and https://github.com/Teradata/covalent/pull/476. Can you confirm?

I am upgrading the quickstart and not seeing issues anymore.

**Comment by asaph26** [comment]
This is resolved now. Thanks @emoralesb05

**Comment by asaph26** [comment]
You can close this issue.
