### ISSUE TITLE
Expansion module has no "code" tab on the web page

### ISSUE THREAD

**Issue by mmoravcik** [Teradata/covalent#475]
### Do you want to request a *feature* or report a *bug*?

feature

#### Feature Request

This URL has an example use of Expansion panels: https://teradata.github.io/covalent/#/components/expansion-panel

It is missing "code" tab, which is present for other components, for example:
https://teradata.github.io/covalent/#/components/steps

#### What is the expected behavior?

To have DEMO and CODE tabs here: 
https://teradata.github.io/covalent/#/components/expansion-panel

#### What is the motivation / use case for changing the behavior?

To be consistent with rest of the page and help with the implementation

**Comment by tarekis** [comment]
I too wondered why there is no code preview for the expansion panel...
For a workaround, you can view the app's source code, specifically - [this file](https://github.com/Teradata/covalent/blob/gh-pages/src/app/components/components/expansion-panel/expansion-panel.component.html).

**Comment by emoralesb05** [comment]
Yeah, there are still some docs and examples that need more love. 

We are trying tackle component by component as we go, but anyone is free to help our with a small PR too 😄
