### ISSUE TITLE
[Data-table] sort style does not appear

### ISSUE THREAD

**Issue by thiagocsfoz** [Teradata/covalent#481]
I am using the data table as per the following code, column sorting works normally, but it does not display the pointers nor the column that was ordered in bold.

HTML:
![image](https://cloud.githubusercontent.com/assets/4909558/24622484/9b9d07ca-187b-11e7-925b-4fa60adcd173.png)

TS:
![image](https://cloud.githubusercontent.com/assets/4909558/24622524/b43c2f5e-187b-11e7-973f-c40f99a094b7.png)

![image](https://cloud.githubusercontent.com/assets/4909558/24622534/bf5e628a-187b-11e7-80a7-826ec302355d.png)

Interface:
![image](https://cloud.githubusercontent.com/assets/4909558/24622594/f4f46e8a-187b-11e7-9017-ef3def90fff1.png)

**Comment by emoralesb05** [comment]
ah, you are missing the `[active]` input which has to be true on the sorted column.

**Comment by thiagocsfoz** [comment]
Thank you, it worked perfectly.
