### ISSUE TITLE
Design Patterns: Immersive Experiences

### ISSUE THREAD

**Issue by kyleledbetter** [Teradata/covalent#49]
tl;dr
Don't use modals for creation when you can use a fullscreen form/view, drill down from a list view to a detail view, and then drill down into that detail view if there are child routes & views

**Comment by jennmedellin** [comment]
Dashboard Best Practices
- full demo
- patterns on dashboard (multiple)

**Comment by jeremysmartt** [comment]
Scope this to animations and transitions that support context.
