### ISSUE TITLE
[td-dynamic-forms] [FAQ] Is it possible to disable fields in dynamic form?

### ISSUE THREAD

**Issue by filipows** [Teradata/covalent#490]
Is it possible to disable all or some of the controls in a `<td-dynamic-forms>`?
I have already tried:
```
@ViewChild(TdDynamicFormsComponent) form: TdDynamicFormsComponent;
...
this.form.controls['input_name'].disable();
```
And what happens is the property of the formControl actually changes to: `disabled: true` (and status: 'DISABLED'), but there's no result in the view (inputs are still editable) :confused: 

Any ideas why that's not working?

**Comment by emoralesb05** [comment]
Tested it and its actually a bug, will add support for this next release.

**Comment by filipows** [comment]
Thanks @Emoralesb05 !
Let me know if I can help with that.

**Comment by benjaminleetmaa** [comment]
Is this fix implemented in Beta 4?

**Comment by kyleledbetter** [comment]
Nope. It has and RC milestone and this issue is still open

**Comment by benjaminleetmaa** [comment]
Any progress regarding disable controls? Why removed from Beta.5?

**Comment by emoralesb05** [comment]
We were fixing other things and improving other components (with limited resources), but right now we are triaging the dynamic form issues and features to create a road map for it. So expect this and more feature to be fixed soon.

**Comment by emoralesb05** [comment]
This has already been fixed implicitly but once you disable the elements, its going to be required to call the `refresh` method of the component.

e.g.

```
@ViewChild('dynamicForm') dynamicForm: TdDynamicFormsComponent;

disableElement(): void {
    this.dynamicForm.controls['element-0'].disable();
    this.dynamicForm.refresh();
  }
```
