### ISSUE TITLE
Datatable refresh cannot be invoke

### ISSUE THREAD

**Issue by hengkyz** [Teradata/covalent#492]
i cannot invoke refresh method from datatable?
it told me that this method is not available
the way i invoke this method
this.CovalentDataTableModule.refresh()

**Comment by emoralesb05** [comment]
`CovalentDataTableModule` is the module, not the component. 

So you need to use `TdDataTableComponent` as type to get the methods.

**Comment by jotatoledo** [comment]
Use @ViewChild() inside of a component that has a TdDataTableComponent on its template. Take a look  [here](http://learnangular2.com/viewChild/)

**Comment by emoralesb05** [comment]
Closing this since it wasnt really an issue.

**Comment by hengkyz** [comment]
lol its been a long time at last i solve this issue (my issue)
using your suggestion thank you
