### ISSUE TITLE
support angular material 2.0.0-beta.3

### ISSUE THREAD

**Issue by akalitenya** [Teradata/covalent#493]

**Comment by Stexxen** [comment]
Looks like its on [develop](https://github.com/Teradata/covalent/tree/develop) if you want it
https://github.com/Teradata/covalent/commit/bd309c8f2974f642cb2b0081b3df6f731fdfbc52

**Comment by Stexxen** [comment]
I see the package.json is hard-set to 
`2.0.0-beta.2`
https://github.com/Teradata/covalent/blob/develop/package.json#L64

Have you tried setting it too `2.0.0-beta.3`, are there any issues

**Comment by emoralesb05** [comment]
Please check opened PR's before opening an issue.
https://github.com/Teradata/covalent/pull/464
We are currently upgrading to latest material and will release as soon as we merge it.

**Comment by michaeljota** [comment]
I don't know why to publish beta 3 with Angular 4 support but without Material beta 3 support. Material beta 2 is does not support Angular 4, so this library can't be use with Material beta 2, but either can be use with Angular 2.

So I don't think there is any combination for Covalent beta 3 to work correctly. (And if there are any, please let me know, thanks you)

**Comment by emoralesb05** [comment]
@michaeljota we released covalent with `ng4` support earlier in the week because `material@beta.3` wasnt released yet, and we didnt know when that was going to happen.

Since now `beta.3` has been released Friday, We are gonna do a patch release with `beta.3` support.

**Comment by michaeljota** [comment]
I understand, but, does Material beta 2 have support for Angular 4? Cause, it does not make sense to release a version with Angular 4 support if Material, the UI library that this use, does not support it. *Do you know what I'm saying?*

**Comment by emoralesb05** [comment]
I do understand your point, but we dont control the breaking changes material has. And we still have to deliver our milestones.

Of course it does not make sense, and `beta.2` for the most part works fine with `ng4`. Since `template` was deprecated but not removed, so its not completely unsupported.

**Comment by emoralesb05** [comment]
closing since it will be fixed in `beta.3-1` https://github.com/Teradata/covalent/pull/464
