### ISSUE TITLE
Design Pattern - Data Table: Sort on multiple columns

### ISSUE THREAD

**Issue by ishatd** [Teradata/covalent#495]
Sort multiple columns
- ability to add columns to those selected for sort
- hooks so we can do the sorting but need indicators in the table of what was sorted
- ability to remove columns from sort

**Comment by kyleledbetter** [comment]
@ishatd I'd recommend making an additional separate Feature Request for hiding/removing columns since it's a separate concern from multiple sorting columns

**Comment by kyleledbetter** [comment]
found another example https://vaadin.com/elements/-/element/vaadin-grid#demos

but even with this one the ux is confusing, i still can't find a clear and easy multi sort ux
![multi-sort](https://cloud.githubusercontent.com/assets/867883/25676351/95e60e52-2ff6-11e7-8ae9-859d35c9ac3c.gif)

**Comment by jdundondev** [comment]
This screen capture shows how this feature is currently implemented in Studio Lite using the PrimeNG data table.

![image](https://user-images.githubusercontent.com/25935633/27880287-47332da8-6179-11e7-8303-7225032068ae.png)

- Clicking on a column header sorts that column ascending
- Clicking again sorts descending
- Clicking a third time removes sorting from that column
- Holding control (or command) while clicking another column adds that column to the sort
- The sort priority is determined by the order the columns are selected

**Comment by owilliams320** [comment]
this is complete but needs implementation see https://design.teradata.com/
