### ISSUE TITLE
Feature Request - Paging: Jump to page n

### ISSUE THREAD

**Issue by ishatd** [Teradata/covalent#496]
Data table paging - Capability to jump to page n

**Comment by kyleledbetter** [comment]
@ishatd can you post a link or screenshot with an example of exactly how you & your team are envisioning this feature?

**Comment by thomaslennan** [comment]
I asked around the group. Sounds like the request is relevant to the PrimeNg "PageLinks" feature.  https://www.primefaces.org/primeng/#/paginator

**Comment by kyleledbetter** [comment]
Bueno thx @thomaslennan
