### ISSUE TITLE
Design Pattern - Data Table: Filtering

### ISSUE THREAD

**Issue by ishatd** [Teradata/covalent#498]
More robust built-in filtering - Starts with, ends with, regular expressions, match case ... list of values and let user choose

**Comment by kyleledbetter** [comment]
Got examples from other products or from the web we should reference?

**Comment by akhedrane** [comment]
Devexpress team made an excellent work here: [Devexpress DataGrid Demo](https://js.devexpress.com/Demos/WidgetsGallery/Demo/Data_Grid/Filtering/Angular/Light/)

**Comment by kyleledbetter** [comment]
Great example. Thx @akhedrane

**Comment by kyleledbetter** [comment]
Kendo ui has a great example of this and several other features mentioned. They're be some design transition to material but much would still apply http://www.telerik.com/kendo-ui/grid

![kendo-datatable](https://cloud.githubusercontent.com/assets/867883/25402555/e5f0992a-29ad-11e7-9d4b-409986b3c1df.gif)

**Comment by jdundondev** [comment]
This screen capture shows multi-column and global filtering as currently implemented in Studio Lite using the PrimeNg data table.

![multicolumnfilter](https://user-images.githubusercontent.com/25935633/27881879-2f955cd8-617f-11e7-98f1-6344c1c1c6cc.gif)

- Clicking the filter button shows or hides the global filter and the individual column filters
- Hiding the filters also disables filtering
- Showing filters re-enables filtering and restores any previously entered filter values
- Clicking the Clear Filters button (X) clears both global and column filters
- Filter events are emitted automatically after entering text and following a short pause (e.g. 500ms) to allow multiple characters to be entered before triggering filtering

The advantage to this approach is that the filter values remain visible as long as the filters are not hidden. From a UX perspective, being able to see all the filter values at a glance is very useful.

**Comment by jdundondev** [comment]
Thinking about the close relationship between filtering and searching, I think that combining the two into a unified interface would be ideal.

- Searching locates and highlights values in the table while retaining all rows
- Filtering reduces the rows shown to only those matching the filter criteria

If we combine the two, filtering becomes just a toggle option of search (show only matching rows).

- Values matching the search criteria are highlighted in the table
- "Show only matching rows" can be toggled on or off to add or remove filtering

For example, reworking the current filter implementation shown above:

![globalsearchfilter](https://user-images.githubusercontent.com/25935633/27882538-e1d72c3a-6181-11e7-8d11-3b2786440cea.png)

- The search button shows/hides the search/filter fields
- The filter button toggles filtering on and off

**Comment by kyleledbetter** [comment]
That's a great example thanks

**Comment by jdundondev** [comment]
Support for different match modes is also important (e.g. contains, startsWith, endsWith, equals, regex).

This could be added as a drop down selector.

![filtermodeselection-mod1](https://user-images.githubusercontent.com/25935633/27882676-74427322-6182-11e7-901f-6a73a238a0a6.jpg)

Again the UX is enhanced by showing the match mode in a concise way (<, >, <>, =, *)

**Comment by jdundondev** [comment]
The event emitted for search/filter could be something like

{
    filter: true,
    globalSearch: {value: "a[bcd]e", matchMode: "regex"},
    columnSearch: [
        {name: "column1", value: "44", matchMode: "contains"},
        {name: "column2", value: "ab", matchMode: "startsWith"},
        {name: "column3", value: "55", matchMode: "equals"}
    ]
}

**Comment by iamjoyce** [comment]
Hi, will this be part of [release 2.0.0](https://github.com/Teradata/covalent/milestone/21)?
