### ISSUE TITLE
td-file-upload:  Should emit event if upload is cancelled.

### ISSUE THREAD

**Issue by Kumfert** [Teradata/covalent#499]
# Feature Request

There are three ways that a user can interact with the td-file-upload button. They can

1. select a file (or Files)
2. upload a file (or Files)
3. they can cancel the upload

Unfortunately, there are EventEmitters for only 2 out of the 3 user interactions (select and upload).  The cancel event is equally important to know about in practice.

# Use Case

Uploading a file -- particularly a large file, such as video -- can take some time.  To keep the user engaged,  I have a progress bar to track the progress of the video upload.  See screenshot below.

<img width="420" alt="screen shot 2017-04-11 at 6 13 37 pm" src="https://cloud.githubusercontent.com/assets/2791381/24937055/d3351e6c-1ee2-11e7-95c4-8e9667c770e9.png">

In the process of a long upload, it is entirely reasonable for the user to press the little grey cancel button.  Should that happen, I need some form of notification to tear down file transfer to the server and perform additional UI updates such as zeroing out the progress bar.  Otherwise, things get a little out of sync. e.g.

<img width="318" alt="screen shot 2017-04-11 at 6 13 53 pm" src="https://cloud.githubusercontent.com/assets/2791381/24937273/6718f8aa-1ee4-11e7-9717-712d3707baa0.png">

**Comment by emoralesb05** [comment]
Thanks for pointing it out 😄 .

Going to add this to the `beta.4.` milestone.
