### ISSUE TITLE
Mock API server

### ISSUE THREAD

**Issue by ilsiepotamus** [Teradata/covalent#50]
Create a mock API server that can generate realistic data.

MVP
- [x] `offline` mode
- [x] Populate mock API data with realistic datum (i.e. real names & email addresses)
- [x] Populate chart data with time series data based on query parameters in the mock API call
	- [x] axis labeling
	- [x] y-axis ranges and timeframe selectable
	- [x] API pagination
	- [x] wave output selectable (square, sine, triangle, random, etc)

**Comment by kyleledbetter** [comment]
completed in https://github.com/Teradata/covalent-data
