### ISSUE TITLE
td-steps Stepper vertical line is not centered

### ISSUE THREAD

**Issue by akomarovsky** [Teradata/covalent#501]
#### Bug Report

When using the stepper (td-steps) in vertical mode the line is not centered, but aligned to the left. See screenshot below.

I've manged temporarily fix it by adding to global style css the class:
```
.td-line-wrapper{
    margin-left: 12px;
}
```

##### Screenshots
Before the temp fix:
![image](https://cloud.githubusercontent.com/assets/20887752/24952819/a323ea38-1f81-11e7-95cc-e239d3d2a838.png)
After the temp fix:
![image](https://cloud.githubusercontent.com/assets/20887752/24952872/dcc95ae8-1f81-11e7-9506-0ef57797ccc3.png)

#### Which version of Angular and Material, and which browser and OS does this issue affect?
```
"dependencies": {
    "@angular/animations": "^4.0.0",
    "@angular/common": "^4.0.0",
    "@angular/compiler": "^4.0.0",
    "@angular/core": "^4.0.0",
    "@angular/forms": "^4.0.0",
    "@angular/http": "^4.0.0",
    "@angular/material": "^2.0.0-beta.3",
    "@angular/platform-browser": "^4.0.0",
    "@angular/platform-browser-dynamic": "^4.0.0",
    "@angular/router": "^4.0.0",
    "@covalent/core": "^1.0.0-beta.3-1",
}
```

**Comment by emoralesb05** [comment]
Thanks for the report! 

Dont know why it doesnt have that problem in the docs, but i was able to replicate on our plnkr.

**Comment by emoralesb05** [comment]
We created a patch release `beta.3-2` with this fix
