### ISSUE TITLE
NPM error when installing Covalent Core 1.0.0-beta.3-1

### ISSUE THREAD

**Issue by pdjota** [Teradata/covalent#502]
This repository's issues are reserved for feature requests and bug reports.

### Do you want to request a *feature* or report a *bug*?
BUG (Known issue)

#### Bug Report
Updating to the version 1.0.0-beta.3-1 produces an error in the console due to some dependencies of Flex Layout
```
npm ERR! peer dep missing: @angular/common@^2.3.5, required by @angular/flex-layout@2.0.0-beta.7
npm ERR! peer dep missing: @angular/core@^2.3.5, required by @angular/flex-layout@2.0.0-beta.7
npm ERR! peer dep missing: zone.js@^0.7.2, required by @angular/flex-layout@2.0.0-beta.7
```
This should be solved when @angular/flex-layout updates to Angular 4. See https://github.com/angular/flex-layout/issues/254

#### What is the expected behavior?
Installs without errors.

#### Which version of Angular and Material, and which browser and OS does this issue affect?

@angular/cli: 1.0.0
node: 6.9.5
os: darwin x64

```
  "dependencies": {
    "@angular/common": "4.0.2",
    "@angular/compiler": "4.0.2",
    "@angular/core": "4.0.2",
    "@angular/forms": "4.0.2",
    "@angular/http": "4.0.2",
    "@angular/material": "2.0.0-beta.3",
    "@angular/platform-browser": "4.0.2",
    "@angular/platform-browser-dynamic": "4.0.2",
    "@angular/router": "4.0.2",
    "@covalent/core": "1.0.0-beta.3-1",
    "@ngx-translate/core": "~6.0.0",
    "@ngx-translate/http-loader": "0.0.3",
    "hammerjs": "^2.0.8",
    "core-js": "^2.4.1",
    "rxjs": "^5.1.0",
    "zone.js": "^0.8.4"
  },
```

**Comment by asaph26** [comment]
@pdjota As you mentioned this should be solved when @angular/flex-layout is updated.

**Comment by pdjota** [comment]
yes, but perhaps you could label it as FAQs because there is not clear when Flex Layout would be updated.

**Comment by emoralesb05** [comment]
Huh, flex-layout has them as `dependencies` instead of `peerDependencies`. Since we are removing `CovalentCoreModule`, we will probably remove `flex-layout` as dependency. And have people import this on a `need` basis.

At first we intended to use it in our components, but choose not to so we could reduce the bundle size a bit.

**Comment by aderito7** [comment]
I also get an error. Says I should update node/npm, but I have the minimum requirements.
```
114 error node v6.9.2
115 error npm  v3.10.9
116 error code ELIFECYCLE
117 error covalent-quickstart@1.0.0-beta.3 postinstall: `webdriver-manager update && ./scripts/protractor.sh`
117 error Exit status 1
118 error Failed at the covalent-quickstart@1.0.0-beta.3 postinstall script 'webdriver-manager update && ./scripts/protractor.sh'.
118 error Make sure you have the latest version of node.js and npm installed.
118 error If you do, this is most likely a problem with the covalent-quickstart package,
118 error not with npm itself.
118 error Tell the author that this fails on your system:
118 error     webdriver-manager update && ./scripts/protractor.sh
118 error You can get information on how to open an issue for this project with:
118 error     npm bugs covalent-quickstart
118 error Or if that isn't available, you can get their info via:
118 error     npm owner ls covalent-quickstart
118 error There is likely additional logging output above.
119 verbose exit [ 1, true ]
```

**Comment by emoralesb05** [comment]
@aderito7 thats a diff issue with the `postinstall` hook. 

this command is failing ` webdriver-manager update && ./scripts/protractor.sh` 

Which could be any number of things, since its a protractor config step.

**Comment by emoralesb05** [comment]
We are removing the dependency since `CovalentCoreModule` was removed, and this dependency is not needed anymore. 

Should be fixed in beta.4
