### ISSUE TITLE
[Feature Request] Improve the Getting Started documentation.

### ISSUE THREAD

**Issue by MRMokwa** [Teradata/covalent#504]
#### Feature Request
I don't want to clone a github repository for starting a new project. I want to install covalent in a existing project. I'd be nice a fresh instalation guide that includes:
- List of necessary packages;
- Angular-cli.json: scripts, styles and dependencies needed;

#### What is the motivation / use case for changing the behavior?
The other Angular2+ UI libraries have this option and it's fairly easy to get a new project up and running.
For example:
- Clarity
https://vmware.github.io/clarity/get-started
- PrimeNg
https://www.primefaces.org/primeng/#/setup

**Comment by emoralesb05** [comment]
Its the same steps pretty much (just skipping the clone part), start from this step https://github.com/Teradata/covalent/blob/develop/docs/GETTING_STARTED.md#install-covalent-core-module 😄 

We will update our `docs` site with that documentation though.

**Comment by MRMokwa** [comment]
That's exactly what I needed, thank you.

**Comment by emoralesb05** [comment]
Closing since we updated the site with the GETTING_STARTED.md
