### ISSUE TITLE
Renderer.animate is no longer supported

### ISSUE THREAD

**Issue by paistipoikka** [Teradata/covalent#510]
This repository's issues are reserved for feature requests and bug reports.

### Do you want to request a *feature* or report a *bug*?

material incompatibility (2.0.0-beta.3)

#### Bug Report

simply upgrade to angular 4 and ~Material 2.0.0-beta.3. The material animation changes break the compile.

**Comment by emoralesb05** [comment]
Latest covalent version supports `angular@4.0.0` and `material@beta.3`. (`1.0.0-beta.3-2`)
