### ISSUE TITLE
##Feature Request ## Hide data table column

### ISSUE THREAD

**Issue by arunanamal** [Teradata/covalent#511]
Hi,
Is there way to hide table column, but need to capture that value when row selected.

Thanks

**Comment by emoralesb05** [comment]
Not yet, but we are gonna add this feature soon. Possibly by having a boolean property in the `ITdDataTableColumn`

**Comment by arunanamal** [comment]
Thank you....

**Comment by kyleledbetter** [comment]
found a good example http://iamisti.github.io/mdDataTable/

![image](https://cloud.githubusercontent.com/assets/867883/25683485/3b076c4a-3011-11e7-8d62-b15d5e3e7cbe.png)

**Comment by arunanamal** [comment]
Hi Kyle Ledbetter,
Thanks for the info., but this is done by using some older version of Angular (AngularJS)?
How to apply this for Angular?

Thank you..

**Comment by kyleledbetter** [comment]
We're gonna build the feature in Covalent. That was just inspiration for us :)

**Comment by arunanamal** [comment]
Hi,
This is very basic question. How do I apply above changes for the existing
project?
Could you please tell me steps to follow to update above changes

Thanks

**Comment by emoralesb05** [comment]
You can install it from the `nightly` repo to start testing while it gets released

`npm install https://github.com/Teradata/covalent-nightly.git`

**Comment by arunanamal** [comment]
Thank you...
