### ISSUE TITLE
Data Table: Searchable and unsearchable columns.

### ISSUE THREAD

**Issue by thormentor** [Teradata/covalent#513]
Is it possible to flag a column to not to be searchable?
If yes, how do I do that.

**Comment by kyleledbetter** [comment]
Currently the search component in our demo searches the entire object. If this is a feature request please give examples of how this would work visually with screenshots and gifs that align with material design spec, as well as API examples and code examples of how you'd expect this to work

**Comment by thormentor** [comment]
Thanks for the quick reply. Actually my question has nothing to do with design. What I need is a property like the property sortable. A boolean property called "searchable" that would allow me to enable or disable a column form being searched.

Some other problems that I run into it is that when I format the columns they become unsearchable. Am I doing something wrong? Have you observe this comportament before?
