### ISSUE TITLE
Stepper Child Routes

### ISSUE THREAD

**Issue by ianqueue** [Teradata/covalent#514]
### Do you want to request a *feature* or report a *bug*?

feature

#### Feature Request

To have steps in a wizard like flow would benefit from being able to apply Angular child routes to each step bound to their own step component.  This might have numerous of applications like route linking to a specific step, etc.  This may also may prove to have better code organization if each step's code can be self contained and tested within a component.

#### What is the expected behavior?

```typescript
// app.routes.ts
{
  path: 'solo', component: 'SoloComponent', children: [
    {
      path: 'luke', component: 'LukeComponent', outlet: 'jedi'
    },
    {
      path: 'leia', component: 'LeiaComponent', outlet: 'jedi'
    }
  ]
}
```

```html
<!-- solo.component.html -->
<md-steps>
  <md-step>
    <router-outlet name='jedi'></router-outlet>
  </md-step>
</md-steps>
```

#### What is the motivation / use case for changing the behavior?

This would make adding steps dynamically somewhat easier and wouldn't require a dev to go to the lengths of following... [Dynamic Component Loader](https://angular.io/docs/ts/latest/cookbook/dynamic-component-loader.html) in order to programmatically create steps in a stepper.

#### Which version of Angular and Material, and which browser and OS does this issue affect?

latest beta.3-2

##### Other information
Haven't looked at the library code yet to work a fix out yet, but hope to soon, would love to get folks thoughts on if this sounds like a good feature add or if it can be done through another method I haven't thought of, thanks!

**Comment by zilurrane** [comment]
Waiting for this feature
