### ISSUE TITLE
[Data-table] Paging does not reset

### ISSUE THREAD

**Issue by thiagocsfoz** [Teradata/covalent#515]
When cleaning the filter in the data table query, the paging still continues with the old values.

@covalent/core": "1.0.0-beta.2-1",
"@angular/core": "^2.4.0",

![image](https://cloud.githubusercontent.com/assets/4909558/25236494/5fd0e70c-25be-11e7-8c04-093a880fb6d8.png)

When using pagination it refreshes normally.

But when I reset the filter used, it does not update the paging values.
![image](https://cloud.githubusercontent.com/assets/4909558/25236581/919da4fa-25be-11e7-9159-fb176e787d91.png)

How do I reset paging?

Here's the html and TS of how it was used

HTML:
![image](https://cloud.githubusercontent.com/assets/4909558/25236676/cbe9b018-25be-11e7-9417-77eb5c619403.png)

TS:
![image](https://cloud.githubusercontent.com/assets/4909558/25236700/dcd77810-25be-11e7-9aa0-50885b546d98.png)

**Comment by emoralesb05** [comment]
Can you elaborate a little more on the problem? 

Are you trying to go to page 1 programatically?

**Comment by thiagocsfoz** [comment]
That, as I've done a new filter, paging should go back to page 1.

**Comment by jotatoledo** [comment]
Could you put some more information from your Ts file?
On a first look, I would say that u have to either call the `page($event) `method  or call `#paginBar.navigateToPage(1) ` when the filter changes

**Comment by thiagocsfoz** [comment]
How do I call #paginBar.navigateToPage (1) in TS?

![image](https://cloud.githubusercontent.com/assets/4909558/25282395/b49d000e-2686-11e7-96c6-3feae9d3828d.png)

**Comment by jotatoledo** [comment]
To call `#paginBar.navigateToPage (1)` you need to use a `@ViewChild`. Take a look [here](http://learnangular2.com/viewChild/)

**Comment by emoralesb05** [comment]
Yep, as @jotatoledo mentioned it. You would need to reference the `TdPagingBarComponent` with `@ViewChild` and then call its method.

**Comment by jotatoledo** [comment]
I think this issue could be closed @emoralesb05

**Comment by emoralesb05** [comment]
Yeah, closing this. Thanks for the reminder @jotatoledo

**Comment by brandon-a-hay** [comment]
I stumbled upon this thread after encountering this problem, and I'm sure others would also find this helpful when using this great data table control. Perhaps this should be called out in the docs or README.md?

**Comment by emoralesb05** [comment]
Well, we do mention the method in the documentation.. how you access it via TS or HTML is pure angular though.. i will say that the data-table example might need the TS example.

**Comment by brandon-a-hay** [comment]
Okay. My thought was that search is a very common use case with the data
table and this would make it seem "broken" to a naive user in certain
cases. I'm not sure how other data tables handle this, but it seems like
you'd want to reset paging by default when searching, no?
