### ISSUE TITLE
upload file no data to be create just file metadata

### ISSUE THREAD

**Issue by hengkyz** [Teradata/covalent#516]
This repository's issues are reserved for feature requests and bug reports.

### Do you want to request a *feature* or report a *bug*?
bug

#### Bug Report

i use file upload component but when i want to send the file data its just metada like name, extension, size, etc. but cannot find the file data itself

```
uploadEvent(file: File): void {
    console.log(file)
    this._odoo.call('upload.file', 'upload', ['self',file], {})
      .subscribe(res => {
        console.log(res)
      })
  };

```
#### Which version of Angular and Material, and which browser and OS does this issue affect?

Did this work in previous versions of Angular / Material?
Please also test with the latest stable and snapshot versions.

##### Other information
(e.g. detailed explanation, stacktraces, related issues, suggestions how to fix)

**Comment by emoralesb05** [comment]
This is not a covalent problem, its a general JS issue.

There are multiple ways of doing this.

http://stackoverflow.com/questions/750032/reading-file-contents-on-the-client-side-in-javascript-in-various-browsers

http://stackoverflow.com/questions/16214598/how-to-read-file-content-in-a-javascript-variable

**Comment by hengkyz** [comment]
@emoralesb05 what i mean is how to get data file from the input tag, 
coz if i console.log() the input value its just show the metadata not the data itself

**Comment by emoralesb05** [comment]
You cant. You need to do it those ways provided in the links.
