### ISSUE TITLE
Data Table: Sortable don't work as expected

### ISSUE THREAD

**Issue by thormentor** [Teradata/covalent#518]
This is how I think sortable work:
`columns = [
      {
        name: 'column1',
        label: 'Column 1',
        sortable: true
      },
      {
        name: 'column2',
        label: 'Column 2',
        sortable: false
      }
]`

This isn't working, only works globally. If sortable false the arrows disappear and therefore it's no longer possible to sort the data.

Am I doing anything wrong? What is the expected behaviour? Is this supposed to work only globally or in the way I was expecting it to work, as I show in my code?

**Comment by jotatoledo** [comment]
could u explain the situation by using a small plnkr? I dont really understand what u mean with "only works globally".

**Comment by thormentor** [comment]
1. `columns = [ { `
2. `name: 'column1', label: 'Column 1', sortable: true `  
3. `},{`
4. `name: 'column2', label: 'Column 2', sortable: false`
5. `} ]`

Hi @jotatoledo, I really don't think it is necessary to create a pnkr for this. As you can see in the line 2 I have sortable as true and in the line 4 I have sortable as false. This should work but it doesn't.

What I mean with globally is that is possible in the HTML to do like in this example:
`<td-data-table`
`  #dataTable`
`  [data]="filteredData"`
`  [columns]="columns"`
`  [sortable]="true"`
`  [sortBy]="sortBy"`
`  [sortOrder]="sortOrder"`
`  (sortChange)="sort($event)">`
`</td-data-table>`

I can specify that the all table is sorted or not. 
My question is simple, can I individually say that one column is sortable and an other is not?

**Comment by kyleledbetter** [comment]
Be a good citizen and respect others' time when you're asking for help. Create the Plunker

**Comment by thormentor** [comment]
@kyleledbetter I didn't mean to disrespect noone and I haven't done that. Isn't my question clear enough to avoid the Plunker?

**Comment by jotatoledo** [comment]
Hey! Now I understand what u meant. Yes you can, in the documentation there is an example with a non sortable column. Take a look [here](https://teradata.github.io/covalent/#/components/data-table). I cant say what would happen on that example if u still set the sortable attribute of the table. However, by reading the description of ur problem I guess the table attribute will override the individual column sortable property.

**Comment by emoralesb05** [comment]
Yep, the table `[sortable]` overrides the column ones.

So if you need to remove the `[sortable]` input from the table or set it as false.

**Comment by thormentor** [comment]
Thank you for all your help.
I shifted my table to use [Data Table (Atomic) Components]([](https://teradata.github.io/covalent/#/components/data-table)) and it works properly now.
