### ISSUE TITLE
Detect page sizes in <td-paging-bar>

### ISSUE THREAD

**Issue by paistipoikka** [Teradata/covalent#520]
This repository's issues are reserved for feature requests and bug reports.

### Do you want to request a *feature* or report a *bug*?

Feature

#### Feature Request

Can the `<td-paging-bar>` detect if the pageSizes array is empty. If empty, don't display the drop down.

#### What is the motivation / use case for changing the behavior?

If the page size is fixed at  (for example) 25 records then the drop down is not needed.

**Comment by jotatoledo** [comment]
Another point that could be considered:
Would be possible to separate the pagechange and pageSizeChange events?
