### ISSUE TITLE
[Template] Email App template

### ISSUE THREAD

**Issue by kyleledbetter** [Teradata/covalent#522]
#### Template

An material design email app template with inspiration from gmail, inbox, etc, using covalent layouts and components

**Comment by kyleledbetter** [comment]
updated my email template to Covalent beta.3, unfortunately i had to remove the logos in the layout bc routes currently don't work in plunker http://embed.plnkr.co/x80EeFrLwq7naP1aVW5S/

**Comment by emoralesb05** [comment]
Think its better to just remove that dependency or make it optional somehow

**Comment by emoralesb05** [comment]
Closing since this is already done.
