### ISSUE TITLE
bytes pipe doesn't convert correctly

### ISSUE THREAD

**Issue by ilsiepotamus** [Teradata/covalent#527]
#### Bug Report

The bytes pipe should be converting using powers of two (1024 for KB, 1,048,576 for MB, etc) not powers of 10.
` {{ 1024 | bytes }}` is returned as 1.02 KB

##### Screenshots or link to CodePen/Plunker/JSfiddle
![screen shot 2017-04-27 at 3 35 19 pm](https://cloud.githubusercontent.com/assets/6831837/25503214/1962fc78-2b5f-11e7-837a-a48eb00060db.png)
Plunker: http://plnkr.co/edit/gLMsYWq064zvaN9FOl32

#### What is the expected behavior?
pipe should divide by powers of two- {{ 1024 | bytes }} should equal 1 KB.  1 MB does not equal 1,000,000 bytes.

#### What is the motivation / use case for changing the behavior?
Conform with IEEE standards etc

#### Which version of Angular and Material, and which browser and OS does this issue affect?
All of them.
Did this work in previous versions of Angular / Material?
No.

**Comment by aciccarello** [comment]
Should k be 1024 here?
https://github.com/Teradata/covalent/blob/develop/src/platform/core/common/pipes/bytes/bytes.pipe.ts#L17
