### ISSUE TITLE
Overlapping text when using back button

### ISSUE THREAD

**Issue by jtschei** [Teradata/covalent#53]
This repository's issues are reserved for feature requests and bug reports.

### Do you want to request a *feature* or report a *bug*?

*bug*

#### Bug Report

please provide steps to reproduce and if possible screenhots or animated Gifs.
you can easily create animated Gif with this free PC/OSX App: http://www.cockos.com/licecap/

(using Safari with no extensions) 

Was looking at code 

Clicked link: https://teradata.github.io/covalent/

Clicked Style Guide

Clicked Product Icons

Clicked Iconography 

Clicked back on Browser

Header has overlapping text

##### Screenshots or link to CodePen/Plunker/JSfiddle

![bug](https://cloud.githubusercontent.com/assets/6226780/17943348/d6ffb4b0-69ef-11e6-8e22-f701b1f85fe8.png)

#### What is the expected behavior?

Text shouldn't overlap

#### Which version of Angular and Material, and which browser and OS does this issue affect?

Did this work in previous versions of Angular / Material?
Please also test with the latest stable and snapshot versions.

##### Other information
(e.g. detailed explanation, stacktraces, related issues, suggestions how to fix)

there was mention could be upstream angular + safari back button bug

**Comment by kyleledbetter** [comment]
This is a known (fixed) upstream Angular 2 bug with Safari & IE11 specific to using the back button in the browser https://github.com/angular/angular/issues/7722

It will be fixed in the next Covalent release (0.7) when we consume the upstream merged fix

btw the overlapping text is actually the accessibility feature of a broken font icon in angular-material

**Comment by kyleledbetter** [comment]
upstream bug https://github.com/angular/angular/issues/7722
and fix https://github.com/angular/angular/commit/f08060b0b00c98341c7e1fd9acb984402c280396

**Comment by emoralesb05** [comment]
Closed since it was fixed upstream and added in `0.7.0` release.
