### ISSUE TITLE
(feature) implement "mode" in Nav View layout

### ISSUE THREAD

**Issue by drakelovesbarbie** [Teradata/covalent#530]
The Layout "Nav View" is not implementing the "mode" attribute ('over' and 'side'), useful for tablet and desktop viewports.
Would greatly help to have it, fits with material specifications (see sidenav of angular-material and materializecss) and is better for small/medium projects that doesn't need the double-navbar given by using td-layout-manage-list.

**Comment by elmartino** [comment]
+1 for this one. See https://contacts.google.com for example

**Comment by emoralesb05** [comment]
Gonna have to brainstorm with the team a bit about this. The implementation is trivial, but want to see if we can create something reusable for other layouts.

**Comment by kyleledbetter** [comment]
Hi @drakelovesbarbie & @elmartino i made a quick plunker to show that you can do the Google Contacts style left nav with our current nav-view override and material's sidenav

(we still plan on adding the inputs for mode, opened, and width on nav-view btw)

http://plnkr.co/edit/wtxo9AoZTi6DXJXrxIX4?p=preview
![covalent-contacts](https://cloud.githubusercontent.com/assets/867883/25915767/584e4c9a-3577-11e7-9d43-33c29ee434b0.gif)

**Comment by elmartino** [comment]
Looks good! I will try!

**Comment by elmartino** [comment]
Works very good! Thanks!

**Comment by jdrew1303** [comment]
linking to PR #609 although the plnkr from @kyleledbetter is a slightly different idea but seeing as this also links to #581 

the above can be seen in the Aviva Insurance design 
![image](https://cloud.githubusercontent.com/assets/2535432/26358568/d918e4fe-3fca-11e7-9533-5398dbdbe4ee.png)

and the one the PR is the default-ish style like below. 
![](https://cdn-images-1.medium.com/max/800/1*MsPp0oqSAGILzdwi8Off3w.gif)

Nice job on these :+1:

**Comment by emoralesb05** [comment]
Yessir. One is more of a pattern with a mix of `td-layout-nav` + `md-sidenav` and the other one is the flexibility to make `td-layout` achieve the second one 😄

**Comment by emoralesb05** [comment]
Closing this since with the last PR we can achieve this by having this 

```
<td-layout-nav>
  <button md-icon-button td-menu-button (click)="sidenav.toggle()">
    <md-icon>menu</md-icon>
  </button>
  <td-layout-manage-list #sidenav>
    <md-nav-list td-sidenav-content>
    </md-nav-list>
    CONTENT
  </td-layout-manage-list>
```
