### ISSUE TITLE
IE Support

### ISSUE THREAD

**Issue by mbeckenbach** [Teradata/covalent#531]
I noticed, that you don't support IE because of Flex support. Looks like you have no min-heights set up. IE needs this. Then Flex should work.

**Comment by jdrew1303** [comment]
Linking this to #524 :+1:

**Comment by kyleledbetter** [comment]
Hi @mbeckenbach i'm currently chasing down some IE11 issues, can you give me a little more info on which min-heights you're referring to? 

On our docs site I've solved the homepage and layout min-height issues, is there anything else I'm missing? Is there a _layouts.scss platform min-height solution we're missing?

**Comment by mbeckenbach** [comment]
Hi @kyleledbetter,

I've just seen this issues when I checked out your demos in april. Not sure where the issues where. Sorry.
Most of the time setting a min-height for flex container to 1px for IE is enought to make IE happy in my applications.

Did you have a look at the angular flex layout? It's in beta but works quite fine cross browser. 
They apply lots of IE fixes by default.

**Comment by emoralesb05** [comment]
Closing this since we already have an issue tracking IE related tasks
