### ISSUE TITLE
Bug: table[td-data-table] sorting icon issues

### ISSUE THREAD

**Issue by michael-lang** [Teradata/covalent#532]
This repository's issues are reserved for feature requests and bug reports.

### Do you want to request a *feature* or report a *bug*?
Bug

#### Bug Report

When using the td-data-table attribute on a table element, there are some inconsistencies in the sorting behavior.  The icon does not switch direction to show proper ascending or descending status.  Doing the same but with td-data-table element does handle the icon switching properly, using the same component code

##### Screenshots or link to CodePen/Plunker/JSfiddle

http://plnkr.co/edit/RnJ5LANGoGQ9Wqw781xN?p=preview

#### What is the expected behavior?
Work the same as when using the td-data-table element.

```
     <table td-data-table>
        <th td-data-table-column [name]="'Name'" [sortable]="true" (sortChange)="sort($event)" [sortOrder]="sortOrder">
          Name
        </th>
        <th td-data-table-column [name]="'Points'" [sortable]="true" (sortChange)="sort($event)" [sortOrder]="sortOrder">Points</th>
        <th td-data-table-column [name]="'Col3'" [sortable]="true" (sortChange)="sort($event)" [sortOrder]="sortOrder">Col3</th>
        <tbody>
          <tr td-data-table-row *ngFor="let a of displayResults" (click)="itemSelected(v)">
            <td td-data-table-cell>{{a.Name}}</td>
            <td td-data-table-cell>{{a.Points}}</td>
            <td td-data-table-cell>{{a.Col3}}</td>
          </tr>
        </tbody>
      </table>
```

#### What is the motivation / use case for changing the behavior?
Consistency.  I want to use the attribute instead of the element in some scenarios.

#### Which version of Angular and Material, and which browser and OS does this issue affect?
I am using Angular 4.0.1, Angular Material 2.0.0-beta.3 and Covalent 1.0.0-beta.3-2.  I am using Windows 10 with Chrome 57.  

The Plunkr is using Using Covalent 1.0.0-beta.3-2 with Angular 4.0.0 and Material 2.0.0-beta.3

Did this work in previous versions of Angular / Material?
I have not tested on older  versions.  I believe this is on the latest version of each component.

##### Other information
This originally only used 'sortOrder' bound to each th[td-data-table-column] but then the sort only occured once and subsequent clicks did nothing.  So to hack around it I added a 'sortNextDir' and bound that instead (as in the plunkr).  The made the sort occur on each click and properly toggle from ASC to DESC, but the icon still doesn't update.  The md-icon should toggle between mat-asc and mat-desc, but rather it is stuck on mat-asc.

The sorting behavior should be the same as if I use this table, which works:

 ```
     <td-data-table
        #dataTable
        [data]="displayResults"
        [columns]="columns"
        [sortable]="true"
        [sortBy]="sortBy"
        [sortOrder]="sortOrder"
        (sortChange)="sort($event)">
      </td-data-table>
```

**Comment by icenold** [comment]
Also, the $event emitted by the sortChange event doesn't toggle DESC and ASC in $event.order

**Comment by hugo-martinez-chamonica** [comment]
I am using:
<td-data-table
                [data]="data"
                [columns]="columns"
                [selectable]="true"
                [sortable]="true"
                [sortBy]="sortBy"
                [sortOrder]="sortOrder"
                (sortChange)="sortEvent($event)"
                (rowSelect)="selectEvent($event)"
                (selectAll)="selectAllEvent($event)">
            <template tdDataTableTemplate="columnName" let-value="value" let-row="row" let-column="column">
                <div layout="row">
                    <span flex>{{value}}</span> // or <span flex>{{row[column]}}</span>
                    <md-icon>star</md-icon>
                </div>
            </template>
and sort is not working, here is my sort event implementation:

sortEvent(sortEvent: ITdDataTableSortChangeEvent): void {
        this.sortBy = sortEvent.name;
        this.sortOrder = sortEvent.order;
        console.log('sorting by: '+this.sortBy);
        console.log('sorting order: '+this.sortOrder);
        this.filter(false);
    }
filter(searching: boolean): void {
        let newData: any[] = this.originData;
        console.log('Datos de consulta: '+this.originData.length);
        const excludedColumns: string[] = this.columns
            .filter((column: ITdDataTableColumn) => {
                return ((column.filter === undefined && column.hidden === true) ||
                (column.filter !== undefined && column.filter === false));
            }).map((column: ITdDataTableColumn) => {
                return column.name;
            });
        newData = this._dataTableService.filterData(newData, this.searchTerm, true, excludedColumns);
        this.filteredTotal = newData.length;
        if(searching && this.filteredTotal!=undefined && this.filteredTotal > 0){
            this.fromRow = 1;
            this.currentPage = 1;
        }
        newData = this._dataTableService.sortData(newData, this.sortBy, this.sortOrder);
        newData = this._dataTableService.pageData(newData, this.fromRow, this.currentPage * this.pageSize);
        console.log('Filter info lenght: '+newData != undefined ? newData.length : 0 );
        this.filteredData = newData;
    }

**Comment by dpinheiro** [comment]
I'm having the same problem as described by @michael-lang

**Comment by emoralesb05** [comment]
You are missing the [active] flag to show which column is being sorted, once you add it it will render the icon on the correct direction.

This might need to change though.

**Comment by michael-lang** [comment]
I added an active flag to each column and it works.  It may be worth documenting this or a similar sample on the documentation site for [the Data Table (Atomic) Components](https://teradata.github.io/covalent/#/components/data-table) which currently has no  sample.

here is the revised working sample for td-data-table-column.
http://plnkr.co/edit/kGYjdjjCzT8i2TznzseT?p=preview

It would be easier from a user point of view to put sortBy and sortOrder on the <table td-data-table ..> element, and let it manage the 'active' state and sort properties of each of it's "ContentChildren".  But I can see why you possibly wanted to keep the implementation of td-data-table simpler.

**Comment by emoralesb05** [comment]
Thats a good idea, ill revisit this next release and see how we can improve its usage more.

**Comment by pcwa-ahendricks** [comment]
The active flag is important, but I'll also point out that the ternary expression in that plunker on line ~29 `this.sortOrder = sortEvent.order === TdDataTableSortingOrder.Ascending ? 'DESC' : 'ASC';` seems to be a requirement for me too when using the atomic form of the data table component.  When I don't use the atomic form of the table I need to omit this in the sort function.
