### ISSUE TITLE
Responsive Paging Bar Layout on Mobile

### ISSUE THREAD

**Issue by paistipoikka** [Teradata/covalent#533]
### Do you want to request a *feature* or report a *bug*?

Bug

#### Bug Report

When the screen size is very small the button layout is ugly. Paging bar icons jump to the next line.

##### Screenshots or link to CodePen/Plunker/JSfiddle

![screen shot 2017-04-28 at 20 00 04](https://cloud.githubusercontent.com/assets/20871336/25538940/664d117e-2c4d-11e7-854f-db1f217d7aa6.png)

#### What is the expected behavior?

Ideally it should be more like this. That is, the buttons are grouped something like this:

![screen shot 2017-04-28 at 19 57 29](https://cloud.githubusercontent.com/assets/20871336/25538931/60f1fd5c-2c4d-11e7-8ef5-2a33f3727705.png)

#### What is the motivation / use case for changing the behavior?

Better looking components.
#### Which version of Angular and Material, and which browser and OS does this issue affect?

Latest everything
Chrome

##### Other information
(e.g. detailed explanation, stacktraces, related issues, suggestions how to fix)

**Comment by emoralesb05** [comment]
I feel that this is more of a question of what gets shown at a time.. You can probably hide the text when the screen is smaller, and we can probably add a field to hide/show the `select` box to do the same.

**Comment by paistipoikka** [comment]
@emoralesb05 I think this is more about the wrapping of the buttons. It may be better to group them so that the bar doesn't have that ugly wrap to next line. It would be preferable to have the two buttons wrap rather than a single button.
