### ISSUE TITLE
[feature request] need (onContentReady) Event for <td-markdown>

### ISSUE THREAD

**Issue by zealitude** [Teradata/covalent#536]
This repository's issues are reserved for feature requests and bug reports.

### Do you want to request a *feature* or report a *bug*?
feature
#### Feature Request
I need to auto resize the <td-markdown>, however I can not know <td-markdown> size at the beginning and the there is no way to know when the markdown content rendering is finished. 

I need a event to notify me if the markdown content rendering is finished, so that I can resize or modify the rendered content.

**Comment by emoralesb05** [comment]
Would need the same event in `td-highlight` possibly.

**Comment by stevenov7** [comment]
Hey Ed. I am going to open a new issue for the same feature needs for td-highlight as you noted in this thread.

**Comment by emoralesb05** [comment]
Sounds good! 🎉
