### ISSUE TITLE
Covalent core module deprecated message

### ISSUE THREAD

**Issue by jbojcic1** [Teradata/covalent#537]
I followed the steps from https://teradata.github.io/covalent/#/docs to install covalent but in the Webstorm I am getting the message that CovalentCoreModule is deprecated.

<img width="807" alt="screen shot 2017-04-29 at 6 05 00 pm" src="https://cloud.githubusercontent.com/assets/10374826/25556909/6d381a42-2d06-11e7-8348-7fec0189c08d.png">

<img width="1200" alt="screen shot 2017-04-29 at 6 06 05 pm" src="https://cloud.githubusercontent.com/assets/10374826/25556913/8c1fef84-2d06-11e7-9bed-0a7c9cf9fe93.png">

**Comment by emoralesb05** [comment]
Yep, we deprecated it in beta.3 like `material` deprecated the `MaterialModule` to push people into importing modules on demand. We are updating the documents with this change though. 

Thanks for the heads up!
