### ISSUE TITLE
Landing Page Template not scrolling on iphone ipad safari chrome

### ISSUE THREAD

**Issue by yukichikawada** [Teradata/covalent#538]
### Do you want to request a *feature* or report a *bug*?

bug

#### Bug Report

please provide steps to reproduce:
iPhone iPad
I'm having trouble with the landing page template. With a bare bones reproduction and Covalent Quickstart, the screen blanks when attempting to scroll unless reloaded or the orientation is changed, if it's the first page loaded. However elements that are already in view can be engaged - like buttons.

it's deployed here: http://yukichikawada.s3-website-us-west-1.amazonaws.com/#/
repo here: https://github.com/yukichikawada/yuk-re-cov-ios-test

#### What is the expected behavior?
scrolling should work on first load and not require a change in orientation from portrait to landscape or vice versa

#### What is the motivation / use case for changing the behavior?
getting the landing page template to work on iphone safari chrome

#### Which version of Angular and Material, and which browser and OS does this issue affect?
Angular 4.0
Material 2.0.0-beta.3
iOS Safari + Chrome

Did this work in previous versions of Angular / Material? I don't know
Please also test with the latest stable and snapshot versions.

##### Other information
The Covalent Quickstart Landing Page doesn't work when linked straight to it as opposed to navigating to it through the Quickstart home page. The couple Android devices I've been able to use haven't had an issue.

**Comment by emoralesb05** [comment]
Is this still an issue?

**Comment by yukichikawada** [comment]
Judging by the plnkr preview of the landing page template it works so I don't think it's still an issue. I haven't tried the latest version of covalent though.

**Comment by jeremysmartt** [comment]
This appears to no longer be an issue
