### ISSUE TITLE
Upgrade @angular/flex-layout to beta8

### ISSUE THREAD

**Issue by jraadt** [Teradata/covalent#542]
This repository's issues are reserved for feature requests and bug reports.

### Do you want to request a *feature* or report a *bug*?
bug

#### Bug Report

Cannot build app using Angular CLI with Angular CLI 1.0 and Angular 4.0.  @angular/flex-layout dependency inside Covalent is currently at beta7, which does not work with Angular 4 building, but it has been [fixed in beta8](https://github.com/angular/flex-layout/issues/236).

The error I currently get is:
`ERROR in Error encountered resolving symbol values statically. Calling function 'makeDecorator', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol NgModule in /myapp/node_modules/@covalent/core/node_modules/@angular/flex-layout/node_modules/@angular/core/src/metadata/ng_module.d.ts, resolving symbol NgModule in /myapp/node_modules/@covalent/core/node_modules/@angular/flex-layout/node_modules/@angular/core/src/metadata.d.ts, resolving symbol NgModule in /myapp/node_modules/@covalent/core/node_modules/@angular/flex-layout/node_modules/@angular/core/src/core.d.ts, resolving symbol NgModule in /myapp/node_modules/@covalent/core/node_modules/@angular/flex-layout/node_modules/@angular/core/index.d.ts, resolving symbol FlexLayoutModule in /myapp/node_modules/@covalent/core/node_modules/@angular/flex-layout/flexbox/_module.d.ts, resolving symbol FlexLayoutModule in /myapp/node_modules/@covalent/core/node_modules/@angular/flex-layout/flexbox/_module.d.ts`

**Comment by emoralesb05** [comment]
Thanks for the issue! We are actually gonna remove the dependency since CovalentCoreModule has been deprecated and there is no real use for that module internally.

**Comment by aciccarello** [comment]
Related #239 and #334
