### ISSUE TITLE
[feature request] File Upload: add custom form data

### ISSUE THREAD

**Issue by farkidev** [Teradata/covalent#546]
This repository's issues are reserved for feature requests and bug reports.

### Do you want to request a *feature* or report a *bug*?
*feature*

#### What is the expected behavior?

A key value pair or FormData parameter should be added to IUploadOptions where we can pass custom form data e.g. file type, comment, etc.

#### What is the motivation / use case for changing the behavior?

I now we can headers but I think these kind of data doesn't belong to the header

##### Other information
If you are interested I can do it and create a pull request.

**Comment by emoralesb05** [comment]
Sure, really interested in a PR with that 😄

**Comment by fpserp** [comment]
Today I made the necessary changes  (this is my work account) but when I run ng serve --aot I get a JavaScript heap out of memory. (Everything else is working including ng build --aot.) There is an open [issue](https://github.com/angular/angular-cli/issues/5618) about it at the cli repo.
Should I create a PR with the my new feature branch anyway?

**Comment by emoralesb05** [comment]
Sure, PR away and we can start discussing this kinds of things in the PR. 😄
