### ISSUE TITLE
Support for multiple files in IUploadOptions

### ISSUE THREAD

**Issue by MJomaa** [Teradata/covalent#552]
This repository's issues are reserved for feature requests and bug reports.

### Do you want to request a *feature* or report a *bug*?

feature

#### Feature Request

I'm using the teradata upload service in conjunction with the file-upload button. Currently the interface IUploadOptions doesn't take a FileList, so you have to upload the form data files one by one.
Current interface:

```
export interface IUploadOptions {
  url: string;
  method: 'post' | 'put';
  file: File;
  headers?: {[key: string]: string};
}
```

#### What is the expected behavior?

To be able to insert multiple form data files into IUploadOptions. For Example:

```
export interface IUploadOptions {
  url: string;
  method: 'post' | 'put';
  files: FileList;
  headers?: {[key: string]: string};
}
```

#### What is the motivation / use case for changing the behavior?

Less HTTP requests to the server will reduce the server load. Furthermore the code becomes simpler for the user of the library.

#### Which version of Angular and Material, and which browser and OS does this issue affect?

Angular: 4.0.3
Material: 2.0.0-beta.3
Browser: Chrome, Firefox, Edge
OS: Windows10, Debian8

**Comment by emoralesb05** [comment]
Would this solve your issue??

https://github.com/Teradata/covalent/commit/77c89acd4ba83b43754ce422fd74e6351e2a6297

Now there will be an extra property for `FormData`, where you can send anything.

**Comment by MJomaa** [comment]
@emoralesb05 Yes it would, thanks!

**Comment by emoralesb05** [comment]
Awesome, closing this issue since that feature will solve it.
