### ISSUE TITLE
TdSearchInput events not firing

### ISSUE THREAD

**Issue by jfinci1** [Teradata/covalent#556]
This is a bug report.

Search box is not firing events as expected.

http://plnkr.co/edit/QmVqIf4LqcLfpfFodxwc?p=preview

First attempt at using it.

Windows 7, Chrome (latest)

"@angular/animations": "^4.0.2",
    "@angular/common": "^4.0.0",
    "@angular/compiler": "^4.0.0",
    "@angular/core": "^4.0.0",
    "@angular/forms": "^4.0.0",
    "@angular/http": "^4.0.0",
    "@angular/platform-browser": "^4.0.0",
    "@angular/platform-browser-dynamic": "^4.0.0",
    "@angular/router": "^4.0.0",
    "@covalent/core": "^1.0.0-beta.3-2",
    "@swimlane/ngx-datatable": "^8.2.1",

Am i crazy? I feel like i might be

Also this component library is killer, great work you guys are doing, thanks. would love to contribute

**Comment by emoralesb05** [comment]
Thanks! Looking forward for any contributions, just open an issue with a proposal and we can start collaborating 😄 

Regarding this though, the correct output events are `(search)` and `(clear)` since angular's other event syntax already uses `on` in it, so its frowned upon to use it in the name.

e.g. `(search)="search()"` vs `on-search="search()"`

**Comment by jfinci1** [comment]
I've updated the plnkr, http://plnkr.co/edit/QmVqIf4LqcLfpfFodxwc?p=preview

I think thats correct?

**Comment by emoralesb05** [comment]
The events are firing, you are just not assigning the string to the correct variable

```
setSearchFilter(event) {
  search = event;
 }
```

should be

```
setSearchFilter(event) {
   this.search = event;
 }
```

**Comment by jfinci1** [comment]
Your def right about that lol my bad, tried to go to fast, but still no luck...
Updated: 
http://plnkr.co/edit/QmVqIf4LqcLfpfFodxwc?p=preview

**Comment by emoralesb05** [comment]
It works fine for me. 

Are you pressing enter? There are 2 types of events.. (search) which is thrown as the user presses `enter` and (debounceSearch) which is thrown as the user keysdown.

More info in https://teradata.github.io/covalent/#/components/search

**Comment by jfinci1** [comment]
Sorry that was silly.  Didn't see the snippet about the enter key there.  I am attempting to use he debounce version though in my own app:

http://plnkr.co/edit/QmVqIf4LqcLfpfFodxwc?p=preview

**Comment by emoralesb05** [comment]
Thanks! We will continue to improve our documentation as we go on for sure, since we want to give more examples and demos 😄

**Comment by jfinci1** [comment]
Do you guys have a to-do list or roadmap spec'd out for them? I'd be happy to help you guys out. I've been using Covalent a lot and it's great, so easy to use.

**Comment by emoralesb05** [comment]
We are planning out that at the moment, once we finish a draft of it we will upload it so as a standard for our docs. 😄
