### ISSUE TITLE
TD-Dynamic-Forms : not able to create numeric textbox only for integer value

### ISSUE THREAD

**Issue by Sam89Jha** [Teradata/covalent#564]
Feature Request

when we pass TdDynamicType.Numeric in ITdDynamicElementConfig as input for td-dynamic fotm components, it will generate HTML numeric input element.

1. Input element by default accepts dot (.) in its value.
2. what if we require only to enter integer value not decimal, which is highly/mostly required.
3. should separate int , decimal in TdDynamicType

![numeric](https://cloud.githubusercontent.com/assets/22675812/25778501/07fb0eec-331d-11e7-8d05-db73bf3d877a.png)

**Comment by emoralesb05** [comment]
I think in this one we either leverage the `pattern` one too, or would have to create a directive that doesnt allow the `.` or `e` characters on a number field.

**Comment by emoralesb05** [comment]
This will be taken care of with custom validators in https://github.com/Teradata/covalent/pull/708
