### ISSUE TITLE
TD-Dynamic-Forms : not able to add custom restriction/validation on text input field

### ISSUE THREAD

**Issue by Sam89Jha** [Teradata/covalent#565]
Feature Request

if we pass TdDynamicType.Text then an input control is rendered accepting all values, but we always have some restrictions or validations over input values, which can not be passed in current component, validation example: 

Allow only few special characters
only alpha numeric field , etc

Expected behavior :
should accepts regex with each dynamic element config which will validated on input values and add ng-valid/ng-invalid accordingly and highlight the control if not matches with the regex

**Comment by emoralesb05** [comment]
I think we will just allow people to pass a `Validator` and in it they can have their own custom validations as needed.

**Comment by emoralesb05** [comment]
This will be taken care of with custom validators in https://github.com/Teradata/covalent/pull/708
