### ISSUE TITLE
TD-Dynamic-Forms : required property not validated if we enter white spaces

### ISSUE THREAD

**Issue by Sam89Jha** [Teradata/covalent#566]
Bug:

If we pass required : true in ITdDynamicElementConfig but when we enter white space it will mark input as valid.

this should be handled. required fields must not contains only empty spaces

**Comment by emoralesb05** [comment]
Technically empty spaces are a value, so its not entirely wrong. The way you would handle that is by using the `pattern` so its basically the same as https://github.com/Teradata/covalent/issues/565

**Comment by Sam89Jha** [comment]
Right !
I think if we'll have options to pass pattern, then all the concerns has been resolved automatically

**Comment by emoralesb05** [comment]
This will be taken care of with custom validators in https://github.com/Teradata/covalent/pull/708
