### ISSUE TITLE
TD-Dynamic-Forms : HTML rendering is not in good format

### ISSUE THREAD

**Issue by Sam89Jha** [Teradata/covalent#568]
Issue :

The HTML render with the elements pass in ITdDynamicElementConfig array is not looks good, all elements should align in correct  way or with same width.
I don't know this is default view or we can have control over that, or we should handle by ourselves with Custom Css.
please find screenshot below, right side panel is output of TD-Dynamic-Form template
please help.

![image](https://cloud.githubusercontent.com/assets/22675812/25782597/a0e6bedc-336b-11e7-8b28-24b7414f7b73.png)

Thanks - Sameer

**Comment by kyleledbetter** [comment]
In the first "mvp" release we tried to pick flexbox % widths for elements that worked the best on average. An enhancement would be letting the dev override the default %

**Comment by Sam89Jha** [comment]
Good enough !!
Will you help me to set same width for all elements ? Or we can do it by
custom CSS only ?

Thanks - Sameer

**Comment by kyleledbetter** [comment]
I'm sure you can force widths via scss. We'll consider % settings for a beta4 feature if possible

**Comment by emoralesb05** [comment]
I think we can leverage `flex` and `flex-order` to do allow everybody to order them and set the flex in % as needed.

**Comment by Sam89Jha** [comment]
Thanks, we'll wait for the new release with expected enhancement

**Comment by emoralesb05** [comment]
This has already been merged, you can change the `flex` % width at any time.
