### ISSUE TITLE
Data-Table Search after Format keeps searching in unformatted data.

### ISSUE THREAD

**Issue by thormentor** [Teradata/covalent#574]
Most of the data in my table has to be formatted before shown. Examples are enumerations that I've to format to readable text, decimal values and currencies to be shown according to the country.

Although the format works really well the search uses the unformatted data instead of the formatted to filter the table.

How can I solve this?

**Comment by emoralesb05** [comment]
Thats a good question. Normally you would do that in your filtering implementation, while taking into consideration the formats.

I dont have a good example for this, but when filtering you would do something like this:

```
    let filteredData: any[];
    let data: any[] = // data to filter
    let columns: ITdDataTableColumn[] = // assign columns here.
    filteredData = data.filter((item: any) => {
      const res: any = columns.find((col: ITdDataTableColumn) => {
        const itemValue: string = ('' + item[col.name]);
        return col.format(itemValue).indexOf(searchTerm) > -1;
      });
      return !(typeof res === 'undefined');
    });
```

Dont know if it actually works, just to give you a gist of how to achieve it. (assuming you used the `format` method in the columns)

**Comment by thormentor** [comment]
Thanks @emoralesb05!
The code below fixed my issue:

```ts
this.filteredData = this.data.filter((item: any) => {
  const res: any = this.columns.find((col: FastnetDataTableColumn) => {
    let itemValue = (col.format) ? col.format(item[col.name]) : item[col.name];
    return itemValue.toLowerCase().indexOf(this.searchTerm.toLowerCase()) > -1;
  });
  return !(typeof res === 'undefined');
});
```

However, is there any chance of having something like supported directly by the `TdDataTableService#filterData` in the near future?

**Comment by emoralesb05** [comment]
The team decided this is a proper solution and will not support it directly
