### ISSUE TITLE
Cards image layout is broken

### ISSUE THREAD

**Issue by gryole** [Teradata/covalent#575]
#### Bug Report
Covalent styles for cards [_card.scss](covalent/src/platform/core/common/styles/_card.scss) changes some padding and margin values. It also changes styles for `md-card-image`. But styles for `md-card-sm-image`, `md-card-md-image`, `md-card-lg-image`, `md-card-title-group` are absent. More about image directives at [official docs](https://material.angular.io/components/component/card)
As result, layout using these images is broken - images are moved outside card borders.

#### What is the expected behavior?
Using `md-card-sm-image`, `md-card-md-image`, `md-card-lg-image` with `md-card-title-group` does not broke layout. 

#### Which version of Angular and Material, and which browser and OS does this issue affect?
"covalent/core": "1.0.0-beta.3-2"
"angular/material": "2.0.0-beta.3"

##### Other information
I propose 2 options: 
1) Add styles for `md-card-sm-image`, `md-card-md-image`, `md-card-lg-image`, `md-card-title-group`
2) Change selector hierarchy for covalent cards styles by adding addition class name
Current: 
body {
  .mat-card {
    ...
  }
}
Proposed:
body {
  .covalent-card {
    ...
  }
}
This will allow usage both of material original card layout and covalent layout. Also new features in cards layout will not be broken with new material version.

**Comment by aleixsuau** [comment]
Same problem here :(

**Comment by jotatoledo** [comment]
Experienxed the same problem today.

**Comment by kyleledbetter** [comment]
working on a fix for this now, coincidentally i found a bug in Material2 for `md-card-lg-image`:
https://github.com/angular/material2/issues/4938

**Comment by kyleledbetter** [comment]
PR for review pls https://github.com/Teradata/covalent/pull/653

**Comment by ericis** [comment]
I believe this issue is back. I'm getting no padding in the main content area for a `mat-card` with a basic `td-layout` with navigation side menu
