### ISSUE TITLE
Logo in `td-layout` does not resize properly

### ISSUE THREAD

**Issue by ethanroday** [Teradata/covalent#578]
#### Bug Report

When using the `logo` attribute on any of the `td-layout` family of layouts (e.g. `td-layout-nav-list`), the logo is automatically sized to have a width of 100px. This is a problem when the aspect ratio of the logo is not landscape. See, for example, the following, which is just the 'T' from the Teradata logo included in the Covalent quickstart repository:

![image](https://cloud.githubusercontent.com/assets/896670/25860160/86587fee-3495-11e7-8f82-3d443f46f46b.png)

Full running example is available at [https://github.com/ethanroday/covalent-demos/tree/icon-resizing](https://github.com/ethanroday/covalent-demos/tree/icon-resizing).

#### What is the expected behavior?

The logo should be resized so that it fits within the toolbar. There is currently no workaround that I can think of, except to create awkward blank space on either side of the logo in the SVG itself.

#### Version information

Angular 4.1.0
Covalent 1.0.0 beta 3-2
Node 6.9.5
NPM 4.1.2

**Comment by emoralesb05** [comment]
For a workaround you can override `.md-icon-logo` and replace its width.

I think we should pass the width maybe as an input to make it more flexible since this would vary a lot between logos .

**Comment by kyleledbetter** [comment]
As a side note you're not using the Teradata T as a logo by itself right? :) Big branding no no

**Comment by ethanroday** [comment]
@kyleledbetter Of course not :) Just an example.

**Comment by aciccarello** [comment]
Would it make sense for the logo to be styled based on the height? That way you can use any aspect ratio logo.

**Comment by kyleledbetter** [comment]
Trick is that you need height and width for SVG. If you set s height in px and width:auto the SVG could actually be far too wide. I think we'll have to add inputs with details for logoHeight and logoWidth

**Comment by emoralesb05** [comment]
But this does bring up a point that we do have a max-height depending on the md-toolbar.. so we might have to limit that.

**Comment by kyleledbetter** [comment]
changing to a new feature request to have @inputs for logoHeight and logoWidth

**Comment by kyleledbetter** [comment]
We've thought about this a lot and rather than adding inputs for height and width that will be required all over the place, it would just be easier to add this to styles.scss:

```
md-toolbar .mat-icon.md-icon-logo { width: 300px; height: 300px; }
```

closing for now

**Comment by aciccarello** [comment]
@kyleledbetter That makes sense. It would be great to include that information in the layout docs so others can find that information easier.

**Comment by kingkassem** [comment]
the problem still for me with angular 5
more over when open the demo for the quickstart it's there !!!!
