### ISSUE TITLE
[Bug] ng serve: File to import not found or unreadable: ~@angular/material/theming

### ISSUE THREAD

**Issue by fpeterdev** [Teradata/covalent#579]
#### Bug Report

I just forked and cloned the repo, and when I run `ng serve` I got the following error:

ERROR in ./\~/css-loader?{"sourceMap":false,"importLoaders":1}!./\~/postcss-loader?{"ident":"postcss"}!./\~/sass-loader/lib/loader.js?{"sourceMap":false,"precision":8,"includePaths":[]}!./src/theme.scss
Module build failed:
@import '~@angular/material/theming';

#### Other information
There's an [issue ](https://github.com/angular/angular-cli/issues/6242)abbout it at angular-cli github page. It seems there's a bug in the last release of sass-loader (6.0.4).

When I explicitly install 6.0.3 it works

#### Suggestion
Put `"sass-loader": "6.0.3"` into package.json until this issue is solved.

**Comment by emoralesb05** [comment]
Cool, thanks for the report! 

We will probably use `yarn.lock` to install the fixed dependencies for now while that gets fixed upstream.

Gonna leave this opened until it gets fixed in the meantime.

**Comment by fpeterdev** [comment]
They've already released a patch (6.0.5), based on the comments it's working again. (I can only test it tomorrow.)

**Comment by emoralesb05** [comment]
awesome, good to know!

**Comment by emoralesb05** [comment]
Closing this since it seems its not a problem anymore.
