### ISSUE TITLE
TD-Dynamic-Forms: Date type on TdDynamicElement or TdDynamicType

### ISSUE THREAD

**Issue by vertigo7x** [Teradata/covalent#584]
Feature Request

It would be great to have a date type on TdDynamicElement or TdDynamicType. By default it could use the HTML5 datepicker.
Btw a nice material designed datepicker would be nice also ;)

**Comment by kyleledbetter** [comment]
Material 2 has merged their datepicker into master so we can add this after their next release!

**Comment by buu700** [comment]
Is this still planned now that the Material datepicker's been released?

**Comment by emoralesb05** [comment]
Yup, we have in the road map a lot of dynamic forms features including this one

**Comment by emoralesb05** [comment]
Adding support for datepicker in https://github.com/Teradata/covalent/pull/1058

**Comment by buu700** [comment]
Nice, thanks for the update!
