### ISSUE TITLE
How do I add a custom TdDynamicElement element type?

### ISSUE THREAD

**Issue by rjsteinert** [Teradata/covalent#585]
We're interested in using TdDynamicForm but would need to extend it to support elements like custom text boxes, images, and other nonstandard form elements. Is that currently possible to do in a clean way without forking Covalent? If not currently, is there any thinking about how covalent might expose that ability? We might be interested in building that extensibility as a PR to covalent so we could then have our custom elements in our own code base.

**Comment by emoralesb05** [comment]
We have an issue for this exact feature, and will work on it for the next milestone. 

We are thinking that it might just require you to extend an interface and implement certain things, and then pass the `Type` of the `Custom` component.

Here is the issue asking for it https://github.com/Teradata/covalent/issues/512

and all the dynamic forms features/enhancement we will work on soon.

https://github.com/Teradata/covalent/projects/7

**Comment by emoralesb05** [comment]
Closing this in favor of #512
