### ISSUE TITLE
Feature Request - data-table row clickable link instead of row selection checkbox

### ISSUE THREAD

**Issue by manickam91** [Teradata/covalent#592]
this is a feature request to have two different actions for data table row clickable , instead of Selection

### Data Table  *feature* to improve navigation

when i set [selectalbe]=true and [multiselect]= true, i am able to listen an event from selection, which i used to navigate to other pages, but in another scenario, i need to select multiple rows and delete it or perform random operations which is not possible right now, because both list click and checkbox click hits the same action, please have a different actions so it would be helpful for navigation

**Comment by kyleledbetter** [comment]
Like this? https://github.com/Teradata/covalent/pull/572

**Comment by emoralesb05** [comment]
Yeah, https://github.com/Teradata/covalent/pull/572 should take care of this since we are separating the events.

Selection will only happen when clicking on the checkbox.
rowClick will happen when clicking on the row.

**Comment by emoralesb05** [comment]
So yeah, this will be achieves with the new `[clickable]` input and `(rowClick)="navigateTo($event)"` output.

**Comment by manickam91** [comment]
New update does not have expected results, there are no separate event listeners for row click and checkbox click
