### ISSUE TITLE
IRestQuery doesn't accept multiple keys with the same value

### ISSUE THREAD

**Issue by ilsiepotamus** [Teradata/covalent#599]
### Do you want to request a *feature* or report a *bug*?
bug

#### Bug Report
The IRestQuery interface only allows you to specify a single key with a given string.  For instance,

```
query: IRestQuery = {
  'id': 1,
  'id': 2,
};
```
will throw an error.  

#### What is the expected behavior?
Either,

IRestQuery should be an array of key/value pairs:
```
query: IRestQuery = [
  { 'id': 1 },
  { 'id': 2 },
];
```
Or alternately, to keep backwards compatability, leave the IRestQuery interface the same, and allow RESTService to accept either a single `IRestQuery` or an array `IRestQuery[]`.

#### What is the motivation / use case for changing the behavior?
Sending multiple identical keys in a REST API query `http://server/endpoint?id=1&id=2` is a common pattern.

#### Which version of Angular and Material, and which browser and OS does this issue affect?
This affects all browser/OS/Angular/Materials as it's a limitation of the ts interface type

**Comment by jeremysmartt** [comment]
HTTP is being deprecated from Covalent
