### ISSUE TITLE
CovalentMessageModule fails to import

### ISSUE THREAD

**Issue by madmandrew** [Teradata/covalent#600]
I can import it in the above import statement in app.module
`import { CovalentMessageModule } from '@covalent/core';`

but adding it in
`imports : [CovalentMessageModule]`

causes this error 
`/node_modules/@covalent/core/index"' has no exported member 'CovalentMessageModule'.`

I'm running vers. 1.0.0-beta.4

UPDATE: 
Turns out it was a cache issue! sorry : /

I cleared node_modules and reinstalled, and restarted my computer for good measure and it worked :)

UPDATE 2:
This may be a separate issue but the color="primary" or accent/warn doesn't seem to work, but class selector for colors does.

**Comment by emoralesb05** [comment]
Hmm.. we dont have this issue in our internal products. 

Can you provide more information? Also try doing `rm -rf node_modules dist tmp` since also the cache of npm might be affecting this.

**Comment by madmandrew** [comment]
Turns out it was a cache issue! sorry : /

I cleared node_modules and reinstalled, and restarted my computer for good measure and it worked :)

**Comment by emoralesb05** [comment]
haha no worries 😄 , closing this then
