### ISSUE TITLE
Feature request: Dynamic items on chips autocomplete list

### ISSUE THREAD

**Issue by jotatoledo** [Teradata/covalent#601]
#### Feature Request

Allow the items to be loaded as result of an async. service request depending on the current user input

#### What is the expected behavior?

The items displayed on the autocomplete list are loaded from server depending on the user input.

#### What is the motivation / use case for changing the behavior?

Lets say that I have a list on my backend made of 1000 elements or more, that I want to suggest to the user as possible match for his input. I dont want to load the 1000 elements on component creation, instead, I would like to load sections of it that match his current input.

##### Other information
For this to work I think It would be required to implement an `@Output` property for the input/keypress event (that ignores the enter key), that allows a programmer to change the elements given to the td-chips component.

For example:

```
<td-chips placeholder="Enter something" [(ngModel)]="input" [items]="items$ | async" (onInput)="handleInput($event)" requireMatch></td-chips>

export class SomePresentationComponent {
   items$: Observable<string[]>;
   input : string[];
    constructor(private _service: SomeService){
     this.input = [];
     this.items$ = of([]);
    }

    // Event contains the current value on the input field of the chips element
   handleInput(event: string){
      this.items$ = this._service.getOnDemand(event);
   }
}
```

**Comment by emoralesb05** [comment]
We are working on this asap and currently implementing it in our internal products (we need this too), so expect this soon 😄

**Comment by jotatoledo** [comment]
Nice to hear!
Any ETA?

**Comment by emoralesb05** [comment]
Cant know for sure since we are in the midst of implementing it (which will require lots of testing and backwards compatibility to not introduce breaking changes), but hopefully beta.5 should include it.

**Comment by emoralesb05** [comment]
https://github.com/Teradata/covalent/pull/626 will take care of this 😄 .

**Comment by jotatoledo** [comment]
nice, considering the added functionalities a minor breaking change as exchange for it sounds fair to me 😃
