### ISSUE TITLE
(Feature Request) Implement parent/child items on the left NavList

### ISSUE THREAD

**Issue by bengwall** [Teradata/covalent#603]
Add the ability to have Parent/Child nav items on the left nav list (the navigation drawer).  

Example with Google Contacts:  [https://contacts.google.com/](https://contacts.google.com/).

![screen shot 2017-05-18 at 8 25 44 am](https://cloud.githubusercontent.com/assets/4481748/26204188/a699cdc0-3ba3-11e7-8cb5-bce629a48869.png)

This other Angular 4/Material Template does it slightly differently:  [https://fury.martinsuess.com/](https://fury.martinsuess.com/).  This template has a pretty nice overall implementation of a side nav.

![screen shot 2017-05-17 at 10 51 23 am](https://cloud.githubusercontent.com/assets/4481748/26204182/a3e7e01c-3ba3-11e7-8cbe-96644890c476.png)

**Comment by emoralesb05** [comment]
This seems like a combo of using `td-expansion-panel`s inside the navigation drawer and also maybe a `tree` component.

**Comment by bengwall** [comment]
Or expansion-panels within expansion-panels perhaps (for multi-levels) ???  Does anyone else like the UI of the Fury sidebar?  Thanks for the consideration.  Great work to all those involved in all building this.

**Comment by kyleledbetter** [comment]
expansions within expansion can get heavy on the browser and probably not great on the ux, at that point you'd want a full on tree i think...

**Comment by emoralesb05** [comment]
Closing this in favor of `tree` component or `td-expansion-panel`s
