### ISSUE TITLE
Feature Request - Dynamic Forms add option for Horizontal Form

### ISSUE THREAD

**Issue by chrizy** [Teradata/covalent#604]
Feature Request - Dynamic Forms

It would be nice to have an option to display the label to the left of the input. This makes the input screen clearer when for example writing business apps where you might be sharing the screen in front of a customer, the shrinking labels make it harder to read the screen.

suggested option - Horizontal Form/Stacked Form

Example:
![image](https://cloud.githubusercontent.com/assets/3624292/26222670/d6a7f982-3c12-11e7-895a-1a3093423d25.png)

**Comment by emoralesb05** [comment]
Would need to think about this a bit since `mdInput` placeholder doesnt allow this.. so it would have to be something custom.

**Comment by emoralesb05** [comment]
Closing this since its not in the MD spec for `inputs`
