### ISSUE TITLE
Feature request: Change color for input inside chips

### ISSUE THREAD

**Issue by Dunos** [Teradata/covalent#605]
### **Do you want to request a *feature* or report a *bug*?**

**Feature Request**

Allow to change the color style of the input field inside the td-chips element

**What is the expected behavior?**

To have a property to set the _color_ parameter of the input container so we can easy change the color accordingly to our theme style.

Example of the expected container tag:

```
<md-input-container color="accent">
</md-input-container>
```

**What is the motivation / use case for changing the behavior?**

I have a custom form where some inputs do not use the default _primary_ color, so I need to change the color to other type, like _accent_ or _warn_.

**Comment by emoralesb05** [comment]
Yeah, we need to expose the `color` input for both `chips` and `input`, since now by default its `primary` on both.

**Comment by emoralesb05** [comment]
https://github.com/Teradata/covalent/pull/627 will take care of this.

**Comment by Dunos** [comment]
Excelent, can't wait for it!
