### ISSUE TITLE
td-file-input display image after select it

### ISSUE THREAD

**Issue by carnould** [Teradata/covalent#607]
HTML
                    <img (src)="cover" *ngIf="cover" />

                    <td-file-input (select)="selectEvent($event)"
                                   accept=".jpg,.png,.jpeg"
                                   [multiple]="false">Choose cover</td-file-input>

TS
    selectEvent(file: File) {
        debugger;
        this.cover = file.name;
    }

What i would like is a way to display the image (not the name) after selected it. is it possible?

**Comment by emoralesb05** [comment]
So `file` should give you everything you need to achieve this.. dont have a code snipper how but its basically using `FileReader` and an `img` tag

**Comment by ranouf** [comment]
OK, I will try something with your help, I will post it for the next who are looking for a example :)

**Comment by ranouf** [comment]
selectEvent(file: File) {
        if (file) {
            reader = new FileReader();
            reader.onload = () => {
                this.shop.coverUrl = reader.result;
            };
            reader.readAsDataURL(file);
        }
    }

<img (src)="coverUrl" *ngIf="coverUrl" />

Thank you for your help 👍

**Comment by ranouf** [comment]
I dont know where I can do it, but we can put this issue as Resolved

**Comment by emoralesb05** [comment]
Cool, will close this 😄
