### ISSUE TITLE
Atomic template, how to pass inputs?

### ISSUE THREAD

**Issue by RicardoVaranda** [Teradata/covalent#614]
Hey guys, I'm using Data Table (Atomic) Components

as shown here: https://teradata.github.io/covalent/#/components/data-table

I currently have a table that looks something like the following:

```
<table td-data-table>
  <th td-data-table-column>
    <md-icon>comment</md-icon>
    <span>Comments</span>
  </th>
  <th td-data-table-column
      *ngFor="let column of columns"
      [numeric]="column.numeric">
    {{column.label}}
  </th>
  <tr td-data-table-row *ngFor="let row of basicData">
    <td td-data-table-cell (click)="openPrompt(row, 'comments')">
      <button md-button [class.mat-accent]="!row['comments']">{{row['comments'] || 'Add Comment'}}</button>
    </td>
    <td td-data-table-cell *ngFor="let column of columns" [numeric]="column.numeric">
      {{column.format ? column.format(row[column.name]) : row[column.name]}}
    </td>
  </tr>
</table>
```

How can I pass inputs into td-data-table for example, to enable rows being clickable or sortable ?

Thanks for your time and for the great set of components 👍

**Comment by emoralesb05** [comment]
Is there a reason you are using the atomic components rather than the normal component? Since that behavior is not really included in the atomic components, it is built onto the `td-data-table` component.

Now one might argue that the atomic components should handle it too haha

**Comment by RicardoVaranda** [comment]
Thanks for the reply, ok so let me explain you our use case,

We have a table of data where one of the columns is an image, I was using atomic components in order to be able to render the image rather than show the text. We also wanted to have a field be a tick or an x depending if the column's value was true or false. These are the reasons we needed custom components, the reason I need select or sortable is because I want to make this data table selectable so a user can select a couple of rows.

How hard would it be to implement it into the code, if you could point me in the right way I could look at creating a PR

**Comment by jotatoledo** [comment]
Im pretty sure that u could handle your use case by using row templates as in one of the examples in the documentation, and by doing it you wouldnt use atomic components

**Comment by RicardoVaranda** [comment]
As far as I'm aware, that still doesn't give me access to the tr-data-table-row which is a requirement for our use case. If it's possible could you let me know how I can access the tr-data-table-row with the ng-template

**Comment by emoralesb05** [comment]
You have access to the `row` in the template.

Go into the demo's and check demo number 2.

```
<td-data-table
  [data]="basicData"
  [columns]="columns">
  <ng-template tdDataTableTemplate="type" let-value="value" let-row="row" let-column="column">
    <div layout="row">
      <span flex>{{value}}</span> // or <span flex>{{row[column]}}</span>
      <md-icon>star</md-icon>
    </div>
  </ng-template>
</td-data-table>
```

You have access to the whole `row`, the cell `value` or the `column` name

**Comment by RicardoVaranda** [comment]
Yes, I know you can access the value of row, the thing is I don't need the value of row, I need the tr dom element of the row (td-data-table-row)

**Comment by emoralesb05** [comment]
Ah, gotcha.

To be honest i would not use a `context-menu` and have a icon at the end of the row with the menu. Since the material spec doesnt use `context-menu` that much, or at all to be honest.

**Comment by RicardoVaranda** [comment]
I managed to get this working in the end and quite well, thanks once again for the great component set :)

**Comment by jotatoledo** [comment]
You mind sharing something about your solution for future generations? 😜

**Comment by RicardoVaranda** [comment]
In all fairness most of the issues I experienced were was due to misunderstanding how the component itself worked after taking a look at the components internally it helped clear most of my questions.

So we have a very specific use case to say the least, our table consisted of quite a few out of the ordinary things that you might see in a data table, we needed to display an live updating image in of the columns, the rest of them were normal data, if this didn't complicate it enough, each row in the table also needed to have it's own context menu (we used ngx-contextmenu). Instead of trying to put a Input into the data table instead with atomic templates what you have to do is loop through the array of data something like the following:

```
<table td-data-table>
        <th td-data-table-column
            *ngFor="let column of columns"
            [numeric]="column.numeric">
          {{column.label}}
        </th>
        <tr td-data-table-row *ngFor="let row of data" [contextMenu]="basicMenu" [contextMenuSubject]="row">
          <td td-data-table-cell [numeric]="columns[0].numeric">
            <img (dblclick)="doSomething(row.id)" src="{{row.liveFeed}}" style="max-height: 50px;"/>
          </td>
          <td td-data-table-cell>
            {{row.name}}
          </td>
          <td td-data-table-cell>
            {{row.status}}
          </td>
          <td td-data-table-cell [numeric]="columns[3].numeric">
            {{row.cpu}}
          </td>
          <td td-data-table-cell [numeric]="columns[4].numeric">
            {{row.ram | bytes}}
          </td>
          <td td-data-table-cell [numeric]="columns[5].numeric">
            {{row.storage | bytes}}
          </td>
        </tr>
      </table>
```
