### ISSUE TITLE
a11y(dialogs): select value in prompt dialog

### ISSUE THREAD

**Issue by quanterion** [Teradata/covalent#616]
Native prompt dialog selects value in input making it easier to press BACKSPACE or DELETE key and enter a new value. Currently the user should press BACKSPACE multiple times to remove old value enter a new one.
Can you expose the same behavior in Covalent dialogs or add an option to enable selectAll() on prompt dialog show?

**Comment by emoralesb05** [comment]
Ah, i see. You want the populated text to be `selected` by default. 

We can throw that in the mix, just need to think if we make that a default behavior or configurable.

**Comment by emoralesb05** [comment]
Closing this since it was already merged.

**Comment by quanterion** [comment]
Thank you for great work. It helps so much!
