### ISSUE TITLE
flexible space for toolbars

### ISSUE THREAD

**Issue by bhoproove** [Teradata/covalent#618]
#### Feature Request

Reading up on the material design guideline, I really want the flexible space for toolbar to be included on covalent.

Here is the link to how it acts: 
https://material.io/guidelines/patterns/scrolling-techniques.html#scrolling-techniques-behavior

Basically, it is toolbar resizing the height of itself upon scroll and repositioning of the title or background along with it. Hopefully this is included in next version of your release!

Thank you.

**Comment by kyleledbetter** [comment]
Since we use the md-toolbar this might be a better feature request from @angular/material

**Comment by emoralesb05** [comment]
Closing this since its a request for `angular/material`.
