### ISSUE TITLE
Button text Color

### ISSUE THREAD

**Issue by carnould** [Teradata/covalent#621]
Hi,

How can I configure the app.component.scss to modify the text color of the button? 
Currently it s black, I would like to put a white color.

Currently my app.component.scss is like this:
`@import ' ~@angular/material/core/theming/all-theme';
@import ' ~@covalent/core/theming/all-theme';

@include mat-core();

$mat-custom: ( 50: #FFFFFF, 100: #b2dfdb, 200: #80cbc4, 300: #4db6ac, 400: #26a69a, 500: #60BA02, 600: #00897b, 700: #00796b, 800: #00695c, 900: #004d40, A100: #a7ffeb, A200: #333333, A400: #1de9b6, A700: #00bfa5, contrast: ( 50: $black-87-opacity, 100: $black-87-opacity, 200: $black-87-opacity, 300: $black-87-opacity, 400: $black-87-opacity, 500: white, 600: white, 700: white, 800: $white-87-opacity, 900: $white-87-opacity, A100: $black-87-opacity, A200: $black-87-opacity, A400: $black-87-opacity, A700: $black-87-opacity, ) );

$primary: mat-palette($mat-custom, 500);
$accent: mat-palette($mat-custom, A200, A100, A400);
$warn: mat-palette($mat-red, 600);

$theme: mat-light-theme($primary, $accent, $warn);

@include angular-material-theme($theme);
@include covalent-theme($theme);`

**Comment by carnould** [comment]
In the same time, I would to change the color of the notification count too.

**Comment by emoralesb05** [comment]
Your problem is the contrast in `A200: $black-87-opacity`.

It should be `A200: $white-87-opacity`

**Comment by carnould** [comment]
👍 
Excellent it works perfectly!
