### ISSUE TITLE
TD-Dynamic-Forms: ERROR Error: Cannot find control with name: 'el04'

### ISSUE THREAD

**Issue by pabloxn** [Teradata/covalent#624]
#### Bug Report

I have a form that previews the forms as you build it. When I enter the first element I have no problem - but every subsequent entries after that have the error:

ERROR Error: Cannot find control with name: 'el04'

If I load the saved form it works fine - only seems to be a problem for adding on the fly.

<img width="1413" alt="screen shot 2017-05-25 at 12 50 22" src="https://cloud.githubusercontent.com/assets/18709271/26449205/d7d382e6-4148-11e7-8258-addb68d606dd.png">

#### What is the expected behavior?
to add controls without falling over

**Comment by emoralesb05** [comment]
so you are adding another element on the fly and it fails?

**Comment by pabloxn** [comment]
yup - sorry if I wasn't clear

**Comment by emoralesb05** [comment]
Cool, no worries 😄 

Just wanted to get all the info i could to understand the use case.

**Comment by emoralesb05** [comment]
This will be fixed in `beta.7` but it will be needed to call a new introduced `refresh` method when modifying anything in the element array
