### ISSUE TITLE
DynamicForm formatting

### ISSUE THREAD

**Issue by Randy85253** [Teradata/covalent#625]
Great tech, but the default layout of the DynamicForms is funky, and I'm being kind.  If I could just change the <div layout*> attribute values on the div just under the form element (shown below) I could manage my layout much better.  Specifically, I want layout='column' and layout-align=''. 

How can this be done?  CSS?  ChildViews?  Or does this need to be a change in a future version?

`
<form [formGroup]="dynamicForm" novalidate>
  <div layout="row" 
         layout-wrap 
         layout-margin 
         layout-align="start center">
`
Thanks, and great work.

**Comment by kyleledbetter** [comment]
Funky = planned for MVP

There's other open issues for this. We use Flexbox Layouts for everything so will expose flex width % soon

**Comment by Randy85253** [comment]
Not sure just exposing 'flex width %' will achieve my desired results.  Will this allow for setting the layout to Column as well?
Sorry of this is a nub question.

**Comment by kyleledbetter** [comment]
If flex is 100% the form element would have its own row. Is that what you're going for?

**Comment by Randy85253** [comment]
Basically, I will just wait and see.   My concern is wrapping the whole form in a 'layout-row' div. 

Is there a ETA for this?

I understand how complex form building can get.  A few years ago I build a form composition UI on  ExtJS. I look forward to getting this update and testing it out.

Again, great work.  & Thanks for the response

**Comment by kyleledbetter** [comment]
you can achieve this now w/ a simple scss override in styles.scss add:

```
td-dynamic-element {
    -webkit-box-flex: 1 !important;
    -ms-flex: 1 1 100% !important;
    flex: 1 1 100% !important;
    max-width: 100% !important;
}
```

no ETA yet, hasn't been triaged or assigned

**Comment by jeremysmartt** [comment]
@JulieMarie to investigate
