### ISSUE TITLE
Design for autocomplete with custom inputs  or custom chips

### ISSUE THREAD

**Issue by anapanadero** [Teradata/covalent#629]
The placeholders and labels for autocomplete with custom inputs or custom chips doesn't follow the official Material Design spec guidelines.

![autocomplete](https://cloud.githubusercontent.com/assets/8911984/26487764/1e0f14e2-4201-11e7-9f6c-7d9f0b914834.png)

**Comment by kyleledbetter** [comment]
That spec if for the standalone autocomplete this is chips autocomplete so slightly different usage and we're using a non float label that's a feature of angular material, and we're also following the pattern of chips autocomplete from angular-material v1
