### ISSUE TITLE
there is a problem with TdMediaService

### ISSUE THREAD

**Issue by agborkowski** [Teradata/covalent#630]
#### Bug Report

1) i tried used RWD service like in docs by
`
import { TdMediaService } from '@covalent/core';
`
2) app loading is catch and i get error in console: No provider for TdMediaService

#### What is the expected behavior?
Load service and start broadcast

#### Which version of Angular and Material, and which browser and OS does this issue affect?
Angular 4.0.0
2.0.0-beta.5

##### Other information
i tried use covalent beta and night build, file responsible for that service (media.service.d.ts) in TS is different than in master branch

**Comment by agborkowski** [comment]
ok i fixed it, i didn't add CovalentMediaModule to module..

**Comment by agborkowski** [comment]
ok i fixed it, i didn't add CovalentMediaModule to module..

**Comment by wizlif** [comment]
```
StaticInjectorError(AppModule)[SearchComponent -> TdLoadingService]: 
  StaticInjectorError(Platform: core)[SearchComponent -> TdLoadingService]: 
    NullInjectorError: No provider for TdLoadingService!
Error: StaticInjectorError(AppModule)[SearchComponent -> TdLoadingService]: 
  StaticInjectorError(Platform: core)[SearchComponent -> TdLoadingService]: 
    NullInjectorError: No provider for TdLoadingService!
```
When i import from
` import { CovalentMediaModule} from '@covalent/core/media';`
and no error when i import from
`import { CovalentMediaModule} from '@covalent/core';`

**Comment by emoralesb05** [comment]
You need to import everything from either `@covalent/core` or everything from the secondary entry points.. if you mix them you will get this error..
