### ISSUE TITLE
Question: Do you plan to use material2/md-data-table as base for td-data-table?

### ISSUE THREAD

**Issue by jvbianchi** [Teradata/covalent#635]
When [material2/md-data-table](https://github.com/angular/material2/issues/581) becomes stable, do you plan to use as base to td-data-table?

**Comment by jotatoledo** [comment]
Not truly relevant at the moment in my opinion. The data table component of material is still in design/alpha state. So its going to take some (long) time to see it ready 😄

Btw, most likely the dev team of covalent already took care of this by sticking to material design. And for what I saw both components handle the data as an immutable collection, so conceptually they are most likely very similar

**Comment by kyleledbetter** [comment]
we'll take a look at wrapping md-data-table (as we did w/ our autocomplete chips) when it's released, but it will be some time before they release, and we're going to continue adding features to ours. closing since it's a conversation more than an issue
