### ISSUE TITLE
material 2.0.0-beta.6 theme import

### ISSUE THREAD

**Issue by lanmingle** [Teradata/covalent#636]
ERROR in ./~/css-loader?{"sourceMap":false,"importLoaders":1}!./~/postcss-loader?{"ident":"postcss"}!./~/sass-loader/lib/loader.js?{"sourceMap":false,"precision":8,"includePaths":[]}!./src/themes.s
css
Module build failed:
undefined
              ^
      Argument `$color` of `opacity($color)` must be a color

Backtrace:
        node_modules/@covalent/core/common/styles/_theme-functions.scss:58, in function `opacity`
        node_modules/@covalent/core/common/styles/_theme-functions.scss:58, in function `if`
        node_modules/@covalent/core/common/styles/_theme-functions.scss:58, in function `mat-color`
        node_modules/@angular/material/_theming.scss:2540, in mixin `mat-slider-theme`
        node_modules/@angular/material/_theming.scss:2757, in mixin `angular-material-theme`
        stdin:13
      in E:\Projects\local\covalent-example\node_modules\@covalent\core\common\styles\_theme-functions.scss (line 58, column 16)
 @ ./src/themes.scss 4:14-189
 @ multi ./~/@covalent/core/common/platform.scss ./src/styles.scss ./src/themes.scss

@angular/material": "2.0.0-beta.5 is ok
@angular/material": "2.0.0-beta.6 is error

**Comment by jotatoledo** [comment]
Same error for me, had to go back to material 5

**Comment by emoralesb05** [comment]
dup: https://github.com/Teradata/covalent/issues/632

Already fixed.
