### ISSUE TITLE
[Bug] Adding covalent theming to theme.scss

### ISSUE THREAD

**Issue by MRMokwa** [Teradata/covalent#637]
#### Bug Report
When I add `@import '~@covalent/core/theming/all-theme';` inside of my themes.scss app breaks.

Brand new instalation:

1. `ng new my-app --style scss`
2. Follow [getting started](https://material.angular.io/guide/getting-started) of angular-material (steps 1 to 4)
2.1. Add Custom theme.scss from [theming guide](https://material.angular.io/guide/theming)
2.2. Add theme.scss to angular-cli.scss

Here, everything works: materal styling and material components (button for example).

3. `npm install --save @covalent/core`
4. Add to angular-cli.json platform.css

>  "styles": [
>         `"../node_modules/@covalent/core/common/platform.scss"`,
>         "styles.scss",
>         "themes.scss"
>       ],

5. Include the core
5.1. Inside of theme.scss `@import '~@covalent/core/theming/all-theme';`

6. ng serve
6.1. App breaks

##### Screenshots or link to CodePen/Plunker/JSfiddle
![image](https://cloud.githubusercontent.com/assets/12090931/26559401/bce2e072-4485-11e7-820e-86f6b26b196a.png)

#### Which version of Angular and Material, and which browser and OS does this issue affect?

![image](https://cloud.githubusercontent.com/assets/12090931/26559406/c50a34ee-4485-11e7-88ea-7b265a860a1d.png)

**Comment by emoralesb05** [comment]
Duplicate of https://github.com/Teradata/covalent/issues/632

This was already fixed but its not yet released.

You can try using our `nightly build` to verify or return to `material@beta.5` until we release our `beta.5`

**Comment by MRMokwa** [comment]
Ops, my bad. I'm closing it.
