### ISSUE TITLE
Prerendering components

### ISSUE THREAD

**Issue by lycanlee** [Teradata/covalent#638]
I have scaffolded a project with Angular 4 and ASP Core using https://github.com/aspnet/JavaScriptServices
npm install -g yo generator-aspnetcore-spa. I have tried adding covalent however I am getting errors when attempting to run. 

When I add the following line to the app.module.shared.ts
import { CovalentLayoutModule, CovalentStepsModule /*, any other modules */ } from '@covalent/core'; 

I get "  An unhandled exception has occurred: Call to Node module failed with error: Prerendering failed because of error: ReferenceError: window is not defined"

which lead me to believe there is an issue with pre-rendering the component. But when I add the same line to the app.module.client.ts file then it does not recognize any layout component. (ex. <td-layout>).

I have added the following lines to my webpack.config.vendor.js hoping it might resolve part of the issue but haven't got any luck. 
 '@covalent/core',
 '@covalent/core/common/platform.css',

Any insight would be greatly appreciated

![dotnet run](https://cloud.githubusercontent.com/assets/13842022/26561627/ded9e6b4-448d-11e7-8f5c-98648cc9d5f9.PNG)

**Comment by emoralesb05** [comment]
Yeah, we still have some components that dont support server side rendering. 

We are trying our best to find out which ones are failing, so any more information would be awesome!

For the most part we need to stop using `window` or `DOM` access as much as possible.
