### ISSUE TITLE
Feature Request, object.property binding in TdChips

### ISSUE THREAD

**Issue by zyarnold** [Teradata/covalent#644]
```
//..component.ts
this.heroes= [
  { id:1, name:"Groot"  },
  { id:21, name:"StarLord" }
];
```
```
//..component.html
<td-chips [(ngModel)]="favoriteHeroID" [items]="heroes" [chipValue]="'item.id'" [chipTitle]="'item.name'"  ></td-chips>
```

chipValue and chipTitle should default to 'item' if not specified

**Comment by emoralesb05** [comment]
Already merge object support https://github.com/Teradata/covalent/pull/626 and will be available in beta.5

**Comment by emoralesb05** [comment]
#### Usage
```
<td-chips [items]="objects"
          [(ngModel)]="objectsModel"
          requireMatch>
  <ng-template td-basic-chip let-chip="chip">
    {{chip.city}}, (Pop: {{chip.population}})
  </ng-template>
  <ng-template td-autocomplete-option let-option="option">
    <md-icon>location_city</md-icon> {{option.city}}
  </ng-template>
</td-chips>
```

**Comment by zyarnold** [comment]
> <td-chips [items]="objects"
>           [(ngModel)]="objectsModel"
>           requireMatch>
>   <ng-template td-basic-chip let-chip="chip">
>     {{chip.city}}, (Pop: {{chip.population}})
>   </ng-template>
>   <ng-template td-autocomplete-option let-option="option">
>     <md-icon>location_city</md-icon> {{option.city}}
>   </ng-template>
> </td-chips>

so how do I command the chip to bind ngmodel on the .city while displaying .population as a display string?

**Comment by emoralesb05** [comment]
`let-chip="chip"` in the template micro syntax

**Comment by zyarnold** [comment]
ok thanks...please close issue

**Comment by denyshetzel** [comment]
How to add new chip working with objects and autocomplete? 
When I add a new chip, it does not appear as expected. I did not find a way to solve this.

![image](https://user-images.githubusercontent.com/25107256/28908950-4e2a1694-77f4-11e7-9563-4c25328da9bf.png)

Please see the test code: http://plnkr.co/edit/iR7Pbq?p=preview
