### ISSUE TITLE
 Is there a plan to increase DatePicker? It's very often used.

### ISSUE THREAD

**Issue by xiaochong44** [Teradata/covalent#648]
Is there a plan to increase DatePicker? It's very often used.

**Comment by emoralesb05** [comment]
Increase datepicker? what do you mean by that?

**Comment by kyleledbetter** [comment]
We include all the angular material components including datepicker if you meant include: https://material.angular.io/components/component/datepicker

**Comment by xiaochong44** [comment]
@kyleledbetter 
very good.
I didn't see it in demo. Ask all of them

**Comment by jotatoledo** [comment]
wut

**Comment by emoralesb05** [comment]
Closing this since its not related to covalent, and `md-datepicker` is a material component that can be used already since `material@beta.5`
