### ISSUE TITLE
Module not found error

### ISSUE THREAD

**Issue by tabrez96** [Teradata/covalent#651]
This repository's issues are reserved for feature requests and bug reports.

#### Bug Report

Failed to compile.

./~/css-loader?{"sourceMap":false,"importLoaders":1}!./~/postcss-loader?{"ident":"postcss"}!./src/styles.css
Module not found: Error: Can't resolve '@covalent/core/theming/all-theme' in 'F:\Demo\New folder\New folder\ang-mterial\src'
 @ ./~/css-loader?{"sourceMap":false,"importLoaders":1}!./~/postcss-loader?{"ident":"postcss"}!./src/styles.css 4:10-182
 @ ./src/styles.css
 @ multi ./src/styles.css

#### Which version of Angular and Material, and which browser and OS does this issue affect?

@angular/cli: 1.1.0
node: 6.10.3
os: win32 x64
@angular/animations: 4.1.3
@angular/common: 4.1.3
@angular/compiler: 4.1.3
@angular/core: 4.1.3
@angular/forms: 4.1.3
@angular/http: 4.1.3
@angular/material: 2.0.0-beta.6
@angular/platform-browser: 4.1.3
@angular/platform-browser-dynamic: 4.1.3
@angular/router: 4.1.3
@angular/cli: 1.1.0
@angular/compiler-cli: 4.1.3
@angular/language-service: 4.1.3
node :6.10.3
npm:3.10.10
browser used : Chrome
Windows 8 64 bit
##### Other information
(e.g. detailed explanation, stacktraces, related issues, suggestions how to fix)

**Comment by jotatoledo** [comment]
downgrade material to beta5

**Comment by MRMokwa** [comment]
Already fixed for beta 5 and should come online soon.

**Comment by tabrez96** [comment]
@jotatoledo mate I'm totally new to covalent and material. Can you please walk me through the downgrade process.

**Comment by jotatoledo** [comment]
- delete the `node_modules` folder in your project folder
- change the `@angular/material` version in your package.json file
- run `npm install`

**Comment by emoralesb05** [comment]
Any updates on this?

**Comment by tabrez96** [comment]
Works fine now! Thanks mate
