### ISSUE TITLE
Datatable: Select All Rows doesn't trigger ngModelChange

### ISSUE THREAD

**Issue by jeremysmartt** [Teradata/covalent#652]
#### Bug Report

Example:
Markup:
```
<td-data-table
          #dataTable
          [data]="filteredData"
          [columns]="columns"
          [selectable]="selectable"
          [clickable]="clickable"
          [multiple]="multiple"
          [sortable]="true"
          [sortBy]="sortBy"
          [(ngModel)]="selectedRows"
          (ngModelChange)="getDataArray(selectedRows)"
          [sortOrder]="sortOrder"
          (sortChange)="sort($event)"
          (rowClick)="showAlert($event)">
```

Typescript:
```
getDataArray(rows: any): void {
    for (let i: number = 0; i < rows.length; i++) {
      // do something
      console.log(rows[i].id);
    }
  }
```
getDataArray is never called on Select All

#### What is the expected behavior?
getDataArray is called on Select All

#### What is the motivation / use case for changing the behavior?
Ability to use ngModelChange

**Comment by emoralesb05** [comment]
does `selectRow` trigger it? 🤔 

Since technically the`ngModel` never changes in either case because its an array reference.

**Comment by jeremysmartt** [comment]
@emoralesb05 Yes, it works for a single selection.

**Comment by emoralesb05** [comment]
ah, i see why. 

We call the `change` event on single but not on all.
