### ISSUE TITLE
Feature request : "old-fashioned" menu in toolbar

### ISSUE THREAD

**Issue by jpmous** [Teradata/covalent#656]
Hello,

I know it is not in material design principles, but for a web appli (still) targeted first for desktop, it would be fine to have a cute menu in toolbar. And with an active class to show active page.

JPM

**Comment by jotatoledo** [comment]
You cant call this a feature request...

- Use the issue template
- Define "cute"  (maybe some examples) :smile: 
- Define "old fashioned" (maybe some examples) :smile: 
- The class `active `can be defined by yourself

**Comment by emoralesb05** [comment]
I think for the most part this can already be achieved with `md-tab` links and `md-menu`s in a toolbar. So i think its more of a template or design pattern.

**Comment by kyleledbetter** [comment]
I've got an example here http://embed.plnkr.co/imBanFIiKDgBLK0aH3Dr/

**Comment by kyleledbetter** [comment]
And if you want dropdowns you could probably trigger them from the top tab links and md-menu's

**Comment by jpmous** [comment]
Hello,

Sorry I was not clear (and in fact did not want to refer other UI framework)
Here is an example of a "old-fashioned" menu : http://hpics.li/b0bcad0
The drawer is fine for mobile, not my preference for desktop app.
When there are not many icons to display, toolbar looks empty.

I just saw the "Covelant Templates" from quickstart (even it takes some height) : will have a deeper look .

The issue template was too oriented "issue" at first sight : I will pay attention next time.

Thanks

JPM

**Comment by kyleledbetter** [comment]
Did you check the landing page template? http://embed.plnkr.co/imBanFIiKDgBLK0aH3Dr/

It uses tabs for a menu like your screenshot

**Comment by kyleledbetter** [comment]
you can also reference the new top menu in the Covalent docs https://github.com/Teradata/covalent/blob/develop/src/app/components/toolbar/toolbar.component.html#L7-L13

gonna close this as we have several alternatives given w/o building a new component
