### ISSUE TITLE
TdDialogService should take an optional validator as an input

### ISSUE THREAD

**Issue by Xample** [Teradata/covalent#660]
#### Feature Request
TdDialogService should allow putting a validator while we enter the text.
I am using it to rename files and would need to disable the okay button in the case the name already exists.

**Comment by emoralesb05** [comment]
I think this will cover your need https://github.com/Teradata/covalent/pull/606

**Comment by jotatoledo** [comment]
Ill get the pr done during the weekend! :muscle:
