### ISSUE TITLE
How to upgrade from beta 3.2 to beta 4

### ISSUE THREAD

**Issue by aliabbas-2012** [Teradata/covalent#661]
I had 1.0.0-beta.3-2 now upgraded to 1.0.0-beta.4, none of the things are working 

I am facing  Unhandled Promise rejection: Template parse errors: 
`<table td-data-table #dataTable>

    <th td-data-table-column [ERROR ->]*ngFor="let column of columns" width="{{column.width}}" [numeric]="column.numeric" [sortable]="true"
"): ng:///SharedModule/DatatableComponent.html@12:29
Property binding ngForOf not used by any directive on an embedded template. Make sure that the property name is spelled correctly and all directives are listed in the "@NgModule.declarations". ("
`

**Comment by aliabbas-2012** [comment]
Problem with "CovalentCoreModule" it is not found n beta 4

Thanks

**Comment by aliabbas-2012** [comment]
If you can give me the quick start of beta-4 that will be great. original quick starts also not working, I have changed everything according to [https://github.com/Teradata/covalent/blob/develop/docs/CHANGELOG.md#100-beta4-johnny-b-goode-2017-05-16](https://github.com/Teradata/covalent/blob/develop/docs/CHANGELOG.md#100-beta4-johnny-b-goode-2017-05-16

**Comment by lincze** [comment]
if you checkout the current quickstart on develop, it is built with beta-4 of covalent core

**Comment by jotatoledo** [comment]
The CovalentCoreModule was deprecated in beta.4, developers now have to import the modules that they need individually. The only detail in the quickstart repo is that uses material beta.6, but the current version of covalent is not compatible with it (beta.5 will). So you need material beta.5 to use covalent beta.4

**Comment by kyleledbetter** [comment]
@jotatoledo would you mind doing a quick PR fixing that ?
Really appreciate all your help

**Comment by emoralesb05** [comment]
He already did and its already merged~ 😄

**Comment by aliabbas-2012** [comment]
I got it

Thanks


*Ali Abbas*
*Senior Software Engineer ( Php , Python , Ror)*
*skype : ali.abbas2012*

**Comment by emoralesb05** [comment]
Closing this since quickstart is running in beta.4 and people can reference for it.
