### ISSUE TITLE
Compiler warnings with latest Angular 4.2.0-rc.2

### ISSUE THREAD

**Issue by paistipoikka** [Teradata/covalent#662]
### Do you want to request a *feature* or report a *bug*?

Bug (well not yet but it has the potential to be)

#### Bug Report

When compiling the application after upgrading angular to latest RC. 

```
WARNING in ./~/@covalent/core/common/animations/toggle/toggle.directive.js
24:27-45 "export 'ɵDomAnimationEngine' (imported as 'DomAnimationEngine') was not found in '@angular/animations/browser'

WARNING in ./~/@covalent/core/common/animations/fade/fade.directive.js
34:27-45 "export 'ɵDomAnimationEngine' (imported as 'DomAnimationEngine') was not found in '@angular/animations/browser'
```
#### What is the expected behavior?

No compile warnings.

#### Which version of Angular and Material, and which browser and OS does this issue affect?

4.2.0-rc.2
Covalent 1.0.0 Beta 4

Did this work in previous versions of Angular / Material?

Yes

**Comment by emoralesb05** [comment]
Yup, we fixed those already. You can keep track of them in this PR https://github.com/Teradata/covalent/pull/608

**Comment by paistipoikka** [comment]
Thanks @emoralesb05
