### ISSUE TITLE
td-data-table: Posibility to hide columns depending on screen resolution

### ISSUE THREAD

**Issue by vertigo7x** [Teradata/covalent#667]
### Do you want to request a *feature* or report a *bug*?

feature

#### Feature Request

Add the possibility  to hide or show columns depending on screen resolution or orientation.

#### What is the expected behavior?

Depending on screen resolution, the columns might be shown or hidden.

##### Other information

 I've implemented a solution using the atomic components with the TdMediaService and a method witch is called on every resolution change. I would like to use the same mechanism but I don't know how to access (or even if it's possible) the refresh method of the td-data-table from component side.

**Comment by emoralesb05** [comment]
Yeah, you can access the data table within a component and call its refresh method via `@ViewChild`

**Comment by vertigo7x** [comment]
Thanks for your response @emoralesb05. I'm a newbie with Angular and sometimes it's hard to know all the possibilities it offers. Thanks for the great work you and your team are doing!
Works perfectly!

**Comment by emoralesb05** [comment]
No worries! Thanks for the support 😄
