### ISSUE TITLE
Layout Footer

### ISSUE THREAD

**Issue by netbka** [Teradata/covalent#668]
This repository's issues are reserved for feature requests and bug reports.

### Do you want to request a *feature* or report a *bug*?
Bug

#### Bug Report

Tried to apply "primary" color for td-layout-footer color="primary"
and the color remains grey, while applying to
td-layout-nav toolbarTitle="Title" icon="verified_user" color="primary" navigationRoute="/"
is making toolbar with correct primary color.

**Comment by kyleledbetter** [comment]
Closing dup of https://github.com/Teradata/covalent/issues/489
We'll get to it soon
(You could easily style with CSS until then)
