### ISSUE TITLE
Custom Data Table sorting arrows not changed

### ISSUE THREAD

**Issue by aliabbas-2012** [Teradata/covalent#673]
Custom Data table sorting arrows are not changing, Good thing is sorting is working but arrows are not changing 
Here are the pictures
**Sort By asc**

![screenshot_order_asc](https://user-images.githubusercontent.com/2234215/26926197-256b9138-4c66-11e7-81dc-51e363e7b65b.jpg)

**Sort By Desc**

![screenshot order_desc](https://user-images.githubusercontent.com/2234215/26926205-30fd4dd4-4c66-11e7-8ebc-3176cc2448de.jpg)

**Here is my code** 

`<table td-data-table #dataTable>

    <th td-data-table-column *ngFor="let column of columns" [numeric]="column.numeric" 
 [sortable]="true"
        [sortOrder]="columnSortOrders[column.name]" (sortChange)="sort($event,column.name)">
        {{column.label}}
    </th>

    <tbody>
      
        <tr td-data-table-row *ngFor="let row of filteredData; let index=index" on-mouseover="hoveredIndex=index">
            <td td-data-table-cell *ngFor="let column of columns" [numeric]="column.numeric">
                {{column.format ? column.format(row[column.name]) : row[column.name]}}
            </td>
            

        </tr>
    </tbody>
</table>`

What thing is wrong ? it should change the arrows also for Customs Data Table, We need Custom because we need to add custom buttons and menus

**Comment by emoralesb05** [comment]
Can you create a plnkr with the issue?

**Comment by aliabbas-2012** [comment]
Sure tomorrow

Thanks

**Comment by aliabbas-2012** [comment]
[https://embed.plnkr.co/RKZfDexIjOmR5zfRdYjH/](https://embed.plnkr.co/RKZfDexIjOmR5zfRdYjH/)

**Comment by emoralesb05** [comment]
Ah, i see whats happening. You are missing the [active] input.

Add [active]="true" when you are sorting something so it renders the icons and keeps them there.

**Comment by aliabbas-2012** [comment]
Many Thanks
