### ISSUE TITLE
td-data-table: Date column not sorting correctly:

### ISSUE THREAD

**Issue by rahulasharm** [Teradata/covalent#674]
TD data table: date column sorting but not correctly
before pipe 2017-04-13T12:58:07.560Z and after using pipe Apr 13, 2017 18:28:07 not sorting correctly. and some date column not even sorts as well.

![sort 2](https://user-images.githubusercontent.com/27914600/26933948-9ff21d0e-4c85-11e7-89a0-18a768fc0c5a.jpg)

![sort](https://user-images.githubusercontent.com/27914600/26933981-b34eac96-4c85-11e7-84c6-c959277548c3.jpg)

**Comment by Octopixell** [comment]
I got the similar issue where dates are not being sorted by the data table at all. Same as this issue -> https://github.com/Teradata/covalent/issues/461 - Could be these issues are related.
