### ISSUE TITLE
Add executable Data Table Example to quickstart

### ISSUE THREAD

**Issue by javajosh** [Teradata/covalent#675]
#### Feature Request
Add a Data Table example to https://teradata.github.io/covalent-quickstart/

##### Other information
I'm just learning Angular, Material, and Covalent, and would really appreciate a fully working Data Table example, a la the quickstart. Other components are exercised in the above project, but not Data Table. The component documentation at https://teradata.github.io/covalent/#/components/data-table contains some good examples, but it can be difficult to get Covalent working, especially in the presence of changing names & technology. (Also there are some minor problems with the example code that make it not work as-is, mainly just typos in the code).

It would also be nice to get some information about the upcoming Angular Material Grid component, which was mentioned in the Angular Material blog recently.

**Comment by emoralesb05** [comment]
We might actually add an example as a template.

Once the `cdk-datatable` is up and good to go, we are probably gonna use it internally to leverage its features.

**Comment by javajosh** [comment]
Ah, okay. I'm going to leave a comment here with a little post-mortem so I can check on progress later :)

I didn't see a demo of ck-datatable in https://material.angular.io/components so I didn't know of it's existence. Nor is it in the [Angular Material2 demo](https://material2-app.firebaseapp.com/). Putting together clues (importantly an [Apr 15 2017 Google Doc](https://docs.google.com/document/d/1ZyKhwrgqfTBAn7saTq2jPlep2_CwSw5DeoZ8UbaXrC0/edit) by Andrew Seguin (andrewseguin), Erin Coughlan (ErinCoughlan)... presumably @google? )...and also the list of statuses at [angular/material2](https://github.com/angular/material2) says that they are currently working on an official data-grid under [issue 581](https://github.com/angular/material2/issues/581).
