### ISSUE TITLE
Spacebar interaction with Data Table input

### ISSUE THREAD

**Issue by Pypoli** [Teradata/covalent#677]
#### Bug Report
When creating a data-table with selectable rows that include inputs, any attempt to use the space bar doesn't register the space and selects the row. 

#### What is the expected behavior?
A space gets added to the input and the row is not selected

#### Which version of Angular and Material, and which browser and OS does this issue affect?
Using Windows 7.
On Chrome: No space and the row is selected.
On Internet Explorer 11.0.42: The space IS added, and the row is selected

##### Other information
I understand that this is intentional behavior (I was able to change this behavior by directly editing data-table files), however it clashes with the use of inputs inside the table. Ideally i could pass a parameter that would disable this behavior.

**Comment by GroverShipra** [comment]
Any update on this issue... i'm facing the same

**Comment by emoralesb05** [comment]
I think you can stop the event propagation with `$event.stopPropagation` for this cases in the `(keydown.space)` or `(keyup.space)`

**Comment by jeremysmartt** [comment]
no traction on issue in a year, closing
