### ISSUE TITLE
IHttpInterceptor and Authorization header

### ISSUE THREAD

**Issue by webplease** [Teradata/covalent#683]
Hi to all,

using IHttpInterceptor is it possible to add an Authorization header? Where ?

Thanks.

**Comment by emoralesb05** [comment]
Yup, you do it in the `onRequest` method, you can access the `headers` there and include it.

**Comment by webplease** [comment]
`onRequest(requestOptions: RequestOptionsArgs): RequestOptionsArgs {
    requestOptions.headers = new Headers({ 'Authorization': 'Bearer ' + mytoken });
    return requestOptions;
}`

Perfect, thanks!

**Comment by emoralesb05** [comment]
Closing this but setting as `faq` for future questions
