### ISSUE TITLE
Feature request: add clickeable property in ITdDataTableColumn

### ISSUE THREAD

**Issue by jotatoledo** [Teradata/covalent#688]
#### Feature Request

Allow developers to define if a column is clickable or not individually through the interface. 

This might be related to some other issues in the tracker.

#### What is the motivation / use case for changing the behavior?

In one of my applications, I wanted to define an options column, where a dropdown menu is displayed on click with a set of actions to apply in the corresponding row. On row click I navigate to a details page of the clicked row. By clicking in the dropdown menu, navigation to the details page is triggered. 

I can think that there a lot of other use cases where a developer would like to be able to set a column as non clickable, withouth having to turn off this feature in the whole table

**Comment by emoralesb05** [comment]
You can do that right now by adding a `stopRowClick` attr 

https://github.com/Teradata/covalent/blob/develop/src/platform/core/data-table/data-table.component.html#L44

Not the best way to do it, but we had to somehow check which elements are clickable and which ones arent internally with this.

**Comment by jotatoledo** [comment]
Havent tried until now, I need to make some small changes to test your suggestion. Ill reply as soon as I try

**Comment by jotatoledo** [comment]
Hey @emoralesb05, sorry for the late reply. I just tried to apply your suggestion but I cant find a way to not trigger the rowClick. I guess it could be possible/easier to do by using atomic components, but its not my case. 

I currently have the following template:

```
<td-data-table #dataTable [data]="entries" [columns]="columns" [clickable]="true" (rowClick)="handleRowClick($event)">
  <ng-template tdDataTableTemplate="actions" let-value="value" let-row="row">
    <div fxLayout="row" fxLayoutAlign="center center">
      <button md-mini-fab color="warn" (click)="handleDelete(row.dbParam)" mdTooltip="{{ 'TERM.DELETE' | translate }}">
        <md-icon>delete</md-icon>
      </button>
    </div>
  </ng-template>
</td-data-table>
```

I added the `stopRowClick ` in all the childs of ng-template and in this last, but no success.

By checking https://github.com/Teradata/covalent/blob/develop/src/platform/core/data-table/data-table.component.html#L54 I guess that there is no way to add `stopRowClick `attribute to the `td `node that containts the rendered template (in this case the div element) 😢

**Comment by emoralesb05** [comment]
Well, in reality we might revamp the data-table a bit to make it more flexible.. since its getting hard to expose all the events per cell, column and even row.. so it makes more sense to do it in a way where those things are exposed to the devs and they can implement any event they want. Still brainstorming a bit on it and checking if we can leverage the cdk-table from material.

**Comment by jotatoledo** [comment]
That would be great. For now I will just bind the effect that I wanted to archive to a button rendered in the action column of my template.

**Comment by elmartino** [comment]
any news on this?
