### ISSUE TITLE
Failed to execute 'animate' on 'Element': Partial keyframes are not supported.

### ISSUE THREAD

**Issue by jt-helsinki** [Teradata/covalent#695]
This repository's issues are reserved for feature requests and bug reports.

### Do you want to request a *feature* or report a *bug*?

Bug

#### Bug Report

An application that uses the `tdToggle` directive is throwing the following error:

> SomeForm.html:57 ERROR DOMException: Failed to execute 'animate' on 'Element': Partial keyframes are not supported.
>     at WebAnimationsPlayer.webpackJsonp../node_modules/@angular/animations/@angular/animations/browser.es5.js.WebAnimationsPlayer._triggerWebAnimation (http://localhost:4200/vendor.bundle.js:8940:35)
>     at WebAnimationsPlayer.webpackJsonp../node_modules/@angular/animations/@angular/animations/browser.es5.js.WebAnimationsPlayer._buildPlayer (http://localhost:4200/vendor.bundle.js:8914:29)
>     at WebAnimationsPlayer.webpackJsonp../node_modules/@angular/animations/@angular/animations/browser.es5.js.WebAnimationsPlayer.play (http://localhost:4200/vendor.bundle.js:8969:14)
>     at TimelineAnimationEngine.webpackJsonp../node_modules/@angular/animations/@angular/animations/browser.es5.js.TimelineAnimationEngine.command (http://localhost:4200/vendor.bundle.js:7115:24)
>     at InjectableAnimationEngine.webpackJsonp../node_modules/@angular/animations/@angular/animations/browser.es5.js.AnimationEngine.setProperty (http://localhost:4200/vendor.bundle.js:8778:34)
>     at AnimationRenderer.webpackJsonp../node_modules/@angular/platform-browser/@angular/platform-browser/animations.es5.js.AnimationRenderer.setProperty (http://localhost:4200/vendor.bundle.js:98641:25)
>     at issueAnimationCommand (http://localhost:4200/vendor.bundle.js:98324:21)
>     at RendererAnimationPlayer.webpackJsonp../node_modules/@angular/platform-browser/@angular/platform-browser/animations.es5.js.RendererAnimationPlayer._command (http://localhost:4200/vendor.bundle.js:98252:16)
>     at RendererAnimationPlayer.webpackJsonp../node_modules/@angular/platform-browser/@angular/platform-browser/animations.es5.js.RendererAnimationPlayer.play (http://localhost:4200/vendor.bundle.js:98281:14)
>     at TdToggleDirective.webpackJsonp../node_modules/@covalent/core/common/animations/toggle/toggle.directive.js.TdToggleDirective.hide (http://localhost:4200/vendor.bundle.js:106807:35)

#### What is the expected behavior?

This happened with the latest upgrade of angular / covalent.

#### Which version of Angular and Material, and which browser and OS does this issue affect?

Angular 4.2.2
Material 2.0.0-beta.6
Covalent 1.0.0-beta.5-1

Did this work in previous versions of Angular / Material?

Works with: Covalent 1.0.0-beta.4 works with Angular 4.1.3/Material 2.0.0-beta.6

Please also test with the latest stable and snapshot versions.

Covalent 1.0.0-beta.4 works with Angular 4.2.2/Material 2.0.0-beta.6 - not working
Covalent 1.0.0-beta.5-1 does not work with Angular 4.1.3/Material 2.0.0-beta.6 - not working

##### Other information
(e.g. detailed explanation, stacktraces, related issues, suggestions how to fix)

**Comment by emoralesb05** [comment]
Can you do a plnkr to show when this happens? We have it in our docs and its not throwing that error.

**Comment by paistipoikka** [comment]
uurrghh...I thought you might ask that. I will try to produce a plnkr however in the meantime this is the offending code...

`<div [tdToggle]="(hideEntryForm || !(licenceDateValidForRaceMeet && eligibleCategories.length))"> `

Based on a web search, it appears that this may be a problem with Angular and not Covalent. However I may be wrong.

**Comment by emoralesb05** [comment]
I think it might be a bit of both. The reason we ask for a plunkr is because sometimes the context affect the behavior.. like if its in a `md-tab` or something.

**Comment by paistipoikka** [comment]
@emoralesb05 Yes, It's a component nested in an `md-tab` so it may be due to this: 

[angular/material2#4271](https://github.com/angular/material2/issues/4271)

I've also found other instances in the application where this error happens. They are also nested inside `md-tab` components.

**Comment by jotatoledo** [comment]
Im seeing the same error using a `tdToggle` directive inside of a `td-layout-manage-list`

**Comment by jotatoledo** [comment]
Up, this is still visible on latest.

**Comment by merry75** [comment]
I have exactly the same issue but not for electron but angular web app. I dont know how to fix the issue
