### ISSUE TITLE
Feature: sidenav fit width to content

### ISSUE THREAD

**Issue by jibbers42** [Teradata/covalent#696]
#### Feature Request
Modify sidenav width to fit content, like `<md-sidenav>`.

#### What is the motivation / use case for changing the behavior?
Make it easier to fit nav items with proper whitespace and no horizontal scrolling.

Also, regarding:
https://teradata.github.io/covalent/#/layouts
> Sets the 'width' of the sidenav in either 'px' or '%' ('%' is not well supported yet as stated in the layout docs). Defaults to '320px'.

Where are the mentioned docs that discusses this?

**Comment by emoralesb05** [comment]
I think they already fixed the % issue. So we will be removing that from the docs.

By default the sidenav has a fixed `px` width, but you can override it by stating `[sidenavWidth]="undefined"`, so it takes the native width from the md-sidenav.

**Comment by jibbers42** [comment]
It never occurred to me to do that, thanks! I wonder if that tip should be put in the docs when they get updated (or maybe it's considered common knowledge)?

**Comment by emoralesb05** [comment]
I think we are gonna remove the default width and make people provide one if needed. Its more strwightforward to add one than to override it to remove it.
