### ISSUE TITLE
Navigation drawer drop arrow and text alignment a bit off

### ISSUE THREAD

**Issue by jibbers42** [Teradata/covalent#697]
#### Bug Report
In the `navigation-drawer`, the vertical alignment of the name or email and the drop arrow are a bit off. Also, the cursor is a pointer on the arrow, but not the text even though the action triggers for both.

##### Other information
I'm guessing we can just change https://github.com/Teradata/covalent/blob/develop/src/platform/core/layout/navigation-drawer/navigation-drawer.component.html#L13 to add class `cursor-pointer` and attribute `layout-align="start center"`.

So from
` <div class="md-body-1" layout="row" href *ngIf="email || name" (click)="toggleMenu()">`
to
` <div class="md-body-1 cursor-pointer" layout="row" layout-align="start center" href *ngIf="email || name" (click)="toggleMenu()">`

(or move the click event down to the arrow button for the pointer issue)

**Comment by owilliams320** [comment]
latest looks ok 

<img width="326" alt="Screen Shot 2022-05-11 at 7 35 15 PM" src="https://user-images.githubusercontent.com/3837706/167964196-e42f6e19-b337-42e7-8faf-5f046ed21951.png">
