### ISSUE TITLE
Error: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked

### ISSUE THREAD

**Issue by kthomas80** [Teradata/covalent#698]
#### Bug Report
When using the Quickstart code for the td-layout-manage-list I get this error below:

`ERROR Error: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: '[object Object]'. Current value: 'side'.`

`<td-layout-manage-list #manageList
                        [opened]="media.registerQuery('gt-sm') | async"
                        [mode]="(media.registerQuery('gt-sm') | async) ? 'side' : 'push'">`

##### Screenshots or link to CodePen/Plunker/JSfiddle
Screenshot - [https://ibb.co/mnBw05](url)

#### What is the expected behavior?
No error

#### Which version of Angular and Material, and which browser and OS does this issue affect?

I am running "@covalent/core": "^1.0.0-beta.5-1",

os: darwin x64 
angular/core: 4.2.2 
covalent/core: 1.0.0-beta.5-1
angular/material: 2.0.0-beta.6

**Comment by emoralesb05** [comment]
Check the changelog, there are changes in change detection for angular 4.2.0

https://github.com/Teradata/covalent/blob/develop/docs/CHANGELOG.md#100-beta5-1-2017-06-12

So we updated the documentation with the necessary steps

**Comment by emoralesb05** [comment]
Closing this since we already updated the documentation with the necessary steps to avoid this angular issue.
