### ISSUE TITLE
Providing custom width to td-data-table columns

### ISSUE THREAD

**Issue by Saif03** [Teradata/covalent#701]
I am new to covalent, I was going through docs and tried replicating one of the data table examples.

![image](https://user-images.githubusercontent.com/15065985/27283675-c8d04160-550e-11e7-8ed5-819284a80983.png)
In the above example I want that the fields with more content in it should make its column with to increase either dynamically or any custom tweak to make that happen. Currently I am trying to do:

```
<td-data-table #dataTable [data]="filteredData" [columns]="columns" [(ngModel)]="selectedRows" (sortChange)="sort($event)">
    <ng-template tdDataTableTemplate="action" let-value="value" let-row="row" let-column="column">
        <button md-icon-button id="icon-btn"><md-icon>mode_edit</md-icon></button>
    </ng-template>
</td-data-table>
```

I also tried customizing via the following method:

```
<table td-data-table>
    <th td-data-table-column *ngFor="let column of columns" [numeric]="column.numeric">
        {{column.label}}
    </th>
    <tr td-data-table-row *ngFor="let row of data">
        <td td-data-table-cell *ngFor="let column of columns" [numeric]="column.numeric">
            {{column.format ? column.format(row[column.name]) : row[column.name]}}
        </td>
    </tr>
</table>
```

but this piece of code generates the following error on  line *ngFor="let row of data"

![image](https://user-images.githubusercontent.com/15065985/27283846-ad60ad06-550f-11e7-9493-420ad003d232.png)

**Comment by emoralesb05** [comment]
That `.hasData` error is a markup error on your side when copying the demo code.

That being said, you can add widths as wanted with the atomic components, but the feature to customize them in the `td-data-table` is coming soon. Probably for next release.

**Comment by Saif03** [comment]
Thanks for your response and active work on this great thing,

Well There isn't anything complex in the demo code it's pretty straight forward, but I'll look into it one more time to figure out what possibly be going wrong here.

**Comment by Saif03** [comment]
That error was due to a stupid mistake, never mind that. provided above table structure how can I combine sortable feature with that? I tried something like below but that doesn't make sort buttons ( those showing along side column names) interactive, i.e. clicking them doesn't sort data plus also doesn't animates to show current sorted order.

```
<table td-data-table>
        <th td-data-table-column active="true" sortable="true" [sortOrder]="sortOrder"
            (sortChange)="sort($event)" *ngFor="let column of columns">
            {{column.label}}
        </th>
    <tr td-data-table-row *ngFor="let row of filteredData">
            <td td-data-table-cell [numeric]="column.numeric" *ngFor="let column of columns">
                {{column.format ? column.format(row[column.name]) : row[column.name]}}
            </td>
    </tr>
</table>
```
