### ISSUE TITLE
Feature: update to @angular/material@2.0.0-beta.7

### ISSUE THREAD

**Issue by fpeterdev** [Teradata/covalent#707]
#### Feature Request

Beta.7 is out for the material package, but covalent requires version 6. Could you update the package to use the new version?

**Comment by emoralesb05** [comment]
I tried doing this a few days ago and there was an error in material with some mixins. Will try it again after the weekend, since they did fix it but havent released the fix.

**Comment by emoralesb05** [comment]
So yeah, beta.7 has a bug with the mixins. What im gonna do is relax the dependency to make it `^`.

**Comment by emoralesb05** [comment]
This will be taken care of with https://github.com/Teradata/covalent/pull/747.

Actually upgrading all the way up to beta.8 and also relaxing the dependency to be `^`

**Comment by fpeterdev** [comment]
Thank you! Do you have any plans for the release date?

**Comment by emoralesb05** [comment]
Probably over the weekend or monday, we just need to test real good that PR to make sure everything works properly
