### ISSUE TITLE
Mat combatibilty mode for stepper

### ISSUE THREAD

**Issue by jltnf54** [Teradata/covalent#709]
This repository's issues are reserved for feature requests and bug reports.

#### Feature Request

please first make sure your request falls under the official Material Design spec guidelines https://material.google.com/

#### Bug Report

please provide steps to reproduce and if possible screenhots, animated Gifs and/or a Plunker (or similar).
you can easily create animated Gif with this free PC/OSX App: http://www.cockos.com/licecap/ and a Plunker to help us reproduce it
Plunker template: http://plnkr.co/edit/7uZQn4mLNJkL6XN9WSNd

#### Which version of Angular and Material, and which browser and OS does this issue affect?

Did this work in previous versions of Angular / Material?
Please also test with the latest stable and snapshot versions.

##### Other information
(e.g. detailed explanation, stacktraces, related issues, suggestions how to fix)

**Comment by jltnf54** [comment]
It seems stepper use md-icon tags which do not render correctly when running with mat- prefix for angular/material

**Comment by jltnf54** [comment]
Is mat- prefix not supported

**Comment by emoralesb05** [comment]
Yeah, we arent supporting `mat-` prefixes atm. This will require some discussions around the team to find out if its worth it or not.

**Comment by rexhxiao** [comment]
@emoralesb05 會有支援mat-的計畫嗎? 還是目前這會有什麼阻礙呢?

**Comment by emoralesb05** [comment]
This sill stop being an issue since material will deprecate `md` in their next beta.
