### ISSUE TITLE
Chips underline is misplaced when used in conjunction with material indigo theme

### ISSUE THREAD

**Issue by parker-mike** [Teradata/covalent#710]
When chips component is used in app that utilizes material indigo theme the .mat-input-underline gets bottom set, and underline is moved up and becomes a strike through the chips...
To fix this please add
bottom: 0;
to
https://github.com/Teradata/covalent/blob/develop/src/platform/core/chips/chips.component.scss#L60-L65

**Comment by kyleledbetter** [comment]
can you add a plunker showing this pls?

**Comment by parker-mike** [comment]
@kyleledbetter Definitely, here the [plnkr ](http://plnkr.co/edit/sLDVvjMBvuxytvmSFONF?p=preview)

**Comment by emoralesb05** [comment]
Actually, this seems to be an issue when using the `beta.7` theming, If you specifically target the `beta.6` theming its gonna work.

We cant upgrade to `beta.7` since the mixin doesnt work.. so ill keep this open to keep track of it once we can upgrade.

**Comment by parker-mike** [comment]
That is truth, for now I'm going to add bottom: 0 manually since I don't see any other problems with this or other covalent components we're using when working with `beta.7`

**Comment by emoralesb05** [comment]
This will be taken care of with https://github.com/Teradata/covalent/pull/747 with the beta.8 upgrade.
