### ISSUE TITLE
Feature Request: Chips: beforeInsert and beforeDelete event

### ISSUE THREAD

**Issue by demetrio812** [Teradata/covalent#711]
Hello,
as discussed in Gitter, I need some events to validate the insertion (or removal) of the chip. 

I'm using Chips to add tags and if I use different cases (like Test, test, TEST, tEst, etc.) it adds them so I have to filter them using `(add)` so after the chip is inserted. It's probably better to do it before inserting so a sort of validation mechanism before insertion (and before removal) would be very useful.

Thanks,
Dem

**Comment by egonzalez-T** [comment]
Hi, this would be a very useful feature. Is there any plant to implement this?

**Comment by kwilliams-curago** [comment]
It would be great if there were some hooks to implement validation, or even utilizing the Angular validators to validate the input.

In the meantime, I was able to implement a workaround by utilizing requireMatch and pushing the valid value (email address in my use case) to the filtered list. 

This strategy seems to work decently, although seems to get hung up on the debounce.

It can probably be improved a little by utilizing the inputChange event instead to validate input and ensure that the custom value is in the filtered list.

**Comment by emoralesb05** [comment]
Agree this would be great, we are almost stable, so we are planning the roadmap for 1.1 features.. this can potentially be one of them 😄
