### ISSUE TITLE
Toolbar links

### ISSUE THREAD

**Issue by crackcomm** [Teradata/covalent#715]
Could you help me with creating a toolbar with links like the one on https://teradata.github.io/covalent/
I can't find examples and replicating docs doesn't give me the same results, I tried many different things. I can't find any help in angular material docs about it too.

**Comment by aciccarello** [comment]
What happened when you tried to duplicate the docs? Look at the [toolbar component](https://github.com/Teradata/covalent/blob/develop/src/app/components/toolbar/toolbar.component.html) in the docs source. That uses flex layout (see [lines 5 and 6](https://github.com/Teradata/covalent/blob/develop/src/app/components/toolbar/toolbar.component.html#L5-L6)) to push all the content to the right. Then the [links are defined](https://github.com/Teradata/covalent/blob/develop/src/app/components/toolbar/toolbar.component.html#L7-L13) with normal `<a>` tags. You should also note that the toolbar is [styled as a block](https://github.com/Teradata/covalent/blob/develop/src/app/components/toolbar/toolbar.component.scss).

**Comment by crackcomm** [comment]
This is the best I could get:

![](http://i.imgur.com/HNN6Vi6.png)

Pretty nice but style is incosistent ;)

```HTML
<td-layout-nav color="accent" logo="assets:covalent">
  <div td-toolbar-content layout="row" layout-align="end center" flex>
    <span flex></span>
    <nav hide show-gt-md class="text-upper text-sm" layout="row">
      <a class="push-right text-nodecoration" [routerLink]="['/docs']" [routerLinkActive]="['active']">Docs</a>
      <a class="push-right text-nodecoration" [routerLink]="['/components']" [routerLinkActive]="['active']">Components</a>
      <a class="push-right text-nodecoration" [routerLink]="['/layouts']" [routerLinkActive]="['active']">Layouts</a>
      <a class="push-right text-nodecoration" [routerLink]="['/style-guide']" [routerLinkActive]="['active']">Style Guide</a>
      <a class="push-right text-nodecoration" [routerLink]="['/templates']" [routerLinkActive]="['active']">Templates</a>
    </nav>
    <ui-nav-notifications></ui-nav-notifications>
  </div>
  <!-- … -->
</div>
```

**Comment by crackcomm** [comment]
@aciccarello is there something I missed?

**Comment by kyleledbetter** [comment]
Add this to your theme scss as well https://github.com/Teradata/covalent/blob/develop/src/theme.scss#L158

**Comment by crackcomm** [comment]
@kyleledbetter thank you :+1:

**Comment by crackcomm** [comment]
I was able to replicate this setup, thank you.

Unfortunately I realized it does not fit well next to `md-tab-link`'s.

![](https://ipfs.io/ipfs/QmcoHvUDgjNnfBgsPGS8DEBHkP4Fb355R2QQKbnbjiWPrq)

**Comment by kyleledbetter** [comment]
I'd use one or the other not both

**Comment by crackcomm** [comment]
I decided to use tab links after briefly figuring out how to embed them in the toolbar.

Thanks for your help!

**Comment by emoralesb05** [comment]
Awesome, closing this then 😄
