### ISSUE TITLE
Scrolling Timeline Feature

### ISSUE THREAD

**Issue by RDUBPhoto** [Teradata/covalent#716]
This repository's issues are reserved for feature requests and bug reports.

#### Feature Request

please first make sure your request falls under the official Material Design spec guidelines https://material.google.com/

##### Screenshots or link to CodePen/Plunker/JSfiddle

Demo site - https://slides.com/changelog

#### What is the expected behavior?

Similar timeline with virtual scroll / infinite scroll behavior

**Comment by emoralesb05** [comment]
This will require some brainstorm to see how we can reuse or abstract some of the `stepper` components
