### ISSUE TITLE
Row [clickable] hover not working

### ISSUE THREAD

**Issue by nikola1970** [Teradata/covalent#717]
There is no hover state when 'clickable' is TRUE. rowClick works though.

using: "@covalent/core": "^1.0.0-beta.5-1"

**Comment by emoralesb05** [comment]
Hmm, does this happen in a particular browser?

**Comment by nikola1970** [comment]
Newest Google Chrome.

**Comment by emoralesb05** [comment]
Hmm, cant seem to replicate this? Can you post a plnkr with the issue?

**Comment by jeremysmartt** [comment]
no traction on issue in over a year, closing
