### ISSUE TITLE
[website mistake] Update TypeScript code for "Data Table with components"

### ISSUE THREAD

**Issue by nikola1970** [Teradata/covalent#718]
It would be nice to have updated and working code for "Data Table with components", it is using different data (there are sweets in the example but something other in typescript code...).
I am looking for the code snippet for sorting when we have more then one column that can be sorted by.
Please check. Thanks.

**Comment by emoralesb05** [comment]
Yeah, we need to improve our demos to be more "real" and are probably gonna leverage plnkr to do so as we continue.

Getting ready to upstream lots of new data table features and add cool demos for them

**Comment by freastro** [comment]
I also noticed that the code has two titles (line 3 and line 6).
