### ISSUE TITLE
Feature Request: Editable Chips

### ISSUE THREAD

**Issue by morganfens** [Teradata/covalent#720]
Would like the option to be able to edit a chip when it's double clicked or the enter key is pressed while that chip is selected.

**Comment by emoralesb05** [comment]
Need to think about this since editable chips only make sense when its a `string` list, and its custom inputs..

I know the material 1 chips allowed this behavior but in reality (personally) never found a reason to use it like that.

Can you tell us your use case?

**Comment by morganfens** [comment]
We wanted to use the stacked chips for warnings that would be assigned to different products , these lines of text will probably not go over 3 sentences but would be a pain to the user to have to delete the entire text to fix a typo.

**Comment by owilliams320** [comment]
this component is deprecated and will no longer be supported in future versions. please use https://material.angular.io/components/chips/overview
