### ISSUE TITLE
Feature Request: add support to modify the toolbar content within a child component

### ISSUE THREAD

**Issue by Glains** [Teradata/covalent#723]
#### Feature Request

Add support to modify the toolbar content from the **management-list layout** within a child component.

#### What is the motivation / use case for changing the behavior?

Lets consider the example taken from the documentation:

```
<td-layout-nav sidenavTitle="title" logo="logo" icon="icon" color="primary">
  <div td-toolbar-content>
    .. main toolbar content
  </div>
  <td-layout-manage-list opened="true" mode="side" sidenavWidth="257px">
    <md-toolbar td-sidenav-content>
      ... toolbar in sidenav
    </md-toolbar>
    <md-nav-list td-sidenav-content>
      ... sidenav content
    </md-nav-list>
    <div td-toolbar-content>
      ... sub toolbar content
    </div>
   <router-outlet>
    <td-layout-footer-inner>
      ... sub footer content
    </td-layout-footer-inner>
  </td-layout-manage-list>
</td-layout-nav>
```

The toolbar can only be defined within this component, but possible child components injected via the `<router-outlet>` cannot change or modify the toolbar in a simple way. 

The documentation recommends this type of layout for
* a product landing page with subnavigation and

What if each subpage requires _different_ items in the toolbar? For example the settings from one page could differ from the settings from another page or a second page may require items in the toolbar that the first one does not need.

Using the layout multiple times in components would lead to duplicate code, especially for the navigation. Is there any other recommended approach to solve this problem?

**EDIT:**
Removing the `td-toolbar-content` and creating a `<md-toolbar>` within the child component would lead to two loolbars displayed next to each other, which is also not the solution.

**Comment by Glains** [comment]
A possible solution would be to generate the custom toolbar component dynamically:
```
setCustomToolbarComponent(component: Type<{}>) {
    this.toolbarContainer.clear();
    const factory: ComponentFactory<any> = this._resolver.resolveComponentFactory(component);
    this.toolbarComponentRef = this.toolbarContainer.createComponent(factory);
  }
```

**Comment by emoralesb05** [comment]
We have a PR open that fill fix this issue. https://github.com/Teradata/covalent/pull/657

So now you need to include the toolbar and such

**Comment by Glains** [comment]
Thanks for your answer! Cant wait for it to be released, closing this issue.

**Comment by emoralesb05** [comment]
You can try this if you pull the night build since we merged this already https://github.com/Teradata/covalent/pull/657
