### ISSUE TITLE
Cannot build the project on Linux Ubuntu 14.04

### ISSUE THREAD

**Issue by metacoding** [Teradata/covalent#73]
This repository's issues are reserved for feature requests and bug reports.
### Do you want to request a _feature_ or report a _bug_?

bug
#### Feature Request

please first make sure your request falls under the official Material Design spec guidelines https://material.google.com/
#### Bug Report

please provide steps to reproduce and if possible screenhots or animated Gifs.
you can easily create animated Gif with this free PC/OSX App: http://www.cockos.com/licecap/
I ran the steps provided here https://teradata.github.io/covalent/#/docs
on linux for command with -g I add a sudo prefix
everything worked without issue until I ran npm i
the the error shown on the image happened.
##### Screenshots or link to CodePen/Plunker/JSfiddle

https://snag.gy/W3bu7G.jpg
#### What is the expected behavior?

To build without error
#### Which version of Angular and Material, and which browser and OS does this issue affect?

Did this work in previous versions of Angular / Material?
Please also test with the latest stable and snapshot versions.
##### Other information

(e.g. detailed explanation, stacktraces, related issues, suggestions how to fix)

**Comment by kyleledbetter** [comment]
Hi, this is a known upstream angular-material issue. The packages actually install still. Try to 'ng serve'

**Comment by Daeluse** [comment]
Also, the newest versions of NPM and NodeJS should change these Errors into Warnings as they were intended to be. Updating both of these should clean that up for you.

**Comment by kyleledbetter** [comment]
@metacoding are you having these issues w/ Covalent 0.7 w/ angular-cli beta15+ and webpack?

**Comment by emoralesb05** [comment]
Closing this since we havent heard anything else about this issue.
