### ISSUE TITLE
tdLoading until star syntax gives error in A2 Language Service: the template context does not have an implicit value

### ISSUE THREAD

**Issue by nfdevil** [Teradata/covalent#732]
This repository's issues are reserved for feature requests and bug reports.

### Do you want to request a *feature* or report a *bug*?

Bug 

#### Bug Report

On the tdLoading documentation page (https://teradata.github.io/covalent/#/components/loading) under header '[tdLoading] until star syntax with variable reference and observables', the code tab, the first line of the template is currently 
`<div *tdLoading="let items until listObservable | async; type: circle; color: accent">`

This gives an error in the Angular Language Service 'the template context does not have an implicit value'.

Adding the single quotes to this: 
`<div *tdLoading="'let items until listObservable | async; type: circle; color: accent'">`
fixes the error of the Language Service, but does not work.

Is this a bug in the Language Service or in Covalent?

I'm using Angular Language Service v0.1.4 in VSCode 1.13.1 with Covalent version 1.0.0-beta.5-1

**Comment by emoralesb05** [comment]
I saw this a few days ago, need to figure out if we are missing something that the language service is looking for.

You can the demo code even if the language service complains, its not gonna affect compilation.

**Comment by emoralesb05** [comment]
Found the issue 😄 

This PR will take care of it https://github.com/Teradata/covalent/pull/734
