### ISSUE TITLE
Feature Request - Data Table: Responsive Sizing

### ISSUE THREAD

**Issue by jdundondev** [Teradata/covalent#740]
In addition to allowing the user to select the number of rows to display in each page of the table, it is also very useful to provide an option to auto-fit the number of rows to the available space.

In some cases, selecting a fixed number of rows does not provide the best user experience. For example, if the number of rows selected is larger than the available space, a vertical scrollbar is needed to view the entire table. The user has to click the pager at the bottom, scroll up to the top, then scroll back down to the bottom again to go to the next page. This may need to be done repeatedly for each page. Conversely, if the selected number of rows is smaller than the available space, the number of visible rows is limited unnecessarily.

In many cases the user just wants to see as many rows as possible for each page. If the size of the window is changed or an internal splitter is moved, the table should automatically adjust the number of rows to the space available.

The following screen capture shows how this feature works in the current implementation of Studio Lite with both the PrimeNG and Covalent data tables (the screen capture is using the Covalent data table).

It should also be possible to hide the page size selector if only "Fit" or another fixed size is needed.

Note that if Fit mode is selected, a vertical scrollbar for the table is never needed.

![responsiveresizing](https://user-images.githubusercontent.com/25935633/27883491-787c6f6c-6185-11e7-8c0b-ac1b0afecfc3.gif)

**Comment by jdundondev** [comment]
The determination of how much space is available may be difficult to do in a generic way due to differing layout of each application. A resize event passed to the application can allow the application to perform any necessary calculations to determine the right number of rows.

This can be accomplished using the standard Angular @HostListener annotation.

`
@HostListener('window:resize', ['$event'])
onResize(): void {
  this.calculateTableSize();
  ...
}`

**Comment by jdundondev** [comment]
Allowing the user to include a 'Fit' value in the list of pageSizes would allow the application to support both fixed page sizes and responsive page sizing.

<td-paging-bar #pagingBar [pageSizes]="[Fit, 5, 10, 15, 20]" [pageSize]="pageSize">
    or
<td-paging-bar #pagingBar [pageSizes]="[Fit]" [pageSize]="'Fit'">

**Comment by kyleledbetter** [comment]
this is coming soon when we upstream the latest datatable features we've done internally (not the paging bar one)

**Comment by jdundondev** [comment]
That’s great to hear. Not sure what you mean by "(not the paging bar one)”.  Do you mean adding the “Fit” option?

**Comment by emoralesb05** [comment]
The paging bar component is agnostic of screen size or container size, so you can (and should) calculate the number of rows that fit in the viewport and assign it to `[pageSize]`.

**Comment by jdundondev** [comment]
What happens when the container size changes? In Studio Lite, I've implemented a resize listener and I dynamically adjust the number of rows in the table when the container changes size.

I was thinking it would be nice to have a "Fit" option so the user could select a specific page size or let the system adjust (fit) the page size to container.

Also, it would be nice to be able to hide the page size selector if only one options is available.

**Comment by emoralesb05** [comment]
If the container size changes then you recalculate again, its all about the viewport (same logic behind virtual scrolling)

When the window resizes you update the rows in the data-table, the paging bar doesnt know about it, nor it knows which container element. 

But honestly, i dont see how this would useful, if anything it complicates it since you are removing rows when shrinking the view and asking for more when its getting bigger (cause now you can fit more).. so its a lot of overhead for little (or none) reward.

**Comment by jdundondev** [comment]
I think we are in agreement. I don't really need the page size chooser if I can dynamically adjust the number of rows per page. The only use case I can see is if the user wants to set the page size to larger than the container will hold. Then you get a vertical scrollbar. But I think we can live without that option and make "Fit" the only behavior.

Can the page size selector be hidden if we have a dynamic page size? The only way I saw to hide it was to add some CSS.

When the page size changes
1) the number of pages changes (e.g. if there were 100 pages, now there may be 122 pages)
2) the current page I'm on changes (e.g. if I'm currently on page 10 and I shrink the container, I may now be on page 15)

The paging bar should reflect both of those changes.

**Comment by emoralesb05** [comment]
Absolutely, hiding the `pageSizes` select box is a good feature we need to add. We might hide it by default with not options, and hide it when `[pageSizes]` is undefined or an empty array. 

From there you can mix and match to fit our needs.
