### ISSUE TITLE
Feature Request - Data Table: Cell and Row Context Menu

### ISSUE THREAD

**Issue by jdundondev** [Teradata/covalent#741]
Cell Context Menu:
- When one or more cells are selected a right click action should display a context menu
- The application should be able to define custom actions based on the cell(s) selected
- Right-clicking an unselected cell should select the cell and display the context menu

Row Context Menu:
- If a table supports row selection, when a user right clicks within the selected row  (or the selection cell - usually the first column), a context menu should be displayed (if defined)
- The application should be able to define custom actions depending on which and how many rows are selected (e.g. delete history items)

**Comment by joaoeudes7** [comment]
I also think this functionality would be interesting, is it in the covalent's plans?

**Comment by emoralesb05** [comment]
Yes it is, the problem ATM is that the `mat-menu` doesnt support right click hooks and what not, so once material supports it we will add it asap.

**Comment by owilliams320** [comment]
Closing this as we will not be support td-data-table in future versions. please use the data table provide by angular material.

https://material.angular.io/components/table/overview
