### ISSUE TITLE
Feature Request - Paging Bar: Jump to Row # or Percent

### ISSUE THREAD

**Issue by jdundondev** [Teradata/covalent#743]
This issue is related to another closed issue: [https://github.com/Teradata/covalent/issues/496](url)

For tables with a large number of rows, clicking next-page or jumping to a particular page number is not an ideal user experience. For example, if I have 1M rows, I have 17 rows per page and I want to jump to the rows half way through, which page number should I enter (answer: 1000000 / 17 / 2 = page 29411).

In addition to jumping to a particular page, it would be nice to be able to jump to a particular row number or percentage of the total number of rows. For example:

Jump to: page 29441
Jump to: row 500000
Jump to: 50%

The jump type could be specified via a selector following the field. For example:

![screen shot 2017-07-05 at 2 00 16 pm](https://user-images.githubusercontent.com/25935633/27884799-643c2cae-618a-11e7-9304-a0c14f80aa79.png)

**Comment by jdundondev** [comment]
The existing API (emitting a IPageChangeEvent) would not need to change if the page calculation was done internally.

**Comment by kyleledbetter** [comment]
yup want this as well, it's actually a paging bar component feature request

**Comment by jdundondev** [comment]
Great. I changed the title to indicate it's related to the paging bar.

**Comment by emoralesb05** [comment]
This is going to be more docs and demos rather than a feature since devs can already implement this. We just had to add few minor changes to the layout.

e.g.

```html
<td-paging-bar #pagingBar [pageSizes]="[50,100,200,500,1000,2000]" pageLinkCount="5" [firstLast]="false" [initialPage]="1" [pageSize]="100" [total]="1345" (change)="change($event)">
  <span td-paging-bar-label hide-xs>Row per page:</span>
  {{pagingBar.range}} <span hide-xs>of {{pagingBar.total}}</span>
  <p hide-xs>Go to:</p>
  <md-input-container>
    <input #goToInput
          mdInput
          type="number"
          [min]="1"
          [max]="pagingBar.maxPage"
          [value]="pagingBar.page"
          (blur)="goToInput.value = pagingBar.page"
          (keyup.enter)="pagingBar.navigateToPage(goToInput.value); goToInput.value = pagingBar.page"/>
  </md-input-container>
</td-paging-bar>
```
