### ISSUE TITLE
Feature Request - Data Table: Row Expansion

### ISSUE THREAD

**Issue by jdundondev** [Teradata/covalent#744]
The amount of data in each field of a data row can vary widely. Fields can also contain multi-line values. However, the data displayed in the table cells is necessarily limited in length.

- A very useful mechanism for displaying large data value is row expansion
- This can be done by clicking in a special expansion column to cause an application-defined expansion panel to be shown
- This allows each data field to be displayed on a separate line and for fields that may contain large amounts of data to be displayed in a text area that supports both scrolling and expansion
- This also allows arbitrary user-defined contents to be displayed in the expansion panel

The following screen capture show how this feature works in the current release of Studio Lite using the PrimeNg Data Table.

![rowexpansion](https://user-images.githubusercontent.com/25935633/27884963-06fc7b92-618b-11e7-940b-4e2ce9da5919.gif)

**Comment by jdundondev** [comment]
The PrimeNG data table supports this feature using an <ng-template>. This is used in the current release of Studio Lite as follows.

The first column defines the attribute expander="true" and the <ng-template> defines the content to be displayed when the expansion is activated.

![screen shot 2017-07-05 at 2 06 24 pm](https://user-images.githubusercontent.com/25935633/27884995-35d75d6a-618b-11e7-92e8-a6c56b40e719.png)

**Comment by jdundondev** [comment]
This feature could also be implemented as an overlay card. But the inline expansion is a much better UX.

**Comment by kyleledbetter** [comment]
something similar can be used today if you use a dialog instead of the row expansion

**Comment by jdundondev** [comment]
Agreed. But I do think the row expansion makes a better UX. This one is lower priority for that reason.

**Comment by pantonis** [comment]
Is master-detail supported by the datatable?

**Comment by praveenpuglia** [comment]
Really need this. Or even a way to insert another row with the following syntax.
```html
<td-data-table
    [data]="filteredData"
    [columns]="columns"
    [selectable]="true">
```

**Comment by owilliams320** [comment]
Closing this as we will not be support td-data-table in future versions. please use the data table provide by angular material.

https://material.angular.io/components/table/overview

**Comment by owilliams320** [comment]
Closing this as we will not be support td-data-table in future versions. please use the data table provide by angular material.

https://material.angular.io/components/table/overview
