### ISSUE TITLE
Bug media.service

### ISSUE THREAD

**Issue by VesperDev** [Teradata/covalent#749]
![captura](https://user-images.githubusercontent.com/14016458/27944968-f02ef540-62af-11e7-9139-9e3d55a156cc.PNG)

#### Bug Report

        this._globalSubscription = this._ngZone.runOutsideAngular(function() {
            return Observable.fromEvent(window, 'resize').subscribe(function() {
                // way to prevent the resize event from triggering the match media if there is already one event running already.
                if (!_this._resizing) {
                    _this._resizing = true;
                    setTimeout(function() {
                        _this._onResize();
                        _this._resizing = false;
                    }, 100);
                }
            });
        });

Apparently there is a problem in the following file node_modules \ @covalent \ core \ media \ services \ media.service.js there is a problem in this function fromEvent is not a function if I mention the code line of the function the component works well

![captura](https://user-images.githubusercontent.com/14016458/27945114-c29ec28a-62b0-11e7-9255-3c775e951ca2.PNG)

        // we make sure that the resize checking happend outside of angular since it happens often
        this._globalSubscription = this._ngZone.runOutsideAngular(function() {
            // return Observable.fromEvent(window, 'resize').subscribe(function () {
            //     // way to prevent the resize event from triggering the match media if there is already one event running already.
            //     if (!_this._resizing) {
            //         _this._resizing = true;
            //         setTimeout(function () {
            //             _this._onResize();
            //             _this._resizing = false;
            //         }, 100);
            //     }
            // });
        });

so comment this line of code in the function fromEvent and all worked fine

**Comment by emoralesb05** [comment]
This is gonna be fixed in the material@beta.8 upgrade PR. We are releasing also over the weekend to support material beta.8.

**Comment by emoralesb05** [comment]
This should be fixed in our `beta.6` release
