### ISSUE TITLE
Covalent@1.0.0-beta.6 resolves to beta.5-1 with yarn install

### ISSUE THREAD

**Issue by istvanszoboszlai** [Teradata/covalent#754]
#### Bug Report

Warning during `yarn install`:
`warning "@covalent/core@1.0.0-beta.5-1" has incorrect peer dependency "@angular/material@2.0.0-beta.6".`

After `yarn cache clean && rm -rf node_modules && rm yarn.lock && yarn install` in my yarn.lock file I have this:
```
"@covalent/core@^1.0.0-beta.6":
  version "1.0.0-beta.5-1"
  resolved "https://registry.yarnpkg.com/@covalent/core/-/core-1.0.0-beta.5-1.tgz#503d816bcb36bf164a388870ad74ccd240b12846"
```

With `npm install` the correct dependency is resolved.

I do not know if it is related to yarn or Covalent.

#### What is the expected behavior?
No warning, and correct dependency of `"@covalent/core": "^1.0.0-beta.6"`

#### Which version of Angular and Material, and which browser and OS does this issue affect?
```
    "@angular/material": "2.0.0-beta.8",
    "@angular/cdk": "2.0.0-beta.8",
    "@covalent/core": "^1.0.0-beta.6"
```

**Comment by emoralesb05** [comment]
did you try `yarn upgrade`? can't think of a reason why this is failing.

**Comment by istvanszoboszlai** [comment]
`yarn upgrade` does the same. It is more likely to be a yarn issue. I have checked Covalent in yarn registry and seems fine. Do you guys use yarn without an issue?

**Comment by istvanszoboszlai** [comment]
I have upgraded yarn to v0.27.5, wich did not solve the issue.
There are 2 things that can solve it (although the bug - in most likely yarn - still exists):
1. edit yarn.lock by hand to use beta.6 (which will be overwritten to the wrong dependency on a yarn upgrade)
2. use fixed dependency version in package.json: `"@covalent/core": "1.0.0-beta.6"`

It looks like yarn thinks beta.5-1 is greater then beta.6 :)
Interesting.
As this is not covalent related, I close the issue.

**Comment by emoralesb05** [comment]
huh, that's weird. Gonna add `faqs` to this since people might encounter this issue.

**Comment by nni123** [comment]
I have same issue and install beta 6 "npm install @covalent/core@1.0.0-beta.6 @covalent/dynamic-forms@1.0.0-beta.6 etc"

Usually "npm install @covalent/core@latest" should do the trick but it didn't work with beta 6.
