### ISSUE TITLE
Allow styling/customization of the data table's column header tooltips

### ISSUE THREAD

**Issue by brandon-a-hay** [Teradata/covalent#758]
This repository's issues are reserved for feature requests and bug reports.

#### Feature Request

Hello, I would like to request the ability to customize the column header tooltips for the data table. Currently, you can specify a `tooltip` property on `ITdDataTableColumn`, but you cannot change the look at all to my knowledge. It would be great to be able to pass a `tooltipClass` as a property on the column to apply some styling to that.

Thanks,

- Brandon

**Comment by emoralesb05** [comment]
We are in the midst of abstracting the columns so we can provide them as elements, that way you can implement your own implementation of tooltip, and even add other things as needed.

e.g.
```
<div tdColumn [mdTooltip]="tooltip">
  Label
</tdColumn>
```

**Comment by owilliams320** [comment]
this component is deprecated please use https://material.angular.io/components/table
