### ISSUE TITLE
disable dynamic control

### ISSUE THREAD

**Issue by ferdaousharmel** [Teradata/covalent#761]
Hello ,

Please i am working with dynamic forms.
I just need to disable a TdDynamicInputComponent regarding a boolean.
How can i achieve that ?

THANKS.

**Comment by emoralesb05** [comment]
We have an open issue for this. Since we cant do it atm.

**Comment by aciccarello** [comment]
Would that be #490?

**Comment by emoralesb05** [comment]
closing since we will follow the thread in https://github.com/Teradata/covalent/issues/490
