### ISSUE TITLE
How to use the RESTService example 

### ISSUE THREAD

**Issue by TheParad0X** [Teradata/covalent#768]
Hello,

On this page: https://teradata.github.io/covalent/#/components/http

The usage example for the REST Service only shows the service, not how it is called. Also, the code as-is seems to be wrong:

`headers: new Headers(),`

should be

`baseHeaders: new Headers(),`

How do I use the REST Service ? The usage of parameters of type IRestQuery and IRestTransform are rather confusing. 

An example for every method would be more than welcome.

Cheers

**Comment by owilliams320** [comment]
this service will be deprecated in future versions
