### ISSUE TITLE
misaligned MdInput placeholder w/ MdPrefix

### ISSUE THREAD

**Issue by brackio** [Teradata/covalent#773]
BUG

#### Bug Report

The input placeholder height is off when using MdPrefix; the placeholder and the MdPrefix icon are not aligned.  Also, the placeholder font-size is larger that material2 using convalent platform.scss.  See screenshot below.

**With covalent platform.scss**
![image](https://user-images.githubusercontent.com/5306924/28420676-e3b50102-6d30-11e7-96bb-246ac9965520.png)

**Without covalent platform.scss**
![image](https://user-images.githubusercontent.com/5306924/28420985-d69dc444-6d31-11e7-99b5-185690bc3ed3.png)

**Comment by emoralesb05** [comment]
Gonna check this out. We are trying to remove the dependency of `platform.scss` in the upcoming releases.

**Comment by felipeik** [comment]
Hello, I took 2 screenshots with and without `platform.scss`.

I see no difference in the results.


With platform.scss | Without platform.scss
------------ | -------------
<img width="238" alt="input with platform_css" src="https://user-images.githubusercontent.com/766365/46626321-5ec85200-cb0d-11e8-9c07-3f21c0a3bb5e.png">|<img width="255" alt="input without platfom_css" src="https://user-images.githubusercontent.com/766365/46626324-60921580-cb0d-11e8-972c-84ba389c9f69.png">




### MatCard issue

I do see a difference on font-size when we render inputs inside a MatCard, but this isn't a `platform.scss` issue.

**Font-size is smaller inside a MatCart**

<img width="261" alt="input inside matcard" src="https://user-images.githubusercontent.com/766365/46626435-bcf53500-cb0d-11e8-9f50-2d713637a0fa.png">

### Questions

I see misalignment and font-size differences on the screenshots on the description of this task, but I found no misalignment or text-size differences regarding `platform.scss` on my tests.

The MdPrefix has no effect on the screenshots.

Are there specific steps to reproduce the text-size and misalignment issues?

### Covalent commit
```
commit 3bbf97088eccbd1e98a139653e38ff05c8f4ffc2 (HEAD -> develop, origin/develop, origin/HEAD)
Author: emoralesb05 <eduardo.morales@teradata.com>
Date:   Mon Oct 8 10:30:24 2018 -0700
```

**Comment by jeremysmartt** [comment]
This looks to be OBE
