### ISSUE TITLE
Breakpoints incorrect in _variables.scss

### ISSUE THREAD

**Issue by kelle62819** [Teradata/covalent#782]
-sm,-md- and -lg breakpoint variables are incorrect in /src/platform/core/common/styles/_variables.scss

I've created a pull request to fix this. #781

**Comment by jotatoledo** [comment]
Maybe related to https://github.com/angular/material2/issues/5960 (dont know how to directly link external issues 😄 )

**Comment by emoralesb05** [comment]
Has been merged 😄
