### ISSUE TITLE
When there are multiple chips on the same page... Only one dropdown list should be visible at a time

### ISSUE THREAD

**Issue by vadim82** [Teradata/covalent#783]
#### Bug Report

If you have several chips inputs on the same page... then clicking above one of them will trigger the top one to show its menu while not closing the bottom one. 

##### Screenshots or link to CodePen/Plunker/JSfiddle

I was able to reproduce this issue on the demo page.
1. Click on the bottom chips component and get  the menu to apear.
2. Click on the top chips component where its highlighted in the screenshot and enter something that would cause the popup to appear

![image](https://user-images.githubusercontent.com/1355112/28537090-b426a54a-7077-11e7-8c14-8eda063b3991.png)

![image](https://user-images.githubusercontent.com/1355112/28537213-16340f16-7078-11e7-93f2-6aeb855f5b61.png)

#### What is the expected behavior?

Only one dropdown menu should be visible at a time.

**Comment by kyleledbetter** [comment]
Hmmm is this really an issue or an edge case for QA testing? You typically wouldn't use multiple chips in one page like this but I'd expect both to function

**Comment by vadim82** [comment]
We had a slide out panel in our application and in that panel users can select a bunch of filters. These filters are represented as chips. They end up overlapping each other and preventing users from being able to use the bottom, or top chips component unless they click somewhere else to clear the screen. 

Regardless of how they are used.. shouldn't only one dropdown have its contents visible at a time.

**Comment by emoralesb05** [comment]
This is more of an `md-autocomplete` issue, not really a chips issue. 

We will keep this opened to keep track of it to see when its fixed upstream in `material`

**Comment by emoralesb05** [comment]
Well, actually it might be a bit of both since for some reason clicking in chips is not being registered as part of `DOCUMENT`. Gonna dig around though and see what we can find

**Comment by emoralesb05** [comment]
Ok, found a small work around for this since stopping the propagation of the chips click event was causing this issue. So for now we will manually close it on `mousedown`
