### ISSUE TITLE
 Error: No provider for TdLayoutComponent! while testing the component

### ISSUE THREAD

**Issue by chpie** [Teradata/covalent#788]
#### Bug Report

Hi,

while testing our angular 4 component (ng test), we are getting this error. Note that the component and the template is working when we start the server (ng start). The problem is only related to the unit testing.

Failed: No provider for TdLayoutComponent!
        Error: No provider for TdLayoutComponent!
            at injectionError (http://localhost:9876/_karma_webpack_/vendor.bundle.js:74869:90)
            at noProviderError (http://localhost:9876/_karma_webpack_/vendor.bundle.js:74907:12)
            at ReflectiveInjector_.webpackJsonp.../../../core/@angular/core.es5.js.ReflectiveInjector_._throwOrNull (http://localhost:9876/_karma_webpack_/vendor.bundle.js:76349:19)

In our testing code, we did try to initialize the module with CovalentLayoutModule and SharedModule:

beforeEach(async(() => {
    TestBed.configureTestingModule({
      declarations: [
        ProductsListComponent
      ],
      imports: [
        SharedModule,
        HttpModule,
        NoopAnimationsModule
      ],
      providers: [
        ProductService,
        {
          provide: TdMediaService,
          useValue: {
            registerQuery: noop,
            query: noop,
            broadcast: noop,
            createComponent: noop,
            createReplaceComponent: noop,
            register: noop,
            resolve: noop,
          }
        },
        { provide: APP_BASE_HREF, useValue: '/' }
      ]
    });
    fixture = TestBed.createComponent(ProductsListComponent);
    productsComponent = fixture.componentInstance;
  }));

The problem seems to arise when we are using td-layout-manage-list and tdLayoutToggle directives. The html template is based the basic demo provided in the layout page:

https://teradata.github.io/covalent/#/layouts/manage-list

      
#### What is the expected behavior?

We would expect no error if we provide the CovalentLayoutModule in the TestingModule.

#### Which version of Angular and Material, and which browser and OS does this issue affect?

We are using the latest Angular 4.0.0 and Covalent 1.0.0-beta.6.

Thanks

**Comment by emoralesb05** [comment]
Did you add it in `exports` in the SharedModule?

**Comment by emoralesb05** [comment]
oh nvm, this is because of the `tdLayoutToggle`, you need to provide a mock class for `TdLayoutComponent` since your component probably doesnt have a reference for `td-layout` in it. (assuming its a child component).

**Comment by chpie** [comment]
Mm, not sure how to do that sorry. Can you explain a little more how to mock it? I try mock returning the values of the ILayoutTogglable interface. The behavior is the same that if I put the TdLayoutComponent as a provider:  Test are working now, but the karma interface in chrome seems to freeze.

**Comment by emoralesb05** [comment]
Sorry for the late answer, so you need to provide a mock `TdLayoutComponent`, which you would do it this way:

e.g.

```
{provide: TdLayoutComponent, useClass: TdMockLayoutToggableComponent}
```
using

TdMockLayoutToggableComponent class
```
import { Component, Input, ViewChild, EventEmitter } from '@angular/core';

import { MdSidenav, MdSidenavToggleResult } from '@angular/material';

import { ILayoutTogglable } from '../layout-toggle.class';

import { Observable } from 'rxjs/Observable';

export class TdMockLayoutToggableComponent implements ILayoutTogglable {
  sidenav: any = {
    onOpenStart(): EventEmitter<void> {
      return new EventEmitter<void>();
    },
    onCloseStart(): EventEmitter<void> {
      return new EventEmitter<void>();
    },
  };

  toggle(): Promise<MdSidenavToggleResult> {
    return Promise.resolve(undefined);
  }
  open(): Promise<MdSidenavToggleResult> {
    return Promise.resolve(undefined);
  }
  close(): Promise<MdSidenavToggleResult> {
    return Promise.resolve(undefined);
  }
}
```

We will probably make this class part of covalent/core or make the injection optional to avoid problems like this.. since typically the unit test dont have the parent route containing the injected `TdLayoutComponent`

**Comment by jeremysmartt** [comment]
need to discuss if will make this class part of covalent/core or make the injection optional to avoid problems like this

**Comment by oalencar** [comment]
Hi, I'm having this same problem, but using version 2.0. Can you help me?

**Comment by emoralesb05** [comment]
https://github.com/Teradata/covalent/pull/1262 will fix this
