### ISSUE TITLE
dialog not closing on clicking outside the dialog container

### ISSUE THREAD

**Issue by Saif03** [Teradata/covalent#790]
Tera Data Covalent's dialog doesn't closes automatically when clicked any where outside the dialog container. I am currently working like this:

```
    this._dialogService.openConfirm({
      message: 'Are you sure you want to delete ' + this.taskGroup.name + ' ?',
      disableClose: false,
      viewContainerRef: this._viewContainerRef, //OPTIONAL
      title: 'Confirm', //OPTIONAL, hides if not provided
      cancelButton: 'Disagree', //OPTIONAL, defaults to 'CANCEL'
      acceptButton: 'Agree', //OPTIONAL, defaults to 'ACCEPT'
    }).afterClosed().subscribe((accept: boolean) => {
      if (accept) {
        // Emit task group id to parent
        this.onTaskGroupDelete.emit(this.taskGroup.id);
      } else {
        // DO SOMETHING ELSE
      }
    });
```

When clicked outside the dialog box the back shadow/overlay disappears but dialog box stays on top. and the user needs to manually click on close button as shown in below screenshot.

[Screenshot](http://imgur.com/a/1IiIQ)

What I am possibly doing wrong? I followed the guideline available at covalent component's docs.

**Comment by jotatoledo** [comment]
Can you please post `ng -v` (if you are using angular cli) and some more info about your covalent/material dependencies? The example in the doc page works fine, so its most likely something related to your local develop environment.

**Comment by Saif03** [comment]
my angular CLI version is 1.2.0,
material: "2.0.0-beta.6",
covalent: "1.0.0-beta.5",

I had it working before but its now not working, I am positive I haven't updated any npm packages may be I am doing something different now.

**Comment by emoralesb05** [comment]
Any browsers in particular? cant seem to replicate this behavior.

**Comment by Saif03** [comment]
tested on chrome and Firefox and same results on both.

**Comment by emoralesb05** [comment]
we can try to help if you can try do a pnkr to replicate the issue.. but just as an initial analysis from the screenshot you posted, it looks like the background overlay is missing for some reason

**Comment by Saif03** [comment]
I can try to replicate this issue. The background overlay appears correctly and when the user clicks anywhere around outside the dialog, background overlay disappears as expected but the dialog stays active which isn't the expected beahvior.

**Comment by Saif03** [comment]
When I remove:
`viewContainerRef: this._viewContainerRef`

it works as expected, why is it causing this issue?

**Comment by emoralesb05** [comment]
hmm, i guess its because the dialog is created in the parent rather than the whole window.. this seems like a `material` issue.
