### ISSUE TITLE
ux(dialog): support multiline text in simple dialogs

### ISSUE THREAD

**Issue by quanterion** [Teradata/covalent#791]
Currently if you pass multiline string to openAlert()

```
let info = `Model statistics: 
Objects: ${objCount}
Meshes: ${meshCount}
Triangles: ${triCount}`;
    this.dialogService.openAlert({ message: info });
```

Simple Dialogs display all message on a single line. But native dialogs displays the example message on 4 lines. Is it possible to align Teradata dialogs behavior with native?

**Comment by jeremysmartt** [comment]
clsoing as duplicate of #713
