### ISSUE TITLE
md-input type number in firefox

### ISSUE THREAD

**Issue by alexandrupaul7** [Teradata/covalent#792]
#### Do you want to request a *feature* or report a *bug*?
BUG

#### Bug Report

in firefox input placeholder doubles the text in placeholder. you can see the behavoir in covalent dynamic forms
https://teradata.github.io/covalent/#/components/dynamic-forms

even a simple md-input type number does the same think

##### Screenshots or link to CodePen/Plunker/JSfiddle

https://teradata.github.io/covalent/#/components/dynamic-forms

#### What is the expected behavior?
to work like in chrome

#### Which version of Angular and Material, and which browser and OS does this issue affect?
Browser Firefox

**Comment by alexandrupaul7** [comment]
![firefox](https://user-images.githubusercontent.com/28051061/28639709-c720a12e-7251-11e7-9a5c-e8ef5f76ecf0.PNG)

on firefox 54.0.1

**Comment by jotatoledo** [comment]
I once had the same problem. Have u changed anything related to change detection strategy in the component that contains the form?

**Comment by alexandrupaul7** [comment]
no i didn't.
the printscreen is taken from the covalent demo , dynamics forms where the same problem occures.

https://teradata.github.io/covalent/#/components/dynamic-forms

**Comment by lincze** [comment]
i'm just experiencing the same (fedora 24, firefox 54) both on the above mentioned dynamic forms page, and in my toy application, actually a template driven form, with an empty number type input (after filling in the field, the duplication disappears). probably md problem, not covalent.

![screenshot at 2017-07-26 23-40-43](https://user-images.githubusercontent.com/4760711/28645010-2302f3fc-725c-11e7-887e-6f8e86a8c963.png)
![screenshot at 2017-07-26 23-39-55](https://user-images.githubusercontent.com/4760711/28645009-230130e4-725c-11e7-9dbe-94f9bd5187c0.png)

**Comment by emoralesb05** [comment]
They did a fix for this a few weeks ago, so it might be released soon since `input` had issues with change detection.

**Comment by emoralesb05** [comment]
Closing this since its a material issue thats fixed with the latest firefox
