### ISSUE TITLE
redundant toolbar on td-layout-manage-list

### ISSUE THREAD

**Issue by tuanngominh** [Teradata/covalent#793]
This repository's issues are reserved for feature requests and bug reports.

### Do you want to request a *feature* or report a *bug*?
It's a bug

#### Bug Report
There is a redundant toolbar on the right column.

##### Screenshots or link to CodePen/Plunker/JSfiddle
![covalent_layout_-_manage_list_-_minimum_demo_-_plunker_](https://user-images.githubusercontent.com/2210733/28659177-a6fafba6-72d8-11e7-9eea-14151f0c6954.jpg)
Plunker: 
- Minimal demo: https://embed.plnkr.co/zavydsK5kgcPsHxqPX5a/
- Basic demo: https://embed.plnkr.co/s58mh3vH1DO5HhbOkIEv/

#### What is the expected behavior?
That redundant toolbar should not be there.
The layout should be exactly like in the demo at https://teradata.github.io/covalent/#/layouts/manage-list

#### Which version of Angular and Material, and which browser and OS does this issue affect?
in plunker:
- angularVer = '@4.2.0';
- cdkVer = '@2.0.0-beta.8';
- materialVer = '@2.0.0-beta.8';
- covalentVer = '@1.0.0-beta.6';
( I fork from plunkers in https://teradata.github.io/covalent/#/templates )

in my project:
- angular/core: 4.2.3
- material: 2.0.0-beta.6
- covalent: 1.0.0-beta.5-1

browser: chrome latest
OS:  OSX 10.11.6

> Did this work in previous versions of Angular / Material?

I don't know. This my first time.

> Please also test with the latest stable and snapshot versions.

Looks like I did

##### Other information
(e.g. detailed explanation, stacktraces, related issues, suggestions how to fix)

**Comment by emoralesb05** [comment]
You need to use `beta.6`, since the change to remove the toolbar came up later. The plnkr is using `beta.4`

**Comment by tuanngominh** [comment]
Thanks for your quick reply. You are right that I am using the old version of covalent for the plunker. With beta.6 the issue is fixed.

But please be informed that plunkers here https://teradata.github.io/covalent/#/templates are using old versions of covalent. I accidentally fork from those plunkers.
