### ISSUE TITLE
helllppp 

### ISSUE THREAD

**Issue by yaronmil** [Teradata/covalent#795]
WARNING in ./~/@covalent/core/expansion-panel/expansion-panel.module.js
34:12-24 "export 'PortalModule' was not found in '@angular/cdk'

WARNING in ./~/@covalent/core/file/file.module.js
44:12-24 "export 'PortalModule' was not found in '@angular/cdk'

WARNING in ./~/@covalent/core/loading/loading.module.js
36:12-24 "export 'PortalModule' was not found in '@angular/cdk'

WARNING in ./~/@covalent/core/steps/steps.module.js
39:12-24 "export 'PortalModule' was not found in '@angular/cdk'

WARNING in ./~/@covalent/core/common/behaviors/disabled.mixin.js
30:31-52 "export 'coerceBooleanProperty' was not found in '@angular/cdk'

WARNING in ./~/@covalent/core/common/behaviors/disable-ripple.mixin.js
30:31-52 "export 'coerceBooleanProperty' was not found in '@angular/cdk'

WARNING in ./~/@covalent/core/chips/chips.component.js
43:2-25 "export 'TemplatePortalDirective' was not found in '@angular/cdk'

WARNING in ./~/@covalent/core/chips/chips.component.js
57:2-25 "export 'TemplatePortalDirective' was not found in '@angular/cdk'

WARNING in ./~/@covalent/core/chips/chips.component.js
175:28-49 "export 'coerceBooleanProperty' was not found in '@angular/cdk'

WARNING in ./~/@covalent/core/chips/chips.component.js
189:33-54 "export 'coerceBooleanProperty' was not found in '@angular/cdk'

WARNING in ./~/@covalent/core/chips/chips.component.js
343:17-20 "export 'TAB' was not found in '@angular/cdk'

WARNING in ./~/@covalent/core/chips/chips.component.js
349:17-23 "export 'ESCAPE' was not found in '@angular/cdk'

WARNING in ./~/@covalent/core/chips/chips.component.js
364:8-15 "export 'RxChain' was not found in '@angular/cdk'

WARNING in ./~/@covalent/core/chips/chips.component.js
364:58-70 "export 'debounceTime' was not found in '@angular/cdk'

WARNING in ./~/@covalent/core/chips/chips.component.js
534:17-25 "export 'UP_ARROW' was not found in '@angular/cdk'

WARNING in ./~/@covalent/core/chips/chips.component.js
548:17-27 "export 'LEFT_ARROW' was not found in '@angular/cdk'

WARNING in ./~/@covalent/core/chips/chips.component.js
549:17-23 "export 'DELETE' was not found in '@angular/cdk'

WARNING in ./~/@covalent/core/chips/chips.component.js
550:17-26 "export 'BACKSPACE' was not found in '@angular/cdk'

WARNING in ./~/@covalent/core/chips/chips.component.js
559:17-28 "export 'RIGHT_ARROW' was not found in '@angular/cdk'

WARNING in ./~/@covalent/core/chips/chips.component.js
576:17-23 "export 'DELETE' was not found in '@angular/cdk'

WARNING in ./~/@covalent/core/chips/chips.component.js
577:17-26 "export 'BACKSPACE' was not found in '@angular/cdk'

WARNING in ./~/@covalent/core/chips/chips.component.js
583:17-25 "export 'UP_ARROW' was not found in '@angular/cdk'

WARNING in ./~/@covalent/core/chips/chips.component.js
584:17-27 "export 'LEFT_ARROW' was not found in '@angular/cdk'

WARNING in ./~/@covalent/core/chips/chips.component.js
591:61-71 "export 'LEFT_ARROW' was not found in '@angular/cdk'

WARNING in ./~/@covalent/core/chips/chips.component.js
604:17-27 "export 'DOWN_ARROW' was not found in '@angular/cdk'

WARNING in ./~/@covalent/core/chips/chips.component.js
605:17-28 "export 'RIGHT_ARROW' was not found in '@angular/cdk'

WARNING in ./~/@covalent/core/chips/chips.component.js
612:61-72 "export 'RIGHT_ARROW' was not found in '@angular/cdk'

WARNING in ./~/@covalent/core/chips/chips.component.js
734:37-44 "export 'RxChain' was not found in '@angular/cdk'

WARNING in ./~/@covalent/core/chips/chips.component.js
734:95-101 "export 'filter' was not found in '@angular/cdk'

WARNING in ./~/@covalent/core/data-table/data-table.component.js
188:31-52 "export 'coerceBooleanProperty' was not found in '@angular/cdk'

WARNING in ./~/@covalent/core/data-table/data-table.component.js
203:30-51 "export 'coerceBooleanProperty' was not found in '@angular/cdk'

WARNING in ./~/@covalent/core/data-table/data-table.component.js
218:29-50 "export 'coerceBooleanProperty' was not found in '@angular/cdk'

WARNING in ./~/@covalent/core/data-table/data-table.component.js
233:29-50 "export 'coerceBooleanProperty' was not found in '@angular/cdk'

WARNING in ./~/@covalent/core/data-table/data-table.component.js
464:17-22 "export 'ENTER' was not found in '@angular/cdk'

WARNING in ./~/@covalent/core/data-table/data-table.component.js
465:17-22 "export 'SPACE' was not found in '@angular/cdk'

WARNING in ./~/@covalent/core/data-table/data-table.component.js
469:17-25 "export 'UP_ARROW' was not found in '@angular/cdk'

WARNING in ./~/@covalent/core/data-table/data-table.component.js
495:17-27 "export 'DOWN_ARROW' was not found in '@angular/cdk'

WARNING in ./~/@covalent/core/data-table/directives/data-table-template.directive.js
28:2-25 "export 'TemplatePortalDirective' was not found in '@angular/cdk'

WARNING in ./~/@covalent/core/expansion-panel/expansion-panel.component.js
30:2-25 "export 'TemplatePortalDirective' was not found in '@angular/cdk'

WARNING in ./~/@covalent/core/expansion-panel/expansion-panel.component.js
44:2-25 "export 'TemplatePortalDirective' was not found in '@angular/cdk'

WARNING in ./~/@covalent/core/expansion-panel/expansion-panel.component.js
58:2-25 "export 'TemplatePortalDirective' was not found in '@angular/cdk'

WARNING in ./~/@covalent/core/expansion-panel/expansion-panel.component.js
115:28-49 "export 'coerceBooleanProperty' was not found in '@angular/cdk'

WARNING in ./~/@covalent/core/file/directives/file-select.directive.js
36:29-50 "export 'coerceBooleanProperty' was not found in '@angular/cdk'

WARNING in ./~/@covalent/core/file/directives/file-drop.directive.js
54:29-50 "export 'coerceBooleanProperty' was not found in '@angular/cdk'

WARNING in ./~/@covalent/core/file/file-upload/file-upload.component.js
81:29-50 "export 'coerceBooleanProperty' was not found in '@angular/cdk'

WARNING in ./~/@covalent/core/file/file-input/file-input.component.js
38:2-25 "export 'TemplatePortalDirective' was not found in '@angular/cdk'

WARNING in ./~/@covalent/core/file/file-input/file-input.component.js
103:29-50 "export 'coerceBooleanProperty' was not found in '@angular/cdk'

WARNING in ./~/@covalent/core/json-formatter/json-formatter.component.js
251:8-11 "export 'Dir' was not found in '@angular/cdk'

WARNING in ./~/@covalent/core/loading/services/loading.factory.js
43:64-79 "export 'ComponentPortal' was not found in '@angular/cdk'

WARNING in ./~/@covalent/core/loading/services/loading.factory.js
72:55-69 "export 'TemplatePortal' was not found in '@angular/cdk'

WARNING in ./~/@covalent/core/paging/paging-bar.component.js
56:34-54 "export 'coerceNumberProperty' was not found in '@angular/cdk'

WARNING in ./~/@covalent/core/paging/paging-bar.component.js
71:29-49 "export 'coerceNumberProperty' was not found in '@angular/cdk'

WARNING in ./~/@covalent/core/paging/paging-bar.component.js
89:26-46 "export 'coerceNumberProperty' was not found in '@angular/cdk'

WARNING in ./~/@covalent/core/paging/paging-bar.component.js
151:21-41 "export 'coerceNumberProperty' was not found in '@angular/cdk'

WARNING in ./~/@covalent/core/paging/paging-bar.component.js
162:25-45 "export 'coerceNumberProperty' was not found in '@angular/cdk'

WARNING in ./~/@covalent/core/paging/paging-bar.component.js
303:37-40 "export 'Dir' was not found in '@angular/cdk'

WARNING in ./~/@covalent/core/search/search-input/search-input.component.js
153:37-40 "export 'Dir' was not found in '@angular/cdk'

WARNING in ./~/@covalent/core/steps/step.component.js
36:2-25 "export 'TemplatePortalDirective' was not found in '@angular/cdk'

WARNING in ./~/@covalent/core/steps/step.component.js
50:2-25 "export 'TemplatePortalDirective' was not found in '@angular/cdk'

WARNING in ./~/@covalent/core/steps/step.component.js
64:2-25 "export 'TemplatePortalDirective' was not found in '@angular/cdk'

WARNING in ./~/@covalent/core/steps/step.component.js
115:28-49 "export 'coerceBooleanProperty' was not found in '@angular/cdk'

WARNING in ./~/@covalent/core/steps/step.component.js
146:34-48 "export 'TemplatePortal' was not found in '@angular/cdk'

**Comment by gbrigens** [comment]
How did you solve this am getting same error warnings and a errors of

`has no exported member 'TemplatePortalDirective'.`

**Comment by thinkingmedia** [comment]
@gbrigens  `npm` is not warning you that you have mismatched versions of Angular Material. The latest version of Covalent requires `2.0.0-beta.8` but you most likely have version `2.0.0-beta.10` installed.

Modify your `package.json` so that this is the versions:

```
    "@angular/material": "2.0.0-beta.8",
    "@angular/cdk": "2.0.0-beta.8",
```

`npm` does not see **beta** version numbers as different values. It's confused by the `2.0.0` and doesn't see `beta.8` as a lower value than `beta.10`.

You can fix this by not using the **^** prefix on the version which forces npm to do an exact match. Now `npm` will issue a warning when your Covalent and Angular Material libraries are not matching.
