### ISSUE TITLE
Don't render tdLoading template when using tdLoadingStrategy="replace"

### ISSUE THREAD

**Issue by aciccarello** [Teradata/covalent#798]
#### Feature Request
Don't evaluate the `tdLoading` template if `tdLoadingStrategy="replace"` and `tdLoadingUntil="falsey"`.

##### Screenshots or link to CodePen/Plunker/JSfiddle
[Loading flicker demo](http://plnkr.co/edit/CSR7q7jti5xVGHSspH7I?p=preview) (Throttle CPU to increase the effect)

#### What is the motivation / use case for changing the behavior?
1. There would be no flicker of empty content before progress bar replaces content
2. Developers could write templates without needing to handle empty content

Both motivations can be handled by wrapping the content in an `*ngIf` using the same expression as `tdLoadingUntil`. Therefore this feature request is mainly to simplify writing templates for developers.

Not evaluating templates is helpful if waiting for an object to be loaded asynchronously.
```html
  <md-card>
    <md-card-title>Demo</md-card-title>  
    <md-card-content>
      <ng-template tdLoading [tdLoadingUntil]="objectLoaded">
        <!-- use safe navigation operator to avoid "Cannot read property 'value' of undefined" -->
        This is the content: {{ objectLoaded?.value }}
        The object may be referenced many times: {{ objectLoaded?.value }}
        <div *ngIf="objectLoaded">
          Could also wrap content in ngIf to avoid loading template: {{ objectLoaded.value }}
        </div>
      </ng-template>
    </md-card-content>
  </md-card>
````

#### Which version of Angular and Material, and which browser and OS does this issue affect?

- Angular v4.3.2
- Angular Material v2.0.0-beta.8
- Covalent v1.0.0-beta.6

**Comment by owilliams320** [comment]
this component is deprecated and will no longer be supported in future versions https://material.angular.io/components/progress-spinner/overview
