### ISSUE TITLE
<td-layout> [mode] and [sidenavWidth] don't work.

### ISSUE THREAD

**Issue by MRMokwa** [Teradata/covalent#799]
#### Bug Report

From https://teradata.github.io/covalent/#/layouts

```
<td-layout [mode]="side" [opened]="true" [sidenavWidth]="257px">
  <div td-sidenav-content>
   .. more sidenav content
  </div>
  .. main content
</td-layout>
```

The [mode] doesn't respect "side" and "push" options.
The [sidenavWidth] doesn't respect the width. If you specifie "px" like the example above the app breaks.

#### Which version of Angular and Material, and which browser and OS does this issue affect?

"angular/core": "^4.3.3",
"angular/material": "^2.0.0-beta.8",
"covalent/core": "^1.0.0-beta.6",

**Comment by emoralesb05** [comment]
You are adding them as variable names, not as `strings`.. please remove the `[]` off the inputs.

Adding `[]` to an input makes angular evaluate whats assigned to it, in this case its looking for a variable called `side` and a variable called `257px`

**Comment by MRMokwa** [comment]
Without the `[]` it worked.
Just want to point out that the `[opened]=true` also works and that I was following instructions from the
> TdLayoutComponent - td-layout -> API Summary -> Usage
It'll be necessary to update this doc.
