### ISSUE TITLE
Template Broken on Safari

### ISSUE THREAD

**Issue by RicardoVaranda** [Teradata/covalent#801]
This repository's issues are reserved for feature requests and bug reports.

### Do you want to request a *feature* or report a *bug*?
BUG

#### Bug Report

Browsing to https://teradata.github.io/covalent/ shows the bugs in the template, some pictures for clarity below.

##### Screenshots or link to CodePen/Plunker/JSfiddle
https://www.browserstack.com/issue-tracker/3f9f2a9409dafaaae3c446ff0d95e9400ce51e3e/realios_iPhone_6.jpg

https://www.browserstack.com/issue-tracker/ebc90e94aabed292c052d01f3990255a25e8da7b/realios_iPhone_6.jpg

#### What is the expected behavior?

No Graphical bugs? :)

#### What is the motivation / use case for changing the behavior?

Nicer UX 💃 

##### Other information
(e.g. detailed explanation, stacktraces, related issues, suggestions how to fix)

I ran these tests on browser stack as well as on physical devices with the latest safari browser and the results were identical.

**Comment by kyleledbetter** [comment]
Very odd. Which version of iOS? I'm running 10.3.3 and it looks fine 
![img_3873](https://user-images.githubusercontent.com/867883/28972070-2648d314-78e3-11e7-9072-9e909fd58634.PNG)

**Comment by RicardoVaranda** [comment]
Hi @kyleledbetter it's Safari 9

**Comment by kyleledbetter** [comment]
What version specifically? Also that's an old desktop version and you're posting iOS screenshots. Are you just doing random tests?

**Comment by RicardoVaranda** [comment]
It's actually still available on iOS also, I found the specific device I was testing on was even older, running safari 8 and thus why it would show it like that, sorry for the hassle.
