### ISSUE TITLE
dynamic forms select values

### ISSUE THREAD

**Issue by pabloxn** [Teradata/covalent#802]
#### Feature Request

I would like to have the ability to create a value for selection separate to the displayed value. 
My reason would be parametric reports would show a description but have a numerical value for calculating a result.

**Comment by berga** [comment]
@emoralesb05 can you consider to accept selections as objects array `[{value:, label:}]`
and template like 
`<md-option *ngFor="let selection of selections" [value]="selection.value | selection">{{selection.label | selection}}</md-option>`

**Comment by pabloxn** [comment]
Yup that would work perfectly

**Comment by emoralesb05** [comment]
dup of https://github.com/Teradata/covalent/issues/832

**Comment by berga** [comment]
@emoralesb05 I've pushed b505cd7 to the new branch feature/form_select_values to my fork, may I PR?

**Comment by emoralesb05** [comment]
Sure, go for it @berga ! 😄

**Comment by emoralesb05** [comment]
https://github.com/Teradata/covalent/issues/802 will take care of this.
