### ISSUE TITLE
just interesting

### ISSUE THREAD

**Issue by lincze** [Teradata/covalent#803]
i went through this today, and my be even better for error reporting, feature request, etc, than plunkr.

https://medium.com/@ericsimons/stackblitz-online-vs-code-ide-for-angular-react-7d09348497f4
https://stackblitz.com/edit/angular-j2jaxd

**Comment by aciccarello** [comment]
I think it'd be helpful if there were links to some of @kyleledbetter's [stackblitz starters](https://stackblitz.com/@kyleledbetter) in the readme and issue template.

**Comment by emoralesb05** [comment]
Yeah, @kyleledbetter just migrated our templates to stackblitz, so we need to update the links in the `issue template` and stuff like that to showcase the starter one

**Comment by emoralesb05** [comment]
Closing this since we are using stackblitz now 😄
