### ISSUE TITLE
Error when ng serve

### ISSUE THREAD

**Issue by gronel** [Teradata/covalent#806]
Good day ,

i just follow the instruction how to run locally but this is the result
please help.

ERROR in d:/files/mygithub/covalent/node_modules/@types/node/index.d.ts (73,13): Subsequent variable declarations must have the same type.  Variable 'require' must be of type 'any', but here has type 'NodeRequire'.

ERROR in D:/Files/myGitHub/covalent/src/universal-app/battle-royale.ts (6,53): Cannot find module './dist/aot/combat-training/combat-training.ngfactory'.
webpack: Failed to compile.

Thanks

**Comment by kyleledbetter** [comment]
Are you building off develop or our latest release beta.6?

**Comment by emoralesb05** [comment]
This happened because of some recent commits we have, will be fixed soon.

**Comment by emoralesb05** [comment]
This has been fixed now

**Comment by gronel** [comment]
​I clone it again and its ok now. thanks alot​
