### ISSUE TITLE
Td-data-table

### ISSUE THREAD

**Issue by Leonzen** [Teradata/covalent#808]
This repository's issues are reserved for feature requests and bug reports.

### Do you want to request a *feature* or report a *bug*?
Bug

#### Bug Report
I'm using the td-data-table with paging, select and multiple select. I press the select all checkbox on one page all elements on this page are selected. But if I press the select all checkbox to remove my selection on this page all selections (on every page) are gone.

please provide steps to reproduce and if possible screenhots, animated Gifs and/or a Plunker (or similar).
you can easily create animated Gif with this free PC/OSX App: http://www.cockos.com/licecap/ and a Plunker to help us reproduce it
Plunker template: http://plnkr.co/edit/7uZQn4mLNJkL6XN9WSNd

##### Screenshots or link to CodePen/Plunker/JSfiddle
http://plnkr.co/edit/mmnriENZu5jorgtHzFPe?p=preview

#### What is the expected behavior?
If I press the checkbox on one page to remove the selection, the selections should only be removed on the current page.

#### What is the motivation / use case for changing the behavior?
It can always happen that the user wants to remove all selections on the current page and presses the  "accidently" the select all checkbox and all selections are removed instead of just the selections on the current page.

#### Which version of Angular and Material, and which browser and OS does this issue affect?
Angular: 4.0.0
Material: 2.0.0-beta.8
Covalent: 1.0.0-beta.6
OS: Windwos 7
Browser: Chrome 59

##### Other information
Is there a way to get the data of only one row by selecting it or is it only possible through an array which hold the data of all selected rows?

**Comment by emoralesb05** [comment]
Taken care in https://github.com/Teradata/covalent/pull/859
