### ISSUE TITLE
TdFileInputComponent - clear event is not emitted from component 

### ISSUE THREAD

**Issue by nni123** [Teradata/covalent#810]
Hello, I am working on TdFileInputComponent and it is not emitting clear event. I did check the source code and eventemitter is missing after this.clear() in component JS file.

API Summary has clear event 
https://teradata.github.io/covalent/#/components/file-input 

Only select event is emitted and someone forgot to write about clear event.

**Comment by jotatoledo** [comment]
There is no description of a clear event in the API documentation.

**Comment by nni123** [comment]
I misinterpreted the doc. It is function and won't emit any event on fileInput.clear() call.

Ideally it should emit clear event when you use fileInput.clear() function.

**Comment by nni123** [comment]
[1] If you allow multiple file upload in that case how user can remove single file. Right now, default behaviour is remove all the files & reselect. It is same from FileInput & FileUpload component. 

[2]  I am checking if you have any plan to add following events to fileinput or upload component

onClear : files in queue are removed without uploading using clear all button.

onProgress : To calculated progress value.

Thanks
