### ISSUE TITLE
Missing row double click event in data table

### ISSUE THREAD

**Issue by micobarac** [Teradata/covalent#813]
Data table only has **rowClick** event. Double click event is missing. I must say it is counter intuitive to use row click for showing details or edit form. This way user cannot copy any value from data grid. Double click row event is way better, and is missing, according to documentation.

**Comment by kyleledbetter** [comment]
Double click is a desktop anti pattern. If you want clickable items for some columns but not all you can use a template for a column and not use the rowclick

**Comment by emoralesb05** [comment]
Right, clicking on a row to show details is not really good `material design` approach, you can add a button/icon to click for any display/edit action.

**Comment by aciccarello** [comment]
A related [SO question](https://stackoverflow.com/q/47179785/4252741) just came up. Perhaps the docs could include tips on alternatives to double click.

**Comment by jeremysmartt** [comment]
closing, not supporting double click on table at this time.
