### ISSUE TITLE
Data table proposed template for no results is bad

### ISSUE THREAD

**Issue by micobarac** [Teradata/covalent#814]
```
    <div class="md-padding" *ngIf="!dataTable.hasData" layout="row" layout-align="center center">
            <h3>No results to display.</h3>
    </div>
```
The problem with this approach is that no results message will be visible during data loading process, which is not optimal.

**Comment by jotatoledo** [comment]
Where did you got that from? The table component doesnt render that as default behavior, and it has no way to know if you are currently waiting for data to arrrive. This can easily be solved by adding a loadinf flag value to your if condition.

_Sent from my Huawei ALE-L21 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by jotatoledo** [comment]
This could be solved by adding a loading flag value. Not a real issue

_Sent from my Huawei ALE-L21 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by micobarac** [comment]
Where do I get loading flag from? I cannot find it in data table component properties.

**Comment by micobarac** [comment]
This is a part of the official docs demo:

`<td-data-table
  #dataTable
  [data]="filteredData"
  [columns]="columns"
  [selectable]="selectable"
  [clickable]="clickable"
  [multiple]="multiple"
  [sortable]="true"
  [sortBy]="sortBy"
  [(ngModel)]="selectedRows"
  [sortOrder]="sortOrder"
  (sortChange)="sort($event)">
</td-data-table>
<div class="md-padding" *ngIf="!dataTable.hasData" layout="row" layout-align="center center">
  <h3>No results to display.</h3>
</div>`

Where does the loading flag come from?

**Comment by emoralesb05** [comment]
What @jotatoledo meant was using a loading flag working with the `tdLoading` directive, you can use a loader to hide that text while doing a request.

**Comment by jotatoledo** [comment]
I meant something like

*ngIf="!(loading$ | async) && !table.hasData"

_Sent from my Huawei ALE-L21 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by micobarac** [comment]
Where does loading$ come from? I tried it, it doesn't work. No results message is always visible, no matter what.

**Comment by jotatoledo** [comment]
That is an `Observable<boolean>` that you should create and manage.

**Comment by jeremysmartt** [comment]
Solution provided, closing issue
