### ISSUE TITLE
how to put element into the header of the table in "status" column

### ISSUE THREAD

**Issue by charedim** [Teradata/covalent#817]
I use with "td-data-table" elment, Im want to insert the filter icon into the header of the table instead the column name. 

In typeScript I add 
  this.columns=  [
        { name: 'client', label: 'Cliente/Nota/Recebivel' },
        { name: 'dueDate', label: 'Vencimento',format:v=>v.toLocaleDateString() },
        { name: 'originalValue', label: 'valor',format:v=>'R$'+v },
        { name: 'taxa', label: 'Taxa',format:v => v+'%',sortable:false},
        { name: 'totalSum', label: 'Total Sum',format:v=>'R$'+v.toFixed(2)},
        { name: 'status',label:""},

      ];

HTML:
<td-data-table
  #dataTable
  [data]="filteredData"
  [selectable]="selectable"
  [columns]="columns"
  [sortable]="true"
  [sortBy]="sortBy"
  [sortOrder]="sortOrder"
  (sortChange)="sort($event)">

I'm want instead of "label" to put the filter icon;

![screenshot from 2017-08-17 17-22-34](https://user-images.githubusercontent.com/29884070/29417513-168f2e84-8372-11e7-81ec-25a1d6e5c43e.png)

**Comment by emoralesb05** [comment]
This capability will be added later on, its not yet possible to achieve this using `<td-data-table>`

**Comment by digitalmedia34** [comment]
Curious, was this ever added?

**Comment by owilliams320** [comment]
this component is deprecated please use https://material.angular.io/components/table
