### ISSUE TITLE
Messages & Alerts Demo breaks after looking at code

### ISSUE THREAD

**Issue by aciccarello** [Teradata/covalent#819]
#### Bug Report
In the [Messages & Alerts documentation](https://teradata.github.io/covalent/#/components/message) the styling of the messages breaks after switching to the code demo. There aren't any errors reported in the console.

##### Screenshots or link to CodePen/Plunker/JSfiddle
![message demo breaking](https://user-images.githubusercontent.com/11273838/29433659-59d3e6fe-835d-11e7-8069-80bcb71a5b1e.gif)

#### What is the expected behavior?
The message styling should stay the same.

#### Which version of Angular and Material, and which browser and OS does this issue affect?
Chrome 60 64-bit on Windows 7

**Comment by emoralesb05** [comment]
This is a problem that happens because `md-tabs` cancel initial animations on components rendered in them for some reason.. they have an issue open to address this in material.

**Comment by aciccarello** [comment]
Looks like this is no longer an issue
