### ISSUE TITLE
Feature request: Dynamic forms checkboxes from array

### ISSUE THREAD

**Issue by natejgardner** [Teradata/covalent#820]
There are many cases when I'd like the user to be able check a number of related boxes and have the results be turned into an array.

Ideal:

```
filters: ITdDynamicElementConfig[] = [{
    name: "userChoices",
    type: TdDynamicType.CheckboxArray,
    selections: [
        {name: 'choice1', label: 'Choice One'}
        {name: 'choice2', label: 'Choice Two'}
        {name: 'choice3', label: 'Choice Three'}
    ],
    default: ['choice1', 'choice3'],
    required: true //this would throw an error if nothing is selected
    }]
```

This would display something like this:

- [x] Choice One
- [ ] Choice Two
- [x] Choice Three

And provide an array on the backend like:

```
['choice1','choice3']
```

This is particularly useful when assembling filters where a user may be selecting many options and it's not convenient to manually check the boolean state of every checkbox as the developer.

**Comment by markonyango** [comment]
#1201 I have created this PR as I very much would like such an option too.
