### ISSUE TITLE
how can I override the 'font family' .

### ISSUE THREAD

**Issue by charedim** [Teradata/covalent#821]
Hi, I'm want to ovveride the font family
from Robeto to  'https://fonts.googleapis.com/css?family=Ubuntu+Condensed'
how can I do It??

**Comment by jotatoledo** [comment]
https://material.angular.io/guide/typography

**Comment by emoralesb05** [comment]
Yes, we will actually start implementing the `typography` from material in our components soon.

**Comment by emoralesb05** [comment]
Now you will be able to override it in covalent following the `material` typography example. We just merged a PR with this support https://github.com/Teradata/covalent/pull/963
