### ISSUE TITLE
[Feature] Fixed table header

### ISSUE THREAD

**Issue by Leonzen** [Teradata/covalent#824]
### Do you want to request a *feature* or report a *bug*?
Feature

#### Feature Request
Please make the header of the td-data-table fixed, so that if the table needs to be scrolled the header stays. 

#### What is the motivation / use case for changing the behavior?
If the table value exceeds the maximum size of the table the user has to scroll. It is good to see the header while scrolling to know what the value means.

#### Which version of Angular and Material, and which browser and OS does this issue affect?
Angular: 4.3.5
Material: 2.0.0-beta.8
Covalent: 1.0.0-beta.6
OS: Windwos 7
Browser: Chrome 60

**Comment by emoralesb05** [comment]
This will be taken care of with https://github.com/Teradata/covalent/pull/859
