### ISSUE TITLE
Open dialogue from edit action Button in DataTable

### ISSUE THREAD

**Issue by turab007** [Teradata/covalent#828]
I am using teraData Covalent dataTable. I want to open a dialogue when edit is selected from the actionButtons. The code template i used only had option for a url. How do i pass open a dialogue?

The code for action buttons is below
```
 actionButtons: any[] = [
    {
      'title': "View",
      'icon': "visibility",
      'url': "/business-opps/contacts/view"
    },
    {
      'action':'update',
      'title': "Update",
      'icon': "edit",
    },
    {
      'action': 'delete',
      'title': "Delete",
      'icon': "delete",
      'url': ""
    }
  ]
```
And this is my datatable 

```
        <datatable *ngIf="eodReports" 
                [dataList]="eodReports" 
                [columns]="dtColumns" 
                [actionButtons]="actionButtons"
                [totalRecords]="totalRecords" 
                [sortBy]="'date'"
                (deleteRecord)="deleteRecord($event)"
                (nextPage)="nextPage($event)"
                (filterRecords)="filterRecords($event)"
            >
            </datatable>
```

**Comment by jotatoledo** [comment]
this isnt an issue, if you need support/help please use either stackoverflow or gitter

**Comment by emoralesb05** [comment]
As @jotatoledo stated, you can use the gitter chat to ask the community for help on specific usages 😄  (which in this case is using a cell template)

https://gitter.im/Teradata/covalent

Closing since it should be addressed over gitter
