### ISSUE TITLE
Unable  to check the checkbox in Table with components teradata template.

### ISSUE THREAD

**Issue by buddhikaumagiliya** [Teradata/covalent#830]
I'm working with  Data Table with components.
I need to check the check box on edit mode. but i was unable to find a way.
div layout="row" layout-align="start center" class="pad-left-sm pad-right-sm" [class.mat-selected-title]="selectedRowsApp.length && selectableApp">
    <span *ngIf="!searchBoxApp.searchVisible" class="push-left-sm">
        <span *ngIf="selectedRowsApp.length && selectableApp" class="md-body-1">{{selectedRowsApp.length}} selected</span>
    </span>
    <td-search-box #searchBoxApp backIcon="arrow_back" class="push-right-sm" placeholder="Search here" (searchDebounce)="searchApp($event)" flex>
    </td-search-box>
    <div mdTooltip="Manage User Role">
        <button md-icon-button [disabled]="!selectedRowsApp.length" (click)="sendtoApp(selectedRowsApp)">
            <md-icon>check</md-icon>
        </button>
    </div>
</div>
<md-divider></md-divider>
<td-data-table #dataTableApp
               [data]="filteredDataApp"
               [columns]="columnsApp"
               [selectable]="selectableApp"
               [multiple]="multipleApp"
               [(ngModel)]="selectedRowsApp"
               (sortChange)="sortApp($event)">
</td-data-table>
<div class="md-padding" *ngIf="!dataTableApp.hasData" layout="row" layout-align="center center">
    <h3>No results to display.</h3>
</div>
<td-paging-bar #pagingBarApp [pageSizes]="[5, 10, 15, 20]" [total]="filteredTotalApp" (change)="pageApp($event)">
    <span td-paging-bar-label hide-xs>Row per page:</span>
    {{pagingBarApp.range}} <span hide-xs>of {{pagingBarApp.total}}</span>
</td-paging-bar>
Image
Please Help me
![image](https://user-images.githubusercontent.com/4515747/29665865-9e06fc30-88f3-11e7-9576-896bfadeca60.png)

**Comment by emoralesb05** [comment]
Can you give more context? What do you mean unable to find a way?

**Comment by buddhikaumagiliya** [comment]
I need set the value of checkbox using server side response. i was unable to do that.
Using typescript i need to set that value.
you can see the image using below link
https://user-images.githubusercontent.com/4515747/29700270-d7bda5f4-8980-11e7-870e-6dd1210542c8.png
//////////////////// html//////////////////////////////////
  <md-card-content class="push-bottom-none">
                    <div layout="row" layout-align="start center" class="pad-left-sm pad-right-sm" [class.mat-selected-title]="selectedRows.length && selectable">


                        <span *ngIf="!searchBox.searchVisible" class="push-left-sm">
                            
                            <span *ngIf="selectedRows.length && selectable" class="md-body-1">Ref. Detail No : {{selectedRows[0].UserRoleName}} selected</span>
                        </span>
                        <td-search-box #searchBox backIcon="arrow_back" class="push-right-sm" placeholder="Search here" (searchDebounce)="search($event)" flex>
                        </td-search-box>
                        <div mdTooltip="Edit">
                            <button md-icon-button [disabled]="!selectedRows.length" (click)="editURoleHeader(selectedRows)">
                                <md-icon>mode_edit</md-icon>
                            </button>
                        </div>
                        <div mdTooltip="Manage User Role">
                            <button md-icon-button [disabled]="!selectedRows.length" (click)="ManageURole(selectedRows)">
                                <md-icon>web</md-icon>
                            </button>
                        </div>
                    </div>
                    <md-divider></md-divider>
                    <td-data-table #dataTable
                                   [data]="filteredData"
                                   [columns]="columns"
                                   [selectable]="selectable"
                                   [multiple]="multiple"
                                   [sortable]="true"
                                   [sortBy]="sortBy"
                                   [(ngModel)]="selectedRows"
                                   [sortOrder]="sortOrder"
                                   (sortChange)="sort($event)">
                    </td-data-table>
                    <div class="md-padding" *ngIf="!dataTable.hasData" layout="row" layout-align="center center">
                        <h3>No results to display.</h3>
                    </div>
                    <td-paging-bar #pagingBar [pageSizes]="[5, 10, 15, 20]" [total]="filteredTotal" (change)="page($event)">
                        <span td-paging-bar-label hide-xs>Row per page:</span>
                        {{pagingBar.range}} <span hide-xs>of {{pagingBar.total}}</span>
                    </td-paging-bar>
                </md-card-content>
////////////////////////////////// Type Script ////////////////////////////////////
    selectableApp: boolean = true;
    multipleApp: boolean = true;
    griddataApp: any[] = [];
    sortByApp: string = 'varAppName';
    filteredDataApp: any[] = [];
    filteredTotalApp: number = 0;
    searchTermApp: string = '';
    fromRowApp: number = 1;
    currentPageApp: number = 1;
    pageSizeApp: number = 20;
    selectedRowsApp: any[] = [];
    sortOrderApp: TdDataTableSortingOrder = TdDataTableSortingOrder.Descending;


    filterApp(): void {
        let newDataApp: any[] = this.griddataApp;
        newDataApp = this._dataTableService.filterData(newDataApp, this.searchTermApp, true);
        this.filteredTotalApp = newDataApp.length;
        newDataApp = this._dataTableService.sortData(newDataApp, this.sortByApp, this.sortOrderApp);
        newDataApp = this._dataTableService.pageData(newDataApp, this.fromRowApp, this.currentPageApp * this.pageSizeApp);
        this.filteredDataApp = newDataApp;
    }

 columnsApp: ITdDataTableColumn[] = [
        //{ name: 'numID', label: 'ID', sortable: true },
        { name: 'varAppName', label: 'App Name', sortable: true },
        { name: 'varFunctionName', label: 'Function Name', sortable: true },
        { name: 'varModuleName', label: 'Module Name', sortable: true },
        { name: 'bitAllow', label: 'Allowed', }
    ];

    searchApp(searchTerm: string): void {
        this.searchTermApp = searchTerm;
        this.filterApp();
    }
    pageApp(pagingEvent: IPageChangeEvent): void {
        this.fromRowApp = pagingEvent.fromRow;
        this.currentPageApp = pagingEvent.page;
        this.pageSizeApp = pagingEvent.pageSize;
        this.filterApp();
    }

thank you.

**Comment by emoralesb05** [comment]
We cant replicate this, can you provide a plnkr?

**Comment by emoralesb05** [comment]
Closing this since no additional information was provided.
