### ISSUE TITLE
responsive Datatable

### ISSUE THREAD

**Issue by charedim** [Teradata/covalent#833]
Is there a way to declare the DataTable as responsive

I'm using <td-data-table> in One Component, I'm want to declare it as responsive, How Can I????

Thank You!!

**Comment by emoralesb05** [comment]
What do you mean by "responsive"? A data table by definition is not responsive unless you hide/show columns.

**Comment by kyleledbetter** [comment]
@charedim the data table will use overflow scroll and scroll horizontally which isn't responsive but works on mobile. 

What you're probably asking for is super complex and hard to automate. 

The only thing I'd recommend is using our hide-xs and hide-xs layout attributes to hide the data table and the replace it by showing a md-list instead on xs and sm

**Comment by charedim** [comment]
Thank you for your help.

What I would like to know is if there is a way to determine the width of each column separately

**Comment by emoralesb05** [comment]
Yes, after `beta.7` release this is possible. Closing this since you can now set the `width` for each column

**Comment by GopiAnnan** [comment]
@kyleledbetter 

Can DataTable automatically shown as List View  for smaller device Like PrimeNG Datatable.  PFA Images.

If we see in PrimeNG Datatable if responsive set to true.  It will automatically shown as list item for smaller device. 
Is there anyway we can achieve this.?

![dasktop view](https://user-images.githubusercontent.com/20523260/34007686-b19b85d8-e0d0-11e7-8da3-a465e1bf90c2.jpg)

![mobile view](https://user-images.githubusercontent.com/20523260/34007749-e91a7884-e0d0-11e7-821d-60e633ca062d.jpg)

**Comment by kyleledbetter** [comment]
@GopiAnnan to achieve something similar that follows the Material Design spec I'd recommend what I recommended above :)

Hide the datatable on xs or sm screens and reveal a mat-list
