### ISSUE TITLE
"npm run build" at the current development branch

### ISSUE THREAD

**Issue by lincze** [Teradata/covalent#834]
This repository's issues are reserved for feature requests and bug reports.

#### Bug Report

i'm getting error in the current devlopment branch (8b548e675...):

```
...
[18:50:23] Using gulpfile {path_to_covalent}/covalent/gulpfile.js
[18:50:23] Starting 'rollup-code'...
[18:50:23] 'rollup-code' errored after 107 ms
[18:50:23] Error: Could not resolve './animations' from {path_to_covalent}/covalent/deploy/platform/core/common/common.module.js
    at {path_to_covalent}/covalent/node_modules/rollup/dist/rollup.js:8763:40
    at process._tickCallback (internal/process/next_tick.js:109:7)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:504:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! covalent@1.0.0-beta.6 build: `bash scripts/build-release`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the covalent@1.0.0-beta.6 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/incze/.npm/_logs/2017-08-27T16_50_23_908Z-debug.log
...
```

though "npm serve" works as expected.

#### Which version of Angular and Material, and which browser and OS does this issue affect?

---
it's not entirely new, i've been experiencing it for some last couple of develop commit's. this behavior shows itself even after "npm run rebuild" (node v6.11.2, npm v5.3.0, global ng-cli 1.3.0, local 1.2.7 as in the package.json)

**Comment by emoralesb05** [comment]
We are well aware of this, so dont worry about issues concerning the repos build/deploy process, we are gonna (and need to) fix them when we release. 

Thanks for looking out though. 😄
