### ISSUE TITLE
Documentation throws ExpressionChangedAfterItHasBeenCheckedError in Chip Events demo

### ISSUE THREAD

**Issue by aciccarello** [Teradata/covalent#836]
#### Bug Report
When removing a chip in the Chip Events demo, the ChipsDemoComponent.html throws an `ExpressionChangedAfterItHasBeenCheckedError`.

##### Screenshots or link to CodePen/Plunker/JSfiddle
![image](https://user-images.githubusercontent.com/11273838/29788288-41c12b5e-8bef-11e7-9edf-9f21c0d7e2b2.png)

#### What is the expected behavior?
Removing a chip from the demo should not cause

#### What is the motivation / use case for changing the behavior?
The documentation should not cause errors. Additionally, the demos should be good examples of how to use features for developers.

#### Which version of Angular and Material, and which browser and OS does this issue affect?
Affects Chrome 60 and IE11.

##### Other information
(e.g. detailed explanation, stacktraces, related issues, suggestions how to fix)
Encounter while testing the ie11 development branch for #831. Appears to have been caused by #785

**Comment by aciccarello** [comment]
I can no longer reproduce this. Seems to have been fixed.

**Comment by emoralesb05** [comment]
I love when something gets fixed without doing anything 🎉
