### ISSUE TITLE
TdChips Autocomplete disappears on "even" numbered keystrokes

### ISSUE THREAD

**Issue by larssoldahl** [Teradata/covalent#837]
This repository's issues are reserved for feature requests and bug reports.

### Do you want to request a *feature* or report a *bug*?

Report a bug

#### Bug Report
Using a setup near-identical to the demo, the autocomplete options will disappear every-other-keystroke. 

##### Screenshots or link to CodePen/Plunker/JSfiddle

http://plnkr.co/edit/7b9IyqMrjRjp24apxYEW?p=preview

#### What is the expected behavior?
Autocomplete drop-down to remain visible when it has valid filter options.

#### Which version of Angular and Material, and which browser and OS does this issue affect?

Using Covalent 1.0.0-beta.6 with Angular 4.2.0 and Material 2.0.0-beta.8

Did this work in previous versions of Angular / Material?
Yes

##### Other information
We noticed this issue last week after an npm update, while investigating a related bug.  The bug was initially reported as "adding labels breaks edit form", on trace I was able to see Angular throwing an error when the `router` was trying to `navigate()`:

    ERROR Error: Uncaught (in promise): Error: Cannot move a destroyed View in a ViewContainer!

**Comment by emoralesb05** [comment]
This is an implementation error:

The following piece of code is the one thats triggering that behavior

```
.filter((filteredObj: any) => {
      return this.currentLabels ? this.currentLabels.indexOf(filteredObj) < 0 : true;
    });
```

Since its basically saying, remove everything thats in `currentLabels`... this is supposed to be to remove everything thats part of the chips model.

**Comment by larssoldahl** [comment]
Doh!
You're 100% correct, thanks for the quick reply. I'll try to reproduce the underlying issue that got me down this path, with the router failing to navigate after a TdChipsComponent's autocomplete is triggered.

**Comment by emoralesb05** [comment]
No worries 😄 . Let us know when you find the issue to see if we need to create a bug fix for that.
