### ISSUE TITLE
How to use date-picker?

### ISSUE THREAD

**Issue by gozeon** [Teradata/covalent#839]
This repository's issues are reserved for feature requests and bug reports.

#### Feature Request

please first make sure your request falls under the official Material Design spec guidelines https://material.google.com/

#### Bug Report

please provide steps to reproduce and if possible screenhots, animated Gifs and/or a Plunker (or similar).
you can easily create animated Gif with this free PC/OSX App: http://www.cockos.com/licecap/ and a Plunker to help us reproduce it
Plunker template: http://plnkr.co/edit/7uZQn4mLNJkL6XN9WSNd

#### Which version of Angular and Material, and which browser and OS does this issue affect?

Did this work in previous versions of Angular / Material?
Please also test with the latest stable and snapshot versions.

##### Other information
(e.g. detailed explanation, stacktraces, related issues, suggestions how to fix)

**Comment by aciccarello** [comment]
@gozeon Covalent does not have it's own date picker component. You can use the official angular material component:

https://material.angular.io/components/datepicker/overview

**Comment by gozeon** [comment]
only use [timepicker](http://code.promactinfo.com/md2/#/datepicker) ...
