### ISSUE TITLE
Unable to click autocomplete options on TdChips (nightly build)

### ISSUE THREAD

**Issue by larssoldahl** [Teradata/covalent#840]
This repository's issues are reserved for feature requests and bug reports.

### Do you want to request a *feature* or report a *bug*?

bug

#### Bug Report

With the latest versions of Angular and Covalent, mouse interaction on the autocomplete menu is broken. The autocomplete options respond to hover, but the entire menu disappears without calling the internal `addChip()`, no new chip is added. Keyboard navigation/selection works without error.

##### Screenshots or link to CodePen/Plunker/JSfiddle

http://plnkr.co/edit/Cs65qrewh2FnQElAAvpT?p=preview

#### What is the expected behavior?
Users can click Autocomplete options to populate chips

#### Which version of Angular and Material, and which browser and OS does this issue affect?

Using Covalent-nightly with Angular 4.3.6 and Material 2.0.0-beta.8

#### Did this work in previous versions of Angular / Material?

Reverting to the 1.0.0-beta.6 of covalent resolves the issue.

##### Other information
Interesting to note: the options on the autocomplete won't un-style their hover/active state until moused over again.

**Comment by kyleledbetter** [comment]
Can you describe the 2 months of fixes? Nightly builds are obviously use at your own risk and volatile until the official releases

**Comment by larssoldahl** [comment]
I'll edit the original post to drop the bug fixes text, I guess a better phrasing would be: "two months of commits". As far as nightly being volatile that's totally understood, do you want bug reports for stuff like this on it?

**Comment by emoralesb05** [comment]
Bug reports are good in this repo, since the nightly build will eventually be the thing that gets released. 

Having said that we just fixed this in the IE11 support PR that just got merged https://github.com/Teradata/covalent/pull/831/commits/cbc98529a4d307b0d030781ccb7a9ba057738ec5 so once the build gets redeployed into the nightly build everything should be fine 😄

**Comment by larssoldahl** [comment]
Good stuff @emoralesb05 , thanks!

**Comment by emoralesb05** [comment]
Closing this since this was merged and will be released in beta.7
