### ISSUE TITLE
MdSelectionModule should be MdSelectModule?

### ISSUE THREAD

**Issue by DanjBethel** [Teradata/covalent#841]
This repository's issues are reserved for feature requests and bug reports.

### Do you want to request a *feature* or report a *bug*?
bug

#### Bug Report

Build error on ng build and ng serve. Screenshot below

<img width="956" alt="screen shot 2017-08-29 at 9 44 58 pm" src="https://user-images.githubusercontent.com/4720302/29851695-98b7d100-8d03-11e7-9d9b-651ddcbc9979.png">

#### Which version of Angular and Material, and which browser and OS does this issue affect?

Latest version of angular
Latest version of cli
latest version of covalent

##### Other information
(e.g. detailed explanation, stacktraces, related issues, suggestions how to fix)

**Comment by DanjBethel** [comment]
Probably just shouldn't have updated my angular/material. My bad I guess!

**Comment by emoralesb05** [comment]
Yeah, we will release soon to support the latest angular material since a lot of breaking changes where introduced.
