### ISSUE TITLE
Covalent vs Angular Material 2.0.0-beta.10

### ISSUE THREAD

**Issue by phamtuananh791994** [Teradata/covalent#842]
This repository's issues are reserved for feature requests and bug reports.

### Do you want to request a *feature* or report a *bug*?

BUG

#### Bug Report
After upgrade to Angular Material 2.0.0-beta.10 
![covalent](https://user-images.githubusercontent.com/14154992/29852109-66fc1662-8d62-11e7-8357-299037861260.png)

**Comment by jotatoledo** [comment]
Obviously you cant just go all cowboy and upgrade one of the dependencies of covalent and expect all to go right. Wait for the dev team to upgrade covalent first, and then update.

**Comment by phamtuananh791994** [comment]
Thanks 🇻🇳

**Comment by emoralesb05** [comment]
Yeah, we will release soon to support the latest angular material since a lot of breaking changes where introduced.

**Comment by jonathanmeguira** [comment]
how to downgrade to previous version of material then ? since changing it in package.json and running npm install still installs the last version 10

**Comment by emoralesb05** [comment]
You have control over that, you choose with material version to install.. if you have `^` infront of it then it will always install the latest.

**Comment by e-cloud** [comment]
@emoralesb05 `^` doesn't work for unstable releases

**Comment by emoralesb05** [comment]
Exactly my point, im saying that if he has `^` then the latest will be installed.. which he should remove.

**Comment by AnthonySaldana** [comment]
@jonathanmeguira In your package.json set angular/material to use beta-8 for now as beta-10 introduced breaking changes

"@angular/material": "2.0.0-beta.8"

Then you have to either do a fresh npm install or remove the angular/material package and then do npm install.

**Comment by jotatoledo** [comment]
**Pro tip**: fix the dependencies of your projects that have a beta suffix to a specific version (dont use ^ or ~). Or use a lock file (yarn or npm>=5). Beta is a synonym for **anarchy**  and **chaos** 💣  when new versions are released, as breaking changes will most probably be introduced.

**Comment by Gustav0ar** [comment]
Looking forward for this update, material beta 10 update fix some issues that I was having with their library, but unfortunately I can't use of covalent

**Comment by kyleledbetter** [comment]
btw track our progress in beta10 in this PR https://github.com/Teradata/covalent/pull/847

@Gustav0ar care to elaborate?

**Comment by Gustav0ar** [comment]
Nothing major, just a few bugs with material2 datepicker that was solved in beta.10. 
Thanks for the update.

**Comment by gozeon** [comment]
```bash 
npm install --save @angular/cdk@2.0.0-beta.8 @angular/material@2.0.0-beta.8
```

**Comment by emoralesb05** [comment]
This has just been merged, so anybody that wants to be adventurous can install the nightly build 😛
