### ISSUE TITLE
Json formatter parsing [[number]] to date?

### ISSUE THREAD

**Issue by madmandrew** [Teradata/covalent#852]
There seems to be an issue with the json formatter. if i have an array of an array of numbers it auto formats to date, and I don't see how to stop it? like [[1,2],[3,4],[5,6]] gets parsed to...

![2017-09-01 11_32_34-harbormasterui](https://user-images.githubusercontent.com/12468460/29981081-9fd35970-8f09-11e7-864f-ac1eba498513.png)

browser: chrome Version 60.0.3112.101
covalent version: 1.0.0-beta.3-2
angular version: 4.0.0

**Comment by jotatoledo** [comment]
Versions? Browser? Please use the issue template

**Comment by emoralesb05** [comment]
Can you create a plnkr with this issue please?

**Comment by emoralesb05** [comment]
Fix will be present in next release https://github.com/Teradata/covalent/pull/899
