### ISSUE TITLE
Landing Page 

### ISSUE THREAD

**Issue by jega4u** [Teradata/covalent#855]
#### Feature Request

Want a Landing page component (like Jquery template single page scrolling effects ) 

Sample :  
http://www.shegy.nazwa.pl/materialupmarket/mdlp2/index_light.html

**Comment by kyleledbetter** [comment]
So this isn't really a Covalent thing. There's plenty of Angular modules out there for scroll effects. Use those with a landing page layout (we have an example landing page here https://teradata.github.io/covalent/#/templates)

**Comment by emoralesb05** [comment]
Closing this since its outside the scope of our roadmap
