### ISSUE TITLE
Dynamic forms & Chips: Sticky dropdown menus

### ISSUE THREAD

**Issue by natejgardner** [Teradata/covalent#861]
All dropdown menus, autocomplete menus, and overlay components stick in Firefox and Chrome. When a user selects an option, the menu doesn't go away. When the user scrolls, the menu floats in place. There is no way to get the menu to disappear. Clicking to the side and hitting escape don't work.

**Comment by emoralesb05** [comment]
I cant seem to replicate this.. can you provide more information and maybe a plnkr?

**Comment by emoralesb05** [comment]
Closing this since there wasnt a way to replicate it nor more information provided
