### ISSUE TITLE
USE COVALENT WITH LATEST MATERIAL VERSION 

### ISSUE THREAD

**Issue by jhonToni** [Teradata/covalent#866]
How to use `COVALENT` with latest beta version of `material 2` ??

**Comment by joeldatabox** [comment]
Please, see this #856

**Comment by jymdman** [comment]
If you can't wait for next release, you can use nightly instead:

`npm install --save https://github.com/Teradata/covalent-nightly.git`

**Comment by emoralesb05** [comment]
This is a dup.. please check the existing issues before opening a new one. 😄
