### ISSUE TITLE
Data table rows can not have custom height after beta.7

### ISSUE THREAD

**Issue by quanterion** [Teradata/covalent#868]
Before beta.7 Data-Table row can be of any height. For example, if I set ng-template for a row

```
<ng-template tdDataTableTemplate="name" >
  <div [style.height.px]="200"></div>
</ng-template>
```

When all data table rows will have 200px height.

It is not he case after this PR https://github.com/Teradata/covalent/pull/859. It is no longer possible because height of td-data-table-cell-content-wrapper have been explicitly set to 48px in this file https://github.com/Teradata/covalent/blob/530d8a14db3a7abf67cf63548208d0f5ce485d30/src/platform/core/data-table/data-table-cell/data-table-cell.component.scss

How to allow custom height of data table rows now if I don't need virtual scroll?

**Comment by clarkebishop** [comment]
I recently ran into this issue. I've got a custom data table, but in some cases the content overflows one line. The fixed height causes the content to be compressed in an ugly way.

Please switch this to a min-height, or provide a good way to override the values set in ~@covalent/core/theming/all-theme.

**Comment by memetolsen** [comment]
@clarkebishop Do you mean something like this?

![before](https://user-images.githubusercontent.com/6040515/30806547-8dbf6b8e-a1f6-11e7-9fd0-d0d476b28609.png)

I've managed to "fix" this by overriding the css and applying [text-overflow](https://developer.mozilla.org/nl/docs/Web/CSS/text-overflow): ellipsis

![after](https://user-images.githubusercontent.com/6040515/30806614-d614bd6c-a1f6-11e7-8b34-885febfe85b5.png)

Although this fixes the ugly compression, I would like the row height to be dynamically determined so the whole text becomes visible, like in the older versions.

My suggestion would be to introduce a boolean property on **td-data-table** so one can choose to apply fixed height or not.

**Comment by clarkebishop** [comment]
For my use case, I'm displaying a file name, and have some long names. I like your ellipsis trick, but it won't work for me.

The boolean or some other method seems like the right answer.

**Comment by Kumfert** [comment]
My table rows have thumbnail images.  48px height restriction is really getting in the way.

<img width="763" alt="screen shot 2017-09-30 at 10 38 26 am" src="https://user-images.githubusercontent.com/2791381/31048114-9210afe4-a5cb-11e7-8b20-2fe9d19edde9.png">

**Comment by emoralesb05** [comment]
There is a PR opened to address this this https://github.com/Teradata/covalent/pull/898, but it still requires lots of testing
