### ISSUE TITLE
HttpInterceptorService Subscriber.complete() is not called

### ISSUE THREAD

**Issue by debben** [Teradata/covalent#87]
#### Bug Report

When using HttpInterceptorService in place of Http, the `complete` callback is not being fired for the returned observables.

##### Screenshots or link to CodePen/Plunker/JSfiddle
Example:

```
let http: HttpInterceptorService;

public getDataPromise() : Promise<any> {
    let promise = this.http.get('/some/url').toPromise();
    return promise.then((data) => {
       console.log('this function will never be called');
    },
    (error) => { 
      console.log('this will be called if there was an error');
    });
}
```
The promise will never have its resolve method called because `toPromise` returns a promise that only resolves once the observable is complete.

#### What is the expected behavior?
The `complete `callback should be called. Many methods call `subscribe `and provide a callback for `complete`.

#### Which version of Angular and Material, and which browser and OS does this issue affect?

All browsers/versions.

##### Other information
In lines 52-62 of [http-interceptor.service.ts](https://github.com/Teradata/covalent/blob/develop/src/platform/http/http-interceptor.service.ts#L52) you can see where the `next `and `error `methods are called for subscriber, but `complete` is never hooked up.

**Comment by emoralesb05** [comment]
Hey @debben,
Good catch, I totally forgot about `complete` callback. 

Will add this issue for `0.8.0` milestone.

**Comment by emoralesb05** [comment]
Fixed in https://github.com/Teradata/covalent/pull/88
