### ISSUE TITLE
Data Table cell alignment

### ISSUE THREAD

**Issue by jt-helsinki** [Teradata/covalent#871]
### Do you want to request a *feature* or report a *bug*?

Bug/Regression (?)

#### Feature Request

Require cell alignment in table. Was working.

#### Bug Report

Previously developer was able to specify the text-alignment for a cell. With the new `td-data-table-cell-content-wrapper` div this is no longer possible. 

#### What is the expected behavior?

Developers can add alignment to the table cells.

#### What is the motivation / use case for changing the behavior?

Need ability to modify layout of the contents contained within a data table.

#### Which version of Angular and Material, and which browser and OS does this issue affect?

Material 2.0.0-beta.10
Angular 4.3.6
Covalent 1.0.0-beta.7

Did this work in previous versions of Angular / Material?

Yes

**Comment by philgetz** [comment]
td-data-table-cell-content-wrapper was added to provide flex-box alignment. Implementing cellAlign input to both column and cell atomic components. Goal is to programmatically align center, right, left content inside the cell.
