### ISSUE TITLE
TDExpansionPanel not expanding properly after leaving the view with tabs

### ISSUE THREAD

**Issue by jbthomps** [Teradata/covalent#875]
### Do you want to request a *feature* or report a *bug*?
Bug

#### Bug Report
On the expansion panel, when you switch away from a tab that has an accordion, and switch back to it, if the expansion panel is closed, the expansion panel will change it's arrow to open, but not show the included data.  When you reclose the accordion, the underlying data flickers before it closes.  If you open the accordion again after doing this, it will act as normal.

This can be replicated on the basic demo page for accordions by going between code and demo.

##### Other information
Already did a quick test against basic ngIf, and it doesn't seem to be the interaction between the accordion and ngIf.

**Comment by aciccarello** [comment]
I believe this may be an angular material issue. Is it the same issue as #819?

**Comment by emoralesb05** [comment]
Yes, its the same issue as that one.. its an issue with `md-tabs` after @angular@4.2

**Comment by aciccarello** [comment]
I just checked this and the expansion panel docs still have issues.

![covalent issue 875 expansion panel](https://user-images.githubusercontent.com/11273838/34177868-686b613a-e4c2-11e7-8780-d697047de44f.gif)

**Comment by emoralesb05** [comment]
Yeah, we will go away from this pattern for `demo/code` in all our docs.. to avoid this kind of thing.
