### ISSUE TITLE
Data table cells are not scaling

### ISSUE THREAD

**Issue by Leonzen** [Teradata/covalent#876]
### Do you want to request a *feature* or report a *bug*?
Bug

#### Bug Report
In version 1.0.0-beta.6 the cells of the data table were scaling if the value was too large. With the new update, they are not scaling anymore.

##### Screenshots or link to CodePen/Plunker/JSfiddle
http://plnkr.co/edit/0nxFILC6fYpiAdyMB2b9?p=preview

#### What is the expected behavior?
If a value is too large, the cell should become larger.

#### What is the motivation / use case for changing the behavior?
For a good looking and structural table, a scaling cell is needed.

#### Which version of Angular and Material, and which browser and OS does this issue affect?

Angular: 4.3.6
Material: 2.0.0-beta.10
Covalent: 1.0.0-beta.7
OS: Windwos 7
Browser: Chrome 60

Did this work in previous versions of Angular / Material?
Yes with:
Material: 2.0.0-beta.8
Covalent: 1.0.0-beta.6

**Comment by quanterion** [comment]
I think it is the same as https://github.com/Teradata/covalent/issues/868

**Comment by emoralesb05** [comment]
Closing in favor of #868 since its a dup
