### ISSUE TITLE
Virtual scroll wrong calculation

### ISSUE THREAD

**Issue by olaf89** [Teradata/covalent#878]
#### Bug Report
Rows are not displayed after data is reloaded.

#### What is the expected behavior?
Rows are calculated properly

#### Which version of Angular and Material, and which browser and OS does this issue affect?
latest

##### Other information
first time page is loaded it works. When data is cleaned and different data is loaded, while calculating height queryList is not filled yet therefore rowHeight is 0.

![screen shot 2017-09-16 at 15 58 26](https://user-images.githubusercontent.com/11535118/30512834-42a13b3c-9af8-11e7-8c18-4407ac0d9921.png)

**Comment by emoralesb05** [comment]
huh, we will take a look into this, thanks for the report!
