### ISSUE TITLE
Management list layout has incorrect transitions (bug/change)

### ISSUE THREAD

**Issue by Enngage** [Teradata/covalent#879]
#### Bug Report

Hi guys,

I upgraded to latest version of angular/covalent/angular-material and started experiencing an issue which causes not very user friendly transitions when accessing components from different modules => if you have a component A and B in module and a component C and D in a separate module.

See screencast below.

I created a simple [repo](https://github.com/Enngage/AngularTestApp) where this issue can be easily reproduced.

##### Screenshots or link to CodePen/Plunker/JSfiddle

![module_transition](https://user-images.githubusercontent.com/7137351/30512982-7d222660-9afb-11e7-923d-96e1d744a968.gif)

#### What is the expected behavior?

The transitions between components across all modules should be the same

#### Which version of Angular and Material, and which browser and OS does this issue affect?

Did this work in previous versions of Angular / Material?

Yes, it has.

####

Any ideas how to make it better? :-) 

Thank you!

**Comment by kyleledbetter** [comment]
this animation is actually coming from Angular Material's sidenav

**Comment by jeremysmartt** [comment]
Question answered, no traction in a year, closing issue
