### ISSUE TITLE
Row is empty on row deselect without multiselect

### ISSUE THREAD

**Issue by knight37x** [Teradata/covalent#881]
### Do you want to request a *feature* or report a *bug*?
*bug*

#### Bug Report
When using a data table that is selectable and multiple, on row selection a ITdDataTableSelectEvent is fired. This event contains the row that has been toggled and a boolean value whether you have selected or deselected that row.
If your data table, however, only is selectable and not multiple, then on deselection the row field is blank. Of course it is easy to create a quick fix for it, but I think this is clearly a bug!

See the plunker below to recreate the problem:
click any row -> in console it will print the row you have just clicked on
deselect just selected row -> console will say *undefined*

##### Screenshots or link to CodePen/Plunker/JSfiddle
http://plnkr.co/edit/8YSyQPswBDq6X6Tnc35p?p=preview

#### What is the expected behavior?
I would expect for consistency reasons, that a deselect (just as it does in multiselect mode) provides the row that has been deselected, and in _selected_ field it should say false (as it currently already does).

#### What is the motivation / use case for changing the behavior?
I have constructed a component that wraps covalent data table and with this bug I have to differ between the two modes (multiselect mode and not), whereas I would like to use the same functionality twice.

**Comment by emoralesb05** [comment]
Will be fixed with https://github.com/Teradata/covalent/pull/896
