### ISSUE TITLE
[IE11] - Card Over Layout issue

### ISSUE THREAD

**Issue by aciccarello** [Teradata/covalent#882]
#### Bug Report

In IE11, the card-over layout becomes misaligned if the height of the card changes to be taller or smaller than the window. This is happening in my app during the page load. This causes the card to become minimally wide and the content trying to fit that tiny width.

This was difficult to reproduce so there may be other causes for this bug. The below plunkers can be used to demonstrate the issue.

[Basic card](http://plnkr.co/edit/7hQOsJv0xetEIyV91Lo0?p=preview)
[Card which changes height](http://plnkr.co/edit/t6dcHVQXaz6oJgKkyMM5?p=preview)

##### Screenshots or link to CodePen/Plunker/JSfiddle
![ie card-over bug](https://user-images.githubusercontent.com/11273838/30619037-7069d420-9d5a-11e7-8b25-b76853ce6257.gif)

#### What is the expected behavior?
No matter what the height of the window, the card content should have either 70% or 100% width.

#### Which version of Angular and Material, and which browser and OS does this issue affect?
```javascript
let angularVer = '@4.3.6';
let cdkVer = '@2.0.0-beta.10';
let materialVer = '@2.0.0-beta.10';
let covalentVer = '@1.0.0-beta.7';
let rxjsVer = '@5.4.2'
```

##### Other information

I was able to workaround the issue by wrapping the `<td-layout-card-over>` element in a div. I would prefer to not have to do this in all card-over layouts.

**Comment by aciccarello** [comment]
I'm guessing that is because the `<layout-nav>` template wraps its content in a `layout="column"`.

https://github.com/Teradata/covalent/blob/ccc8ccbc99c947eee4c6babb3e7c60532fffebf5/src/platform/core/layout/layout-nav/layout-nav.component.html#L15-L17

Honestly I still don't know exactly what's going on here but I'm guessing it is related to one of the issues in the [IE docs](https://github.com/Teradata/covalent/blob/develop/docs/IE11.md#ie11-flexbox-workarounds--best-practices) since wrapping the child element in a `div` fixes it.

```html

  <td-layout-nav>
    <my-toolbar td-toolbar-content></my-toolbar>
    <div> <!-- Wrapping for IE -->
      <td-layout-card-over>
        <md-card-content>
          <ng-content></ng-content>
        </md-card-content>
        <div td-after-card>
          <my-footer class="pad-sm"></my-footer>
        </div>
      </td-layout-card-over>
    </div>
  </td-layout-nav>
```

**Comment by kyleledbetter** [comment]
`layout="column"` is an important wrapper for layouts since it's necessary if you want to do any type of height flexing in the content

**Comment by aciccarello** [comment]
Could someone who needs flexing explicitly put their own div with `layout="column"` inside of `<td-layout-nav>`? The main issue I faced was that the flex layout on the nav layout was a hidden implementation detail.

If that change seems unnecessary for an IE bug, feel free to close.

**Comment by kyleledbetter** [comment]
It's debatable...

If we remove this from layout-nav:
```
  <div flex layout="column" class="content md-content" cdkScrollable>
    <ng-content></ng-content>
  </div>
```
and just leave `ng-content` we'd be requiring the devs to use `<div flex layout="column" class="content md-content" cdkScrollable>` when they want to flex vertically with a scroll overflow, which isn't a big deal but kinda starts defeating the point of layouts which is masking complexity...

Let's keep the issue open to track it and see if there's any better solution for IE11 card-over

**Comment by aciccarello** [comment]
Oh, I had assumed that `class="content md-content" cdkScrollable` could stay on the div. If those would have to be moved then I'd prefer working around the IE quirks. I think a note in `IE.md` would be sufficient.
