### ISSUE TITLE
Dynamic Forms component can't resolve provider when used in AOT build

### ISSUE THREAD

**Issue by Legited** [Teradata/covalent#884]
### Do you want to request a *feature* or report a *bug*?
*bug*

#### Bug Report
Regular build with compiler included works as expected. Problem is with the AOT build.
Build process does not throw any errors, but page with `td-dynamic-forms` can't render and throws the following error:
![screen shot 2017-09-22 at 11 22 14 am](https://user-images.githubusercontent.com/13325924/30751852-9de69d7c-9f88-11e7-9ae8-aef816a6872f.png)

Am I missing a module or an extra step for AOT?

#### Which version of Angular and Material, and which browser and OS does this issue affect?
Tested in Chrome 60 and Firefox 55.

angular/common: 4.4.1,
angular/material: "2.0.0-beta.10",
angular/cdk: "2.0.0-beta.10",

**Comment by Toxicable** [comment]
upgrade to 4.4.3

**Comment by Legited** [comment]
@Toxicable Thanks! That helped
