### ISSUE TITLE
OverlayState was not found in @angular/cdk/overlay

### ISSUE THREAD

**Issue by Samushel** [Teradata/covalent#885]
When using Angular Material beta 11 a project with Covalent Beta 7 compiles with a warning:

`WARNING in ./node_modules/@covalent/core/loading/services/loading.factory.js
127:24-36 "export 'OverlayState' was not found in '@angular/cdk/overlay'`

This is due to a breaking change on Angular Material beta 11: https://github.com/angular/material2/blob/master/CHANGELOG.md#breaking-changes

> overlay: OverlayState has been renamed to OverlayConfig

**Comment by jotatoledo** [comment]
Covalent depends on beta10 of material, dont update to 11 yet

**Comment by steve-todorov** [comment]
@jotatoledo I'm also receiving this exception and I'm using `angular 4.4.3` + `material2-2.0.0-beta.11`

```
WARNING in ./node_modules/@angular/material/@angular/material.es5.js
15765:42-54 "export 'OverlayState' was not found in '@angular/cdk/overlay'
```
Browsing through the `node_modules/@angular/material/@angular/material.es5.js` code I can see that it is being imported 

```
import { ... OverlayState, ... } from '@angular/cdk/overlay';
```

But there is no class called `OverlayState` in `@angular/cdk/overlay`? Furthermore, it has been renamed as the change log states. Am I missing something?

**Comment by steve-todorov** [comment]
Actually never mind my last comment - the problem was something totally different :)

**Comment by pabloxn** [comment]
what was the solution - I have the same problem

**Comment by steve-todorov** [comment]
@pabloxn if you are only using `angular` and `material` without `Covalent` - make sure that your dependencies in `package.json` are up to-date:

```
    "@angular/cdk": "^2.0.0-beta.11",
    "@angular/material": "^2.0.0-beta.11",
```

In my case I forgot to update the `@angular/material` package which resolved in the exception above. 

If you are using `Covalent` then @jotatoledo already stated that `Covalent`'s dependencies require beta10. :)

**Comment by emoralesb05** [comment]
Yup, we will support beta.11 soon 😄 https://github.com/Teradata/covalent/pull/890

**Comment by emoralesb05** [comment]
https://github.com/Teradata/covalent/pull/890 has been merged, you can start testing if you install the `nightly-build`, and we are gonna release as soon as we do a last set of tests

**Comment by gozeon** [comment]
https://github.com/angular/material2/pull/6972
