### ISSUE TITLE
TdDialogService  The closeAll function sometimes closes the modeal and sometimes does not

### ISSUE THREAD

**Issue by charedim** [Teradata/covalent#889]
Hi, 
I use the TdDialogService 
the closeAll() function  sometimes closes it and sometimes does not 

```
closePurchase(): void {
  this._dialogService.closeAll();
  }

  openPurchase(): void {
    this._dialogService.open(PurchaseComponent, {disableClose: true, height: '100%', width: '30%', position: {right: '0', top: '0'}} );
 }
```
what could be the problem?

**Comment by aciccarello** [comment]
Do you have any lazy loaded modules? I wonder if the dialog service is getting provided twice. Then you would have two different instances of the dialog service which wouldn't know about each other.

**Comment by emoralesb05** [comment]
Closing this since there wasnt any information provided
