### ISSUE TITLE
Starter app for webpack-rc7

### ISSUE THREAD

**Issue by RSamal** [Teradata/covalent#89]
Hi,

Is there any quick starter app for webpack-rc7 ?

Thanks

**Comment by emoralesb05** [comment]
Currently upgrading our `covalent-quickstart` to use `webpack`. So expect an update soon using `angular-cli@webpack`.

**Comment by RSamal** [comment]
Thank you so much...I just tried to checkout the branch and try to run it but it got failed . I hope once you complete I would like to try it 👍

**Comment by emoralesb05** [comment]
Yeah, was working on it merging with our `crud` PR haha 
I think we have it good to go, just doing some last testing on it and ill merge it.

**Comment by emoralesb05** [comment]
`Quickstart` is updated https://github.com/Teradata/covalent-quickstart/commit/f945890bbda04322087661b13b9fa2b1fa12893d

**Comment by RSamal** [comment]
sudo npm i gives the below error , is that some special file we need to include?
npm ERR! enoent ENOENT: no such file or directory, chmod '/Users/Ramakant/project/angular/covalent-quickstart/node_modules/@covalent/data/node/bin/covalent-data.prg

**Comment by emoralesb05** [comment]
hmm.. its our new mock data `@covalent/data` module, is it not getting installed in your `node_modules` dir?

**Comment by RSamal** [comment]
looks like its not as it gives the same error...I tried to create it through touch too but no luck

**Comment by emoralesb05** [comment]
No need to create it, its supposed to be installed by the `@covalent/data` module, but the module alone is not really needed. 

If you have issues, you can just remove the `"@covalent/data":"0.1.0",` line from `package.json` before doing `npm i` and we will do additional testing on it.
