### ISSUE TITLE
Upstream Angular2 Components

### ISSUE THREAD

**Issue by kyleledbetter** [Teradata/covalent#9]
- [x] [Select](https://github.com/angular/material2/issues/118)
- [x] [Autocomplete](https://github.com/angular/material2/issues/117)
- [x] [Dialog](https://github.com/angular/material2/pull/761) PR
- [x] [Tooltip](https://github.com/angular/material2/pull/799) PR
- [x] [Toast](https://github.com/angular/material2/issues/115)
- [x] [Slider](https://github.com/angular/material2/pull/779) PR
- [x] [Ripple](https://github.com/angular/material2/pull/681) PR

**Comment by emoralesb05** [comment]
Closing this since `autocomplete` will be part of next release and with that its basically all the `major` component we need from material.
