### ISSUE TITLE
Bug: Demo for data-table is not working properly in IE11

### ISSUE THREAD

**Issue by emoralesb05** [Teradata/covalent#903]
#### Bug Report

Using Selection on Rows in Table creates strange concatenated Title in Message area:

![image](https://user-images.githubusercontent.com/5846742/31104425-b9ba7a80-a791-11e7-9164-ca963085d877.png)

Tooltips on column headers in IE11 don't work:

![image](https://user-images.githubusercontent.com/5846742/31104438-cb650304-a791-11e7-8895-0006b5d47f3b.png)

Clear button on Search doesn't work in IE11:

![image](https://user-images.githubusercontent.com/5846742/31104443-d32d9290-a791-11e7-8c57-42f1544bc050.png)

**Comment by jeremysmartt** [comment]
These items no longer appear to be an issue
