### ISSUE TITLE
Bug: extra padding at the end in the virtual scroll component in IE11

### ISSUE THREAD

**Issue by emoralesb05** [Teradata/covalent#904]
#### Bug Report

Virtual scroll pseudo height is not working properly in IE11

##### Screenshots or link to CodePen/Plunker/JSfiddle

![image](https://user-images.githubusercontent.com/5846742/31104467-f89dc540-a791-11e7-9327-e1ef7291c5ae.png)

**Comment by owilliams320** [comment]
this component will be deprecated in future versions please use https://material.angular.io/cdk/scrolling/overview
