### ISSUE TITLE
td-text-editor really slow

### ISSUE THREAD

**Issue by jmls** [Teradata/covalent#909]
I am trying to implement td-text-editor in a non-material (semantic ui) project. I have just installed the td-text-editor  component and imported it into my application module

As you can see, it all seems to be working
![image](https://user-images.githubusercontent.com/929523/31141575-b0b5b286-a86f-11e7-851c-8437305792ad.png)

`<td-text-editor name="description"  [value]="description" [options]="{status:false, spellChecker:false, toolbar: ['bold', 'italic', 'heading', 'heading-1','heading-2','heading-3', '|', 'code','quote', '|', 'unordered-list','ordered-list','|','preview']}"></td-text-editor>'
`

The problem is that the editor is *really* slow. I mean _really_, _really_ slow .. In order of >6s to add a line .. 

When I check top, chrome is hitting >100% cpu while the text is rendering. As soon as the text appears, cpu drops down to 5%

Has anyone else seen this ?

Using angular 4.3.5, semantic-ui and chrome 60.0.3112.101

**Comment by emoralesb05** [comment]
This type of issues would belong to https://github.com/Teradata/covalent-text-editor/, can you please open this issue there?

**Comment by jmls** [comment]
sorry, I honestly thought I had . my bad.
