### ISSUE TITLE
material has no exported member 'ComponentType'.

### ISSUE THREAD

**Issue by ja5onkendall** [Teradata/covalent#913]
It looks like Material2 may have removed this ComponentType component.
A fresh install results in a build error.

ERROR in.... `node_modules/@covalent/core/dialogs/services/dialog.service.d.ts`

`node_modules/@angular/material/material`  ...has no exported member 'ComponentType'.

**Comment by ja5onkendall** [comment]
![bug](https://user-images.githubusercontent.com/16178101/31260750-ab48e532-aa15-11e7-90e7-a46df65380a5.jpg)

**Comment by ja5onkendall** [comment]
![bug-location](https://user-images.githubusercontent.com/16178101/31260785-f52b450a-aa15-11e7-8f0a-9c7a1e93665c.jpg)

**Comment by lincze** [comment]
seemingly it is imported from @angular/cdk/portal now (it was a grep -r search, and some replacements)

```
diff --git a/src/app/components/components/dialogs/dialogs.component.ts b/src/app/components/components/dialogs/dialogs.component.ts
index 62a3eae..92af93b 100644
--- a/src/app/components/components/dialogs/dialogs.component.ts
+++ b/src/app/components/components/dialogs/dialogs.component.ts
@@ -3,6 +3,7 @@ import { Component, HostBinding } from '@angular/core';
 import { slideInDownAnimation } from '../../../app.animations';
 
 import { TdDialogService } from '../../../../platform/core';
+import { ComponentType } from '@angular/cdk/portal';
 
 @Component({
   selector: 'dialogs-demo',
diff --git a/src/platform/core/dialogs/services/dialog.service.ts b/src/platform/core/dialogs/services/dialog.service.ts
index 7fd9715..97a25ff 100644
--- a/src/platform/core/dialogs/services/dialog.service.ts
+++ b/src/platform/core/dialogs/services/dialog.service.ts
@@ -1,5 +1,6 @@
 import { Injectable, ViewContainerRef, Provider, SkipSelf, Optional } from '@angular/core';
-import { MatDialog, MatDialogRef, MatDialogConfig, ComponentType } from '@angular/material';
+import { MatDialog, MatDialogRef, MatDialogConfig } from '@angular/material';
+import { ComponentType } from '@angular/cdk/portal';
 
 import { TdAlertDialogComponent } from '../alert-dialog/alert-dialog.component';
 import { TdConfirmDialogComponent } from '../confirm-dialog/confirm-dialog.component';
```

**Comment by megetron** [comment]
I get this too:
/Users/guy/proj/client/node_modules/@covalent/core/dialogs/services/dialog.service.d.ts(2,52): error TS2305: Module '"/Users/guy/proj/casual_shipping/client/node_modules/@angular/material/material"' has no exported member 'ComponentType'.

**Comment by emoralesb05** [comment]
Im assuming you are all using `beta.12` now in material which we havent tested yet, please downgrade to `beta.11` for now while we add support for `beta.12` since they introduced more breaking changes.

**Comment by megetron** [comment]
after downgrade error was gone, thanks.

**Comment by lincze** [comment]
you are right it became material beta.12.

maybe, it woulld be better to use fix version number in package.json, not the at least version. (i've just run "npm run reinstall", and voilá, material beta.12 was installed, under the hood, not beta.11. if i ran it some hours earlier it would be beta.11 now)

**Comment by emoralesb05** [comment]
Thats why we also use yarn, if we wanna develop normally we use `yarn install` but keep `npm` open to test the latest dependencies.

**Comment by emoralesb05** [comment]
Patch https://github.com/Teradata/covalent/releases/tag/v1.0.0-beta.8-1 has been released with `material` beta.12 support
