### ISSUE TITLE
1.0.0-beta.8 md to mat problem

### ISSUE THREAD

**Issue by AliceCasari** [Teradata/covalent#915]
I have to upgrade to 1.0.0-beta.8 , but after the update some of the md prefix are present so I got an error. 
Please fix this. 
Specific case: md-sidenav-container, generated by td-layout tag.
Thank you for your efforts.

**Comment by emoralesb05** [comment]
Please change the angular material changelog, they removed all `md` prefixes and you should use `mat`now

**Comment by AliceCasari** [comment]
Ok maybe i didn't explain myself. I used td-layout that is a covalent's component and is exactly td-layout that generate md-sidenav-container that goes against material and generate the error that make my app crash. So i am asking if you are considering a refactoring of your components.
Thank you very much.

**Comment by emoralesb05** [comment]
We already updated this in our `beta.8` release and its all in our changelog

**Comment by AliceCasari** [comment]
Ok is as you said. I am really sorry for bothering but during the installation something went wrong, I had package on beta 8 but all the files were effectively an older version. I cleared and reinstalled and now is ok.
Thank you very much for your help and time.

**Comment by emoralesb05** [comment]
No problem, glad it was just an installation issue 😄
