### ISSUE TITLE
Pb with design

### ISSUE THREAD

**Issue by ranouf** [Teradata/covalent#917]
![image](https://user-images.githubusercontent.com/1764519/31292477-9775cdd6-aaa1-11e7-972f-ecd780219124.png)
![image](https://user-images.githubusercontent.com/1764519/31292656-47eaaa88-aaa2-11e7-84e3-a04976f0f408.png)

Do you know why i have this problem?

This is my CSS:
```
@import '~@angular/material/theming';
@import '~@covalent/core/theming/all-theme';

@include mat-core();

$primary: mat-palette($mat-orange, 800);
$accent:  mat-palette($mat-light-blue, 600, A100, A400);

$warn:    mat-palette($mat-red, 600);

$theme: mat-light-theme($primary, $accent, $warn);

@include angular-material-theme($theme);
@include covalent-theme($theme);
```

this is my app.html:
```
<td-layout>
  <td-navigation-drawer flex sidenavTitle="Covalent" logo="assets:teradata" name="Firstname Lastname" email="firstname.lastname@company.com">
    <mat-nav-list>
      <a mat-list-item><mat-icon>home</mat-icon>Home</a>
    </mat-nav-list>
    <div td-navigation-drawer-menu>
      <mat-nav-list>
        <a mat-list-item><mat-icon>account_box</mat-icon>Profile</a>
      </mat-nav-list>
    </div>
  </td-navigation-drawer>
  <td-layout-nav-list logo="assets:teradata" toolbarTitle="Covalent" navigationRoute="/" opened="true" mode="side">
    <button mat-icon-button td-menu-button tdLayoutToggle>
      <mat-icon>menu</mat-icon>
    </button>
    <div td-sidenav-content>
      Sidenav content here
    </div>
    <div td-toolbar-content>
      <button mat-button tdLayoutNavListToggle>
        Toggle
      </button>
    </div>
    <router-outlet></router-outlet>
  </td-layout-nav-list>
</td-layout>

```

I can give you a github if you want.

**Comment by ranouf** [comment]
I added this modules:

- MatIconModule,
- MatButtonModule,
- CovalentCommonModule,
- CovalentLayoutModule,

It helps, but I still not have a perfect UI:
![image](https://user-images.githubusercontent.com/1764519/31294131-bdfa8b94-aaa7-11e7-9192-3f6c11a0a2cf.png)

When I inspect the HTML, I can see: 
<mat-toolbar _ngcontent-c2="" class="mat-toolbar" role="toolbar"><div class="mat-toolbar-layout">

So, I added: 
MatToolbarModule

But I still have a mistake with the display

**Comment by emoralesb05** [comment]
Did you add the `platform.scss`? Right now its a dependency to make every covalent module render properly.. we will remove this dependency in following RC's

**Comment by ranouf** [comment]
I added in .angular-cli.json

```
"styles": [
  "../node_modules/@covalent/core/common/platform.scss"
],
```

How can I confirm that the platform.scss is include in my build?

**Comment by ranouf** [comment]
I added ALL modules from covalent and Angular Material:

- MatAutocompleteModule,
- MatButtonModule,
- MatButtonToggleModule,
- MatCardModule,
- MatCheckboxModule,
- MatChipsModule,
- MatCommonModule,  
- MatDatepickerModule,
- MatDialogModule,
- MatExpansionModule,
- MatFormFieldModule,
- MatGridListModule,
- MatIconModule,
- MatInputModule,
- MatLineModule,
- MatListModule,
- MatMenuModule,
- MatNativeDateModule,
- MatOptionModule,
- MatPaginatorModule,
- MatProgressBarModule,
- MatProgressSpinnerModule,
- MatPseudoCheckboxModule,
- MatRadioModule,
- MatRippleModule,
- MatSelectModule,
- MatSidenavModule,
- MatSliderModule,
- MatSlideToggleModule,
- MatSnackBarModule,
- MatSortModule,
- MatStepperModule,
- MatTableModule,
- MatTabsModule,
- MatToolbarModule,
- MatTooltipModule,  

     

+

- CovalentChipsModule,
- CovalentCommonModule,
- CovalentDataTableModule,
- CovalentDialogsModule,
- CovalentExpansionPanelModule,
- CovalentFileModule,
- CovalentJsonFormatterModule,
- CovalentLayoutModule,
- CovalentLoadingModule,
- CovalentMediaModule,
- CovalentMenuModule,
- CovalentMessageModule,
- CovalentNotificationsModule,
- CovalentPagingModule,
- CovalentSearchModule,
- CovalentStepsModule,
- CovalentVirtualScrollModule,

the problem is still there, so maybe the css is the way to look for :)

**Comment by ranouf** [comment]
So, I pasted all the css from platform.css to app.css

I have an error:
ERROR in ./ClientApp/app/app.component.css Module not found: Error: Can't resolve './styles/font/MaterialIcons-Regular.eot' in 'C:\Users\SideKick\Documents\Visual Studio 2017\Projects\tests\Test1\Test1.Web\ClientApp\app' @ ./ClientApp/app/app.component.css 6:141-191 @ ./ClientApp/app/app.component.ts @ ./ClientApp/app/app.module.ts @ ./ClientApp/main.ts @ multi webpack-hot-middleware/client?path=__webpack_hmr&dynamicPublicPath=true ./ClientApp/main.ts

As you can, I tried to put my style everywhere, but it still missing :
![image](https://user-images.githubusercontent.com/1764519/31299373-1b3f3b7e-aabc-11e7-8ecf-59f0ffd0cc8b.png)

I continue to work on it, other people could have the same pb :)

**Comment by aciccarello** [comment]
It's a little bit outdated, but have you tried looking at https://github.com/Teradata/covalent-quickstart for an example of how to load styles and setup the sidebar?

**Comment by ranouf** [comment]
Hi @aciccarello ,

I already take a look on it, I used it in the past.

So I still have the UI pb with the sidebar:
![image](https://user-images.githubusercontent.com/1764519/31299987-3d0e1c04-aabf-11e7-88c4-d18160d1b66b.png)

In my app.scss I added :
```
$mat-font-url: '../../node_modules/@covalent/core/common/styles/font/';
@import "../../node_modules/@covalent/core/common/styles/font/font";
@import "../../node_modules/@covalent/core/common/styles/variables";
@import "../../node_modules/@covalent/core/common/styles/button";
@import "../../node_modules/@covalent/core/common/styles/card";
@import "../../node_modules/@covalent/core/common/styles/card-colored";
@import "../../node_modules/@covalent/core/common/styles/chips";
@import "../../node_modules/@covalent/core/common/styles/content";
@import "../../node_modules/@covalent/core/common/styles/divider";
@import "../../node_modules/@covalent/core/common/styles/icons";
@import "../../node_modules/@covalent/core/common/styles/input";
@import "../../node_modules/@covalent/core/common/styles/mixins";
@import "../../node_modules/@covalent/core/common/styles/navigation-drawer";
@import "../../node_modules/@covalent/core/common/styles/theme-functions";
@import "../../node_modules/@covalent/core/common/styles/palette";
@import "../../node_modules/@covalent/core/common/styles/palette-dark";
@import "../../node_modules/@covalent/core/common/styles/colors";
@import "../../node_modules/@covalent/core/common/styles/colors-dark";
@import "../../node_modules/@covalent/core/common/styles/layout";
@import "../../node_modules/@covalent/core/common/styles/list";
@import "../../node_modules/@covalent/core/common/styles/structure";
@import "../../node_modules/@covalent/core/common/styles/shadows";
@import "../../node_modules/@covalent/core/common/styles/sidenav";
@import "../../node_modules/@covalent/core/common/styles/toolbar";
@import "../../node_modules/@covalent/core/common/styles/typography";
@import "../../node_modules/@covalent/core/common/styles/whiteframe";
@import "../../node_modules/@covalent/core/common/styles/utilities/utilities";

$app-content-lg: 940px;
$app-content-md: 580px;
$app-content-sm: 360px;

```

With that I have no error, so I guess the css is loaded correctly. I have all the Angular Material and Covalent modules loaded ...

I have no idea of to fix it ...

Here is my branch I created where you can see the bug:
https://github.com/ranouf/AspNetCore2Angular4/tree/ImproveTheUI

Is it a bug with the new version? Did i miss something?

**Comment by aciccarello** [comment]
@ranouf Thanks for sharing the repo. I've got a few questions. If you want you can post in the [gitter channel](https://gitter.im/Teradata/covalent) for more of a back and forth conversation.

**First question:** How are you building the code? You have `@angular/cli` in the dev dependencies and a `.angular-cli.json` file but your `npm start` command runs webpack. So are you using webpack directly or angular-cli?

**Comment by ranouf** [comment]
Hi @aciccarello ,

I m on the chat.

I used this tutorial to create my app:
https://alexklingenbeck.de/articles/17-05-angular-asp-net-core.html

I have no webpack command to execute to redo my vendor, it s completely automatic. I executed a classic angular-cli create project command, then I did `ng eject` so now ng build doesnt work anymore. I hope it will answer your question.

I stay connected on the chat, make me a sign when you are there.

**Comment by ranouf** [comment]
I updated my project using this tuto:
https://www.npmjs.com/package/angular-material-prefix-updater

Currently, I added 

First I just use this command:
`mat-switcher -p ./tsconfig.json `

But I still have problem.

So I used this one:
`mat-switcher -p ./tsconfig.json --extra-css .\node_modules\@covalent\core\common\platform.css`

But the pb is still there.

I continue to investigate, any help will be appreciate

**Comment by ranouf** [comment]
Thanks to @aciccarello who found the solution, in my styles.scss, i need to `@import '~@covalent/core/common/platform.css';`

So from what we conclude, after a `ng eject`, the angular-cli is not used anymore explaining why my platform.css was not correctly imported and my display bugs.
