### ISSUE TITLE
Error on build Teradata Beta8 with Material Beta12

### ISSUE THREAD

**Issue by diegoviscovig** [Teradata/covalent#918]
ERROR in node_modules/@covalent/core/dialogs/services/dialog.service.d.ts (2,52): Module '"/node_modules/@angular/material/material"' has no exported member 'ComponentType'.]
This error appear when I build my application with Material12 and Covalent Beta8

**Comment by emoralesb05** [comment]
We are aware of this, please check the latest PR's and issues before opening a new one 😛 since this has already been fixed and its in the midst of a patch release
