### ISSUE TITLE
Push/pad/pull utility baselines should be based on 4px instead of 5px

### ISSUE THREAD

**Issue by aciccarello** [Teradata/covalent#919]
#### Bug Report

Currently the [utility styles](https://teradata.github.io/covalent/#/style-guide/utility-styles), such as `.pad-sm`, `.push-lg`, and `.pull-right` are implemented based on a 5px baseline.

#### What is the expected behavior?
Utility styles should be implemented in multiples of 4px.

#### What is the motivation / use case for changing the behavior?
The [material design spec](https://material.io/guidelines/layout/metrics-keylines.html#metrics-keylines-baseline-grids) indicates that

> All components align to an 8dp square baseline grid for mobile, tablet, and desktop. Iconography in toolbars align to a 4dp square baseline grid.

The 5px baseline makes the utility styles inaccurate for adjustments that conform to the material spec.

**Comment by emoralesb05** [comment]
Thanks for the heads up dude, care to open a PR? 😄

**Comment by aciccarello** [comment]
Sure! What do you think of the below changes. Things end up a bit smaller because 10px increments are cut to 8px. To make up some of the difference, `lg -> xl` jumps 16px. In the material spec 48px and 56px are used more often than 40px. I'd prefer for it to be consistent though I'm not sure what the best solution is.

- None `0 -> 0`
- xs `5px -> 4px`
- sm `10px -> 8px`
- (no size) `20px -> 16px`
- md `30px -> 24px`
- lg `40px -> 32px`
- xl `50px -> 48px`
- xxl `60px -> 56px`

As a reference the material design spec uses the following values often for margins/padding: 8, 16, 24, 56

As a reminder to myself the utility style docs page should also include the sizes so devs know what style they are applying.

**Comment by kyleledbetter** [comment]
Looks like a solid approach thx for jumping on this Anthony

**Comment by aciccarello** [comment]
Great, hopefully I can put something together before I leave on vacation at the end of the week. Currently the styles are written out by hand. If I have time, I might try doing some scss to build out the styles with less repetition.

**Comment by aciccarello** [comment]
What are the `bottom-button` styles for? I don't see them used anywhere in this repo.

https://github.com/Teradata/covalent/blob/af6fe59a61720cdd1a3ed55a3980b9b5856f14fe/src/platform/core/common/styles/utilities/_push.scss#L83-L85

**Comment by kyleledbetter** [comment]
ahhh i think i added that long ago for padding on the page to allow for a FAB in the bottom right, but we ended up using fab-pad or something instead

**Comment by emoralesb05** [comment]
Right, we can remove that class since its not being used
