### ISSUE TITLE
Using agm maps inside td-expansion-panel doesn't work

### ISSUE THREAD

**Issue by Gnorro** [Teradata/covalent#921]
### Do you want to request a *feature* or report a *bug*?
Bug

#### Bug Report
Using agm maps inside td-expansion-panel doesn't work
Use this code:
```
<td-expansion-panel-group>
    <td-expansion-panel>
      <agm-map style="height: 400px" [latitude]="45.4612" [longitude]="9.1878" [zoom]="12"></agm-map>
    </td-expansion-panel>
```
</td-expansion-panel-group>
Then click on panel to open map

#### What is the expected behavior?
Map opens

#### Which version of Angular and Material, and which browser and OS does this issue affect?
4
^2.0.0-beta.8

Did this work in previous versions of Angular / Material?
don't know

##### Other information
Agm is:
https://angular-maps.com/
Map is always displayed with grey background

**Comment by emoralesb05** [comment]
Can you create a plnkr to replicate this issue? It sounds to be it might be rendered but with `0px` height.

**Comment by Gnorro** [comment]
I would like, but I can't find modules to add to plnkr
