### ISSUE TITLE
change request .mat-drawer-container's status-bar to background in _layout-theme.scss

### ISSUE THREAD

**Issue by jatkeshave** [Teradata/covalent#924]
please change 

```
.mat-drawer-container {
    background-color: mat-color($background, status-bar);
}
```

to

```
.mat-drawer-container {
    background-color: mat-color($background, background);
}
```
because in dark theme status-bar returns black colour and it make card and other shadow effects useless

**Comment by kyleledbetter** [comment]
So we do this to have proper contrast between the background and toolbars/sidenavs, etc, to convey the proper layering in the Material Design principles. 

For instance, in a light theme:
Our theme:
![image](https://user-images.githubusercontent.com/867883/31833168-a0113de4-b57e-11e7-9fa7-cc6cce3b38e0.png)
VS
Angular Material's theme:
![image](https://user-images.githubusercontent.com/867883/31833183-aca17204-b57e-11e7-8fec-361648b914dd.png)

And in a dark theme:
Our theme:
![image](https://user-images.githubusercontent.com/867883/31833210-c26cd04c-b57e-11e7-87f8-99cf9b200c7c.png)

VS
Angular Material's theme:
![image](https://user-images.githubusercontent.com/867883/31833227-ccf4bcfa-b57e-11e7-9fb1-58f7537f354a.png)


In both of those examples, the depth is backwards with the default Angular Material theme. The background should be darker and appear deeper as it is in our theme.

For a Google comparison, the new dark YouTube does the same as Covalent:
![image](https://user-images.githubusercontent.com/867883/31833290-ede70c6a-b57e-11e7-98ec-65db64f00f16.png)
