### ISSUE TITLE
UI does not refresh automatically

### ISSUE THREAD

**Issue by MROALI** [Teradata/covalent#926]
Hello, 

My componnets are not refreshing. I need to click on the component for exemple header of the datatable in order to view table content (refresh), or click on the input text in order to refresh content.

I am using the latest version 8-1 with angular4 and material2.beta12 : 

below is my code : 
 ngOnInit() {
    this._titleService.setTitle( 'Users List' );
    this.accountApi.find(this.lbFilter).subscribe(users => {
            this.data = users;
            this.filteredData = this.data;
            this.filteredTotal = this.data.length;
            this.filter();
    });
  }

filter(): void {
  let newData: any[] = this.data;
  let excludedColumns: string[] = this.columns
  .filter((column: ITdDataTableColumn) => {
    return ((column.filter === undefined && column.hidden === true) ||
            (column.filter !== undefined && column.filter === false));
  }).map((column: ITdDataTableColumn) => {
    return column.name;
  });
  newData = this._dataTableService.filterData(newData, this.searchTerm, true, excludedColumns);
  this.filteredTotal = newData.length;
  newData = this._dataTableService.sortData(newData, this.sortBy, this.sortOrder);
  newData = this._dataTableService.pageData(newData, this.fromRow, this.currentPage * this.pageSize);
  this.filteredData = newData;
}

thankyou in advance for your help

**Comment by MROALI** [comment]
I found a solution but don't know if it the better one :+1:

I am using ChangeDetectorRef and calling  the .detectChanges(); method within the ngOnInit after loading data..

Do you think that what i did is a good solution ?

Thank you in advance

**Comment by emoralesb05** [comment]
This is probably a change detection issue from the implementation side since you had to call `markForCheck`. Closing this since there was a solution
