### ISSUE TITLE
feature(build): move to a single package

### ISSUE THREAD

**Issue by quanterion** [Teradata/covalent#93]
Are you considering publish covalent as a single package as has been done by Angular Material team here https://github.com/angular/material2/pull/1286?

**Comment by emoralesb05** [comment]
We are thinking about it since we want to follow the same standards as material2. We are just trying to tackle other priorities first before deciding to do that.

**Comment by emoralesb05** [comment]
We decided to bundle everything that makes sense under core.

So the only modules that would be stand alone would be:

highlight and markdown since they use 3rd party js libs,
http since the focus of it is different.
core (with everything else on it)

**Comment by emoralesb05** [comment]
Done with https://github.com/Teradata/covalent/pull/201
