### ISSUE TITLE
Relative font url issue

### ISSUE THREAD

**Issue by CalebJaegerSlalom** [Teradata/covalent#931]
### Do you want to request a *feature* or report a *bug*?
BUG

#### Bug Report
Fonts should not use relative location. This breaks when using HTML 5 routing.
The font url should use a default so that it can be provided. 

#### What is the expected behavior?
When the page refreshes at any route the font should load.

#### What is the motivation / use case for changing the behavior?
Enable HTML 5 routing.

#### Which version of Angular and Material, and which browser and OS does this issue affect?
ALL

#### Did this work in previous versions of Angular / Material?

No.

#### Other information
In platform.scss the line:

`$md-font-url: 'styles/font/';`

should be changed to:

`$md-font-url: '/styles/font/' !default;`

**Comment by aciccarello** [comment]
As a workaround the css import can be used. +1 to using `!default` so it can be modified.

**Comment by CalebJaegerSlalom** [comment]
The css has the same issue with HTML5 routing, thats originally how I found it. 

This issue isn't present on the docs because it uses HashLocationStrategy.

**Comment by aciccarello** [comment]
@CalebJaegerSlalom I think there is something more significant than HTML5 routing. I'm using HTML5 routing without issues.

**Comment by CalebJaegerSlalom** [comment]
@aciccarello I only noticed the problem when I had multiple sections in my routes 

**EG:**

**When I load:**
`domain.com/recipies/custard/45`

**It tries to load fonts from:**
`domain.com/recipies/custard/styles/font/MaterialIcons-Regular.woff`

**When it should be loading:**
`domain.com/styles/font/MaterialIcons-Regular.woff`

**Comment by aciccarello** [comment]
That makes sense. What do you have as your `<base>` tag?

**Comment by CalebJaegerSlalom** [comment]
I don't have the `<base>` tag set. 

I made a work around by making a copy of platform.scss and making the above changes.

**Comment by kyleledbetter** [comment]
You'll need to set a base href

**Comment by emoralesb05** [comment]
This will probably be fixed by this https://github.com/Teradata/covalent/pull/959
