### ISSUE TITLE
Bug: Data-table scrolling doesn't work inside flexbox container

### ISSUE THREAD

**Issue by quanterion** [Teradata/covalent#932]
If I put td-data-table inside flex div then scrolling of rows doesn't work: scrollbar is not visible. The problem occurs in Chrome Browser only. Firefox and even MS Edge works great.

http://plnkr.co/edit/eEAtNo?p=preview

I investigate that the problem lies in css height property of scrollable div https://github.com/Teradata/covalent/blob/9d85c23e7f4fe2442d4b6cb67729e6b9a93ed3a6/src/platform/core/data-table/data-table.component.scss#L10 If I change calc() of height to numerical value (inside Chrome DevTools) scroll appears as intended.

**Comment by emoralesb05** [comment]
Can you create a plnkr? because we have already done this and it works, trying to see how we can help you fix it

**Comment by quanterion** [comment]
The plunk is in the first message.
PS: I tried to fix covalent and use display: flex inside td-data-table, but can't find a reliable way to fill the remaining space with scrollable div

**Comment by emoralesb05** [comment]
Oh my bad, didnt see it haha thanks, we will take a look into it

**Comment by kyleledbetter** [comment]
@quanterion you're not using the proper CSS styles.

You need to either use our Flexbox layout CSS attributes explained in the bottom of this page https://teradata.github.io/covalent/#/layouts
OR use the https://github.com/angular/flex-layout module

**Comment by quanterion** [comment]
@kyleledbetter, Can you explain a little bit what's wrong with css in my plunker?

**Comment by quanterion** [comment]
I tried to use flex-layout and add fxLayout directive on the parent div and use fxFlex="auto" on the table itself. It deosn't help and the issue remains

**Comment by jeremysmartt** [comment]
no traction on issue in almost a year, let us know if still a problem
