### ISSUE TITLE
Feature: DataTable sortable prioritize column

### ISSUE THREAD

**Issue by chdanielmueller** [Teradata/covalent#933]
#### Feature Request
Change the behavior of sortable in the data-table.

#### What is the expected behavior?
Currently if the _general_ sortable boolean on the `td-data-table` is set to true it affects all columns.
I would recommend to allow an override on column basis.
e.g. Enable sortable on all columns, Disable sortable on specific column

#### What is the motivation / use case for changing the behavior?
In my personal opinion the settings on column basis should be weight higher than the _general_ setting.
Therefore it would be nice to be able to override a setting on column basis.

#### Which version of Angular and Material, and which browser and OS does this issue affect?
Affects all versions

##### Other information
I did a small fix in the following commit which solves this issue:
https://github.com/chdanielmueller/covalent/commit/42e36cd5decfe7ba679cf4c80c2060bc75be088b

In compliance with the contribution guidelines I will wait with opening a PR until this issue is approved.

**Comment by emoralesb05** [comment]
Yeah, agree! If you can help us out with a PR that would be awesome 😄

**Comment by chdanielmueller** [comment]
@emoralesb05 The PR #935 is ready but there is a "dependency-ci" check hanging since yesterday.

**Comment by emoralesb05** [comment]
Yeah, for some reason that doesnt work properly when its a PR from a fork, but will check the PR later today
