### ISSUE TITLE
how to make the table 100% ?

### ISSUE THREAD

**Issue by stewones** [Teradata/covalent#945]
### Do you want to request a *feature* or report a *bug*?

bug

#### What is the expected behavior?

be able to customize styles

https://github.com/Teradata/covalent/blob/master/src/platform/core/data-table/data-table.component.scss#L15

please avoid the use of `!important` in css. 
I just want to put the table with `100%` instead of `auto`

thanks this lib is awesome.

**Comment by owilliams320** [comment]
this component is deprecated please use https://material.angular.io/components/table
