### ISSUE TITLE
Enhancement: Add validations for dialogs

### ISSUE THREAD

**Issue by richavyas** [Teradata/covalent#961]
#### Feature Request
Add validations for dialogs so that same values aren't saved. 

If dialog box is used while creation and no value is entered, the `Save/OK` button is disabled. Similarly, while editing, if the old value isn't changed, the `Save/OK` button should be disabled. It will avoid two scenarios to enhance UX:
- duplicate values won't be saved in DB
- if DB checks for duplication then user will get to know quickly that the same value cannot be saved instead of waiting for API to throw error.

**Comment by aciccarello** [comment]
Seems like a specialized case of #660

**Comment by jotatoledo** [comment]
I think the best thing would be to able to pass a `FormControl `instance to the prompt dialog, which will allow the consumer of the api to create any sort of validation in the input field.
