### ISSUE TITLE
Support for Angular 5/ Material 5rc0

### ISSUE THREAD

**Issue by Sabartius** [Teradata/covalent#964]
Currently Covalents Package.json does not allow it to install it with Angular 5 and Material 5.0.0-rc0.

**Comment by Enngage** [comment]
I think they are already on it in a separate [branch ](https://github.com/Teradata/covalent/tree/feature/material-rc)

**Comment by emoralesb05** [comment]
Yup, we are working on our RC.0 which will be released this week, and it will have the material@rc support

**Comment by emoralesb05** [comment]
Just heads up, we are still testing the branch a bit to make sure everything works fine and will continue monday. 

And will release as soon as we merge it. 😄

**Comment by emoralesb05** [comment]
Closing this since https://github.com/Teradata/covalent/pull/967 was merged
