### ISSUE TITLE
[Design Pattern]: Empty data states

### ISSUE THREAD

**Issue by adamnel** [Teradata/covalent#968]
Cover empty data states for the following contexts:

- Empty page
- Empty region of page (empty card in a set of cards, for example)
- Empty row or item (such as a list item that doesn't have content in a larger set)

**Comment by adamnel** [comment]
# Spec sheet
![empty data state](https://user-images.githubusercontent.com/1143267/32804976-f5ea4d10-c955-11e7-8fb2-8c49ed515c40.png)

## Empty page sample design
![empty page](https://user-images.githubusercontent.com/1143267/32805080-5a40e616-c956-11e7-8e03-fc4bcaa1d1ca.png)

## Empty region sample design
![empty region](https://user-images.githubusercontent.com/1143267/32805081-5a5a8396-c956-11e7-9852-31c7e8f702ab.png)

## Empty item sample design
![empty item](https://user-images.githubusercontent.com/1143267/32805079-5a2c20be-c956-11e7-9e36-966f1c73d52c.png)

**Comment by aciccarello** [comment]
For reference, here is the material design spec on empty states
https://material.io/guidelines/patterns/empty-states.html

It has some good recommendations for alternative content

## Educational Content
![educational content in empty screen](https://storage.googleapis.com/material-design/publish/material_v_12/assets/0B6Okdz75tqQsZWk2REJtUDN6d2s/patterns-emptystates-education.png)

**Comment by kyleledbetter** [comment]
Examples from a Google product (Tag manager):
![image](https://user-images.githubusercontent.com/867883/32864818-65f0f748-ca15-11e7-8875-fb7b005cf5b3.png)

**Comment by adamnel** [comment]
I do like the more minimal nature of that one. The drop shadow on the icon isn't good but otherwise it's basically a cut down variant of the pattern I proposed.

**Comment by adamnel** [comment]
Another pattern from [Google Trends](https://trends.google.com/trends/explore?q=ember%20javascript,angular%20javascript,react%20javascript,vue%20javascript):
![image](https://user-images.githubusercontent.com/1143267/32900127-ba269a7a-caba-11e7-923a-d2dfdb8e360d.png)

**Comment by adamnel** [comment]
Another pattern from [Google Optimize](https://optimize.google.com/optimize/home):

![image](https://user-images.githubusercontent.com/1143267/32910702-f43fd858-cad7-11e7-9488-a470c801398b.png)

**Comment by adamnel** [comment]
From Google Business Manager:
![google-business-manager__emtpy-state__page](https://user-images.githubusercontent.com/1143267/32917277-aad78eee-caec-11e7-956c-4c1e369f2b81.png)

From Google Contacts:
![google-contacts__empty-state](https://user-images.githubusercontent.com/1143267/32917279-ad354974-caec-11e7-9884-18fdf41f5856.png)

From Google Data Studio:
![google-data-studio__empty-state__page](https://user-images.githubusercontent.com/1143267/32917282-af97dfc4-caec-11e7-9077-12c0e181317d.png)

From Google Firebase:
![google-firebase__empty-data-state__region2](https://user-images.githubusercontent.com/1143267/32917287-b328b4ba-caec-11e7-91e9-6bb0d77514f0.png)
![google-firebase__emtpy-data-state__region](https://user-images.githubusercontent.com/1143267/32917289-b482ce40-caec-11e7-85ec-66206ab73066.png)

From Google Keep:
![google-keep__empty-state__page](https://user-images.githubusercontent.com/1143267/32917294-b859f174-caec-11e7-84a4-378f7ff501e1.png)

From Google Optimize:
![google-optimize__empty-state__card2](https://user-images.githubusercontent.com/1143267/32917299-bc2ebf82-caec-11e7-93c7-feaec4410a15.png)
![google-optimize__empty-state__page](https://user-images.githubusercontent.com/1143267/32917303-bf96343e-caec-11e7-9adc-67f2b7cae087.png)

**Comment by kyleledbetter** [comment]
Awesome research

**Comment by jennmedellin** [comment]
![pasted image at 2017_11_20 10_59 am](https://user-images.githubusercontent.com/17860952/33048637-cdd75c22-ce10-11e7-840f-96ed0f39f930.png)
Thanks for the great input.  We're thinking this one will work well.  What do you all think?

**Comment by jennmedellin** [comment]
Except without the background on the icon, since that looks custom.

**Comment by adamnel** [comment]
I would argue that the background color is important to add some visual consistency to the pattern, as the specific icon in use could vary wildly in visual weight. The background lends structure to what otherwise appears more like a jumble of loosely associated items.

Here are comparisons:
![empty page](https://user-images.githubusercontent.com/1143267/33286676-1fa9be28-d384-11e7-9060-f0908be4267e.png)
![empty region](https://user-images.githubusercontent.com/1143267/33286684-237182a2-d384-11e7-8619-ed1ced845069.png)
