### ISSUE TITLE
TdLoading: ExpressionChangedAfterItHasBeenCheckedError

### ISSUE THREAD

**Issue by filipows** [Teradata/covalent#972]
### Do you want to request a *feature* or report a *bug*?

*bug*

#### Bug Report
To reproduce:
1. use tdLoading directive with tdLoadingStrategy="overlay" on an element that height is smaller than 100px
2. after loaded element changes its height

Then you got:
ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: '78'. Current value: '100'

http://plnkr.co/edit/FEk9b7c2fb1GtrMX7lv9?p=preview

##### Screenshots or link to CodePen/Plunker/JSfiddle
![tdloading-bug](https://user-images.githubusercontent.com/884847/32822501-d4425590-ca13-11e7-98ae-84a9751f3db7.gif)

#### What is the expected behavior?
Shouldn't throw an error

#### Which version of Angular and Material, and which browser and OS does this issue affect?

- Covalent 1.0.0-rc.0
- Angular 5.0.1 
- Material 5.0.0-rc0

##### Other information
The cause is probably related to this part: `getCircleDiameter()`
https://github.com/Teradata/covalent/commit/da0221b6c0d79e56af908e3b7c9ded9e78dc1342#diff-0d22f546d39ab49964181c6d6344e8a8R113

**Comment by emoralesb05** [comment]
Thanks for the report, the reason we didnt cover it is because it doesnt happen when using the component in `OnPush`.. will fix this asap.

**Comment by lincze** [comment]
i've experinced the same error. but i see a problem when onpush is used, e.g. on

https://teradata.github.io/covalent/#/components/loading

page, the "code" tab does not work for me at the moment (firefox quantum), and the console shows a dom exception.

**Comment by lincze** [comment]
this loading service component works very differently in chrome and firefox. keeping the covalent docs/showcase app, as example, the loading page does not work in firefox, at all, and the dom collapses at he 1st page rendering. but in chrome, the page seems to render correctly. I experience the same with my app, collapsed dom in firefox, works in chrome.

so, when onpush, this problem seems to be browser (firefox) specific specific.

**Comment by emoralesb05** [comment]
Yup, just saw that issue in firefox, gonna try and see what the problem is..

**Comment by emoralesb05** [comment]
Both issues were fixed, if you all want to try the nightly build to verify it would be great.

**Comment by lincze** [comment]
I've built from develop, and it works now in firefox. (though the the spinner became much smaller than was before, in my app)

**Comment by filipows** [comment]
It works for me.

I was also wondering if making customizable TD_CIRCLE_DIAMETER would be a feature that we would like to have? But that's another topic.
Thanks for the help!
