### ISSUE TITLE
Getting started docs still mentions platform.scss 

### ISSUE THREAD

**Issue by Enngage** [Teradata/covalent#975]
Based on description of latest release it seems that the 'Getting started' page is outdated as it still states to link the platform.scss which seems to not be required anymore. Is that correct?

**Comment by aciccarello** [comment]
I think `platform.scss` still works but is not required. It's the simplest way to get started, but it has helpers that not everyone needs.

**Comment by emoralesb05** [comment]
Right, as @aciccarello mentioned.. we are not gonna remove the platform.scss, but we do specify its optional and there are multiple ways to achieve this.
