### ISSUE TITLE
bug(td-message): td-message inside ng if can not be hidden and duplicates it self

### ISSUE THREAD

**Issue by quanterion** [Teradata/covalent#981]
I found a strange bug in rc.0 release

If yout put ngIf on **td-message** component when variable inside ngIf becomes false component remains visible and if variable becomes true then there will be two components on screen and so on!

https://stackblitz.com/edit/covalent-pdntnj?file=app%2Fapp.component.html

I use:
ng-cli 1.5.0
ng: 5.0.0
material: 5.0.0-rc.0
covalent: 1.0.0-rc.0

PS: If I put ngIf instead of **td-message** on some parent div then everything works as expected

**Comment by lincze** [comment]
I' had similar experience with an 
```
<td-message *ngIf="invalidError" ...
```
constract (a timer revoked the message after some secs with "this.invalidError=false"). it worked before the rc.0 release, and as a temp fix, now it works with the message element surrounded by a div:
```
<div *ngIf="invalidError>
  <td-message....
</div>
```

**Comment by emoralesb05** [comment]
Yeah, i also noticed this issue.. not sure why its happening. Gonna add it into the backlog for RC's

**Comment by emoralesb05** [comment]
Found the issue, opened a PR to fix this
