### ISSUE TITLE
make td-chips and stacked more flexible using containers

### ISSUE THREAD

**Issue by megetron** [Teradata/covalent#990]
#### Feature Request
if we could make the td-chips and stacked more flexible using containers for the stacked chips and for the input itself
#### What is the expected behaviour?
when using the stacked td-chips I was struggling to make the make:
1. input to be placed above the stacked list (and not below of the stacked list)
2. stacked to be in a container/div to allow scroll on it once it has too many rows (as my form has a limit view in screen).

#### What is the motivation / use case for changing the behaviour?
just to make this component working with stack as flexible as possible

**Comment by emoralesb05** [comment]
Taking care of this in https://github.com/Teradata/covalent/pull/1061
