### ISSUE TITLE
feature: pass initial value to search components

### ISSUE THREAD

**Issue by jotatoledo** [Teradata/covalent#995]
#### Feature Request

Ability to pass an initial value through an input property to both search components.

#### What is the expected behavior?
It should be possible to do something like:

```
<td-search-box 
backIcon="search" 
[placeholder]="'TERM.FILTER' | translate" 
[showUnderline]="true" 
[value]="filter$ | async" 
[debounce]="500" 
(searchDebounce)="handleSearch($event)">
  </td-search-box>

```

**Comment by emoralesb05** [comment]
https://github.com/Teradata/covalent/pull/1041 will add ngModel support to both search-input and search-box
