### ISSUE TITLE
[Design Pattern]: Nav drawer user avatar

### ISSUE THREAD

**Issue by aciccarello** [Teradata/covalent#998]
#### Feature Request
Document how to implement showing an avatar in the navigation drawer. Currently the `<td-layout-nav>` is designed to show a logo, not an avatar. Adding an avatar is (likely) possible but it should be documented.

_Note: I personally am not interested in the account switching functionality described in the material spec._

##### Screenshots or link to CodePen/Plunker/JSfiddle
https://material.io/guidelines/patterns/navigation-drawer.html
![navigation drawer example](https://storage.googleapis.com/material-design/publish/material_v_12/assets/0Bzhp5Z4wHba3Q0tDQ3Z1OHg5VHc/patterns-navdrawer-elevation1.png)

#### What is the expected behavior?
Design patterns section should document how to display/style a user avatar image in a nav drawer.

#### What is the motivation / use case for changing the behavior?
Showing a user avatar is a main feature of the navigation drawer in the design spec. User avatars are commonly used to identify users and the nav drawer already identifies the user name/email in the drawer.

##### Other information

Related to #774

**Comment by kyleledbetter** [comment]
We can certainly entertain adding the avatar.

The reason why we use a logo is that typically enterprises don't have avatars with LDAP/Active Directory, and we took inspiration from Google products where they use a logo & product name instead.

They seem to use logo & product name for desktop/web products and the avatar for mobile apps

**Comment by asiman161** [comment]
+1. It will be very cool if you give choice for us: use avatar or logo only. I'm not interesting in account switching too. I want to show avatar instead of logo.
